Repository syndesisio/syndesis, pull requests merged in 2018-07, with the labels that each got.

#2943 fix: use glob config to include config.json
  app/ui/angular.json
  app/ui/package.json
Labels: pr/approved

#2944 chore: upgrade to patternfly-ng 4.x (partial)
  app/ui/package.json
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/app.module.ts
  app/ui/src/app/connections/create-page/current-connection.ts
  app/ui/src/app/connections/list-page/list-page.component.spec.ts
  app/ui/src/app/connections/list/list.component.spec.ts
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard.module.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
  app/ui/src/app/integration/list-page/list-page.component.spec.ts
  app/ui/src/app/integration/list/list.component.spec.ts
  app/ui/src/app/vendor/vendor.module.ts
  app/ui/yarn.lock
Labels: pr/approved

#2935 change api connector details from inline editor
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
Labels: pr/approved

#2950 fix: remove unused field-level error messaging for now
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts
Labels: pr/approved

#2951 chore: disable/remove package-lock.json in favor of yarn.lock
  app/ui/.gitignore
  app/ui/.npmrc
  app/ui/package-lock.json
Labels: pr/approved

#2957 fix(http/https connector): HTTP Connector method not honored, fixes #…
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpMethodCustomizer.java
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
Labels: pr/approved

#2954 chore: switch create connection wizard templates over to i18n
  app/ui/src/app/connections/common/configuration/configuration.service.ts
  app/ui/src/app/connections/common/configuration/validation.component.html
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/create-page/create-page.component.html
  app/ui/src/app/connections/create-page/review/review.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2970 Meta pod doesn't start because: Cannot determine embedded database driver class for database type NONE
  app/meta/src/main/resources/application.yml
Labels: pr/approved

#2975 [Meta] No suitable driver found for jdbc:postgresql://syndesis-db:5432/sampledb. Unable to fetch and process metadata
  app/connector/sql/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/application.properties.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application.properties
Labels: pr/approved, pr/review-requested

#2979 Allow to specify http headers for datamapper step in Webhooks
  app/connector/webhook/pom.xml
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
Labels: pr/approved, pr/review-requested

#2982 feat(connector): Add timer connector back, related to #2952
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/connector/timer/pom.xml
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#2964 update modal message dialogs
  app/ui/src/app/common/modal/modal.component.html
  app/ui/src/app/common/modal/modal.component.ts
  app/ui/src/app/connections/list-page/list-page.component.spec.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/connections/list/list.component.spec.ts
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2984 fix: get property value from the group object
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts
Labels: pr/approved

#2985 fix: don't bind the checked property
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: pr/approved

#2989 fix: move link handler to an inner element
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
Labels: pr/approved

#2992 fix submit handler for saving api connector details form when in create mode
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
Labels: pr/approved

#2966 Instead of using neither -d(for linux) or -D(for mac), use --decode o…
  tools/misc/extract_integration.sh
Labels: pr/approved

#2994 Move message dialog text into dictionary file
  app/ui/src/app/common/modal/modal.component.html
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2947 Initial version of publishing status monitoring endpoint, fixes 2619 See comment in issue for details.
  app/common/model/src/main/java/io/syndesis/common/model/Kind.java
  app/common/model/src/main/java/io/syndesis/common/model/monitoring/IntegrationDeploymentDetailedState.java
  app/common/model/src/main/java/io/syndesis/common/model/monitoring/IntegrationDeploymentStateDetails.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/MonitoringProvider.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/MonitoringProviderImpl.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/monitoring/NoopMonitoringProviderImpl.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/monitoring/IntegrationDeploymentStateDetailsHandler.java
  app/server/monitoring/pom.xml
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/DeploymentStateMonitor.java
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/DeploymentStateMonitorController.java
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/MonitoringConfiguration.java
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/PublishingStateMonitor.java
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/StateHandler.java
  app/server/monitoring/src/main/resources/META-INF/spring.factories
  app/server/monitoring/src/test/java/io/syndesis/server/monitoring/DeploymentStateMonitorControllerTest.java
  app/server/pom.xml
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/test/resources/application-test.yml
Labels: pr/approved, pr/review-requested

#2995 chore(ui): logout endpoint
  app/ui/angular.json
  app/ui/docker/nginx-syndesis.conf
  app/ui/src/app/core/providers/user-provider.service.ts
  app/ui/src/logout.html
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3012 fix: add a space
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
Labels: pr/approved

#3010 UI work for fetching the detailed status
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/list/index.ts
  app/ui/src/app/integration/list/list.module.ts
  app/ui/src/app/integration/list/status-detail.component.ts
  app/ui/src/app/integration/list/status.component.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
  app/ui/src/app/platform/types/integration/integration.api.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/integration/integration.service.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3007 chore: Remove workarounds used for GA release
  install/generator/04-syndesis-server.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
Labels: pr/approved

#3019 chore(ui): Tidy up OAuth settings page
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
Labels: pr/approved

#3008 fix(server): gather integration logs for support
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
Labels: pr/approved, pr/review-requested

#3021 Text fixes: Changed "a OpenAPI" to "an OpenAPI and a few other updates.
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
Labels: pr/approved, pr/review-requested

#3020 chore: OAuth app settings backed by configurati on from the backend
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/package-info.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.models.ts
Labels: pr/approved, pr/review-requested

#3024 chore: tidy up fetching a single integration, fix up status on detail page
  app/ui/src/app/integration/list/status-detail.component.ts
  app/ui/src/app/store/integration/integration.service.ts
Labels: pr/approved

#3030 fix integration name edit in firefox (in integration editor workflow)
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
Labels: pr/approved

#3027 Simplified IVP
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.scss
  app/ui/src/app/integration/edit-page/edit-page.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
Labels: pr/approved, pr/review-requested

#3037 fix: bit 'o refactoring and use specific step indices
  app/ui/src/app/connections/create-page/create-page.component.ts
Labels: pr/approved

#3038 chore: close subscriptions, also exclude node_modules folder in jsconfig.json
  app/ui/jsconfig.json
  app/ui/src/app/connections/create-page/create-page.component.ts
Labels: pr/approved

#3039 chore: show the step name if available
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: pr/approved

#3043 chore: collapse nav when entering the client connector wizard
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
Labels: pr/approved

#3044 dont allow integration name area to shrink
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
Labels: pr/approved

#3049 chore: fix width of detailed status
  app/ui/src/app/integration/list/status-detail.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/store/integration/integration.service.ts
Labels: pr/approved, pr/review-requested

#3053 feature(connector-log): Add log connector to Syndesis from Extensions
  app/connector/log/pom.xml
  app/connector/log/src/main/resources/META-INF/syndesis/connector/log.json
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#3055 feature(connector): add telegram connector to Syndesis from Extensions
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/connector/telegram/pom.xml
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#3058 fix expanded IVP UI with long step/connection name
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved

#3062 shell script to extract Java thred dumps with CPU usage from target POD.
  tools/misc/extract_javathreads.sh
Labels: pr/approved

#3064 refactor(gmail connector): Gmail connector: Change the order of field…
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
Labels: pr/approved

#3065 refactor(gmail connector): fixed labels description and hints
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
Labels: pr/approved

#3059 fix(basic-filter-form): basic filter form rewritten with formbuilder
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.scss
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.model.ts
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/index.ts
Labels: group/ui, pr/review-requested

#3068 chore: use both possible key references for config.json substitution
  app/ui/src/app/core/providers/i18n-provider.service.ts
Labels: pr/approved

#3069 chore(db): add scheduled database maintenance
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3070 feature(connector-irc): Add connector-irc to Syndesis from Extensions
  app/connector/irc/pom.xml
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#3077 chore: ensure dev config.json file is nuked when building
  app/ui/package.json
  app/ui/pom.xml
Labels: pr/approved

#3079 Added deployer pod monitoring to state details
  app/server/monitoring/src/main/java/io/syndesis/server/monitoring/PublishingStateMonitor.java
  app/server/monitoring/src/test/java/io/syndesis/server/monitoring/DeploymentStateMonitorControllerTest.java
Labels: pr/approved

#3056 Fix upgrade pod issues for operator
  tools/upgrade/Dockerfile
  tools/upgrade/migration/preflight.sh
  tools/upgrade/steps/upgrade_40_update_resources
Labels: pr/approved, pr/review-requested

#3078 fix(a11y-cleanup): improve router navigation experience
  app/ui/src/app/app.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.scss
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
Labels: group/ui, pr/approved, pr/review-requested

#3084 Issue #2693: resuming after publish of integration violates same name
  app/ui/src/app/integration/edit-page/flow-page.service.ts
Labels: pr/approved, pr/review-requested

#3086 fix: don't try to mount syndesis-db-data volume
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3089 increase bottom padding of expanded IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3091 move IVP add step/connection popover below plus button, adjust paddings
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved

#3085 ENTESB-8194: removed risk of name clashes inzips created from support…
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java
  app/server/endpoint/src/test/resources/logback-test.xml
Labels: pr/approved, pr/review-requested

#3094 fix: make the icon in the editor clickable too
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved

#3100 chore: update placeholder text in oauth settings
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3102 Running yarn with Openshift using oc cluster up
  app/ui/scripts/minishift-restore.sh
  app/ui/scripts/minishift-setup.sh
Labels: pr/approved, pr/review-requested

#3104 fix: ensure the integration and connection names are displayed properly
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/app/integration/import-export/integration-import-export.component.html
  app/ui/src/app/integration/import-export/integration-import-export.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3106 chore: integration import tidying/hardening
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/app/integration/import-export/integration-import-export.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3097 Unecessary requests to `/api/v1/integrations`
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
Labels: pr/approved, pr/review-requested

#3111 set preserveWhitespaces = true for JIT and AOT
  app/ui/angular.json
  app/ui/src/main.ts
  app/ui/src/tsconfig.app.json
Labels: pr/approved, pr/review-requested

#3112 fix: fetch more things from the backend, add a config parameter
  app/ui/src/app/store/action/action.service.ts
  app/ui/src/app/store/connection/connection.service.ts
  app/ui/src/app/store/connector/connector.service.ts
  app/ui/src/app/store/entity/rest.service.ts
  app/ui/src/app/store/extension/extension.service.ts
  app/ui/src/app/store/integration/integration.service.ts
  app/ui/src/app/store/oauthApp/oauth-app.service.ts
Labels: pr/approved

#3115 fix: Found duplicate and different resources: git.properties
  app/pom.xml
Labels: pr/approved

#3117 fix: add tsconfig.json back and just inherit from tsconfig.app.json so vscode behaves
  app/ui/src/tsconfig.json
Labels: pr/approved

#3114 Fixes for errors flagged when building in Eclipse
  app/pom.xml
  doc/tools/syndesis-documentation-maven-plugin/src/main/java/io/syndesis/server/builder/maven/TooltipExtractorMojo.java
  doc/tools/syndesis-documentation-maven-plugin/src/test/java/io/syndesis/server/builder/maven/TooltipExtractorMojoTest.java
Labels: pr/approved, pr/review-requested

#3127 chore: Update to AtlasMap 1.35.5
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#3128 update api connector cancel modal dialog
  app/ui/src/app/common/cancel_confirmation_modal/cancel-confirmation-modal.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3133 fix(log-connector): Added the icon to log-connector
  app/connector/log/src/main/resources/META-INF/syndesis/connector/log.json
Labels: pr/approved

#3134 refactor(telegram-connector): Add the icon as base64 svg
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#3124 fix: Specify mapping definition file encoding on camel-atlasmap endpoint
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
Labels: pr/approved

#3138 fix: consistently display the error response from the meta service
  app/ui/src/app/api/providers/api-http-provider.service.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Labels: pr/approved

#3144 fix: Update to openshift 3.9.0 for "syndesis minishift"
  tools/bin/commands/minishift
Labels: cat/bug, cat/build, pr/approved

#3154 fix(connector): set Timer's output shape to none
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
Labels: pr/approved

#3157 fix(connector): Salesforce output unmarshalling
  app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java
  app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizerTest.java
Labels: pr/approved, pr/review-requested

#3139 Fix for the concur swagger definitions #3041
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/approved, pr/review-requested

#3159 enhancement: Clarified labels and hints for Gmail connector
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
Labels: pr/approved, pr/review-requested

#3146 Enforce the minimum version of oc
  tools/bin/commands/tests/test-oc-version.sh
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#3163 fix(template): Add missing label to db pvc
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#3156 chore: Update to AtlasMap 1.35.5 in Integration BOM
  app/integration/bom/pom.xml
Labels: pr/approved

#3166 fix: sort fetched integrations in dashboard by updatedAt/createdAt
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
Labels: pr/approved

#3153 Issue #2706 - sql connector should not parse body when no parameters
  app/connector/odata/create-entity/pom.xml
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/JSONBeanUtilTest.java
Labels: pr/approved, pr/review-requested

#3171 have cancel button in create connection wizard prompt the user via modal to confirm cancellation
  app/ui/src/app/connections/create-page/create-page.component.html
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3177 chore: Update to AtlasMap 1.35.6
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#3160 Advanced filter throws exception when message body is plaintext
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java
Labels: pr/approved, pr/review-requested, pr/wip

#3179 fix: add initialDelaySeconds to readyness/liveness checks for prometheus
  install/generator/06-syndesis-prometheus.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3185 Timer connector fix
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
Labels: pr/approved

#3186 fix(timer-connector): Timer connector requires camel-quartz2 as runti…
  app/connector/timer/pom.xml
Labels: pr/approved

#3182 fix: ensure the step indicator is driven by the route, also better property checking
  app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.ts
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/app/connections/create-page/current-connection.ts
Labels: pr/approved

#3183 fix: show/hide relevant menu entries; disable publish/edit when publishing
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.ts
  app/ui/src/app/integration/list/action-menu.component.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
Labels: pr/approved

#3187 fix(basic-filter-form): update form bindings for default state
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: group/ui, pr/approved, pr/review-requested

#3189 fix(basic-filter-form): add back autocomplete for property name field
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
Labels: group/ui, pr/approved, pr/review-requested

#3190 bug fix: Typo in slack json file fixed
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved, pr/review-requested

#3192 feature(install): Moved syndesis-operator to monorepo
  install/operator/.gitignore
  install/operator/Gopkg.lock
  install/operator/Gopkg.toml
  install/operator/README.md
  install/operator/cmd/syndesis-operator/main.go
  install/operator/config/config.yaml
  install/operator/deploy/operator.yaml
  install/operator/deploy/syndesis-crd.yaml
  install/operator/deploy/syndesis-operator.yaml
  install/operator/deploy/syndesis.yaml
  install/operator/docs/info.txt
  install/operator/docs/syndesis-operator-states.png
  install/operator/docs/syndesis-operator-states.xml
  install/operator/hack/info.txt
  install/operator/hack/update_deepcopy.sh
  install/operator/hack/update_resources.sh
  install/operator/pkg/apis/syndesis/v1alpha1/doc.go
  install/operator/pkg/apis/syndesis/v1alpha1/register.go
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/openshift/register.go
  install/operator/pkg/openshift/serviceaccount/serviceaccount.go
  install/operator/pkg/openshift/template/scheme.go
  install/operator/pkg/openshift/template/templateprocessor.go
  install/operator/pkg/stub/handler.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/startup.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/action/upgradebackoff.go
  install/operator/pkg/syndesis/action/upgradelegacy.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/configuration/envvars.go
  install/operator/pkg/syndesis/configuration/secret.go
  install/operator/pkg/syndesis/configuration/util.go
  install/operator/pkg/syndesis/configuration/version.go
  install/operator/pkg/syndesis/legacy/controller.go
  install/operator/pkg/syndesis/operation/attach.go
  install/operator/pkg/syndesis/operation/utils.go
  install/operator/pkg/syndesis/reconcile.go
  install/operator/pkg/syndesis/template/inspect.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
  install/operator/resources/bindata.go
  install/operator/resources/template.yaml
  install/operator/test/resources/dep.json
  install/operator/test/resources/dep.yml
  install/operator/tmp/build/Dockerfile
  install/operator/tmp/build/build.sh
  install/operator/tmp/build/docker_build.sh
  install/operator/tmp/codegen/boilerplate.go.txt
  install/operator/tmp/codegen/update-generated.sh
  tools/images/godev/README.md
  tools/images/godev/build.sh
Labels: pr/approved

#3193 refactor(operator): Used meta direct as key, simplified a bit
  install/operator/pkg/syndesis/operation/attach.go
  install/operator/pkg/syndesis/template/inspect.go
Labels: pr/approved

#3191 update wording in cancel modals in api connector and connection create wizards
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3199 fix: enable the done button on the data mapper page
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
Labels: pr/approved

#3203 Fix #3168: adjust priority and remove chatId from telegram consumer
  app/connector/telegram/pom.xml
  app/connector/telegram/src/main/java/io/syndesis/connector/telegram/TelegramSendMessageCustomizer.java
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#3205 fix: refactor the integration list on the dashboard; make the buttons show appropriately
  app/ui/src/app/dashboard/dashboard.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
Labels: pr/approved

#3209 fix: correct time format in last updated tab
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
Labels: pr/approved, pr/review-requested

#3211 fix: ensure IDs are set on all steps before saving
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved

#3206 feat: mark Connectors provided as tech preview
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
  app/ui/src/app/common/card-tech-preview.component.scss
  app/ui/src/app/common/card-tech-preview.component.ts
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/platform/types/connection/connection.models.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3212 refactor position of technical preview component, update dictionary case
  app/ui/src/app/common/card-tech-preview.component.scss
  app/ui/src/app/common/card-tech-preview.component.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/connections/list/list.component.scss
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3217 refactor(ui): use popover for tech preview
  app/ui/src/app/common/card-tech-preview.component.ts
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3218 feat(ui): help menu link to Connectors Guide
  app/ui/src/app/app.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3226 fix: check an oauth app's config to see if it's configured
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
Labels: pr/approved

#3219 fix(ui): mutation order in API Client connector wizard OAuth settings
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
Labels: pr/approved, pr/review-requested

#3228 update technical preview popover placement
  app/ui/src/app/common/card-tech-preview.component.scss
  app/ui/src/app/common/card-tech-preview.component.ts
Labels: pr/approved, pr/review-requested

#3213 feature(operator): Initial build and install support for syndesis-operator
  .circleci/config.yml
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-amq-example.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/generator/05-syndesis-security.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/operator/.dockerignore
  install/operator/.gitignore
  install/operator/Dockerfile
  install/operator/cmd/syndesis-operator/main.go
  install/operator/deploy/operator.yaml
  install/operator/deploy/syndesis-crd.yml
  install/operator/deploy/syndesis-operator.yml
  install/operator/deploy/syndesis.yml
  install/operator/hack/update_resources.sh
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/version.go
  install/operator/pkg/syndesis/template/inspect.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
  install/operator/resources/bindata.go
  install/operator/resources/template.yaml
  install/syndesis-dev.yml
  install/syndesis.yml
  tools/bin/commands/build
  tools/bin/commands/completion
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/release
  tools/bin/commands/util/maven_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
  tools/bin/syndesis
  tools/images/godev/Dockerfile
Labels: pr/approved, pr/review-requested

#3231 fix(release): Filter out non-three digit version when calculating snapshot name
  tools/bin/commands/release
Labels: pr/approved

#3235 fix: Fix CircleCI docker image build
  .circleci/config.yml
Labels: pr/approved

#3237 Servicenow - can't retrieve data from custom table
  app/connector/servicenow/pom.xml
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtension.java
  app/connector/servicenow/src/test/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtensionTest.java
  app/connector/servicenow/src/test/resources/logback-test.xml
Labels: pr/approved

#3240 fix(build): Fixed typo in var name
  tools/bin/commands/util/operator_funcs
Labels: pr/approved

#3242 link "technology previews" text in popover
  app/ui/src/app/common/card-tech-preview.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested
