Repository syndesisio/syndesis, pull requests merged in 2018-03, with the labels that each got.

#1719 fix: MQTT Connector
  app/connectors/connectors-catalog/pom.xml
  app/connectors/connectors/mqtt/pom.xml
  app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifier.java
  app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierAutoConfiguration.java
  app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java
  app/connectors/connectors/mqtt/src/main/resources/META-INF/spring.factories
  app/connectors/connectors/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
  app/connectors/connectors/mqtt/src/main/resources/META-INF/syndesis/connector/verifier/paho
  app/connectors/pom.xml
  app/rest/dao/src/test/java/io/syndesis/dao/DataManagerTest.java
  app/verifier/pom.xml
Labels: approved

#1745 DataBuckets exception - Incompatible Source Document 'null'
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationSchedulerTest.java
Labels: approved

#1746 refactor(connectors): AWS S3 connector: Use the new order field for c…
  app/connectors/connectors/aws-s3-connector/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/ui/src/app/connections/common/configuration/configuration.service.ts
Labels: approved

#1747 refactor(connectors): AWS S3 connector copy object has any an Input
  app/connectors/connectors/aws-s3-connector/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: approved

#1749 Scripts, added logging
  tools/bin/commands/minishift
  tools/bin/syndesis
Labels: approved

#1750 chore: fix mqtt connector leftovers
  app/connectors/connectors-catalog/pom.xml
  app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifier.java
  app/connectors/connectors/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java
  app/connectors/connectors/mqtt/src/main/resources/META-INF/syndesis/connector/verifier/paho
  app/pom.xml
  app/verifier/pom.xml
Labels: approved

#1748 [SDH] Add missing instructions for adding a new command
  doc/sdh/cli/cmd_doc.adoc
  doc/sdh/cli/cmd_system_test.adoc
  doc/sdh/cli/index.adoc
Labels: approved

#1757 fix: Version parameterisation in test
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/integration.json
Labels: approved

#1758 TidyUp, remove commented lines
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Labels: approved

#1754 fix: I suppose people want to add steps sometimes
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
Labels: approved, group/ui

#1760 chore: update field labels a bit for #1229
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
Labels: group/ui

#1761 DataBuckets exception - Incompatible Source Document 'null'
  app/core/model/src/main/java/io/syndesis/model/WithSplit.java
  app/core/model/src/main/java/io/syndesis/model/action/ConnectorDescriptor.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/OutMessageCaptureInterceptStrategy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/capture/MessageCaptureAutoConfiguration.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/capture/OutMessageCaptureProcessor.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AbstractEndpointStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/EndpointStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SimpleEndpointStepHandler.java
  app/integration/runtime/src/main/resources/META-INF/spring.factories
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationSchedulerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/capture/OutMessageCaptureProcessorTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ExtensionStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/StepWithIdTest.java
Labels: approved

#1762 chore: add link to previous step's describe output data shape page for shapeless thingies
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
Labels: approved

#1759 fix: Fix creation of temp dir for 'syndesis release'
  tools/bin/commands/release
Labels: approved

#1763 chore: Logout when doing a login via the script
  tools/bin/commands/release
Labels: approved

#1733 fix: duplicate dependency
  app/rest/runtime/pom.xml
Labels: approved

#1770 fix: fixing racecondition with SqlParserTest #1769
  app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/common/SqlConnectionRule.java
  app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
Labels: approved

#1768 fix: Connection URL and username should not be secrets
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: approved

#1776 fix(ui): display error from the backend
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/store/entity/entity.store.ts
Labels: approved, group/ui, size/s

#1775 Integration details UI
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
  app/ui/src/app/integration/integration_detail/integration-history.component.scss
Labels: approved

#1777 Added missing Syndesis metrics to Prometheus config
  app/deploy/generator/06-syndesis-prometheus.yml.mustache
Labels: approved

#1778 Added missing Syndesis metrics to Prometheus config, fixed RE2 expression
  app/deploy/generator/06-syndesis-prometheus.yml.mustache
Labels: approved

#1779 feat(syndesis release): Allow to specifcy the remote with --git-remote for pushing git tags
  tools/bin/commands/release
Labels: approved

#1765 chore(openshift): prefix to openshift resources
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Labels: approved, group/rest, size/s

#1785 feat(syndesis minishift): Add --vm-driver option
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/minishift
Labels: approved

#1786 fix: adding close statements
  app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/common/SqlConnectionRule.java
Labels: approved

#1771 Extenstion import ui
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/extension/ExtensionHandler.java
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.scss
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.scss
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
  app/ui/src/app/customizations/tech-extensions/tech-extension-common.scss
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.scss
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved, group/ui

#1787 fix: use the right fake link for the datamapper popover
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
Labels: approved, group/ui

#1784 feat(metrics): integrations activity grid (w/o detail view) including refresh and pagination features
  app/ui/src/app/common/button.component.ts
  app/ui/src/app/common/validation/validation-error.component.scss
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/integration/integration_detail/index.ts
  app/ui/src/app/integration/integration_detail/integration-activity/index.ts
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.scss
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/integration_detail/integration-history.component.html
  app/ui/src/app/integration/integration_detail/integration-history.component.scss
  app/ui/src/app/integration/integration_detail/integration-history.component.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
Labels: approved, cat/feature, group/integration, group/ui, notif/uxd

#1790 Db-logging, tone down logging
  app/rest/db-logging/src/main/java/io/syndesis/rest/dblogging/controller/ActivityTrackingController.java
Labels: approved

#1793 align step name/icon, add title attribute for long/truncated step names
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: approved

#1794 Related to #1752: add base support for library extensions
  app/core/model/src/main/java/io/syndesis/model/extension/Extension.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/RepackageExtensionMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/SupportMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/layout/ModuleLayoutFactory.java
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
Labels: approved

#1796 feat(forms): add basic support for relation property
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: approved, group/ui

#1797 chore: use new relation support to disable the specification, name and description field
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
Labels: group/ui

#1800 Added order field to AMQP connector and action properties, fixes #1696
  app/connectors/connectors/jms/amqp-connector/src/main/resources/META-INF/syndesis/connector/amqp.json
  app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
Labels: approved

#1806 Switch to Prometheus metris provider by default
  app/rest/metrics-prometheus/src/main/java/io/syndesis/rest/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/rest/runtime/src/main/resources/application.yml
Labels: approved

#1809 [connector] http4 connector
  app/connector/http/get/pom.xml
  app/connector/http/get/src/main/java/io/syndesis/connector/http/HttpGetComponent.java
  app/connector/http/get/src/main/java/io/syndesis/connector/http/springboot/HttpGetConnectorAutoConfiguration.java
  app/connector/http/get/src/main/java/io/syndesis/connector/http/springboot/HttpGetConnectorConfiguration.java
  app/connector/http/get/src/main/java/io/syndesis/connector/http/springboot/HttpGetConnectorConfigurationCommon.java
  app/connector/http/get/src/main/resources/META-INF/services/org/apache/camel/component/http-get-connector
  app/connector/http/get/src/main/resources/META-INF/spring.factories
  app/connector/http/get/src/main/resources/camel-connector-schema.json
  app/connector/http/get/src/main/resources/camel-connector.json
  app/connector/http/pom.xml
  app/connector/http/post/pom.xml
  app/connector/http/post/src/main/java/io/syndesis/connector/http/HttpPostComponent.java
  app/connector/http/post/src/main/java/io/syndesis/connector/http/springboot/HttpPostConnectorAutoConfiguration.java
  app/connector/http/post/src/main/java/io/syndesis/connector/http/springboot/HttpPostConnectorConfiguration.java
  app/connector/http/post/src/main/java/io/syndesis/connector/http/springboot/HttpPostConnectorConfigurationCommon.java
  app/connector/http/post/src/main/resources/META-INF/services/org/apache/camel/component/http-post-connector
  app/connector/http/post/src/main/resources/META-INF/spring.factories
  app/connector/http/post/src/main/resources/camel-connector-schema.json
  app/connector/http/post/src/main/resources/camel-connector.json
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorFactories.java
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorVerifierExtension.java
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpMethodCustomizer.java
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpVerifierAutoConfiguration.java
  app/connector/http/src/main/resources/META-INF/spring.factories
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/http/src/test/java/io/syndesis/connector/http/HttpConnectorFactoriesTest.java
  app/connector/http/src/test/java/io/syndesis/connector/http/HttpConnectorVerifierTest.java
  app/connector/http/src/test/java/io/syndesis/connector/http/util/BasicValidationHandler.java
  app/connector/http/src/test/resources/logback-test.xml
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/connector/support/component/http/pom.xml
  app/connector/support/component/http/src/main/java/io/syndesis/connector/support/component/http/HttpComponent.java
  app/connector/support/component/http/src/main/java/io/syndesis/connector/support/component/http/HttpComponentAutoConfiguration.java
  app/connector/support/component/http/src/main/java/io/syndesis/connector/support/component/http/HttpComponentConfiguration.java
  app/connector/support/component/http/src/main/java/io/syndesis/connector/support/component/http/HttpEndpoint.java
  app/connector/support/component/http/src/main/resources/META-INF/services/org/apache/camel/component/syndesis-http
  app/connector/support/component/http/src/main/resources/META-INF/spring.factories
  app/connector/support/component/http/src/main/resources/META-INF/spring.provides
  app/connector/support/component/pom.xml
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
  app/meta/pom.xml
  app/meta/src/main/java/io/syndesis/connector/meta/impl/HttpVerifier.java
  app/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/ui/src/assets/icons/http4.connection.png
  app/ui/src/assets/icons/http4.integration.png
Labels: approved, group/connector, target/tp4

#1810 fix(jsondb): use in-memory database for tests
  app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
Labels: approved, cat/techdebt, size/s

#1811 chore: remove unused connector/support/verifier
  app/connector/pom.xml
  app/connector/support/verify/pom.xml
  app/connector/support/verify/src/main/java/io/syndesis/connector/support/verifier/ConnectorVerifier.java
Labels: approved

#1803 general improvements to integration UI, add mixin/helper class for toolbar
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/edit-page.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.ts
  app/ui/src/app/integration/integration-common.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/scss/base/_mixins.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved

#1812 Dropbox
  app/connector/dropbox/pom.xml
  app/connector/dropbox/src/main/java/io/syndesis/connector/dropbox/DropBoxVerifier.java
  app/connector/dropbox/src/main/java/io/syndesis/connector/dropbox/DropBoxVerifierAutoConfiguration.java
  app/connector/dropbox/src/main/java/io/syndesis/connector/dropbox/DropBoxVerifierExtension.java
  app/connector/dropbox/src/main/resources/META-INF/spring.factories
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/verifier/dropbox
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/meta/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: approved

#1814 refactor(connector): dropbox connector, lets use only the options we …
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: approved

#1819 When publishing an integration, change pending state wording from "in progress" to "publishing"
  app/ui/src/app/integration/list/status.component.ts
Labels: approved

#1820 Fix/1730 replace metrics ui values
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/common/duration.pipe.ts
  app/ui/src/app/common/index.ts
  app/ui/src/app/dashboard/dashboard.component.html
  app/ui/src/app/dashboard/dashboard.component.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.spec.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.html
  app/ui/src/app/integration/integration_detail/integration-metrics.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/platform/types/integration/integration.reducer.ts
Labels: approved

#1816 Related to #1752: add extension-tag dependency type
  app/common/model/src/main/java/io/syndesis/common/model/Dependency.java
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestResourceManager.java
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/IntegrationConfiguration.java
Labels: approved

#1821 fix: CSS bugfix to force integration detail page span 100% vertically
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
Labels: approved

#1813 Reuse image
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
  app/server/controller/src/main/java/io/syndesis/server/controller/StateUpdate.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/DemoHandlerProvider.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/OnlineHandlerProvider.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/IntegrationHandlerTest.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/MetricsCollector.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/DeploymentData.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: approved

#1834 refactor(connector): Added icons for dropbox connector
  app/ui/src/assets/icons/dropbox.connection.png
  app/ui/src/assets/icons/dropbox.integration.png
Labels: approved

#1835 fix(integration): use the scheme-index endpoint URI
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/EndpointStepHandler.java
Labels: approved, group/connector, size/s

#1829 Nicer error handling when fetching dynamic metadata
  app/common/model/src/main/java/io/syndesis/common/model/connection/DynamicActionMetadata.java
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/MetadataRetrieval.java
  app/meta/src/main/java/io/syndesis/connector/meta/VerifierExceptionMapper.java
  app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java
  app/meta/src/main/java/io/syndesis/connector/meta/v1/metadata/SalesforceMetadataRetrieval.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Mixed.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/exception/Errors.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/dto/MixedTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java
  app/server/runtime/src/test/resources/application-test.yml
  app/server/verifier/src/main/java/io/syndesis/server/verifier/AlwaysOkVerifier.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/MetadataConfigurationProperties.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/VerifierConfiguration.java
  app/ui/src/app/api/api.module.ts
  app/ui/src/app/api/providers/api-http-interceptor.service.ts
  app/ui/src/app/api/providers/index.ts
  ruleset.xml
Labels: approved, group/connector, group/meta, group/server, group/ui, size/m

#1836 refactor(connector): Fix labels and removed oAuth stuff for Dropbox
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: approved

#1838 fix(syndesis minishift): Fixed typos on --yes option
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: approved

#1843 fix: ensure the start/finish step indices update properly
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
Labels: group/ui

#1845 fix(runtime): reintroduce H2 as runtime dependency
  app/server/runtime/pom.xml
Labels: approved

#1848 Fix syndesis extension plugin
  app/extension/maven-plugin/pom.xml
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/RepackageExtensionMojo.java
Labels: approved

#1850 chore: align log ui and handler with UX designs.
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/LogStepHandler.java
  app/server/runtime/pom.xml
  app/ui/src/app/store/step/step.store.ts
Labels: approved

#1852 UX Design: Log Step config
  ux/README.md
  ux/designs/logstep/img/choosestep.png
  ux/designs/logstep/img/configurestep.png
  ux/designs/logstep/logstep.md
Labels: approved

#1851 fix: cancel action modal CTAs enhanced according to UXD requirement
  app/ui/src/app/common/cancel_confirmation_modal/cancel-confirmation-modal.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
Labels: approved, group/ui, group/uxd, notif/uxd

#1849 Fix relative parent locations.
  app/server/logging/jsondb/pom.xml
  app/server/metrics/jsondb/pom.xml
  app/server/metrics/prometheus/pom.xml
Labels: approved

#1846 fix: debugger tracer element removed
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
Labels: approved, cat/blocker, cat/bug, group/ui, target/tp4

#1854 feat: integration activity list sorted by date
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
Labels: approved

#1858 Server, sanitize ids in labels
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
Labels: approved

#1861 updates to integration details panel and tab name
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
Labels: approved

#1863 Bumped Prometheus version to 2.1.0
  install/generator/syndesis-template.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: approved

#1864 Slack connector
  app/connector/pom.xml
  app/connector/slack/pom.xml
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackConnectorFactory.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/connector/support/catalog/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/ui/src/assets/icons/slack.connection.png
  app/ui/src/assets/icons/slack.integration.png
Labels: approved

#1866 fix(connector): Dropbox connector should point to the correct parent POM
  app/connector/dropbox/pom.xml
Labels: approved

#1869 refactor(keygenerator): Changed to make it possible to use ids as label values
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
Labels: approved

#1870 refactor(connector): Slack Connector, use a SlackChannelCustomizer in…
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackChannelCustomizer.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackConnectorFactory.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: approved

#1871 fix: Fix usage of openshiftName method for BC
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
Labels: approved

#1873 refactor(connector): removed timer, since we already have the extension
  app/connector/pom.xml
  app/connector/timer/pom.xml
  app/connector/timer/src/main/java/io/syndesis/connector/timer/PeriodicTimerComponent.java
  app/connector/timer/src/main/resources/META-INF/services/org/apache/camel/component/periodic-timer-connector
  app/connector/timer/src/main/resources/camel-connector-schema.json
  app/connector/timer/src/main/resources/camel-connector.json
Labels: approved

#1805 Reduce the number of DB rows needed to ingest integration activity events.
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/service/DBActivityTrackingService.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/resources/logs-controller-db.json
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/runtime/src/test/resources/logs-controller-db.json
  ruleset.xml
Labels: approved

#1664 feat(forms): add support for new tooltip properties
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/ui/package.json
  app/ui/src/app/app.module.ts
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/core/core.module.ts
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/platform/types/form-factory/form-factory.service.ts
  app/ui/src/app/platform/types/platform.models.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/support/support.component.ts
  app/ui/yarn.lock
Labels: approved, group/ui

#1883 ProjectGenerator, fix support for external Maven repos
  app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorAutoConfiguration.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
  project/DevelopersGuide.md
Labels: approved

#1885 Fix broken labels
  app/common/util/src/main/java/io/syndesis/common/util/Labels.java
  app/common/util/src/main/java/io/syndesis/common/util/Names.java
  app/common/util/src/main/java/io/syndesis/common/util/Strings.java
  app/common/util/src/test/java/io/syndesis/common/util/LabelsTest.java
  app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/resources/logs-controller-db.json
  app/server/logging/jsondb/src/test/resources/test-pod-x23x.txt
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  ruleset.xml
Labels: approved

#1889 chore: Move inner class of Meta to top-level
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java
Labels: approved

#1897 feat(connector): Added Slack Verifier
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifier.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierAutoConfiguration.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java
  app/connector/slack/src/main/resources/META-INF/spring.factories
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/meta/pom.xml
Labels: approved

#1898 refactor(connectors): add connector-dropbox and connector-slack to de…
  app/meta/pom.xml
  app/pom.xml
Labels: approved

#1899 fix(meta): increased timeout to 15 seconds and added warning
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Meta.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/MetadataConfigurationProperties.java
Labels: approved, group/meta, group/server, size/s

#1900 refactor(connector): no need for META-INF verifier in Dropbox connector
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/verifier/dropbox
Labels: approved

#1901 refactor(connector): order the options of dropbox connector at connect…
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: approved

#1904 refactor(connector): Add order to slack connection options
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: approved

#1902 fix: don't overwrite data shapes if the new ones don't have a specification
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: group/ui

#1905 fix: integration monitoring metrics updated to reflect new API response schema
  app/ui/src/app/platform/types/integration/integration.effects.ts
Labels: approved

#1906 fix: rework integration renaming, remove toast popup
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
Labels: group/ui

#1908 chore: icons for ftp/sftp
  app/ui/src/assets/icons/ftp.connection.png
  app/ui/src/assets/icons/ftp.integration.png
  app/ui/src/assets/icons/sftp.connection.png
  app/ui/src/assets/icons/sftp.integration.png
Labels: approved, group/ui

#1911 feat(forms): add support for placeholder text in form controls
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentDefinition.java
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: approved, group/connector, group/ui

#1910 Added Property relation to support conditional UI control of properties Backend feature required for #887
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/PropertyRelation.java
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentDefinition.java
Labels: approved

#1918 Import/Export UI: Review, Redirect
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.scss
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.models.ts
Labels: group/ui

#1919 chore(fix): remove property relation from ComponentDefinition
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentDefinition.java
Labels: approved

#1920 Use --template param explicitly with oc new-app
  app/test/src/test/resources/setup.sh
  install/README.md
  install/staging/README.md
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: approved

#1923 fix: NPE when parsed properties are null.
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
Labels: approved

#1922 Fixes #1855: Allow correlating a Activity Step back to the step id in an integration.
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/resources/logs-controller-db.json
Labels: approved

#1927 refactor(connector): make the empty bodies a no-op
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
Labels: approved, group/connector, size/s

#1925 fix(common): names should not include underscore
  app/common/util/src/main/java/io/syndesis/common/util/Names.java
  app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
Labels: approved

#1929 fix: filter null keys and values before adding them to the properties.
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
Labels: approved

#1917 fix(donut): remove draft state from dashboard integrations donut
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
Labels: approved, group/ui

#1933 feature: integration activity steps logs
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/common/duration-diff.pipe.ts
  app/ui/src/app/common/duration.pipe.ts
  app/ui/src/app/common/index.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.spec.ts
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.html
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: approved

#1913 Replace instances of activate/deactivate with publish/unpublish
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/list/action-menu.component.ts
Labels: approved

#1934 fix: prefer the step name over prettifying the step kind
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: approved

#1798 feature: upload JDBC Driver to verifier
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlConnectionRule.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
  app/connector/sql/src/test/resources/test-options.properties
  app/meta/pom.xml
  app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java
  app/meta/src/test/java/io/syndesis/connector/meta/v1/DriverUploadTest.java
  app/meta/src/test/resources/drivers/syndesis-library-jdbc-1.0.0.jar
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/DefaultVerifierExtensionUploader.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionActivator.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/NoopVerifierExtensionUploader.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/VerifierExtensionUploader.java
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-verifier.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: approved, target/tp4

#1935 fix: Closing resultSets explicitly
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java
Labels: approved

#1944 refactor(connector): Upload Action of dropbox Connector requires remo…
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: approved

#1946 refactor(connectors): Dropbox connector, verify the credentials only …
  app/connector/dropbox/src/main/java/io/syndesis/connector/dropbox/DropBoxVerifierExtension.java
Labels: approved

#1926 refactor(system-tests): upgrades and cleanup
  app/common/pom.xml
  app/pom.xml
  app/server/pom.xml
  app/test/pom.xml
  app/test/src/test/java/io/syndesis/systests/DeploymentTest.java
  app/test/src/test/resources/arquillian.xml
  app/test/src/test/resources/setup.sh
Labels: approved

#1937 feat: add missing goals from plugin execution phases.
  app/extension/maven-plugin/pom.xml
  app/server/builder/maven-plugin/pom.xml
Labels: approved

#1950 Fix driver upload management
  app/meta/pom.xml
  app/meta/src/main/fabric8-includes/run-env.sh
  app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java
  app/meta/src/test/java/io/syndesis/connector/meta/v1/DriverUploadTest.java
  app/pom.xml
  install/generator/04-syndesis-verifier.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: approved

#1951 chore: Update to AtlasMap 1.33.6
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: approved

#1953 fix(forms): update event bindings
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.ts
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.spec.ts
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts
Labels: approved, group/ui

#1958 fix: Custom API Connector delete button is back with a repurposed confirmation modal
  app/ui/src/app/common/delete_confirmation_modal/delete-confirmation-modal.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.ts
Labels: approved

#1960 adding error message to the exception thrown to be more specific #1936
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/MetadataRetrieval.java
Labels: approved

#1964 fix: reset the data shape if the incoming type is kind=none
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: approved

#1963 UX - Connection Icon Assets Folder Created
  ux/connections_icons/png/connectionicons_AMQP.png
  ux/connections_icons/png/connectionicons_AWS-S3.png
  ux/connections_icons/png/connectionicons_SQL.png
  ux/connections_icons/png/connectionicons_activeMQ.png
  ux/connections_icons/png/connectionicons_day_trade.png
  ux/connections_icons/png/connectionicons_facebook.png
  ux/connections_icons/png/connectionicons_ftp.png
  ux/connections_icons/png/connectionicons_github.png
  ux/connections_icons/png/connectionicons_gmail.png
  ux/connections_icons/png/connectionicons_google.png
  ux/connections_icons/png/connectionicons_http.png
  ux/connections_icons/png/connectionicons_https.png
  ux/connections_icons/png/connectionicons_linkedin.png
  ux/connections_icons/png/connectionicons_messaging.png
  ux/connections_icons/png/connectionicons_mqtt.png
  ux/connections_icons/png/connectionicons_salesforce.png
  ux/connections_icons/png/connectionicons_servicenow.png
  ux/connections_icons/png/connectionicons_sftp.png
  ux/connections_icons/png/connectionicons_timer.png
  ux/connections_icons/png/connectionicons_trade_insight.png
  ux/connections_icons/png/connectionicons_twitter.png
  ux/connections_icons/svg/connectionicons_AMQP.svg
  ux/connections_icons/svg/connectionicons_AWS-S3.svg
  ux/connections_icons/svg/connectionicons_SQL.svg
  ux/connections_icons/svg/connectionicons_activeMQ.svg
  ux/connections_icons/svg/connectionicons_day_trade.svg
  ux/connections_icons/svg/connectionicons_facebook.svg
  ux/connections_icons/svg/connectionicons_ftp.svg
  ux/connections_icons/svg/connectionicons_github.svg
  ux/connections_icons/svg/connectionicons_gmail.svg
  ux/connections_icons/svg/connectionicons_google.svg
  ux/connections_icons/svg/connectionicons_http.svg
  ux/connections_icons/svg/connectionicons_https.svg
  ux/connections_icons/svg/connectionicons_linkedin.svg
  ux/connections_icons/svg/connectionicons_messaging.svg
  ux/connections_icons/svg/connectionicons_mqtt.svg
  ux/connections_icons/svg/connectionicons_salesforce.svg
  ux/connections_icons/svg/connectionicons_servicenow.svg
  ux/connections_icons/svg/connectionicons_sftp.svg
  ux/connections_icons/svg/connectionicons_timer.svg
  ux/connections_icons/svg/connectionicons_trade_insight.svg
  ux/connections_icons/svg/connectionicons_twitter.svg
Labels: approved, cat/design

#1965 fix: support for lowercase SQL #1853
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
  app/connector/sql/src/test/resources/test-options.properties
Labels: approved

#1969 Update connection details toolbarUI
  app/ui/src/app/connections/detail-page/breadcrumb.component.ts
  app/ui/src/scss/base/_mixins.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved

#1970 Templates, bumped verifier pvc demands to 1Gi
  install/generator/01-header.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: approved

#1977 SFTP and FTP descriptions
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: approved

#1979 refactor(server): return status 400 for errors from meta
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Labels: approved

#1966 Install script, add support for route auto discovery
  tools/bin/install-syndesis
Labels: approved

#1984 fix(monitoring): Duration formatting fixed for Integration activity logs
  app/ui/src/app/common/duration.pipe.ts
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
Labels: approved, cat/bug, group/ui

#1978 chore(build): add test reports from UI to CircleCI
  .circleci/config.yml
  app/ui/karma.conf.js
Labels: approved

#1987 Extension input labels using description
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
Labels: approved

#1995 fix: adding start stored procedure 'create_lead', fixing issue with t…
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/stored/StoredProcedureColumn.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredConnectorMetaDataExtensionTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredProcedureTest.java
  app/connector/sql/src/test/resources/sql/demo_add_metadata.json
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: approved

#1996 update wording on start/finish connection steps
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
Labels: approved

#2002 fix: adding test back #560
  app/server/dao/src/test/java/io/syndesis/server/dao/DeploymentDescriptorIT.java
Labels: approved

#2001 fix: Setting Twitter Search period type to duration #220
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
Labels: approved

#2004 chore: Adding test resulting in InputShape of none
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataAdapterTest.java
  app/connector/sql/src/test/resources/sql/name_sql_no_param_metadata.json
Labels: approved

#2005 chore: white space.
  app/connector/odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorAutoConfiguration.java
  app/connector/odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorConfiguration.java
  app/connector/odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorConfigurationCommon.java
  app/connector/odata/create-entity/src/main/resources/camel-connector-schema.json
  app/connector/odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorAutoConfiguration.java
  app/connector/odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorConfiguration.java
  app/connector/odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorConfigurationCommon.java
  app/connector/odata/delete-entity/src/main/resources/camel-connector-schema.json
  app/connector/odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorAutoConfiguration.java
  app/connector/odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorConfiguration.java
  app/connector/odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorConfigurationCommon.java
  app/connector/odata/replace-entity/src/main/resources/camel-connector-schema.json
  app/connector/odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorAutoConfiguration.java
  app/connector/odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorConfiguration.java
  app/connector/odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorConfigurationCommon.java
  app/connector/odata/retrieve-entity/src/main/resources/camel-connector-schema.json
  app/connector/odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorAutoConfiguration.java
  app/connector/odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorConfiguration.java
  app/connector/odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorConfigurationCommon.java
  app/connector/odata/update-entity/src/main/resources/camel-connector-schema.json
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConnectorAutoConfiguration.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConnectorConfiguration.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConnectorConfigurationCommon.java
  app/connector/rest-swagger/src/main/resources/camel-connector-schema.json
Labels: approved

#2006 fix: relaxing the assertions so one can add a connector w/o violating…
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: approved

#2008 fix(connectors): Duplicate version declarations in "slack connector"
  app/pom.xml
Labels: approved

#1999 change "select connection type" to "select connector"
  app/ui/src/app/connections/create-page/create-page.component.html
Labels: approved

#2009 fix: Proper commit of pom.xml files
  tools/bin/commands/release
Labels: cat/tooling

#2010 Add changelog
  CHANGELOG.md
Labels: approved

#2018 fix(meta): set-env.sh works now also with -e
  app/meta/src/main/fabric8-includes/run-env.sh
Labels: approved

#1998 [UX Design] Update integration details page design to reflect the tabs
  ux/designs/integration_details/img/integration_details_page_1.22_expand_scroll_BOM.png
  ux/designs/integration_details/img/integration_details_page_3.14_being_published.png
  ux/designs/integration_details/img/integration_details_page_3.14_confirm_delete.png
  ux/designs/integration_details/img/integration_details_page_3.14_error.png
  ux/designs/integration_details/img/integration_details_page_3.14_expand_scroll_bom.png
  ux/designs/integration_details/img/integration_details_page_3.14_genericlayout.png
  ux/designs/integration_details/img/integration_details_page_3.14_kebab.png
  ux/designs/integration_details/img/integration_details_page_3.14_many_stepsconnections.png
  ux/designs/integration_details/img/integration_details_page_3.14_no_draft.png
  ux/designs/integration_details/img/integration_details_page_3.14_publishversion.png
  ux/designs/integration_details/img/integration_details_page_3.14_replacedraft.png
  ux/designs/integration_details/img/integration_details_page_3.14_spinning_up.png
  ux/designs/integration_details/img/integration_details_page_3.14_warning.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_being_published.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_error.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_genericlayout.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_many_stepsconnections.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_no_draft.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_publishaversion.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_replaceadraft.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_spinning_up.png
  ux/designs/integration_details/img/integration_details_page_rework_11.16_warning.png
  ux/designs/integration_details/img/integration_details_page_rework_11.21_kebab.png
  ux/designs/integration_details/integration_details_page.md
Labels: approved, group/ui, group/uxd, notif/doc

#2016 fix(server): fix connection leak
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
Labels: approved

#2019 fix: remove connection tags and don't set them
  app/ui/src/app/connections/create-page/current-connection.ts
  app/ui/src/app/connections/detail-page/info.component.ts
Labels: approved

#2020 Fixing up activity log, we now show proper step names for connection steps. Also fix duration units and improve display precision when dealing with small durations. This also now shows log messages.
  app/ui/src/app/common/duration.pipe.ts
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: approved

#2022 chore: Update Fabric8 Maven Plugin to version 3.5.38
  app/pom.xml
Labels: approved

#1981 fix(server): try to use correct input/output shapes
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
Labels: approved

#2025 chore: suppress circular reference warnings
  app/ui/.angular-cli.json
Labels: approved

#2026 fix: disable create button when the review form is invalid, suppress duplicate clicks too
  app/ui/src/app/connections/create-page/create-page.component.html
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/app/connections/create-page/current-connection.ts
  app/ui/src/app/connections/create-page/review/review.component.ts
Labels: approved

#2034 Fix overflow issues on data mapper page
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
Labels: approved

#2039 fix: [metrics] setting system uptime to server pod uptime
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/metrics/SQLMetricsProviderImpl.java
  app/server/metrics/prometheus/pom.xml
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/server/metrics/prometheus/src/test/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImplTest.java
Labels: approved

#2037 update settings description, add callback url
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
Labels: approved

#2043 fix(amq-connection): tweak forms to avoid double negative
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
Labels: approved, group/ui

#2040 refactor(server): use proper property name
  app/common/pom.xml
  app/integration/project-generator/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/connector/pom.xml.mustache
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java
  app/integration/project-generator/src/test/resources/test.properties
  app/server/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/pom.xml
Labels: approved

#2048 fix: scrolling fixed for Integration activity steps logs output
  app/ui/src/app/common/duration.pipe.ts
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration-activity/integration-activity.component.scss
  app/ui/src/scss/base/_extends.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved

#2047 clean up settings page markup/css, remove persistent scrollbar
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.scss
Labels: approved

#2052 fix: set mapping config the same way we set other configured properties
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: group/ui

#2053 feat: action filtering now takes into consideration output data shape…
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
Labels: approved
