Repository syndesisio/syndesis, pull requests merged in 2018-10, with the labels that each got.

#3704 fix(tools): fix pod list passing
  tools/bin/commands/dev
Labels: pr/approved

#3705 Bump Assertj to version 3.11.1
  app/pom.xml
Labels: pr/approved

#3706 Upgraded to latest Apicurio release (0.2.15). Fixes #3647.
  app/ui/package.json
Labels: pr/approved

#3634 Fix #3460: use a new pv for upgrade
  install/operator/deploy/syndesis.yml
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/needs-backport, pr/review-requested

#3711 Upgrade Maven Resolver Api to version 1.1.1
  app/pom.xml
  app/ui/yarn.lock
Labels: pr/approved

#3713 Fix volume capacity in #3460
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#3703 Complete API Provider creation flow
  app/ui/src/app/common/openapi/openapi.models.ts
  app/ui/src/app/common/openapi/review/review.component.html
  app/ui/src/app/common/openapi/review/review.component.ts
  app/ui/src/app/integration/api-provider/api-provider.actions.ts
  app/ui/src/app/integration/api-provider/api-provider.effects.ts
  app/ui/src/app/integration/api-provider/api-provider.guard.ts
  app/ui/src/app/integration/api-provider/api-provider.models.ts
  app/ui/src/app/integration/api-provider/api-provider.module.ts
  app/ui/src/app/integration/api-provider/api-provider.reducer.ts
  app/ui/src/app/integration/api-provider/api-provider.service.ts
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.html
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-name/step-name.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-name/step-name.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.ts
  app/ui/src/app/integration/api-provider/index.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.scss
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3721 ui text update: Update Slack connector display names to be consistent with other connectors
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved, pr/review-requested

#3722 chore: Update to AtlasMap 1.37.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#3712 Fix #3460: in 1.4.x
  app/connector/rest-swagger/src/main/resources/camel-connector-schema.json
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/deploy/syndesis.yml
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3723 fix: time formatting location aware
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
Labels: pr/approved

#3726 feat: proper base path handling in API provider integrations
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/connector/api-provider/pom.xml
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderServletAutoConfiguration.java
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/RestRouteConfiguration.java.mustache
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorMain.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRouteConfiguration.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/DeploymentData.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved

#3715 refactor: remove `/apis/generator/save` endpoint
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowImportSetCustomizer.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/MetaData.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/api/ApiHandler.java
  ruleset.xml
Labels: pr/approved

#3728 fix: UT010029: Stream is closed with WebHook connector
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/WrapperProcessorTest.java
Labels: pr/approved

#3732 refactor: don't expose WebHook integrations via 3scale
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationBaseTest.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizerTest.java
Labels: pr/approved

#3734 Connections and Step Icons Added
  ux/connections_icons/png/connectionicons_SQL.png
  ux/connections_icons/png/connectionicons_advancedfilter.png
  ux/connections_icons/png/connectionicons_basicfilter.png
  ux/connections_icons/png/connectionicons_datamapper.png
  ux/connections_icons/png/connectionicons_fhir.png
  ux/connections_icons/png/connectionicons_googlecalendar.png
  ux/connections_icons/png/connectionicons_googledrive.png
  ux/connections_icons/png/connectionicons_http.png
  ux/connections_icons/png/connectionicons_logstep.png
  ux/connections_icons/png/connectionicons_templatestep.png
  ux/connections_icons/png/connectionicons_timer.png
  ux/connections_icons/png/connectionicons_workday.png
  ux/connections_icons/svg/connectionicons_SQL.svg
  ux/connections_icons/svg/connectionicons_advancedfilter.svg
  ux/connections_icons/svg/connectionicons_basicfilter.svg
  ux/connections_icons/svg/connectionicons_datamapper.svg
  ux/connections_icons/svg/connectionicons_fhir.svg
  ux/connections_icons/svg/connectionicons_googlecalendar.svg
  ux/connections_icons/svg/connectionicons_googledrive.svg
  ux/connections_icons/svg/connectionicons_http.svg
  ux/connections_icons/svg/connectionicons_kafka.svg
  ux/connections_icons/svg/connectionicons_logstep.svg
  ux/connections_icons/svg/connectionicons_templatestep.svg
  ux/connections_icons/svg/connectionicons_timer.svg
  ux/connections_icons/svg/connectionicons_workday.svg
Labels: pr/approved

#3737 refactor(connector): Make the channel selection for Slack Producer dy…
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved

#3739 First draft github issues introduction
  doc/sdh/development/comms.adoc
  doc/sdh/development/index.adoc
Labels: pr/approved, pr/review-requested

#3742 fix(server): NPE in API provider Integration generation
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
Labels: pr/approved, pr/review-requested

#3709 fix(notifications): Extract reasoning for artifacts differing
  app/common/model/src/main/java/io/syndesis/common/model/action/Action.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java
  app/common/model/src/main/java/io/syndesis/common/model/extension/Extension.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java
  app/common/model/src/main/java/io/syndesis/common/model/support/EquivContext.java
  app/common/model/src/main/java/io/syndesis/common/model/support/EquivPair.java
  app/common/model/src/main/java/io/syndesis/common/model/support/Equivalencer.java
  app/common/model/src/test/java/io/syndesis/common/model/support/EquivalencerTest.java
  app/common/util/src/main/java/io/syndesis/common/util/StringConstants.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
Labels: pr/approved, pr/review-requested

#3751 refactor(api): POST /api/v1/integration-support/import response
  app/common/model/src/main/java/io/syndesis/common/model/Kind.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved, pr/review-requested

#3750 fix(connector): Fix google-calendar-connector behavior when the updat…
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
Labels: pr/approved

#3749 ENTESB-9439: Prevent snyk being run in prod environment
  app/ui/package.json
Labels: pr/approved

#3752 refactor(connector): Update actions description for Google calendar c…
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3748 refactor IVP code
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3759 Fixes usage count for Connections and Extensions
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandlerTest.java
Labels: pr/approved, pr/review-requested

#3758 chore(connector): update icons in connectors
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
  app/connector/log/src/main/resources/META-INF/syndesis/connector/log.json
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
  app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
  app/connector/servicenow/src/main/resources/META-INF/syndesis/connector/servicenow.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: pr/approved

#3772 fix(connector): fix the delay option on slack connector
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#3773 Mark API Provider as tech preview #3764
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
Labels: pr/approved

#3777 refactor(connector): Better description for google-calendar connector…
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3779 chore: Update Data Mapper doc about DataShape.kind = `none` (#3542)
  app/server/docs/design/datamapper.md
Labels: pr/approved

#3720 WIP: Updated Slack user doc to add ability to obtain messages
  doc/connecting/topics/add_slack_connection_middle_finish.adoc
  doc/connecting/topics/add_slack_connection_start.adoc
  doc/connecting/topics/adding_slack_connections.adoc
  doc/connecting/topics/connecting_to_slack.adoc
  doc/connecting/topics/creating_slack_connections.adoc
  doc/connecting/topics/supported_connectors.adoc
  doc/shared/register_with_sf.adoc
Labels: pr/approved

#3782 fix(server): Swagger tags sanitization
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
Labels: pr/approved

#3783 Changes to tooltip functionality on step icons.
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
Labels: pr/approved, pr/review-requested

#3785 Google calendar refactor of fields and descriptions
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3792 fix(connector): Http Connector - HTTP Consumer fails to follow redirect.
  app/connector/http/pom.xml
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorFactories.java
Labels: pr/approved

#3795 refactor(IVP): remove alert from data mismatch icon popover
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
Labels: pr/approved, pr/review-requested

#3810 refactor(IVP): multistep step icon lines no longer overlap
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3812 fix(connector): fix google-calendar-connector get events action last …
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#3813 refactor(connector): Fix description of query events string, more inf…
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3819 Fix issue with overwritten templates
  install/generator/01-header.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#3822 Fix issue with overwritten templates on master
  install/generator/01-header.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#3821 chore: Update to AtlasMap 1.38.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#3824 refactor(IVP): fix the lines and overlapping with the api multistep icon in the IVP
  app/ui/src/app/common/openapi/editor/editor.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3835 fix(connector): Google Calendar Connector: Create Event NPE on empty …
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventsCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/utils/GoogleCalendarUtils.java
Labels: pr/approved

#3836 fix: allow uploading openapi specs as yaml
  app/ui/src/app/common/openapi/uploader/uploader.component.html
  app/ui/src/app/common/openapi/uploader/uploader.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3762 [fix] Failed to stop integration #3405
  app/ui/src/app/core/providers/integration-support-provider.service.ts
Labels: group/ui, pr/approved, pr/review-requested, size/s

#3837 Fix #3828
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventsCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
Labels: pr/approved

#3771 fix(performance) Reduce CPU usage of syndesis server
  app/common/model/src/main/java/io/syndesis/common/model/validation/TargetWithDomain.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/connection/ConnectionWithDomain.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/extension/ExtensionWithDomain.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/integration/IntegrationWithDomain.java
  app/server/dao/src/main/java/io/syndesis/server/dao/validation/extension/NoDuplicateExtensionValidator.java
  app/server/dao/src/main/java/io/syndesis/server/dao/validation/integration/NoDuplicateIntegrationValidator.java
  app/server/dao/src/test/java/io/syndesis/server/dao/validation/NoDuplicateValidatorTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#3838 fix: consistent date formatting across the UI
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/common/date.pipe.ts
  app/ui/src/app/common/index.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.html
  app/ui/src/app/integration/integration_detail/integration-metrics.component.ts
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
  app/ui/src/app/integration/integration_logs/integration-logs.component.html
Labels: pr/approved, pr/review-requested

#3839 fix(API/Apicurio): fix z-index issue with apicurio editor when creating API integration
  app/ui/src/app/common/openapi/editor/editor.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-multiflow.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3842 chore: add built-in step icons; update icon pipe accordingly
  .gitignore
  app/ui/src/app/common/icon-path.pipe.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/assets/icons/steps/expressionFilter.svg
  app/ui/src/assets/icons/steps/log.svg
  app/ui/src/assets/icons/steps/mapper.svg
  app/ui/src/assets/icons/steps/ruleFilter.svg
  app/ui/src/assets/icons/steps/template.svg
Labels: pr/approved

#3781 bug(badge): fix oval shape for api flow count badge, add tooltip
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.scss
Labels: pr/approved, pr/review-requested

#3845 feat(integrationdetails): add support for step icons
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
Labels: pr/approved, pr/review-requested

#3847 fix: save the integration when going back to the operation list
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
Labels: pr/approved

#3850 feature(syndesis): Add '-m upgrade' for creating the upgrade pod
  .circleci/config.yml
  doc/sdh/cli/cmd_build.adoc
  tools/bin/commands/build
Labels: pr/approved

#3852 fix: proper page scrolling with many operations.
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
Labels: pr/approved

#3858 Empty first column in the integration flow view
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/OperationDescription.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperOperationDescriptionGenerationTest.java
  app/server/api-generator/src/test/resources/swagger/empty-summary.json
Labels: pr/approved

#3860 Fix #3800: choose a specific rest implementation
  app/connector/rest-swagger/src/main/resources/camel-connector.json
Labels: pr/approved, pr/review-requested

#3866 fix(connector): remove all non-Syndesis headers
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java
Labels: pr/approved, pr/review-requested

#3867 fix: only allow the data mapper to be used if the next step that has a datashape is not none/any
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved

#3862 fix: add IVP titles for the API Provider pages
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: pr/approved, pr/review-requested

#3868 fix: ensure the publish draft button is available for a running integration
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
Labels: pr/approved

#3874 fix: hide flow name in the IVP when creating a new integration
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: pr/approved

#3876 fix: show the number of integrate flows, not the total count
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/integration/integration.service.ts
Labels: pr/approved

#3877 fix: handle redirect to the api provider creation page when hitting the browser's back button
  app/ui/src/app/app.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
Labels: pr/approved

#3879 fix(connector): Google Calendar connector: Update/Create event action…
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
Labels: pr/approved

#3869 fix(Template Step) Wording problems and abnormalities
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
  app/ui/src/app/store/step/step.store.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3882 fix: hide API Provider from the list of end connections
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#3885 fix: swap ngif blocks from likely bad merge
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: pr/approved

#3883 fix: manually trigger data mapper line machine component after init
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved

#3873 Fixes 3408, added external Prometheus configuration to documentation
  doc/managing_environments/topics/external_prometheus.adoc
  doc/managing_environments/topics/metrics.adoc
Labels: pr/approved, pr/review-requested

#3825 user doc: Modularize content in the tutorials.
  doc/connecting/docinfo.xml
  doc/connecting/master.adoc
  doc/connecting/topics/adding_twitter_connections.adoc
  doc/connecting/topics/connecting_to_sf.adoc
  doc/connecting/topics/connecting_to_twitter.adoc
  doc/connecting/topics/triggering_integrations_with_http_requests.adoc
  doc/integrating_applications/docinfo.xml
  doc/integrating_applications/master.adoc
  doc/shared/attributes.adoc
  doc/shared/create_sf_connection.adoc
  doc/shared/create_twitter_connection.adoc
  doc/shared/log_in.adoc
  doc/shared/register_with_sf.adoc
  doc/shared/register_with_twitter.adoc
  doc/tutorials/master-docinfo.xml
  doc/tutorials/master.adoc
  doc/tutorials/topics/amq2api_add_damage_reporter_step.adoc
  doc/tutorials/topics/amq2api_add_mapping_step.adoc
  doc/tutorials/topics/amq2api_choose_finish.adoc
  doc/tutorials/topics/amq2api_choose_start.adoc
  doc/tutorials/topics/amq2api_confirm_works.adoc
  doc/tutorials/topics/amq2api_create_amq_connection.adoc
  doc/tutorials/topics/amq2api_create_connection_to_broker.adoc
  doc/tutorials/topics/amq2api_create_custom_step.adoc
  doc/tutorials/topics/amq2api_create_integration.adoc
  doc/tutorials/topics/amq2api_create_rest_api_connection.adoc
  doc/tutorials/topics/amq2api_create_rest_api_connector.adoc
  doc/tutorials/topics/amq2api_intro.adoc
  doc/tutorials/topics/amq2api_name_and_publish.adoc
  doc/tutorials/topics/amq2api_start_the_broker.adoc
  doc/tutorials/topics/amq2api_upload_todo_app_icon.adoc
  doc/tutorials/topics/clean_up.adoc
  doc/tutorials/topics/comparison_of_sample_integrations.adoc
  doc/tutorials/topics/create_stored_proc_connection.adoc
  doc/tutorials/topics/one_active_integration.adoc
  doc/tutorials/topics/sf2db_add_mapping_step.adoc
  doc/tutorials/topics/sf2db_choose_finish.adoc
  doc/tutorials/topics/sf2db_choose_start.adoc
  doc/tutorials/topics/sf2db_confirm_works.adoc
  doc/tutorials/topics/sf2db_create_db_connection.adoc
  doc/tutorials/topics/sf2db_create_integration.adoc
  doc/tutorials/topics/sf2db_intro.adoc
  doc/tutorials/topics/sf2db_name_and_publish.adoc
  doc/tutorials/topics/sf2db_prereqs.adoc
  doc/tutorials/topics/t2sf_add_filter_step.adoc
  doc/tutorials/topics/t2sf_add_mapping_step.adoc
  doc/tutorials/topics/t2sf_choose_finish.adoc
  doc/tutorials/topics/t2sf_choose_start.adoc
  doc/tutorials/topics/t2sf_confirm_working.adoc
  doc/tutorials/topics/t2sf_create_integration.adoc
  doc/tutorials/topics/t2sf_intro.adoc
  doc/tutorials/topics/t2sf_name_and_publish.adoc
  doc/tutorials/topics/t2sf_prereqs.adoc
Labels: pr/review-requested

#3893 fix(template step) - Add variable symbol validation
  app/ui/src/app/integration/edit-page/step-configure/templater/mustache-mode.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3891 Upgraded to the latest Apicurio editor release: 0.2.17
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#3897 UI incorrectly indicates Telegram connector is Technology Preview
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#3899 fix(connector): don't set `application/json` as Accept by default
  app/connector/rest-swagger/src/main/resources/camel-connector.json
Labels: pr/approved

#3890 Converting OpenAPI Customization wizard to use common components
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-editor/api-connector-editor.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-editor/api-connector-editor.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-editor/index.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html
  app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
  app/ui/src/app/customizations/api-connector/api-connector.actions.ts
  app/ui/src/app/customizations/api-connector/api-connector.effects.ts
  app/ui/src/app/customizations/api-connector/api-connector.models.ts
  app/ui/src/app/customizations/api-connector/api-connector.module.ts
  app/ui/src/app/customizations/api-connector/api-connector.reducer.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3908 fix: check the metadata map for a step when canceling to ensure we don't delete steps that have no config
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/common/cancel-add-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/approved

#3911 fix(integration-details): fix off-center connection/step icons
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
Labels: pr/approved, pr/review-requested

#3910 fix(connector): remove quotes from simple body values
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
Labels: pr/approved

#3912 [fix] API Provider Data Type Mismatch #3807
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
Labels: pr/approved, pr/review-requested

#3886 fix(ui) Patch codemirror's lint script file
  app/ui/package.json
  app/ui/patches/codemirror+5.40.0.patch
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#3921 fix(step-icons): revert step icons in integration details and editor IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
Labels: pr/approved

#3919 fhir-connector first spike - tech preview
  app/connector/fhir/pom.xml
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetaDataAutoConfiguration.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetaDataExtension.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetadataRetrieval.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadMessageModel.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirUpdateCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirUpdateMessageModel.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirVerifier.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirVerifierAutoConfiguration.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirVerifierExtension.java
  app/connector/fhir/src/main/resources/META-INF/spring.factories
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/fhir/src/main/resources/schemas/dstu3/patient.xsd
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/ui/src/assets/icons/fhir.connection.png
  app/ui/src/assets/icons/fhir.integration.png
Labels: pr/approved

#3929 fix(server): remove dot characters from OpenShift object names
  app/common/util/src/main/java/io/syndesis/common/util/Names.java
  app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
Labels: pr/approved

#3927 fix(template-step) drag and drop overlay reliably displaying
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
Labels: pr/approved, pr/review-requested

#3930 Prevents an extension or connection from being deleted if in use by one or more integrations
  app/ui/src/app/connections/detail-page/info.component.scss
  app/ui/src/app/connections/detail-page/info.component.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/connections/list/list.component.scss
  app/ui/src/app/connections/list/list.component.ts
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts
  app/ui/src/app/platform/types/connection/connection.models.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3935 Fix #3780: use default return code on edit
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
Labels: pr/approved, pr/review-requested

#3937 chore(connector): remove `Exchange.HTTP_URI` header
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
  app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
Labels: pr/approved

#3949 fix(server): make sure the sanitized name has a last alphanumeric character
  app/common/util/src/main/java/io/syndesis/common/util/Names.java
  app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
Labels: pr/approved

#3950 Hide some connections
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/connector/log/src/main/resources/META-INF/syndesis/connector/log.json
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
  app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.ts
  app/ui/src/app/connections/list-page/list-page.component.ts
  app/ui/src/app/dashboard/dashboard.component.ts
  app/ui/src/app/platform/types/connection/connection.models.ts
  app/ui/src/app/store/connection/connection.store.ts
  app/ui/src/app/store/connector/connector.store.ts
Labels: pr/approved, pr/review-requested

#3943 fix(integration): remove flow count from api integration icon
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/list/list.component.html
Labels: pr/approved, pr/review-requested

#3944 fix(integration-editor): fix "add a step" disappearing from IVP popover menus
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
Labels: pr/approved, pr/review-requested

#3936 fix(server): make CORS great again
  app/server/runtime/src/main/java/io/syndesis/server/runtime/SecurityConfiguration.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/SyndesisCorsConfiguration.java
Labels: pr/approved, pr/review-requested

#3939 chore: expose via 3scale configuration in the template and operator
  .pre-commit-config.yaml
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/openshift/register.go
  install/operator/pkg/openshift/serviceaccount/serviceaccount.go
  install/operator/pkg/openshift/template/scheme.go
  install/operator/pkg/openshift/template/templateprocessor.go
  install/operator/pkg/stub/handler.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/startup.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/action/upgradebackoff.go
  install/operator/pkg/syndesis/action/upgradelegacy.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/configuration/envvars.go
  install/operator/pkg/syndesis/configuration/secret.go
  install/operator/pkg/syndesis/configuration/util.go
  install/operator/pkg/syndesis/configuration/version.go
  install/operator/pkg/syndesis/legacy/controller.go
  install/operator/pkg/syndesis/operation/attach.go
  install/operator/pkg/syndesis/operation/utils.go
  install/operator/pkg/syndesis/reconcile.go
  install/operator/pkg/syndesis/template/inspect.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3941 Several cleanups for the operator
  install/operator/.gitignore
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/util/resources_test.go
  install/operator/test/resources/dep.json
  tools/bin/commands/build
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested

#3961 fix(ui): enable gzip for the most relevant mimetypes
  app/server/runtime/src/main/resources/application.yml
  app/ui/docker/nginx-syndesis.conf
Labels: pr/approved

#3968 Fixes 3486, added bridgeErrorHandler to dropbox consumer to report polling errors
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: pr/approved, pr/review-requested

#3966 Fixes 3486, added bridgeErrorHandler to dropbox consumer to report polling errors
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: pr/approved

#3969 chore(settings): remove blue border from oauth app icons
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
Labels: pr/approved, pr/review-requested

#3970 fix(IVP): odd overlap over tooltip feature
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
Labels: pr/approved, pr/review-requested

#3971 chore(integration): update return path icon for api integrations
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.scss
  app/ui/src/assets/icons/multi-flow.connection.png
  app/ui/src/assets/icons/multi-flow.integration.png
Labels: pr/approved, pr/review-requested

#3976 chore: Update to AtlasMap 1.38.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved, pr/needs-backport, pr/review-requested

#3977 chore: Update to AtlasMap 1.38.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/1.5.x, pr/approved

#3964 chore: remove unused png files
  app/ui/src/assets/icons/activemq.connection.png
  app/ui/src/assets/icons/activemq.integration.png
  app/ui/src/assets/icons/amqp.connection.png
  app/ui/src/assets/icons/amqp.integration.png
  app/ui/src/assets/icons/aws-s3.connection.png
  app/ui/src/assets/icons/aws-s3.integration.png
  app/ui/src/assets/icons/day-trade.connection.png
  app/ui/src/assets/icons/day-trade.integration.png
  app/ui/src/assets/icons/facebook.connection.png
  app/ui/src/assets/icons/facebook.integration.png
  app/ui/src/assets/icons/ftp.connection.png
  app/ui/src/assets/icons/ftp.integration.png
  app/ui/src/assets/icons/github.connection.png
  app/ui/src/assets/icons/github.integration.png
  app/ui/src/assets/icons/gmail.connection.png
  app/ui/src/assets/icons/gmail.integration.png
  app/ui/src/assets/icons/google.connection.png
  app/ui/src/assets/icons/google.integration.png
  app/ui/src/assets/icons/http.connection.png
  app/ui/src/assets/icons/http.integration.png
  app/ui/src/assets/icons/http4.connection.png
  app/ui/src/assets/icons/http4.integration.png
  app/ui/src/assets/icons/https4.connection.png
  app/ui/src/assets/icons/https4.integration.png
  app/ui/src/assets/icons/jms.connection.png
  app/ui/src/assets/icons/jms.integration.png
  app/ui/src/assets/icons/linkedin.connection.png
  app/ui/src/assets/icons/linkedin.integration.png
  app/ui/src/assets/icons/messaging.connection.png
  app/ui/src/assets/icons/messaging.integration.png
  app/ui/src/assets/icons/mqtt.connection.png
  app/ui/src/assets/icons/mqtt.integration.png
  app/ui/src/assets/icons/salesforce.connection.png
  app/ui/src/assets/icons/salesforce.integration.png
  app/ui/src/assets/icons/servicenow.connection.png
  app/ui/src/assets/icons/servicenow.integration.png
  app/ui/src/assets/icons/sftp.connection.png
  app/ui/src/assets/icons/sftp.integration.png
  app/ui/src/assets/icons/sql.connection.png
  app/ui/src/assets/icons/sql.integration.png
  app/ui/src/assets/icons/timer.connection.png
  app/ui/src/assets/icons/timer.integration.png
  app/ui/src/assets/icons/trade-insight.connection.png
  app/ui/src/assets/icons/trade-insight.integration.png
  app/ui/src/assets/icons/twitter.connection.png
  app/ui/src/assets/icons/twitter.integration.png
Labels: pr/approved

#3978 bug(integration): Wrong position for warning icon on steps in IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
Labels: pr/approved, pr/review-requested

#3979 fix(integration): show return path icon as end connection in API integration
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: pr/approved

#3980 fix(integration): move data mismatch warning icon on steps in IVP, update API integration return path icon in IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
Labels: pr/approved

#3982 chore: use `http` instead of `https`
  doc/tutorials/topics/amq2api_create_rest_api_connector.adoc
Labels: pr/approved, pr/review-requested

#3995 chore: update the Docker download URL and version
  .circleci/config.yml
Labels: pr/approved

#3994 fix: avoid NPE
  .circleci/config.yml
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
Labels: pr/1.5.x, pr/approved

#3991 fix: rework datashape testing logic, also fix an NPE in the flow view step component
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved

#3987 password should be marked as required
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved

#3997 password should be marked as required (1.5.x backport)
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved

#3993 fix: rework datashape testing logic, also fix an NPE in the flow view step component (1.5.x)
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/store/step/step.store.ts
Labels: pr/1.5.x, pr/approved

#3990 fix(customizations): remove nested card, unused css in api client connector review step.
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.scss
Labels: pr/approved, pr/review-requested
