Repository syndesisio/syndesis, pull requests merged in 2018-12, with the labels that each got.

#4168 I4008
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
Labels: pr/approved, pr/review-requested

#4111 Enhancing the template step
  app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/AbstractTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/FreeMarkerTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/MustacheTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateProcessingException.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateStepConstants.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateStepLanguage.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/TemplateStepPreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/VelocityTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TemplateStepLanguageTest.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestFreeMarkerTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestMustacheTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestVelocityTemplatePreProcessor.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/TemplateStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/MustacheTemplatePreProcessor.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AbstractTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/TemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/FreeMarkerTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/MustacheTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/AbstractVelocityTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/VelocityFormalSyntaxTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/VelocityInformalSyntaxTest.java
  app/ui/package.json
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/abstract-language-lint.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/freemarker-mode-lint.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/index.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/mustache-mode-lint.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/template-symbol.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/codemirror/velocity-lint.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
  app/ui/src/app/store/step/step.store.ts
  app/ui/src/app/vendor/index.ts
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#4201 Update #3620 Google sheets: Add pie chart support
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleChart.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleValueRange.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/CellCoordinateTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/RangeCoordinateTest.java
Labels: pr/approved, pr/review-requested

#4197 Several upgrades to address issues reported by Snyk
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/review-requested

#4209 feat: Have the syndesis build -m operator use build the operator on docker without needing multi-stage builds.
  .circleci/config.yml
  install/operator/Dockerfile-with-build
  install/operator/build.sh
  tools/bin/commands/build
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested

#4210 #4206 Fix generation of connector data shape inspections
  app/connector/activemq/pom.xml
  app/connector/amqp/pom.xml
  app/connector/api-provider/pom.xml
  app/connector/aws-s3/pom.xml
  app/connector/dropbox/pom.xml
  app/connector/fhir/pom.xml
  app/connector/ftp/pom.xml
  app/connector/gmail/pom.xml
  app/connector/google-calendar/pom.xml
  app/connector/google-sheets/pom.xml
  app/connector/http/pom.xml
  app/connector/irc/pom.xml
  app/connector/kafka/pom.xml
  app/connector/log/pom.xml
  app/connector/mqtt/pom.xml
  app/connector/salesforce/pom.xml
  app/connector/servicenow/pom.xml
  app/connector/sftp/pom.xml
  app/connector/slack/pom.xml
  app/connector/sql/pom.xml
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/connector/telegram/pom.xml
  app/connector/timer/pom.xml
  app/connector/twitter/pom.xml
  app/connector/webhook/pom.xml
  app/extension/example/log-step/pom.xml
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#4211 Fixed server builder maven plugin usage
  app/server/builder/maven-plugin/pom.xml
  app/server/runtime/pom.xml
Labels: cat/bug, cat/build, pr/approved, pr/review-requested

#4202 doc(dev): fix ConfigMap name for syndesis-server
  project/DevelopersGuide.md
Labels: pr/approved

#4213 Update #3620: Add pivot table support in Google sheets
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GooglePivotTable.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizerTest.java
Labels: group/connector, pr/approved, pr/review-requested

#4217 fix: Typos in user interface issue template
  .github/ISSUE_TEMPLATE/user-interface.md
Labels: pr/approved

#4220 fix: Several issues affecting productisation (#4155) [backport to master]
  install/generator/02-syndesis-secrets.yml.mustache
  tools/upgrade/common.sh
  tools/upgrade/steps/prep_40_process_template
Labels: pr/approved
