Repository syndesisio/syndesis, pull requests merged in 2018-04, with the labels that each got.

#2217 fix: Correct typos, improve clarity and grammar in labels and hints
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: pr/approved

#2218 feat(describe-data): improve language used around describe data form
  app/ui/src/app/app.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
Labels: pr/approved, pr/review-requested

#2219 chore(install): Add AMQ deployment to templates
  install/generator/04-amq-example.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#2222 Connection card alert styling
  app/ui/src/app/connections/list-page/list-page.component.html
  app/ui/src/app/connections/list-page/list-page.component.scss
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/connections/list/list.component.scss
  app/ui/src/scss/base/_mixins.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: pr/approved

#2221 doc (#883): add doc about our system tests.
  doc/system-tests/README.adoc
Labels: pr/approved

#2207 feature(ui): Full i18N support based on Redux and JSON dictionary files
  app/ui/src/app/app.component.html
  app/ui/src/app/app.module.ts
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/common/i18n.pipe.ts
  app/ui/src/app/core/core.module.ts
  app/ui/src/app/core/factories/index.ts
  app/ui/src/app/core/factories/localstorage.ts
  app/ui/src/app/core/providers/i18n-provider.service.ts
  app/ui/src/app/core/providers/index.ts
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.spec.ts
  app/ui/src/app/platform/index.ts
  app/ui/src/app/platform/platform.module.ts
  app/ui/src/app/platform/types/i18n/README.md
  app/ui/src/app/platform/types/i18n/i18n.actions.ts
  app/ui/src/app/platform/types/i18n/i18n.effects.ts
  app/ui/src/app/platform/types/i18n/i18n.models.ts
  app/ui/src/app/platform/types/i18n/i18n.reducer.ts
  app/ui/src/app/platform/types/i18n/i18n.service.ts
  app/ui/src/app/platform/types/i18n/index.ts
  app/ui/src/app/platform/types/index.ts
  app/ui/src/app/platform/types/platform.effects.ts
  app/ui/src/app/platform/types/platform.reducer.ts
  app/ui/src/assets/.gitkeep
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/src/assets/dictionary/es-ES.json
  app/ui/src/environments/environment.prod.ts
  app/ui/src/environments/environment.ts
  app/ui/src/polyfills.ts
  app/ui/src/tsconfig.json
  app/ui/src/typings.d.ts
Labels: group/ui

#2231 fix (#1993): Introduce new action pattern 'pipe' to describe non
  app/common/model/src/main/java/io/syndesis/common/model/action/Action.java
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: pr/approved

#2236 Header responsive updates
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.scss
Labels: pr/approved

#2239 refactor(ftp and sftp connector): Add order fields to JSON definition
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: group/connector, pr/approved

#2226 chore(build): upgrade PMD
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorFactories.java
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorVerifierExtension.java
  app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/layout/ModuleLayoutFactory.java
  app/meta/src/main/java/io/syndesis/connector/meta/Application.java
  app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
  app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/JsonRecordConsumer.java
  ruleset.xml
Labels: cat/build, group/connector, group/extension, group/meta, group/server

#2242 issue_template, explicit hint about how to use it
  .github/ISSUE_TEMPLATE.md
Labels: pr/approved, pr/review-requested

#2049 feat: Add “View Log in Openshift” link to activities page.
  app/ui/src/app/config.service.ts
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
  app/ui/src/config.json.minishift
  install/generator/01-header.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: group/install, group/ui, pr/approved

#2250 fix: align the draft area property to the returned integration object add a separate draft indicator to the list
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/status.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved

#2252 fix: make the home link highlight properly when at the dashboard
  app/ui/src/app/app.component.html
Labels: pr/approved

#2259 Imported integration has no status
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationOverview.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
Labels: pr/approved

#2261 Newly created salesforce connection requires configuration
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
Labels: pr/approved

#2257 chore: Update AtlasMap to 1.34.1
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#2255 Improve dashboard and integration list responsive views
  app/ui/src/app/dashboard/dashboard.component.scss
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.scss
Labels: pr/approved

#2082 Activity: fix for serialization strategy and empty collections
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/activity/Activity.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/service/DBActivityTrackingService.java
Labels: pr/approved

#2263 Use relative paths in spring-boot loader.path
  app/meta/src/main/fabric8-includes/run-env.sh
Labels: pr/approved

#2265 fix(slack connector): correct username parameter
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved

#2264 chore(server): improve update-controller
  app/server/runtime/src/main/resources/application.yml
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateConfiguration.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateController.java
Labels: pr/approved

#2267 feat(ui): integration activity logs are refetched incrementally upon checking its view
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
Labels: group/ui, pr/approved, pr/review-requested

#2181 bin/syndesis: create cookie for curl invocations
  tools/bin/commands/dev
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#2272 feat(ui): Prevent XSRF exploit by appending token to custom headers from server cookie
  app/ui/src/app/api/api.module.ts
  app/ui/src/app/api/providers/api-xsrf-interceptor.service.ts
  app/ui/src/app/api/providers/index.ts
  app/ui/src/environments/environment.prod.ts
  app/ui/src/environments/environment.ts
Labels: cat/bug, group/ui, pr/approved, pr/review-requested, prio/p1

#2258 truncate long connection names under integration details icons
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
Labels: pr/approved

#2273 chore: remove green check related to 'statusMessage' field
  app/ui/src/app/integration/list/list.component.html
Labels: pr/approved

#2275 dashboard code/ui tweaks
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
Labels: pr/approved

#2270 fix: slimmer inspections in connectors
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
Labels: pr/approved, pr/review-requested

#2288 chore(ui): Customer portal user doc links updated and and managed thru i18n
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.ts
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: group/ui, pr/approved, pr/review-requested

#2304 fix(install): Fix product icon path
  install/generator/03-syndesis-ui.yml.mustache
Labels: pr/approved, pr/review-requested

#2290 chore: Update README to add OPENSHIFT_CONSOLE_URL
  install/README.md
Labels: pr/approved

#2285 chore: Update product-map for TP4
  install/support/product-version-map.yml
Labels: pr/approved

#2293 Integration data mapper issue
  app/common/model/src/main/java/io/syndesis/common/model/action/ActionDescriptor.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
Labels: pr/approved, pr/review-requested

#2254 fix(build): revert PMD version upgrade
  app/pom.xml
  ruleset.xml
Labels: pr/approved

#2305 Missing jsondb index ?
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
Labels: pr/approved

#2311 fix(server): require host, basePath and specification properties
  app/server/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: pr/approved

#2317 Activity Tab not showing step details.
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingConstants.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingListener.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingRoutePolicyFactory.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepDoneTracker.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepStartTracker.java
Labels: pr/approved, pr/review-requested

#2301 fix: Username should be displayed in header #2269
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/user/UserHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/user/UserHandlerTest.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
Labels: pr/approved, pr/review-requested

#2323 UI, Fix typo in Support page
  app/ui/src/app/support/support.component.html
Labels: pr/approved, pr/review-requested

#2324 fix(UI): i18n string fetching can now be performed imperatively support i18n provider
  app/ui/src/app/core/providers/i18n-provider.service.ts
  app/ui/src/app/platform/types/i18n/README.md
  app/ui/src/polyfills.ts
Labels: cat/bug, group/ui

#2325 fix: fixing order of db connector properties
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved

#2334 fix: Activity tab as getting errors.
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
Labels: pr/approved

#2330 Activity Tab not showing step details (activity status steps)
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRuntimeAutoConfiguration.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepDoneTracker.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/T3stSupportITCase.java
Labels: pr/approved, pr/review-requested

#2336 Fix connection leak in extension icon retrieval
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
Labels: pr/approved

#2309 fix(ui): handle swagger specifications with no tags
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
Labels: pr/approved, pr/review-requested

#2337 refactor(ftp and sftp connector): Reordered the connector options
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: pr/approved

#2313 chore(build): enforce unlimited cryptography JVM
  app/pom.xml
Labels: cat/build, pr/approved, pr/review-requested

#2248 feat(i18n): move hard coded strings to dictionary file
  app/ui/src/app/app.component.html
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard.module.ts
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts
  app/ui/src/app/dashboard/dashboard_empty/dashboard-empty.component.html
  app/ui/src/app/dashboard/dashboard_empty/dashboard-empty.component.scss
  app/ui/src/app/dashboard/dashboard_empty/dashboard-empty.component.ts
  app/ui/src/app/dashboard/dashboard_empty/index.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/platform/types/i18n/README.md
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: group/ui, pr/approved, pr/review-requested

#2341 fix: rename stop integration menu item
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
Labels: pr/approved

#2345 Dashboard connection spinner positioning
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
Labels: pr/approved

#2310 chore(server): swagger specification parsing robustness
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRules.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/AbstractSwaggerConnectorTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/PropertyGeneratorsTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/TestHelper.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelperTest.java
Labels: pr/approved, pr/review-requested

#2035 Create empty state card component
  app/ui/src/app/common/common.module.ts
  app/ui/src/app/common/empty-state-card/empty-state-card.component.scss
  app/ui/src/app/common/empty-state-card/empty-state-card.component.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/connections/list/list.component.scss
  app/ui/src/app/connections/list/list.component.ts
  app/ui/src/scss/utils/_helpers.scss
Labels: group/ui, pr/approved

#2322 improve styling of wizard progress bar
  app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.ts
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved

#2349 Feat/218 better error handling
  app/ui/src/app/api/providers/api-http-provider.service.ts
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/app.module.ts
  app/ui/src/app/error-handler/exception-handler.service.ts
  app/ui/src/app/error-handler/http-error.interceptor.ts
  app/ui/src/app/error-handler/index.ts
  app/ui/src/app/error-handler/offline-handler.service.ts
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/src/polyfills.ts
Labels: cat/feature, group/ui, pr/approved, pr/review-requested

#2351 bring header spacing inline with PF default
  app/ui/src/app/app.component.scss
Labels: pr/approved

#2352 Rename Stop Integration to Unpublish
  ux/designs/integration_details/img/integration_details_page_3.14_kebab.png
  ux/designs/integration_details/img/integration_details_page_4.11_kebab.png
  ux/designs/integration_details/integration_details_page.md
Labels: group/ui, group/uxd, pr/approved

#2363 fix(server): consider properties configured on connector
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandlerTest.java
Labels: cat/bug, group/server, pr/approved, pr/review-requested, prio/p2

#2355 Update customizations breadcrumbs to be consistent
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
Labels: pr/approved

#2327 fix(ui): let's centralize the contact email address definition in a single location 📧
  app/ui/src/app/app.component.html
  app/ui/src/app/support/support.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: cat/bug, group/ui, pr/approved, pr/review-requested

#2361 fix(connector): proper basic authentication encoding
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponent.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponentTest.java
Labels: cat/bug, group/connector, pr/approved, size/s

#2359 feat(server): additional oauth2 properties via vendor extensions
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/connector-generator/src/test/resources/swagger/concur.swagger.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: cat/feature, group/server, pr/approved

#2338 This pull request is supposed to provide a fix for #1641.
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
Labels: pr/approved, pr/review-requested

#2368 chore(ui): always propagate http exceptions
  app/ui/src/app/api/providers/api-http-provider.service.ts
Labels: group/ui, pr/approved, pr/review-requested

#2376 fix: NPE when integration has two database selects #2372
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
Labels: pr/approved

#2375 Add syndesis console banners.
  app/integration/runtime/src/main/resources/banner.txt
  app/meta/src/main/resources/banner.txt
  app/pom.xml
  app/server/runtime/src/main/resources/banner.txt
Labels: pr/approved

#2371 .hint-icon placement in syndesis-form-control, settings page responsive update
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.scss
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
Labels: pr/approved

#2394 feat(s3): use duration control type for delay form field
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: group/ui, pr/approved, pr/review-requested

#2398 remove horizontal scrollbar from integration board when it resizes/overflows
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss
Labels: pr/approved

#2392 Create connection wizard ui
  app/ui/src/app/connections/create-page/create-page.component.html
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#2401 fix: Creating API client connector, required fields need a required l…
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
Labels: pr/approved, pr/review-requested

#2402 Breadcrumb not in full length on create API connector wizard pages #2276
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
Labels: pr/approved, pr/review-requested

#2395 chore: api connector ui tidbits
  app/server/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#2405 chore: Updates to "release" and "upgrade"
  doc/sdh/cli/cmd_release.adoc
  tools/bin/commands/release
  tools/upgrade/Dockerfile
  tools/upgrade/build.sh
  tools/upgrade/migration/preflight.sh
  tools/upgrade/steps/prep_40_process_template
  tools/upgrade/upgrade.sh
Labels: pr/approved

#2404 feat(server): detailed version endpoint
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/Version.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/VersionEndpoint.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/VersionITCase.java
Labels: pr/approved, pr/review-requested

#2407 feat(ui): display correct version on support page
  app/ui/src/app/support/support.component.html
  app/ui/src/app/support/support.component.ts
Labels: pr/approved, pr/review-requested

#2366 chore(server): support diverse swagger specifications
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseDataShapeGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/DataShapeGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SwaggerModelInfo.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SwaggerUnifiedShapeConnectorGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRules.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedDataShapeGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGenerator.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/DummyStreamHandler.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/JsonSchemaHelper.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelper.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/SyndesisSwaggerValidationRulesTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGeneratorRequestShapeTest.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/connector-generator/src/test/resources/swagger/expected-pet-schema.json
  app/server/connector-generator/src/test/resources/swagger/kie-server.swagger.json
  app/server/connector-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/todo.unified_connector.json
Labels: group/server, pr/review-requested

#2410 wrap :ng-deep in :host to keep those styles from affecting other areas of the app
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.scss
  app/ui/src/app/support/support.component.scss
Labels: pr/approved

#2415 fix(connector): use proper salesforce icon
  app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
Labels: pr/approved, pr/review-requested

#2369 Activity Log Errors not showing up in the right step
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationActivityEventHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingAutoConfiguration.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingConstants.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingListener.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingRoutePolicyFactory.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/StepDoneTracker.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/IntegrationLoggingDisabledTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/IntegrationLoggingEnabledTest.java
Labels: pr/approved, pr/review-requested

#2424 feature(openshift): Add default labels to infrastructure and integration objects
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/02-syndesis-secrets.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/05-syndesis-security.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
  ruleset.xml
Labels: pr/approved

#2425 Adding IDs to support page elements
  app/ui/src/app/support/support.component.html
Labels: pr/approved, pr/review-requested

#2426 fix (#1641): Fix regression introduced by previous commit: isScaled()…
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/IntegrationController.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
Labels: pr/approved

#2427 Upgradedb, refactored yum dependencies
  tools/upgrade/Dockerfile
  tools/upgrade/build.sh
Labels: pr/approved, pr/review-requested

#2438 bug: #2155 SQL deadlock detected. Do a better job of Delete/insert records that are part of a transaction in path order to avoid deadlocks.
  app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/SqlJsonDB.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
Labels: pr/approved

#2445 chore(mqtt connector): Added username,password and clientId options
  app/connector/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
Labels: pr/approved

#2446 chore(release): Updates to the release process
  tools/bin/commands/release
  tools/upgrade/Dockerfile
Labels: pr/approved

#2429 feat: implement refresh of access token
  app/connector/rest-swagger/pom.xml
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/OAuthRefreshTokenProcessor.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/OAuthRefreshingEndpoint.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponent.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/springboot/SwaggerConnectorConnectorConfigurationCommon.java
  app/connector/rest-swagger/src/main/resources/camel-connector-schema.json
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/OAuthRefreshTokenProcessorTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponentTest.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/credential/src/main/java/io/syndesis/server/credential/generic/OAuth2CredentialProviderFactory.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: cat/feature, group/connector, group/server, pr/approved, pr/review-requested, size/m

#2448 fix(upgrade): Update version only if different than before
  tools/bin/commands/release
  tools/upgrade/steps/upgrade_50_replace_template
Labels: pr/approved

#2451 fix(upgrade): Wait until all pods are gone when scaling down to 0
  doc/sdh/cli/cmd_release.adoc
  tools/upgrade/common.sh
  tools/upgrade/steps/upgrade_20_stop_all
  tools/upgrade/steps/upgrade_40_update_resources
Labels: pr/approved

#2440 Add Xsrf protection in syndesis backend
  app/server/runtime/src/main/java/io/syndesis/server/runtime/SecurityConfiguration.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/SyndesisCsrfRepository.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java
  app/ui/src/app/api/providers/api-xsrf-interceptor.service.ts
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/app/integration/list-page/list-page.component.ts
  app/ui/src/environments/environment.prod.ts
  app/ui/src/environments/environment.ts
Labels: pr/approved

#2455 chore: Update to atlasmap-1.34.2
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#2456 chore: Add a prefix of `syndesis.io` to all labels used by syndesis
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/02-syndesis-secrets.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-amq-example.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/generator/05-syndesis-security.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
  tools/bin/commands/dev
  tools/bin/commands/util/openshift_funcs
  tools/upgrade/common.sh
Labels: pr/approved

#2459 Fixes #2444: Updated integration pod label, made labels configurable in Prometheus metrics implementation
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusConfigurationProperties.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/server/runtime/src/main/resources/application.yml
Labels: pr/approved, pr/review-requested

#2466 fix: Switching between revisions. Images are now tagged with the revi…
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
Labels: pr/approved

#2469 fix(install): Add openshift-sar to restrict access to namespace
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#2467 fix(server): encrypt connection properties from oauth flow
  app/server/credential/src/main/java/io/syndesis/server/credential/CredentialConfiguration.java
  app/server/credential/src/main/java/io/syndesis/server/credential/Credentials.java
  app/server/credential/src/test/java/io/syndesis/server/credential/CredentialsTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
Labels: pr/approved, pr/review-requested

#2471 fix: Remove invalid characters from steps performed.
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
Labels: pr/approved

#2488 Upgrade, invoke db scripts
  tools/upgrade/BOOT-INF/classes/migrations/up-30.js
  tools/upgrade/steps/upgrade_10_migrate_db
Labels: pr/approved, pr/review-requested

#2486 fix: On MySQL - Table name pattern can not be NULL or empty #2482
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseMetaDataHelper.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DatabaseProduct.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataAdapterTest.java
  app/connector/sql/src/test/resources/test-options.properties
Labels: pr/approved

#2478 chore(install): declare accept header for liveness probe
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateAutoConfiguration.java
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#2493 fix(upgrade): Scale replicas to 0 before updating DeploymentConfigs
  tools/upgrade/steps/prep_40_process_template
  tools/upgrade/steps/upgrade_40_update_resources
Labels: pr/approved

#2491 fix(connector): proper data shape kind for mqtt
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
Labels: pr/approved, pr/review-requested

#2479 chore(server): upgrade swagger-core
  app/pom.xml
Labels: pr/approved, pr/review-requested

#2498 Fix, support page text
  app/ui/src/app/support/support.component.html
Labels: pr/approved

#2502 bug: #2489 Integration data buckets are not working for scheduled connectors.
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/capture/OutMessageCaptureProcessorTest.java
Labels: pr/approved

#2496 chore(connector): tidier salesforce properties
  app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
Labels: pr/approved, pr/review-requested

#2490 fix(ui): api connector icon upload when providing url for swagger
  app/ui/src/app/customizations/api-connector/api-connector.service.ts
Labels: pr/review-requested

#2495 fix(ui): don't show properties that are hidden and secret
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: pr/review-requested

#2461 bug: Logout link was not logging user out.
  app/ui/src/app/app.component.ts
  app/ui/src/app/core/providers/user-provider.service.ts
Labels: pr/approved, pr/review-requested

#2513 fix(connector): Add a Java wrapper for plain Slack input
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackChannelCustomizer.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackPlainMessage.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved, pr/review-requested

#2515 [UpgradeDB] Comment out call to syndesis-cli.jar
  tools/upgrade/steps/upgrade_10_migrate_db
Labels: pr/approved, pr/review-requested
