Repository syndesisio/syndesis, pull requests merged in 2018-05, with the labels that each got.

#2526 fix(server): use proper integration version
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
Labels: pr/approved, pr/review-requested

#2527 fix(mqtt connector): MQTT connection - cant validate without user/pas…
  app/connector/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java
Labels: pr/approved

#2529 No activity log shown
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
Labels: pr/approved

#2530 fix(mqtt connector) - Fixed username field
  app/connector/mqtt/src/main/java/io/syndesis/connector/mqtt/MqttVerifierExtension.java
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
Labels: pr/approved

#2536 chore: Update to atlasmap-1.34.3
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#2542 fix(server): don't warn about missing properties on derived connections
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/ConnectionUpdateHandler.java
Labels: pr/approved, pr/review-requested

#2544 fix(ui): highlight step 3 in new connection wizard
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/app/store/connector/connector.service.ts
Labels: pr/approved, pr/review-requested

#2548 feat: re-authorization of oauth connections
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
  app/ui/src/app/connections/detail-page/configuration.component.html
  app/ui/src/app/connections/detail-page/configuration.component.ts
Labels: pr/approved, pr/review-requested

#2545 Deleting a connection which is used by an integration leads to inconsistent state (backend)
  .gitignore
  app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/ui/src/app/core/providers/status-code-decoder-provider.service.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/platform/types/status-code-decoder/status-code-decoder.service.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#2535 Fix, upgradedb, uses correct user and password
  tools/upgrade/common.sh
  tools/upgrade/steps/upgrade_10_migrate_db
  tools/upgrade/upgrade.sh
Labels: pr/approved, pr/review-requested

#2552 Peformance, bump Prometheus memory limits
  install/generator/01-header.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#2550 ENTESB-6910 Add licenses.xml to iPaaS
  app/meta/pom.xml
  app/meta/src/main/resources/license-custom-assembly.xml
  app/meta/src/main/resources/licenses/.gitkeep
  app/pom.xml
  app/s2i/pom.xml
  app/s2i/src/main/docker/Dockerfile
  app/s2i/src/main/resources/license-custom-assembly.xml
  app/s2i/src/main/resources/licenses/.gitkeep
  app/server/pom.xml
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/license-custom-assembly.xml
  app/server/runtime/src/main/resources/licenses/.gitkeep
  app/ui/docker/Dockerfile
  app/ui/docker/licenses/apache.txt
  app/ui/docker/licenses/licenses.xml
  app/ui/docker/licenses/mit.txt
  app/ui/package.json
  tools/upgrade/Dockerfile
  tools/upgrade/licenses/apache_software_license_version_2.0-apache-2.0.txt
  tools/upgrade/licenses/licenses.xml
Labels: pr/approved, pr/review-requested

#2546 fix: correct the values being passed to patch and fix how it's being called
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/ui/src/app/integration/integration-actions-provider.service.ts
Labels: pr/approved

#2557 Remove docker-maven-plugin and fabric8-maven-plugin changes.
  app/meta/pom.xml
  app/s2i/pom.xml
  app/server/runtime/pom.xml
Labels: pr/approved

#2559 chore: Update to AtlasMap 1.34.4
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#2551 feat: add MAX_INTEGRATIONS_PER_USER parameter to syndesis-server configs
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#2516 fix: trim strings by default except for secret fields
  app/ui/src/app/connections/common/configuration/configuration.service.ts
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/platform/types/form-factory/form-factory.service.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
Labels: pr/approved

#2595 refactor(ui): change wording on connector delete confirmation
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
Labels: pr/approved, pr/review-requested

#2651 bug: On DB slowdown, could start doing concurrent activity log cleanups and pod polling. issues #2607
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
Labels: pr/approved

#2659 fix: update 'contact us' link and update link on support page to use dictionary
  app/ui/src/app/app.component.html
  app/ui/src/app/support/support.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2605 fix(ui): send accept header with application/json for /version endpoint
  app/ui/src/app/api/providers/api-http-provider.service.ts
  app/ui/src/app/support/support.component.ts
Labels: pr/approved

#2677 fix(install): Fixed defaults for OCP/OSO variants for maxIntegrations
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
Labels: pr/approved

#2681 fix(server): support ports in swagger host
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/PropertyGenerators.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/PropertyGeneratorsTest.java
Labels: pr/approved

#2654 Fix several typos
  doc/integrating_applications/topics/about_connection_validation.adoc
  doc/integrating_applications/topics/about_connections.adoc
  doc/integrating_applications/topics/about_steps.adoc
  doc/integrating_applications/topics/add_api_client_connection.adoc
  doc/integrating_applications/topics/adding_db_connection_finish_middle.adoc
  doc/integrating_applications/topics/adding_db_connection_start.adoc
  doc/integrating_applications/topics/adding_sf_connections.adoc
  doc/integrating_applications/topics/adding_twitter_connections.adoc
  doc/integrating_applications/topics/connecting_to_amqp.adoc
  doc/integrating_applications/topics/separate_one_source_field_into_multiple_target_fields.adoc
  doc/sdh/development/ui.adoc
  doc/system-tests/README.adoc
  install/README.md
  project/DevelopersGuide.md
  project/proposals/002-filter-data.md
  project/proposals/013-global-settings.md
  project/proposals/016-dynamic-properties.md
  project/proposals/042-health-checks.adoc
  project/proposals/044-integration-model.md
  project/proposals/119-custom-connectors.md
  project/proposals/181-tech-extension.adoc
Labels: pr/approved

#2679 fix(install): Default value for max integrations
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
Labels: pr/approved

#2676 extension : extension's default in/out kind should be 'none'
  app/extension/api/src/main/java/io/syndesis/extension/api/annotations/DataShape.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
Labels: pr/approved

#2696 chore: Moved label 'syndesis.io/app' back to 'app' as it has a meaning for OpenShift
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/02-syndesis-secrets.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-amq-example.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/generator/05-syndesis-security.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/wip

#2665 Do batch inserts of the activity log records. Should incrementally improve performance
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
Labels: pr/approved

#2506 Toast notifications import/export
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#2662 chore(upgrade): Relax preflight check
  tools/upgrade/migration/preflight.sh
Labels: pr/approved

#2700 fix: Ensure there's a default lower limit for durations
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
Labels: pr/approved

#2695 chore(feat): AWS S3 Component - set CamelAwsS3Key header
  app/connector/aws-s3/src/main/java/io/syndesis/connector/aws/s3/AWSS3CopyObjectCustomizer.java
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: pr/approved

#2707 Fix typo in labels.adoc
  doc/sdh/development/labels.adoc
Labels: pr/approved

#2708 OutputDataShape annotation disregarded by maven plugin
  app/extension/maven-plugin/pom.xml
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/extension/maven-plugin/src/resources/META-INF/spring.factories
  app/extension/maven-plugin/src/test/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojoTest.java
  app/extension/maven-plugin/src/test/resources/logback-test.xml
Labels: pr/approved

#2711 chore(install): regenerate templates
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#2714 Add a command to provide shell completion, fixes #2713
  tools/bin/commands/completion
Labels: pr/approved

#2725 Fix typos
  README.md
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
Labels: pr/approved
