Repository syndesisio/syndesis, pull requests merged in 2018-06, with the labels that each got.

#2727 chore: Update to AtlasMap 1.35.0
  app/pom.xml
  app/ui/package.json
  app/ui/src/app/app.module.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/yarn.lock
Labels: pr/approved

#2723 #2719 - update json schema
  app/extension/api/src/main/resources/syndesis/syndesis-extension-definition-schema.json
Labels: pr/approved

#2731 minor spelling correction
  app/extension/archetype/java/src/main/resources/archetype-resources/README.adoc
  app/extension/archetype/spring-boot/src/main/resources/archetype-resources/README.adoc
  app/extension/archetype/xml/src/main/resources/archetype-resources/README.adoc
Labels: pr/approved

#2736 refactor(connector): gmail connector add datashape for input, related…
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailMessageModel.java
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailSendEmailCustomizer.java
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
Labels: pr/approved

#2738 feat(aws-s3 connector): AWS S3 delete object connector
  app/connector/aws-s3/src/main/java/io/syndesis/connector/aws/s3/AWSS3DeleteObjectCustomizer.java
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: pr/approved

#2609 [closes #2608] Get migrate DB scripts also from external folder
  app/server/cli/src/main/java/io/syndesis/server/cli/command/migrate/MigrateCommand.java
  app/server/jsondb/src/main/java/io/syndesis/server/jsondb/dao/Migrator.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/DefaultMigrator.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/MigrationsITCase.java
Labels: pr/approved, pr/review-requested

#2745 Integrations metrics responsiveness
  app/ui/src/app/connections/detail-page/configuration.component.html
  app/ui/src/app/connections/detail-page/detail-page.component.scss
  app/ui/src/app/connections/detail-page/detail-page.component.ts
  app/ui/src/app/connections/detail-page/info.component.scss
  app/ui/src/app/connections/detail-page/info.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.html
Labels: pr/approved, pr/review-requested

#2747 chore(build): disable system tests
  .circleci/config.yml
Labels: pr/approved, pr/review-requested

#2758 improve responsiveness of customizations pages, add hover/active class to extension import drag/drop zone on successful upload
  app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.html
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.scss
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/scss/utils/_helpers.scss
Labels: pr/approved, pr/review-requested

#2762 Remove hover state from drag and drop uploader after file is uploaded
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
Labels: pr/approved, pr/review-requested

#2771 Docs, added examples to inspect provided db
  project/DevelopersGuide.md
Labels: pr/approved

#2560 chore(release): set version & build documentation
  tools/bin/commands/release
Labels: pr/review-requested

#2770 chore: upgrade resteasy to 3.5.1.Final
  app/common/pom.xml
  app/common/resteasy-spring-boot-starter/pom.xml
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/JaxrsApplicationScanner.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyApplicationBuilder.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyAutoConfiguration.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyEmbeddedServletInitializer.java
  app/common/resteasy-spring-boot-starter/src/main/resources/META-INF/spring.factories
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/JaxrsAppRegistrationTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/ResteasyAutoConfigurationTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/ResteasyEmbeddedServletInitializerTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/SampleApp.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication2.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication3.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication4.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication5.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestProvider1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestResource1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestResource2.java
  app/common/resteasy-spring-boot-starter/src/test/resources/logback-test.xml
  app/common/resteasy-spring-boot-starter/src/test/resources/test-config.xml
  app/connector/support/maven-plugin/pom.xml
  app/extension/maven-plugin/pom.xml
  app/meta/pom.xml
  app/pom.xml
  app/server/endpoint/pom.xml
  app/server/metrics/prometheus/pom.xml
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java
  app/server/pom.xml
  app/server/runtime/pom.xml
  app/server/verifier/pom.xml
  app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
Labels: pr/approved

#2773 add .card-pf-heading class to card title in create connection workflow
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.html
  app/ui/src/app/connections/create-page/review/review.component.html
Labels: pr/approved, pr/review-requested

#2710 chore(tools): add syndesis dev --cleanse tool
  tools/bin/commands/dev
Labels: pr/approved, pr/review-requested

#2774 Possible resources leak
  app/common/util/src/main/java/io/syndesis/common/util/CollectionsUtils.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/DefaultVerifierExtensionUploader.java
  app/server/metrics/prometheus/pom.xml
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/server/verifier/pom.xml
  app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
Labels: pr/approved

#2768 chore: editing of scopes, token and authorization endpoints
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilter.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilterTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/BaseITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts
  app/ui/src/app/store/entity/entity.store.ts
Labels: pr/approved, pr/review-requested

#2775 fixes: #2095 missing log entries.
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingListener.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
Labels: pr/approved, pr/review-requested

#2763 Issue #636: Provided a web api to query used versions of Apache Camel…
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/VersionEndpoint.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/VersionService.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/VersionITCase.java
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#2780 improve spacing and ui of swagger upload and security steps
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.scss
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.scss
Labels: pr/approved, pr/review-requested

#2785 change extension file uploader wording from "import" to "upload"
  app/ui/src/app/customizations/tech-extensions/import/tech-extension-import.component.html
Labels: pr/approved, pr/review-requested

#2787 chore: add timestamp display
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
Labels: pr/approved

#2782 fix: toggle loading state when the user clicks 'next'
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Labels: pr/approved

#2792 refactor(aws s3 connector): Fix the get Object action text after remo…
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: pr/approved

#2795 chore: tokenize project name in templates, add app name override to i18n service
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/core/providers/i18n-provider.service.ts
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2796 fix: add advanced filter placeholder; add support for more advanced tooltip formatting
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved

#2776 chore(build): use base-pom for documentation
  app/pom.xml
  doc/tools/pom.xml
  doc/tools/syndesis-documentation-maven-plugin/pom.xml
  doc/tools/syndesis-documentation-maven-plugin/src/main/java/io/syndesis/maven/TooltipExtractorMojo.java
Labels: pr/review-requested

#2800 refactor integration import results area
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.scss
Labels: pr/approved

#2803 feature(gmail-connector): Gmail Stream Consumer connector
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailReceiveEmailCustomizer.java
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/odata/create-entity/src/main/resources/camel-connector.json
  app/connector/odata/delete-entity/src/main/resources/camel-connector.json
  app/connector/odata/replace-entity/src/main/resources/camel-connector.json
  app/connector/odata/retrieve-entity/src/main/resources/camel-connector.json
  app/connector/odata/update-entity/src/main/resources/camel-connector.json
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/extension/bom/pom.xml
  app/extension/example/log-step/pom.xml
  app/integration/pom.xml
  app/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: pr/approved

#2812 feature(build): Give the possibility to build Syndesis against a loca…
  app/s2i/copy_mvn_repo.sh
  doc/sdh/cli/cmd_build.adoc
  doc/tooltips/tooltips.json
  tools/bin/commands/build
Labels: pr/approved

#2813 adding concur-connector
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: pr/approved, pr/review-requested

#2810 remove "last published" in draft integration detail history
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
Labels: pr/approved

#2821 OAuth Gmail
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailMessageModel.java
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailSendEmailCustomizer.java
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: pr/approved

#2822 refactor: add concur icon and description
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/approved, pr/review-requested

#2838 Create a simple ServiceNow Connector
  app/connector/pom.xml
  app/connector/servicenow/pom.xml
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataAutoConfiguration.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetaDataExtension.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowVerifierAutoConfiguration.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowImportSetCustomizer.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowTableGetCustomizer.java
  app/connector/servicenow/src/main/resources/META-INF/spring.factories
  app/connector/servicenow/src/main/resources/META-INF/syndesis/connector/servicenow.json
  app/connector/support/catalog/pom.xml
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadata.java
  app/meta/pom.xml
  app/pom.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: pr/approved

#2846 chore: reword connector names and descriptions
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/mqtt/src/main/resources/META-INF/syndesis/connector/mqtt.json
  app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/approved

#2855 fix: don't allow deleting concur connector
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/approved, pr/review-requested

#2852 align oauth form labels/fields to left
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
Labels: pr/approved

#2849 improve spacing/nesting of upload radio form, always select first authentication type radio
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
Labels: pr/approved

#2848 improve ui of support radio buttons and progressive disclosure
  app/ui/src/app/support/support.component.html
  app/ui/src/app/support/support.component.scss
Labels: pr/approved

#2842 fix: simple expression with stream messages
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimpleHelpers.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/util/JsonSimplePredicateTest.java
Labels: pr/approved, pr/review-requested

#2847 Upgrade patternfly 3.49.0
  app/ui/package.json
  app/ui/src/app/app.component.html
  app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.spec.ts
  app/ui/src/app/common/wizard_progress_bar/wizard-progress-bar.component.ts
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/scss/utils/_overrides.scss
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#2878 refactor(gmail connector): added icon for OAuth Management console
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
Labels: pr/approved

#2876 remove .control-label override style
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/scss/components/_forms.scss
Labels: pr/approved

#2883 chore: suppress the HTTP error toast notification in favor of a console.error message
  app/ui/src/app/error-handler/http-error.interceptor.ts
Labels: pr/approved

#2884 feat: Proposal for Operator usage within Syndesis
  project/proposals/2734-operator-support.pdf
Labels: pr/approved

#2899 fix: ensure we toggle loading off when there's an error response
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Labels: pr/approved

#2900 Provided a Kafka connector. #2737
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataAutoConfiguration.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifier.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierAutoConfiguration.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java
  app/connector/kafka/src/main/resources/META-INF/spring.factories
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KarafConnectorTest.java
  app/connector/kafka/src/test/resources/logback-test.xml
  app/connector/kafka/src/test/resources/sql/demo_add_metadata.json
  app/connector/kafka/src/test/resources/sql/name_sql_metadata.json
  app/connector/kafka/src/test/resources/sql/name_sql_no_param_metadata.json
  app/connector/kafka/src/test/resources/sql/stored_procedure_list.json
  app/connector/kafka/src/test/resources/sql/stored_start_procedure_list.json
  app/connector/kafka/src/test/resources/test-options.properties
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#2903 fix: show a more user freindly error message when the backend is unavailable
  app/ui/src/app/error-handler/http-error.interceptor.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2914 update to patternfly 3.51.2
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#2917 modal message dialog updates
  app/ui/src/app/common/delete_confirmation_modal/delete-confirmation-modal.component.ts
  app/ui/src/app/common/modal/modal.component.html
  app/ui/src/app/common/modal/modal.component.ts
  app/ui/src/app/common/modal/modal.service.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.html
Labels: pr/approved

#2919 improve layout of editable names on integration and connection details pages
  app/ui/src/app/connections/detail-page/info.component.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
Labels: pr/approved

#2924 feat: skip the action config if there's no properties
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved

#2926 fix: display error messages when acquiring credentials fails
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts
  app/ui/src/app/connections/create-page/current-connection.ts
  app/ui/src/app/store/connector/connector.service.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#2933 chore: Update to AtlasMap 1.35.4
  app/pom.xml
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/atlas/SyndesisAtlasService.java
  app/ui/package.json
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/config.json.example
  app/ui/src/config.json.minishift
  app/ui/src/config.json.staging
  app/ui/yarn.lock
Labels: pr/approved
