Repository syndesisio/syndesis, pull requests merged in 2018-09, with the labels that each got.

#3535 refactor(slack-connector): Webhook and token must be Raw and secret
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved

#3545 Fixes #3533, override Salesforce component class to avoid deadlocks in underlying HTTP client by reverting to use an AsyncCallback
  app/connector/salesforce/pom.xml
  app/connector/salesforce/src/main/java/org/apache/camel/component/salesforce/SalesforceConsumer.java
  app/pom.xml
Labels: pr/approved, pr/review-requested

#3553 chore: Add tech preview label to concur connector
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: group/connector, pr/1.4.x, pr/approved, pr/review-requested

#3562 fix: remove the workaround to fetch a remote OpenAPI file
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/polyfills.ts
Labels: pr/approved

#3566 Unable to edit imported integrations
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
Labels: pr/approved, pr/review-requested

#3574 Various api provider endpoint improvements
  app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/APIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/IntegrationHandlerTest.java
Labels: pr/approved, pr/review-requested

#3572 [fix] Query parameters are not set in the API-Connector #3564
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/api-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
Labels: pr/approved

#3573 [fix] Sets the query parameters on concur requests
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/approved

#3554 chore: Move concur-connector out of "dao" to "connectors" in a separate module.
  app/connector/concur/pom.xml
  app/connector/concur/src/main/resources/META-INF/syndesis/connector/concur-api.json
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
Labels: group/connector, pr/approved, pr/review-requested

#3580 fix: ensure oauth app page doesn't break if there's no icon
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
Labels: pr/approved

#3585 feat: ui changes to support API provider integrations
  app/ui/src/app/integration/api-provider/index.ts
  app/ui/src/app/integration/api-provider/operations.component.html
  app/ui/src/app/integration/api-provider/operations.component.scss
  app/ui/src/app/integration/api-provider/operations.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.scss
  app/ui/src/app/integration/list/list.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/entity/rest.service.ts
  app/ui/src/app/store/integration/integration.service.ts
  app/ui/src/assets/icons/multi-flow.connection.png
  app/ui/src/assets/icons/multi-flow.integration.png
Labels: pr/review-requested

#3588 feat: enable date support for dynamic form input
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: pr/approved

#3589 chore: Enable AtlasMap Data Preview in openshift template
  install/generator/03-syndesis-ui.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3595 chore: Add configuration for https://github.com/apps/stale
  .github/stale.yml
Labels: pr/approved

#3596 feat: enable all the other input field types from ng-dynamic-forms
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: pr/approved

#3597 fix: unset empty password strings
  app/ui/src/app/platform/types/form-factory/form-factory.service.ts
Labels: pr/approved

#3593 chore: turn on Typescript's noUnusedLocals
  app/ui/src/app/api/api.module.ts
  app/ui/src/app/api/providers/api-http-provider.service.ts
  app/ui/src/app/common/editable/index.ts
  app/ui/src/app/connections/common/configuration/configuration.service.ts
  app/ui/src/app/core/providers/i18n-provider.service.ts
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts
  app/ui/src/app/integration/api-provider/operations.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/edit-page.component.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/platform/types/i18n/i18n.effects.ts
  app/ui/src/app/platform/types/integration/integration.reducer.ts
  app/ui/src/app/settings/settings-root.component.ts
  app/ui/src/app/store/connection/connection.store.ts
  app/ui/src/app/store/connector/connector.service.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/integration/integration.service.ts
  app/ui/src/tsconfig.app.json
Labels: pr/approved, pr/review-requested

#3592 fix: update syndesis-loading to accept a TemplateRef too
  app/ui/src/app/common/loading/loading.component.html
  app/ui/src/app/common/loading/loading.component.ts
  app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html
  app/ui/src/app/connections/detail-page/detail-page.component.ts
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extension-delete-modal.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/integration/api-provider/operations.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/list-actions/list-actions.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
  app/ui/src/app/integration/list-page/list-page.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/support/support.component.html
Labels: pr/approved

#3609 Fix datamapper support in API provider
  app/connector/api-provider/pom.xml
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderConnectorCustomizer.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/connector/pom.xml
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/util/SimpleJsonSchemaInspector.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/WrapperProcessorTest.java
  app/connector/webhook/pom.xml
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
  app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
  app/pom.xml
Labels: pr/approved

#3610 Deprecate methods in Integration Builder
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
Labels: pr/approved

#3485 add user namespace to use for the subjecAccessReview in oauthproxy
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#3618 fix: restore broken console logging functionality
  app/ui/package.json
  app/ui/src/app/app.component.ts
  app/ui/src/app/config.service.ts
  app/ui/src/app/connections/create-page/current-connection.ts
  app/ui/src/app/connections/create-page/review/review.component.ts
  app/ui/src/app/connections/list/list.component.ts
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/filter-steps/basic-filter.component.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/logging.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#3622 fix: invoking syndesis without arguments
  tools/bin/syndesis
Labels: pr/approved, pr/review-requested

#3599 chore(install): Remove SYNDESIS_REGISTRY for productised templates
  install/generator/01-header.yml.mustache
Labels: pr/approved

#3624 fix(ui): logout on firefox
  app/ui/docker/nginx-syndesis.conf
Labels: pr/approved, pr/needs-backport

#3621 feat(connectors): New Google-Calendar connector
  app/connector/google-calendar/pom.xml
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataAutoConfiguration.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataExtension.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataRetrieval.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifier.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifierAutoConfiguration.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifierExtension.java
  app/connector/google-calendar/src/main/resources/META-INF/spring.factories
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
  app/connector/google-calendar/src/test/resources/logback-test.xml
  app/connector/pom.xml
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/connector/support/catalog/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: pr/approved

#3623 Removed camel-atlasmap.version property
  app/pom.xml
Labels: pr/approved

#3605 Feature: Template step
  app/common/model/src/main/java/io/syndesis/common/model/integration/StepKind.java
  app/common/util/src/main/java/io/syndesis/common/util/StringConstants.java
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/TemplateStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationStepHandlersTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/TemplateStepHandlerTest.java
  app/ui/angular.json
  app/ui/package.json
  app/ui/src/app/integration/edit-page/step-configure/index.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/index.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/app/store/step/step.store.ts
  app/ui/src/app/vendor/index.ts
  app/ui/src/app/vendor/vendor.module.ts
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/src/scss/base/_vendors.scss
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#3627 fix(connectors): Set the right output datashape for get and poll oper…
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: pr/approved

#3625 fix(ui): logout on firefox
  app/ui/docker/nginx-syndesis.conf
Labels: pr/approved

#3626 fix: update oauth apps and operations page to use the syndesis toolbar wrapper
  app/ui/src/app/integration/api-provider/operations.component.html
  app/ui/src/app/integration/api-provider/operations.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
Labels: pr/approved

#3635 fix: revert some unintended template changes
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
Labels: pr/approved

#3591 Removes temporary fix for Camel Salesforce issue ENTESB-9452
  app/connector/salesforce/pom.xml
  app/connector/salesforce/src/main/java/org/apache/camel/component/salesforce/SalesforceConsumer.java
  app/pom.xml
Labels: pr/1.4.x, pr/approved

#3633 [fix] Query parameters are not set in the API-Connector #3564
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/util/SwaggerHelper.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/connector-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
Labels: pr/1.4.x, pr/approved

#3642 (docs) Update documentation to include explanation of template step
  doc/integrating_applications/topics/about_steps.adoc
  doc/integrating_applications/topics/add_steps.adoc
  doc/integrating_applications/topics/add_template_step.adoc
Labels: pr/approved, pr/review-requested

#3644 feat(connector): Added location parameter to send and update event ac…
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3654 refactor(webhook): Updated the action text
  app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
Labels: pr/approved

#3645 fix(template-step): Correct UX elements of template step page
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3665 fix: support Concur APIs with query parameters
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
Labels: pr/1.4.x, pr/approved, pr/review-requested

#3663 Add top 5 integrations map of ids to total messages to Prometheus total metrics summary
  app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpQuery.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusConfigurationProperties.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/ui/karma.conf.js
  app/ui/src/app/dashboard/dashboard.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/platform/types/integration/integration.reducer.ts
Labels: pr/approved

#3669 feat(connector): Add icon to google-calendar connector
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3671 chore: more leftover bits to cleanup
  tools/bin/commands/dev
Labels: pr/approved

#3673 fix: ignore hidden required fields on the oauth settings page
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/oauthApp/oauth-app.store.ts
Labels: pr/approved

#3676 feat: API Provider UI - creation flow
  app/ui/src/app/common/index.ts
  app/ui/src/app/common/openapi/editor/editor.component.html
  app/ui/src/app/common/openapi/editor/editor.component.scss
  app/ui/src/app/common/openapi/editor/editor.component.ts
  app/ui/src/app/common/openapi/index.ts
  app/ui/src/app/common/openapi/openapi.models.ts
  app/ui/src/app/common/openapi/openapi.module.spec.ts
  app/ui/src/app/common/openapi/openapi.module.ts
  app/ui/src/app/common/openapi/review/review.component.html
  app/ui/src/app/common/openapi/review/review.component.scss
  app/ui/src/app/common/openapi/review/review.component.ts
  app/ui/src/app/common/openapi/uploader/uploader.component.html
  app/ui/src/app/common/openapi/uploader/uploader.component.scss
  app/ui/src/app/common/openapi/uploader/uploader.component.ts
  app/ui/src/app/integration/api-provider/api-provider.actions.ts
  app/ui/src/app/integration/api-provider/api-provider.api.ts
  app/ui/src/app/integration/api-provider/api-provider.effects.ts
  app/ui/src/app/integration/api-provider/api-provider.models.ts
  app/ui/src/app/integration/api-provider/api-provider.module.ts
  app/ui/src/app/integration/api-provider/api-provider.reducer.ts
  app/ui/src/app/integration/api-provider/api-provider.service.ts
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.html
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.scss
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-upload/step-upload.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-upload/step-upload.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.ts
  app/ui/src/app/integration/api-provider/index.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.scss
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/src/polyfills.ts
  app/ui/src/scss/utils/_helpers.scss
Labels: pr/approved, pr/review-requested

#3678 fix(server): don't consider hidden OAuth properties
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
Labels: pr/approved, pr/review-requested

#3680 fix(templateStep): match template step UI to UXD designs
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.html
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.scss
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3684 refactor(connector): add additional query parameter for google-calend…
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3685 fix(oauth): handle hidden properties defultValue
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
Labels: pr/approved, pr/review-requested

#3682 fix: Replaced call to an internal api to create an integration from a spec…
  app/ui/src/app/integration/api-provider/api-provider.actions.ts
  app/ui/src/app/integration/api-provider/api-provider.api.ts
  app/ui/src/app/integration/api-provider/api-provider.effects.ts
  app/ui/src/app/integration/api-provider/api-provider.models.ts
  app/ui/src/app/integration/api-provider/api-provider.service.ts
Labels: pr/approved

#3691 refactor: handling of hidden OAuth connector properties
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppTest.java
Labels: pr/approved, pr/review-requested

#3690 fix: sanitize operation tags in OpenAPI
  app/server/api-generator/pom.xml
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
Labels: pr/approved

#3689 Use official resteasy spring boot starter and upgarde to resteasy 3.6.1.Final
  app/common/pom.xml
  app/common/resteasy-spring-boot-starter/pom.xml
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/JaxrsApplicationScanner.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyApplicationBuilder.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyAutoConfiguration.java
  app/common/resteasy-spring-boot-starter/src/main/java/com/paypal/springboot/resteasy/ResteasyEmbeddedServletInitializer.java
  app/common/resteasy-spring-boot-starter/src/main/resources/META-INF/spring.factories
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/JaxrsAppRegistrationTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/ResteasyAutoConfigurationTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/ResteasyEmbeddedServletInitializerTest.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/SampleApp.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication2.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication3.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication4.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestApplication5.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestProvider1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestResource1.java
  app/common/resteasy-spring-boot-starter/src/test/java/com/paypal/springboot/resteasy/sample/TestResource2.java
  app/common/resteasy-spring-boot-starter/src/test/resources/logback-test.xml
  app/common/resteasy-spring-boot-starter/src/test/resources/test-config.xml
  app/meta/pom.xml
  app/pom.xml
  app/server/runtime/pom.xml
Labels: pr/approved, pr/review-requested

#3693 refactor(connector): Changed the google-calendar connector name and id
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataAutoConfiguration.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarVerifierAutoConfiguration.java
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: pr/approved

#3698 Updated OpenAPI spec upload to also accept YAML files
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3699 fix: avoid NPE if there's no available datashape for the step config page
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/approved
