Repository syndesisio/syndesis, pull requests merged in 2018-02, with the labels that each got.

#1504 fix(editor): update event bindings and force change detection
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: approved

#1507 [fix] fixing up PMD issues that are breaking the build #1506
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/Filter.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/JsonRecordSupport.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/expr/BinarySqlExpressionBuilder.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/expr/LiteralSqlExpressionBuilder.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/expr/LogicalSqlExpressionBuilder.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/expr/SqlExpressionBuilder.java
Labels: approved

#1497 fix(ui): show suggested tokenEndpoint parameter for API connector
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
  app/ui/src/app/customizations/api-connector/api-connector.models.ts
Labels: approved, group/ui, size/s

#1488 UX Design: Viewing integration activity Designs
  ux/README.md
  ux/designs/integrationactivity/img/activity.png
  ux/designs/integrationactivity/img/activityexpand.png
  ux/designs/integrationactivity/img/daterange.png
  ux/designs/integrationactivity/img/integrationsummary.png
  ux/designs/integrationactivity/img/viewoutput.png
  ux/designs/integrationactivity/integrationactivity.md
Labels: approved, group/uxd

#1500 chore: Add Action with input/output DataShape for datamapper step
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: approved

#1496 chore(ui): import RxJS like a pro
  app/ui/package.json
  app/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/entity/events.service.ts
  app/ui/src/polyfills.ts
  app/ui/tslint.json
  app/ui/yarn.lock
Labels: approved, cat/build, cat/techdebt, group/ui

#1475 Feature/integrations redux store
  app/ui/src/app/api/providers/api-config-provider.service.ts
  app/ui/src/app/api/providers/api-http-provider.service.ts
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/app.component.ts
  app/ui/src/app/app.module.ts
  app/ui/src/app/config.service.ts
  app/ui/src/app/core/core.module.ts
  app/ui/src/app/core/providers/index.ts
  app/ui/src/app/core/providers/integration-provider.service.ts
  app/ui/src/app/core/providers/user-provider.service.ts
  app/ui/src/app/customizations/api-connector/api-connector.reducer.ts
  app/ui/src/app/dashboard/integrations.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/integration-support-provider.service.ts
  app/ui/src/app/integration/integration-support.module.ts
  app/ui/src/app/integration/list/list.component.ts
  app/ui/src/app/monitor/monitor.reducer.ts
  app/ui/src/app/platform/README.md
  app/ui/src/app/platform/types/api/api-config.service.ts
  app/ui/src/app/platform/types/index.ts
  app/ui/src/app/platform/types/integration/index.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
  app/ui/src/app/platform/types/integration/integration.actions.ts
  app/ui/src/app/platform/types/integration/integration.api.ts
  app/ui/src/app/platform/types/integration/integration.effects.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/platform/types/integration/integration.reducer.ts
  app/ui/src/app/platform/types/integration/integration.service.ts
  app/ui/src/app/platform/types/metadata/metadata.actions.ts
  app/ui/src/app/platform/types/metadata/metadata.reducer.ts
  app/ui/src/app/platform/types/platform.actions.ts
  app/ui/src/app/platform/types/platform.api.ts
  app/ui/src/app/platform/types/platform.effects.ts
  app/ui/src/app/platform/types/platform.models.ts
  app/ui/src/app/platform/types/platform.reducer.ts
  app/ui/src/app/support/support.component.ts
Labels: group/ui

#1526 fix(rest): Blank action for API Client connectors
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/util/OperationDescription.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/util/SwaggerHelper.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/util/IconGenerator.java
  app/rest/connector-generator/src/test/resources/swagger/basic_auth.unified_connector.json
  app/rest/connector-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/rest/connector-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/rest/jsondb/src/test/java/io/syndesis/jsondb/impl/JsonDBTest.java
  app/rest/runtime/src/test/java/io/syndesis/runtime/MigrationsITCase.java
Labels: approved, cat/bug, group/rest

#1527 chore(component-proxy): add an option to programmaticallly customize the delegated endpoint
  app/integration/component-proxy/pom.xml
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
  app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/ComponentProxyWithCustomEndpointTest.java
Labels: approved

#1529 chore: add missing test loggiing configuration
  app/connectors/connectors/jms/activemq-connectors/activemq-model/pom.xml
  app/connectors/connectors/jms/activemq-connectors/activemq-model/src/test/resources/logback-test.xml
  app/connectors/connectors/salesforce/salesforce-common/pom.xml
  app/connectors/connectors/salesforce/salesforce-common/src/test/resources/logback-test.xml
  app/connectors/connectors/salesforce/salesforce-on-create-connector/pom.xml
  app/connectors/connectors/salesforce/salesforce-on-create-connector/src/test/resources/logback-test.xml
  app/connectors/connectors/salesforce/salesforce-on-delete-connector/pom.xml
  app/connectors/connectors/salesforce/salesforce-on-delete-connector/src/test/resources/logback-test.xml
  app/connectors/connectors/salesforce/salesforce-on-update-connector/pom.xml
  app/connectors/connectors/salesforce/salesforce-on-update-connector/src/test/resources/logback-test.xml
  app/connectors/connectors/sql/pom.xml
  app/extension/converter/pom.xml
  app/extension/converter/src/test/resources/logback-test.xml
  app/rest/inspector/pom.xml
  app/rest/inspector/src/test/resources/logback-test.xml
  app/rest/jsondb/pom.xml
  app/rest/jsondb/src/test/resources/logback-test.xml
  app/rest/metrics-collector/pom.xml
  app/rest/metrics-collector/src/test/resources/logback-test.xml
Labels: approved

#1491 Add back in deployment table, wire up some actions
  app/ui/src/app/integration/detail-page/detail.component.html
  app/ui/src/app/integration/detail-page/detail.component.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/integration-support-provider.service.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/entity/rest.service.ts
Labels: approved, group/ui

#1293 Add some ignoreUsedDependencies that are needed in the build
  app/core/pom.xml
Labels: approved, cat/build

#1540 fix(tooling): sources `openshift_funcs` for dev command
  tools/bin/commands/dev
Labels: cat/build, size/s, status/2s2f

#1541 chore: improve MetadataRetrieval
  app/connectors/connector-verifier/src/main/java/io/syndesis/verifier/api/ComponentMetadataRetrieval.java
  app/connectors/connectors/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/verifier/src/main/java/io/syndesis/verifier/v1/ConnectorEndpoint.java
Labels: approved

#1543 [DevGuide] Added a couple of tips
  project/DevelopersGuide.md
Labels: approved

#1544 [Extension] If more than a single extension is used, the integration fails to start
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Labels: approved

#1539 fix: Spelling and grammatical errors
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connectors/connectors/twitter-connector/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/tech-extensions/tech-extensions-list.component.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
  app/ui/src/app/store/step/step.store.ts
Labels: approved, size/s

#1533 fix: filter connections by position in flow for connection select pages
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: group/ui

#1536 [feat] Adding metrics split out by deployment version
  app/core/model/src/main/java/io/syndesis/model/metrics/IntegrationDeploymentMetrics.java
  app/rest/metrics-collector/pom.xml
  app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/IntegrationMetricsHandler.java
  app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/JsonDBRawMetrics.java
  app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/PodMetricsReader.java
  app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/RawMetrics.java
  app/rest/metrics-collector/src/test/java/io/syndesis/rest/metrics/collector/MetricsCollectorTest.java
  app/rest/metrics-collector/src/test/java/io/syndesis/rest/metrics/collector/PodMetricsReaderTest.java
  app/rest/runtime/src/main/resources/application.yml
Labels: approved

#1549 remove duplicated/redundant css across integration editor pages
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.scss
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.scss
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.scss
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.scss
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.scss
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.scss
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.scss
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.scss
Labels: approved

#1532 fix(checkbox): allow string "true" to set checked state by default
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: approved, group/ui

#1546 Add test for OpenShiftServiceImpl::deploy and cleanup some test logs
  app/rest/openshift/pom.xml
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
  app/rest/openshift/src/test/java/io/syndesis/openshift/OpenShiftServiceImplTest.java
  app/rest/openshift/src/test/resources/logback-test.xml
  app/rest/runtime/src/test/java/io/syndesis/runtime/KubernetesClientITCase.java
Labels: approved

#1556 fix: Spelling and grammatical errors (II)
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: approved

#1521 fix: FTP and SFTP connectors
  app/connectors/connectors-catalog/pom.xml
  app/connectors/connectors/ftp/ftp-connector/pom.xml
  app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifier.java
  app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifierAutoConfiguration.java
  app/connectors/connectors/ftp/ftp-connector/src/main/java/io/syndesis/connector/ftp/FtpVerifierExtension.java
  app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/spring.factories
  app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/verifier/ftp
  app/connectors/connectors/ftp/pom.xml
  app/connectors/connectors/ftp/sftp-connector/pom.xml
  app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifier.java
  app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifierAutoConfiguration.java
  app/connectors/connectors/ftp/sftp-connector/src/main/java/io/syndesis/connector/sftp/SftpVerifierExtension.java
  app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/spring.factories
  app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/sftp.json
  app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/verifier/sftp
  app/connectors/pom.xml
  app/rest/dao/src/test/java/io/syndesis/dao/DataManagerTest.java
  app/verifier/pom.xml
Labels: approved

#1498 feature: First draft of an update concept
  doc/sdh/development/groups.adoc
  doc/sdh/development/groups.plantuml
  project/proposals/971-upgrade.adoc
  tools/bin/commands/doc
  tools/bin/commands/upgrade
  tools/bin/commands/upgrade_steps/prep_10_stop
  tools/bin/commands/upgrade_steps/prep_20_backup_db
  tools/bin/commands/upgrade_steps/prep_30_backup_resources
  tools/bin/commands/upgrade_steps/prep_40_process_template
  tools/bin/commands/upgrade_steps/upgrade_10_migrate_db
  tools/bin/commands/upgrade_steps/upgrade_20_stop_all
  tools/bin/commands/upgrade_steps/upgrade_30_upgrade_stateful_resources
  tools/bin/commands/upgrade_steps/upgrade_40_replace_stateless_resources
  tools/bin/commands/upgrade_steps/upgrade_50_replace_template
Labels: cat/tooling

#1555 Support IntegrationDeploymentMetrics in Prometheus metrics provider
  app/deploy/generator/06-syndesis-prometheus.yml.mustache
  app/rest/metrics-prometheus/src/main/java/io/syndesis/rest/metrics/prometheus/PrometheusConfigurationProperties.java
  app/rest/metrics-prometheus/src/main/java/io/syndesis/rest/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/rest/metrics-prometheus/src/main/java/io/syndesis/rest/metrics/prometheus/QueryResult.java
  app/rest/metrics-prometheus/src/test/java/io/syndesis/rest/metrics/prometheus/PrometheusMetricsProviderImplTest.java
  app/rest/runtime/src/main/resources/application.yml
Labels: approved, target/tp4

#1565 Updates to new tutorial based on feedback from David. #921
  doc/tutorials/topics/amq2api_confirm_works.adoc
  doc/tutorials/topics/amq2api_create_custom_step.adoc
  doc/tutorials/topics/amq2api_intro.adoc
  doc/tutorials/topics/amq2api_upload_todo_app_icon.adoc
  doc/tutorials/topics/comparison_of_sample_integrations.adoc
Labels: approved

#1570 fix(ui): Correct the labels for the main steps for creating an API connector
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/api-connector/api-connector-info/api-connector-info.component.html
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
Labels: approved

#1568 fix: Use 'kind' for the data shape type consistently, and align typel…
  app/connectors/connectors-maven-plugin/src/main/java/io/syndesis/maven/connectors/GenerateConnectorInspectionsMojo.java
  app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/sftp.json
  app/connectors/connectors/jms/amqp-connector/src/main/resources/META-INF/syndesis/connector/amqp.json
  app/connectors/connectors/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
  app/connectors/connectors/sql/src/test/resources/sql/demo_add_metadata.json
  app/connectors/connectors/sql/src/test/resources/sql/name_sql_metadata.json
  app/connectors/connectors/twitter-connector/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/core/model/src/main/java/io/syndesis/model/DataShape.java
  app/core/model/src/main/java/io/syndesis/model/DataShapeKinds.java
  app/extension/maven-plugin/src/main/java/io/syndesis/maven/GenerateMetadataMojo.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/SwaggerUnifiedShapeConnectorGenerator.java
  app/rest/connector-generator/src/main/java/io/syndesis/connector/generator/swagger/util/DataShapeHelper.java
  app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectorHandler.java
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
  app/rest/rest/src/test/java/io/syndesis/rest/v1/handler/IntegrationHandlerTest.java
  app/rest/runtime/src/test/java/io/syndesis/runtime/action/DynamicActionSalesforceITCase.java
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/platform/types/platform.models.ts
  app/ui/src/app/store/step/step.store.ts
  app/verifier/src/main/java/io/syndesis/verifier/v1/metadata/SalesforceMetadataRetrieval.java
Labels: approved

#1569 fix: store fetched data shapes on steps, related cleanup
  app/ui/src/app/integration/detail-page/detail.component.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: approved

#1575 chore: increase heap size for rest/runtime IT
  app/rest/runtime/pom.xml
Labels: approved

#1577 refactor(rest): setup integration test memory
  app/pom.xml
  app/rest/runtime/pom.xml
Labels: approved, group/rest, size/s

#1583 Support, restore correct code after wrong checkstyle lead modification
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/support/SupportUtil.java
Labels: approved

#1571 Added support for AMQP certificates, refactored Cert handling into a common connector-utils module
  app/connectors/connector-utils/pom.xml
  app/connectors/connector-utils/src/main/java/io/syndesis/connector/utils/CertificateUtil.java
  app/connectors/connector-utils/src/main/java/io/syndesis/connector/utils/KeyStoreHelper.java
  app/connectors/connector-utils/src/main/java/io/syndesis/connector/utils/TrustAllTrustManager.java
  app/connectors/connector-utils/src/test/java/io/syndesis/connector/utils/CertificateUtilTest.java
  app/connectors/connector-utils/src/test/java/io/syndesis/connector/utils/KeyStoreHelperTest.java
  app/connectors/connector-utils/src/test/resources/logback-test.xml
  app/connectors/connectors/jms/activemq-connectors/activemq-model/pom.xml
  app/connectors/connectors/jms/activemq-connectors/activemq-model/src/main/java/io/syndesis/connector/jms/ActiveMQUtil.java
  app/connectors/connectors/jms/activemq-connectors/activemq-model/src/test/java/io/syndesis/connector/jms/ActiveMQUtilTest.java
  app/connectors/connectors/jms/amqp-connector/pom.xml
  app/connectors/connectors/jms/amqp-connector/src/main/java/io/syndesis/connector/amqp/AMQPUtil.java
  app/connectors/pom.xml
Labels: approved, target/tp4

#1585 Added metadata to data shape for describe data shape, fixes #1552
  app/core/model/src/main/java/io/syndesis/model/DataShape.java
Labels: approved, target/tp4

#1591 fix: collections fallback to empty arrays when the API returns no data under Http 200
  app/ui/src/app/platform/types/integration/integration.reducer.ts
Labels: approved, cat/bug, group/ui

#1567 [fix] consolidating metrics config flags
  app/core/model/src/main/java/io/syndesis/model/metrics/IntegrationMetricsSummary.java
  app/rest/metrics-collector/src/main/java/io/syndesis/rest/metrics/collector/MetricsCollector.java
  app/rest/rest/src/main/java/io/syndesis/rest/metrics/NoopMetricsProviderImpl.java
  app/rest/rest/src/main/java/io/syndesis/rest/metrics/SQLMetricsProviderImpl.java
  app/rest/runtime/src/main/resources/application.yml
  app/rest/runtime/src/test/resources/application-test.yml
Labels: approved

#1584 chore(integration):improve component proxy's delegated endpoint customization
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
Labels: approved

#1588 feature: integration detail page revamped with new UI and metrics view
  app/ui/src/app/integration/components/index.ts
  app/ui/src/app/integration/components/logs.component.ts
  app/ui/src/app/integration/detail-page/detail.component.html
  app/ui/src/app/integration/detail-page/detail.component.scss
  app/ui/src/app/integration/detail-page/index.ts
  app/ui/src/app/integration/index.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/app/integration/integration_detail/index.ts
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/integration/integration_detail/integration-detail.component.scss
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/integration_detail/integration-history.component.html
  app/ui/src/app/integration/integration_detail/integration-history.component.scss
  app/ui/src/app/integration/integration_detail/integration-history.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.html
  app/ui/src/app/integration/integration_detail/integration-metrics.component.scss
  app/ui/src/app/integration/integration_detail/integration-metrics.component.ts
  app/ui/src/app/integration/integration_logs/index.ts
  app/ui/src/app/integration/integration_logs/integration-logs.component.html
  app/ui/src/app/integration/integration_logs/integration-logs.component.ts
Labels: approved, group/ui

#1594 Update connectors metadata according to #1548
  app/connectors/connectors/aws-s3-connector/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connectors/connectors/twitter-connector/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json
Labels: approved

#1595 Firs draft of Logstep
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/LogStepHandler.java
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/store/step/step.store.ts
Labels: approved

#1596 chore: Show DataShape name and mismatch indicator in tooltip
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: approved

#1599 Clean up support page HTML/CSS, global CSS for PF toolbar labels
  app/ui/src/app/support/support.component.html
  app/ui/src/app/support/support.component.scss
  app/ui/src/scss/utils/_overrides.scss
Labels: approved

#1600 fix: don't automatically transition out of action config if there's no config
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Labels: approved, group/ui

#1603 refactor(openshift): debug option for build
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftConfigurationProperties.java
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Labels: approved

#1605 refactor(openshift): debug option for build, remove double withEvn ca…
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
Labels: approved

#1613 chore: Update to atlasmap-1.33.4
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: approved

#1610 feat: add describe data page to editor page flow
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/describe-data/index.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/index.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: approved, group/ui

#1615 No need to add delegator role
  tools/bin/commands/minishift
Labels: approved

#1618 Adding ID to syndesis version paragraph
  app/ui/src/app/support/support.component.html
Labels: approved

#1619 fix: tidy up setting actions vs descriptors vs data shapes
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: approved, group/ui

#1620 Two small updates to AMQ-REST-API tutorial. That's it for TP3. #921
  doc/tutorials/topics/amq2api_add_damage_reporter_step.adoc
  doc/tutorials/topics/amq2api_confirm_works.adoc
Labels: approved

#1612 bring layout for actions with no configurable properties inline with rest of editor workflow
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
Labels: approved

#1626 chore: formalized the CSS architecture in a README
  app/ui/src/scss/README.md
Labels: approved, cat/techdebt, cat/techdoc, group/ui

#1628 Docs, improved english
  app/rest/docs/design/technical_design.md
Labels: approved

#1627 fix: Better error handling on datamapper initialization
  app/ui/package.json
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/yarn.lock
Labels: approved

#1629 fix(forms): correct and cleanup handling of form values
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/platform/types/form-factory/form-factory.service.ts
Labels: approved, group/ui

#1624 fix: Respect DataShapes returned via DynamicActionMetadata
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionActionHandler.java
Labels: approved

#1606 Import Single Integrations
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
  app/ui/src/app/integration/import-export/import/integration-import.models.ts
  app/ui/src/app/integration/import-export/import/integration-import.module.ts
  app/ui/src/app/integration/import-export/integration-import-export.component.html
Labels: approved

#1638 feat: Support storing bulletins of messages associated with integrations and connections. Part of issues #1052
  app/core/model/src/main/java/io/syndesis/model/DataShapeKinds.java
  app/core/model/src/main/java/io/syndesis/model/Kind.java
  app/core/model/src/main/java/io/syndesis/model/buletin/ConnectionBulletinBoard.java
  app/core/model/src/main/java/io/syndesis/model/buletin/IntegrationBulletinBoard.java
  app/core/model/src/main/java/io/syndesis/model/buletin/LeveledMessage.java
  app/rest/dao/src/main/java/io/syndesis/dao/ConnectionBulletinBoardDao.java
  app/rest/dao/src/main/java/io/syndesis/dao/IntegrationBulletinBoardDao.java
  app/rest/dao/src/main/java/io/syndesis/dao/manager/DataAccessObject.java
  app/rest/dao/src/main/java/io/syndesis/dao/manager/DataManager.java
  app/rest/jsondb/src/main/java/io/syndesis/jsondb/dao/JsonDbDao.java
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/connection/ConnectionHandler.java
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/IntegrationHandler.java
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/model/IntegrationOverview.java
  app/rest/rest/src/main/java/io/syndesis/rest/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: approved

#1633 Load all routes included in a given resource
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
Labels: approved

#1642 chore(fix): fix extension maven plugin not taking enums into account
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
Labels: approved

#1625 add mixin and helper class for scrollable body areas in app
  app/ui/src/app/connections/create-page/create-page.component.html
  app/ui/src/app/connections/create-page/create-page.component.scss
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/scss/base/_mixins.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved

#1651 Support for multiple file import
  app/ui/src/app/integration/import-export/import/integration-import.component.html
Labels: approved

#1655 chore: Update to atlasmap-1.33.5
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: approved

#1648 fix: avoid npe in detail page after publishing
  app/ui/src/app/platform/types/integration/integration.effects.ts
Labels: approved, group/ui

#1657 [Upgrade] Fix typos in help
  tools/bin/commands/upgrade
Labels: approved

#1658 Update produtized versions
  app/deploy/generator/03-syndesis-ui.yml.mustache
  tools/ignite-cluster/migrate-images.pl
Labels: approved

#1660 fix(build): system-test misc fixes
  tools/bin/commands/system-test
Labels: approved

#1670 fix(build): system-test needs to use flash,image
  tools/bin/commands/system-test
Labels: approved, cat/build, size/s

#1671 Add UX design for data buckets
  ux/README.md
  ux/designs/data-buckets/data-buckets.md
  ux/designs/data-buckets/img/IVP_notif_icon.png
  ux/designs/data-buckets/img/IVP_stepID_dataType.png
  ux/designs/data-buckets/img/dataBuckets_dataMapper_multSources.png
Labels: approved, group/ui, group/uxd, notif/doc

#1673 Bring integration importer inline with UXD designs
  app/ui/src/app/integration/import-export/import/integration-import.component.html
  app/ui/src/app/integration/import-export/import/integration-import.component.scss
  app/ui/src/app/integration/import-export/import/integration-import.component.ts
Labels: approved

#1685 fix: clicks on modal backdrop will not trigger undesired actions anymore
  app/ui/src/app/common/modal/modal.service.ts
Labels: approved, group/ui, group/uxd, notif/uxd

#1679 fix: delete button removed for custom connectors in API Client Connectors Page
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.html
Labels: approved, cat/glitch, group/ui

#1688 fix the pf toolbar in connector list on first step of creating connec…
  app/ui/src/app/connections/create-page/connection-basics/connection-basics.component.html
  app/ui/src/app/connections/create-page/create-page.component.scss
Labels: approved

#1684 decrease vertical space between steps in the integration editor left sidebar
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
Labels: approved

#1689 chore: Show source documents collapsed if there're multiple
  app/ui/package.json
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/yarn.lock
Labels: approved, ext/atlasmap, group/ui

#1694 FTP connector: datashape definition display errors in UI
  app/connectors/connectors/ftp/ftp-connector/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connectors/connectors/ftp/sftp-connector/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: approved

#1698 Add 'order' attribute alongside connector form definitions
  app/core/model/src/main/java/io/syndesis/model/Ordered.java
  app/core/model/src/main/java/io/syndesis/model/connection/ConfigurationProperty.java
  app/core/model/src/test/java/io/syndesis/model/connection/OrderedConfigurationPropertiesTest.java
Labels: approved

#1702 (fix) rework button text across pages
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
Labels: approved, group/ui

#1708 (chore) Add id to duration select field
  app/ui/src/app/common/ui-patternfly/duration-form-control.component.html
Labels: approved, group/ui

#1711 (chore) add support for showing messages field from an integration
  app/ui/src/app/integration/integration_detail/integration-detail.component.html
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: approved, group/ui

#1707 (chore) add amqp icon
  app/ui/src/assets/icons/amqp.connection.png
  app/ui/src/assets/icons/amqp.integration.png
Labels: approved, group/ui

#1697 Support OpenShift 3.7
  app/rest/controllers/src/main/java/io/syndesis/controllers/integration/IntegrationController.java
  app/rest/controllers/src/main/java/io/syndesis/controllers/integration/online/PublishHandler.java
  app/rest/openshift/pom.xml
  app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java
  tools/bin/commands/minishift
Labels: approved, cat/blocker, cat/tooling, group/integration, target/tp4

#1712 GitHub issue template for new features and bugs
  .github/ISSUE_TEMPLATE.md
Labels: approved

#1705 (chore) add support for the 'order' property when connector/action form config specifies it
  app/ui/src/app/connections/create-page/create-page.component.ts
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/platform/types/connection/connection.models.ts
  app/ui/src/app/platform/types/form-factory/form-factory.service.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: approved, group/ui

#1681 (chore) rework elements for step index, tooltips, datamapper required indicator
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/scss/utils/_helpers.scss
Labels: approved, group/ui

#1720 refactor: Rename 'syndesis-restricted' to 'syndesis', removed docker image mode
  app/deploy/README.md
  app/deploy/generator/01-header.yml.mustache
  app/deploy/generator/03-syndesis-ui.yml.mustache
  app/deploy/generator/04-syndesis-db.yml.mustache
  app/deploy/generator/04-syndesis-oauth-proxy.yml.mustache
  app/deploy/generator/04-syndesis-rest.yml.mustache
  app/deploy/generator/04-syndesis-verifier.yml.mustache
  app/deploy/generator/05-syndesis-security.yml.mustache
  app/deploy/generator/06-syndesis-prometheus.yml.mustache
  app/deploy/generator/run.sh
  app/deploy/generator/syndesis-template.go
  app/deploy/staging/README.md
  app/deploy/syndesis-ci.yml
  app/deploy/syndesis-dev-restricted.yml
  app/deploy/syndesis-dev.yml
  app/deploy/syndesis-restricted.yml
  app/deploy/syndesis.yml
  app/tests/src/test/resources/setup.sh
  app/tests/src/test/resources/teardown.sh
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
  tools/minishift-build/README.md
Labels: approved

#1723 Stored Procedure Selection is not set in edit screen #1718
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: approved

#1728 NPE in DB2StoredProc Integration
  app/connectors/connectors/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/stored/SqlStoredConnectorWitDefaultsTest.java
  app/connectors/connectors/sql/src/test/java/io/syndesis/connector/sql/util/SqlConnectorTestSupport.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
Labels: approved

#1703 feat(chart): utilize patternfly donut chart in dashboard
  app/ui/.angular-cli.json
  app/ui/package.json
  app/ui/src/app/dashboard/dashboard.component.html
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard.module.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
  app/ui/yarn.lock
Labels: group/ui

#1735 fix: bring back mouseover tooltip in collapsed IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
Labels: approved

#1738 feat: add a link that creates a datamapper step in front of whatever step has a mismatch indicator
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts
  app/ui/src/app/store/step/step.store.ts
Labels: approved

#1739 Dashboard UI improvements
  app/ui/src/app/dashboard/dashboard.component.scss
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.scss
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.scss
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.html
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.scss
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.ts
Labels: approved
