Repository syndesisio/syndesis, pull requests merged in 2018-08, with the labels that each got.

#3249 IRC Icon added
  ux/connections_icons/png/connectionicons_irc.png
  ux/connections_icons/svg/connectionicons_IRC.svg
Labels: pr/approved

#3245 adding host field #3197
  app/server/dao/src/main/resources/META-INF/syndesis/api-connectors/connector-concur.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
Labels: pr/approved, pr/review-requested

#3259 [IRC] Polish fields and description
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
Labels: pr/approved

#3257 Fixes error while building with tests
  app/pom.xml
Labels: pr/approved, pr/review-requested

#3262 fix(syndesis): Issue with directory when doing the full build run
  tools/bin/commands/build
  tools/bin/commands/minishift
Labels: pr/approved

#3250 Fixes #2611, Added check for duplicate names across integration deployments, fixed integration delete to delete all deployments
  app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/integration/NoDuplicateIntegration.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationTest.java
  app/server/dao/src/main/java/io/syndesis/server/dao/validation/integration/NoDuplicateIntegrationValidator.java
  app/server/dao/src/main/resources/META-INF/validation/integration-constraint.xml
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/runtime/src/main/resources/messages.properties
  app/server/runtime/src/test/java/io/syndesis/server/runtime/UpdaterITCase.java
  tools/bin/commands/build
Labels: pr/review-requested

#3269 refactor(irc-connector): Add new icon to connector
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
Labels: pr/approved

#3272 feature(build): Add support for building the operator on the Minishift docker daemon.
  tools/bin/commands/build
  tools/bin/commands/util/operator_funcs
Labels: cat/build, group/operator, pr/approved

#3273 refactor(operator): load syndesis-template.yml from /conf
  install/operator/Dockerfile
  install/operator/cmd/syndesis-operator/main.go
Labels: pr/approved, pr/review-requested

#3279 feature: Tuned UX of syndesis according to suggestion and added docs.
  doc/sdh/cli/cmd_build.adoc
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/build
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/release
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
Labels: pr/approved

#3268 Last Page Of ApiCurio Editor Wizard Does Not Have Updated Title and Description
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
Labels: pr/approved

#3282 Resubmit the edited spec for validation to the backend
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
Labels: pr/approved, pr/review-requested

#3283 Please be happy Mr. Lint
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
Labels: pr/approved, pr/review-requested

#3281 fix: typo in build
  .circleci/config.yml
  tools/bin/commands/build
Labels: pr/approved

#3285 Error 500 when deleting integrations
  app/pom.xml
Labels: pr/approved

#3287 Updated label descriptions
  doc/sdh/development/labels.adoc
Labels: pr/approved, pr/review-requested

#3288 Hide the Review/edit button if the provided URL to the spec file is unfetchable
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.ts
Labels: pr/approved, pr/review-requested

#3295 Fix lint errors
  app/ui/src/polyfills.ts
Labels: pr/approved, pr/review-requested

#3290 fix: ensure errors get propogated properly from the store; ensure the detail page reacts to deleted integration
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/store/entity/entity.store.ts
Labels: pr/approved

#3275 refactor(build): when installing with --local use provide the operator with local template
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#3300 chore: update tooltip for disabled API connector edit button
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3303 upgrade patternfly-ng to 4.2.2 (latest) + dependencies
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#3255 fix(server): use timeout of 35mins
  app/server/logging/jsondb/infinitest.filters
  app/server/logging/jsondb/pom.xml
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupportIT.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/TestPodLogMonitor.java
  app/server/logging/jsondb/src/test/resources/logback-test.xml
Labels: pr/review-requested

#3311 fix(build): make sure that logback is a runtime dependency
  app/pom.xml
  app/server/logging/jsondb/pom.xml
Labels: pr/approved, pr/review-requested

#3307 chore(install): Added better error handling and split up admin setup
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/index.adoc
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
  tools/bin/syndesis
Labels: group/install, prio/p1

#3316 fix(ui): display error handling to OAuth /connections/create/review page
  app/ui/src/app/connections/create-page/review/review.component.html
  app/ui/src/app/connections/create-page/review/review.component.ts
Labels: pr/approved, pr/review-requested

#3312 fix: remove text brand element
  app/ui/src/app/app.component.html
Labels: prio/p1

#3323 fix(syndesis): Fix broken --cluster option
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: cat/build, group/install, pr/needs-backport

#3325 fix(syndesis): Fix broken --cluster option
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: cat/build, group/install, pr/1.4.x, pr/approved

#3317 feat(server): add `specification` `configuredProperty` to the `../info` endpoint
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectorSummary.java
  app/server/connector-generator/src/main/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/connector-generator/src/test/java/io/syndesis/server/connector/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/runtime/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/connector/CustomSwaggerConnectorITCase.java
Labels: pr/review-requested

#3331 fix(ui): error handling with OAuth connections
  app/ui/src/app/connections/create-page/review/review.component.html
  app/ui/src/app/connections/create-page/review/review.component.ts
Labels: pr/approved, pr/review-requested

#3332 fix(ui): error handling with OAuth connections
  app/ui/src/app/connections/create-page/review/review.component.html
  app/ui/src/app/connections/create-page/review/review.component.ts
Labels: pr/1.4.x, pr/approved, pr/review-requested

#3333 Fix minor glitch with install script
  tools/bin/commands/install
Labels: pr/approved

#3334 fix: Release syndesis-operator.yml with the proper version
  tools/bin/commands/install
  tools/bin/commands/release
  tools/bin/commands/util/operator_funcs
Labels: cat/build, pr/needs-backport

#3339 fix: set the index and make it's usage more apparent
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
Labels: pr/1.4.x, pr/approved, pr/review-requested

#3348 fix: Release syndesis-operator.yml with the proper version (#3334)
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/install
  tools/bin/commands/release
  tools/bin/commands/util/operator_funcs
Labels: cat/build, pr/1.4.x, pr/approved

#3351 feature(syndesis): Add an option '--operator-only' to only install the operator without resource
  doc/sdh/cli/cmd_install.adoc
  tools/bin/commands/install
  tools/bin/install-syndesis
Labels: pr/approved

#3256 feat(server): Provides uses element to Connections API
  app/common/model/src/main/java/io/syndesis/common/model/EmptyListResult.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java
Labels: pr/approved, pr/review-requested

#3353 fix: ROUTE_HOST_NAME must not be required if used with the operator.
  install/generator/01-header.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: cat/bug, group/install, pr/approved, pr/needs-backport

#3354 fix: ROUTE_HOST_NAME must not be required if used with the operator.
  install/generator/01-header.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: group/install, pr/1.4.x, pr/approved

#3345 Fixes UX issues with API client connector workflow required auth fields
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-auth/api-connector-auth.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#3349 chore(release): Fix quoting for operator version number when creating moving tag
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/release
Labels: cat/build, pr/needs-backport

#3357 fix(operator): stateCheckInterval was not properly picked up by the operator
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  tools/bin/commands/minishift
Labels: cat/bug, group/operator, pr/approved, pr/needs-backport, pr/review-requested

#3361 feature: Add IRC notification on build failure
  .circleci/config.yml
  .circleci/send_irc_notification.sh
Labels: cat/build, pr/approved

#3360 allow user to navigate back to connection-basics step from review step when creating connection
  app/ui/src/app/connections/create-page/review/review.component.ts
Labels: pr/approved, pr/review-requested

#3296 fix: integration list re-rendering when polling
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.ts
Labels: pr/approved

#3363 fix(operator): stateCheckInterval was not properly picked up by the operator [backport]
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  tools/bin/commands/minishift
Labels: group/operator, pr/1.4.x, pr/approved, pr/review-requested

#3364 enhancement: Updated text strings for Kafka connection configuration
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Labels: pr/approved, pr/needs-backport, pr/review-requested

#3358 Activity fixes
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java
  app/server/logging/jsondb/pom.xml
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupportIT.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/TestPodLogMonitor.java
Labels: pr/needs-backport, pr/review-requested

#3359 Backport activity fixes
  app/server/logging/jsondb/pom.xml
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingControllerTest.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupportIT.java
  app/server/logging/jsondb/src/test/java/io/syndesis/server/logging/jsondb/controller/TestPodLogMonitor.java
Labels: pr/1.4.x, pr/review-requested

#3365 Merge pull request #3364 from TovaCohen/update-kafka-json
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Labels: pr/review-requested

#3368 fix(copy-component): fix copy to clipboard component to accepts tooltips
  app/ui/package.json
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.ts
  app/ui/src/app/integration/integration_detail/integration-metrics.component.ts
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-app-modal.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
  app/ui/src/assets/dictionary/en-GB.json
  app/ui/yarn.lock
Labels: group/ui, pr/approved, pr/review-requested

#3321 Update doc to state requirement for Twitter developer account
  doc/connecting/topics/connecting_to_twitter.adoc
  doc/shared/register_with_twitter.adoc
  doc/tutorials/topics/t2sf_prereqs.adoc
Labels: pr/review-requested

#3379 Add a dependency-management version for hibernate-validator.
  app/pom.xml
Labels: pr/approved

#3372 fix(imports): remove (more) unused imports
  app/ui/src/app/common/icon-path.pipe.ts
  app/ui/src/app/connections/create-page/review/review.component.spec.ts
  app/ui/src/app/connections/create-page/review/review.component.ts
  app/ui/src/app/connections/detail-page/info.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/customizations.component.ts
  app/ui/src/app/customizations/tech-extensions/detail/tech-extension-detail.component.ts
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.ts
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/integration_detail/integration-detail.component.ts
  app/ui/src/app/integration/list/list.component.html
  app/ui/src/app/integration/list/list.component.spec.ts
  app/ui/src/app/integration/list/status-detail.component.ts
  app/ui/src/app/vendor/vendor.module.ts
Labels: group/ui, pr/approved, pr/review-requested

#3385 Add a dependency-management version for hibernate-validator. syndes…
  app/pom.xml
Labels: pr/approved, pr/review-requested

#3387 fix(server): don't try to count steps without connections
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
Labels: pr/review-requested

#3383 Enables drag/drop UI for API connector upload to be similar as rest of app
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.scss
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.ts
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3392 fix(server): don't destroy Connector's configuredProperties on second startup (1.4.x backport)
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: pr/approved, pr/review-requested

#3393 fix(server): don't destroy Connector's configuredProperties on second startup
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: pr/approved, pr/review-requested

#3397 fix(server): when discarding activity logs leave the newest entries (1.4.x backport)
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
  app/common/util/src/test/java/io/syndesis/common/util/KeyGeneratorTest.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
Labels: pr/approved, pr/review-requested

#3398 fix(server): when discarding activity logs leave the newest entries
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
  app/common/util/src/test/java/io/syndesis/common/util/KeyGeneratorTest.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
Labels: pr/approved, pr/review-requested

#3406 fix(connector): set exchange if missing
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/capture/OutMessageCaptureProcessor.java
Labels: pr/approved, pr/review-requested

#3391 fix(connector): allow for schema/payloads with only parameters
  app/connector/webhook/pom.xml
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WrapperProcessor.java
  app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
  app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WrapperProcessorTest.java
Labels: pr/approved, pr/review-requested

#3418 Address problems identified in Issues 3411 and 3412
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-swagger-upload/api-connector-swagger-upload.component.html
Labels: pr/approved

#3438 fix(slack connector): Slack Connector: when used with username as act…
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackChannelCustomizer.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/approved

#3439 feature(slack-connector): Add consumer action
  app/connector/rest-swagger/src/main/resources/camel-connector.json
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#3441 fix(slack connector): Slack Connector: when used with username as act…
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackChannelCustomizer.java
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: pr/1.4.x, pr/approved, pr/review-requested

#3445 Fix #3444: making telegram tech preview
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#3446 Fix #3444: making telegram tech preview (on 1.4.x)
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#3366 user doc: user doc for ServiceNow connector
  doc/connecting/master.adoc
  doc/connecting/topics/add_servicenow_connection_finish.adoc
  doc/connecting/topics/add_servicenow_connection_start.adoc
  doc/connecting/topics/add_servicenow_connections.adoc
  doc/connecting/topics/connecting_to_servicenow.adoc
  doc/connecting/topics/create_servicenow_connection.adoc
  doc/connecting/topics/identify_concur_fields_for_mapping.adoc
  doc/connecting/topics/supported_connectors.adoc
Labels: pr/review-requested

#3448 feature(upgrade): Adapte templates and operator for referencing a registry
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: group/install, group/operator, pr/needs-backport, pr/review-requested

#3447 chore(upgrade): migration scripts for 1.4.x
  tools/upgrade/Dockerfile
  tools/upgrade/migration/resource/1.1/02_db_config_map.sh
  tools/upgrade/migration/resource/1.1/03_server_config_map_upgrade.sh
  tools/upgrade/migration/resource/1.1/04_label_updates.sh
  tools/upgrade/migration/resource/1.1/05_annotation_updates.sh
Labels: pr/needs-backport, pr/review-requested

#3449 feature(upgrade): Adapte templates and operator for referencing a reg…
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: group/install, group/operator, pr/1.4.x, pr/approved

#3450 chore(upgrade): migration scripts for 1.4.x (#3447)
  tools/upgrade/Dockerfile
  tools/upgrade/migration/resource/1.1/02_db_config_map.sh
  tools/upgrade/migration/resource/1.1/03_server_config_map_upgrade.sh
  tools/upgrade/migration/resource/1.1/04_label_updates.sh
  tools/upgrade/migration/resource/1.1/05_annotation_updates.sh
Labels: group/install, group/operator, pr/1.4.x, pr/approved

#3494 refactor(kafka-connector): Minor stuff
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataAutoConfiguration.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java
Labels: pr/approved

#3509 bug(blank-slate): update blank slate primary action button
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/dashboard/dashboard_connections/dashboard-connections.component.html
  app/ui/src/app/dashboard/dashboard_integrations/dashboard-integrations.component.html
Labels: pr/approved, pr/review-requested

#3510 fix: avoid NPE and hide basic filter if there's no output data shape in any previous connection
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved

#3501 fix(server): Notifies of stale integration after connection update
  app/common/model/src/main/java/io/syndesis/common/model/action/Action.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/bulletin/LeveledMessage.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connection.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectionBase.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/Connector.java
  app/common/model/src/main/java/io/syndesis/common/model/extension/Extension.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3507 Proposed fix for Issue 2717 Provide more information about the imported Swagger specification
  app/ui/src/app/customizations/api-connector/api-connector-review/api-connector-review.component.html
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/review-requested

#3511 bug(connections): fix "configuration required" spacing in connection list
  app/ui/src/app/connections/list/list.component.scss
Labels: pr/approved, pr/review-requested

#3518 chore: Update to AtlasMap 1.36.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/src/config.json.example
  app/ui/src/config.json.minishift
  app/ui/src/config.json.staging
  app/ui/yarn.lock
Labels: pr/approved

#3522 Fix #3515: do not override command from operator image
  install/operator/deploy/syndesis-operator.yml
Labels: pr/approved

#3525 feature(slack-connector): Add Metadata to retrieve channels in the co…
  app/connector/slack/pom.xml
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataAutoConfiguration.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataExtension.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataRetrieval.java
  app/connector/slack/src/main/resources/META-INF/spring.factories
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/connector/slack/src/test/java/io/syndesis/connector/slack/SlackMetaDataExtensionTest.java
Labels: pr/approved

#3527 refactor(slack-connector): refactoring of readResponse methods
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataExtension.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackVerifierExtension.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/utils/SlackUtils.java
Labels: pr/approved

#3528 refactor(connector): Minor typos fix
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorTest.java
  app/connector/slack/src/main/java/io/syndesis/connector/slack/SlackMetaDataExtension.java
Labels: pr/approved
