Repository syndesisio/syndesis, pull requests merged in 2018-11, with the labels that each got.

#4004 fix: consider all container objects when unwrapping response
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
Labels: pr/needs-backport

#4012 fix(template-step): Removes need for body prefix in template
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/TemplateStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/MustacheTemplatePreProcessor.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/TemplateMustacheConstants.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/templater/TemplateProcessingException.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/TemplateStepHandlerTest.java
  app/ui/src/app/integration/edit-page/step-configure/templater/mustache-mode.ts
Labels: pr/approved, pr/review-requested

#4023 [fix] Upgrade Spring Boot due to vulnerabilities found #3917
  app/pom.xml
Labels: pr/approved

#4032 Fix #4010: remove unneeded subpath
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#4033 Fix #4010: remove unneeded subpath
  install/generator/07-syndesis-upgrade.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved

#4022 Developer handbook fixes
  doc/sdh/cli/cmd_build.adoc
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/index.adoc
  doc/sdh/development/local.adoc
  doc/sdh/introduction.adoc
Labels: pr/approved, pr/review-requested

#4039 chore: introduce wrapped JSON schema identifier (1.5.x backport)
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ResponseCustomizer.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/ResponseCustomizerTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/JsonSchemaHelper.java
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
Labels: pr/approved, pr/review-requested

#4042 Update to Telegram json file to change text in labels and descriptions.
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#4037 chore: introduce wrapped JSON schema identifier
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ResponseCustomizer.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/ResponseCustomizerTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/JsonSchemaHelper.java
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
Labels: pr/review-requested

#4057 Telegram docs backport 1.5.x
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved

#4060 fix: fetch from the backend after a save & validate form
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.html
  app/ui/src/app/settings/oauth-apps/oauth-app-form.component.ts
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.html
  app/ui/src/app/settings/oauth-apps/oauth-apps.component.ts
Labels: pr/approved

#4062 fix: only provide a link when the target integration is created, also cleanup editor state
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.ts
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
Labels: pr/approved

#4065 fix(version): upgrade commons-compress to version 1.18
  app/integration/project-generator/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#4067 [fix] Inform user when integration limit is reached when attempting t…
  app/common/model/src/main/java/io/syndesis/common/model/Kind.java
  app/common/model/src/main/java/io/syndesis/common/model/user/Quota.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/user/UserConfigurationProperties.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/user/UserHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/user/UserHandlerTest.java
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis-dev.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4069 refactor(integration list items): relocating cursor pointer
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#4076 fix(connector): include Spring configuration (1.5.x backport)
  app/connector/rest-swagger/src/main/resources/META-INF/spring.factories
Labels: pr/approved, pr/review-requested

#4075 fix(connector): include Spring configuration
  app/connector/rest-swagger/src/main/resources/META-INF/spring.factories
Labels: pr/approved, pr/review-requested

#4035 Fix #4034: Resource id value cannot be passed for fhir read action
  app/connector/fhir/pom.xml
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirReadMessageModel.java
Labels: pr/approved

#3924 chore(upgrade): Update release script to set the proper upgrade pod tag.
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/upgrade.go
  tools/bin/commands/release
Labels: pr/approved

#4083 fix(dependencies): Upgrade Spring to version 4.3.17.RELEASE
  app/pom.xml
Labels: pr/approved

#4079 chore(upgrade): upgrade image stream tag in the syndesis-server-config ConfigMap
  tools/upgrade/migration/resource/1.2/01_server_config_map_upgrade.sh
Labels: pr/approved, pr/review-requested

#4078 chore(upgrade): upgrade image stream tag in the syndesis-server-config ConfigMap (1.5.x backport)
  tools/upgrade/migration/resource/1.2/01_server_config_map_upgrade.sh
Labels: pr/approved, pr/review-requested

#4088 [fix] Missing icon custom connector after import #4055
  app/common/model/src/main/java/io/syndesis/common/model/Dependency.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved

#4092 [fix] Correct date format in integration activity log
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html
Labels: pr/approved, pr/review-requested

#3984 The use of OAuthClient
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/run.sh
  install/generator/syndesis-template.go
  install/operator/deploy/syndesis-operator.yml
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/reconcile.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
  install/syndesis-privileged.yml
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested

#4099 more sensible defaults
  app/connector/ftp/src/main/resources/META-INF/syndesis/connector/ftp.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
Labels: pr/approved

#4100 Fixes for OAuthClient caused issues
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#4103 [fix] Latest minishift requires openshift >=3.10.0
  tools/bin/commands/minishift
Labels: pr/approved

#4105 Syndesis tool fixes
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#4107 fix: no need to commit anything from app/connector
  tools/bin/commands/release
Labels: pr/approved, pr/review-requested

#4106 fix: no need to commit anything from app/connector
  tools/bin/commands/release
Labels: pr/approved, pr/review-requested

#4110 Fix #4109: Add support for maven-mirror to syndesis build
  app/s2i/pom.xml
  app/s2i/src/main/resources/settings.xml
  tools/bin/commands/build
Labels: pr/approved

#4116 fix(tooltip glyphicon): tooltip misaligned with glyphicon.
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved

#4115 fix: fix unbound variable error
  tools/bin/commands/install
Labels: pr/approved

#4119 Fix #4109: Add missing docs
  doc/sdh/cli/cmd_build.adoc
  tools/bin/commands/build
Labels: pr/approved

#4124 Fix #4123: "syndesis install" accidentally fails
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved

#4127 fix: add ${NAMESPACE} to cluster wide resources
  install/operator/deploy/syndesis-operator.yml
Labels: pr/approved, pr/review-requested

#4128 Google connector improvements
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailReceiveEmailCustomizer.java
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/google-calendar/pom.xml
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarEventsCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarGetEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarMetaDataExtension.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarSendEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/GoogleCalendarUpdateEventCustomizer.java
  app/connector/google-calendar/src/main/java/io/syndesis/connector/calendar/utils/GoogleCalendarUtils.java
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
  app/connector/google-calendar/src/test/resources/logback-test.xml
Labels: group/connector, pr/approved, pr/review-requested

#4129 Google sheets connector basics
  app/connector/google-sheets/pom.xml
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAppendValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsVerifier.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsVerifierAutoConfiguration.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSheet.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSpreadsheet.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleValueRange.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/BatchGoogleSheetsClientFactory.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsClientFactory.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsComponent.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsConfiguration.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsConsumer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsEndpoint.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsProducer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsVerifierExtension.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsConstants.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsPropertiesHelper.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamComponent.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConfiguration.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConstants.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConsumer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamEndpoint.java
  app/connector/google-sheets/src/main/resources/META-INF/services/org/apache/camel/component/google-sheets
  app/connector/google-sheets/src/main/resources/META-INF/services/org/apache/camel/component/google-sheets-stream
  app/connector/google-sheets/src/main/resources/META-INF/spring.factories
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/main/resources/org/apache/camel/catalog/components/google-sheets-stream.json
  app/connector/google-sheets/src/main/resources/org/apache/camel/catalog/components/google-sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/AbstractGoogleSheetsCustomizerTestSupport.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAppendValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/GoogleSheetsVerifierExtensionTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsConfigurationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsIntegrationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsValuesIntegrationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/AbstractGoogleSheetsStreamTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
  app/connector/google-sheets/src/test/resources/logback-test.xml
  app/connector/google-sheets/src/test/resources/test-options.properties
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom/pom.xml
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentDefinition.java
  app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/ComponentDefinitionTest.java
  app/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: group/connector, pr/approved, pr/review-requested

#4135 Google sheets connector basics reviewed
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamComponent.java
  app/meta/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
Labels: pr/approved, pr/review-requested

#4155 fix: Several issues affecting productisation
  install/generator/02-syndesis-secrets.yml.mustache
  tools/upgrade/common.sh
  tools/upgrade/steps/prep_40_process_template
Labels: pr/1.5.x

#4157 Upgrades Jackson to 2.9.7
  app/pom.xml
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/resources/swagger/invalid/warning-petstore.swagger.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
Labels: pr/approved

#4161 [fix] Correct date format in integration activity log
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.html
Labels: pr/approved

#4163 [chore] upgrading to latest activemq
  app/pom.xml
Labels: pr/approved

#4164 [chore in square brackets] upgrading sb
  app/pom.xml
Labels: pr/approved, pr/review-requested

#4174 [closes #4173] Fix parsing minor version
  tools/upgrade/migration/preflight.sh
Labels: pr/approved, pr/review-requested

#4185 fix: syndesis minishift —-install was installing the operator to the wrong namespace (default) if the myproject namespace has been deleted.
  tools/bin/commands/minishift
Labels: pr/approved

#4184 feat: Add a simpler docker based build strategy via Docker the does not depend on multi-stage docker builds.
  install/operator/Dockerfile-builder
  install/operator/build.sh
Labels: pr/approved

#4193 chore: update version in dictionary
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#4194 chore: update version in dictionary - 1.5.x
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/1.5.x, pr/approved

#4160 refactor: set the phases on for Syndesis Maven plugins
  app/connector/activemq/pom.xml
  app/connector/amqp/pom.xml
  app/connector/api-provider/pom.xml
  app/connector/aws-s3/pom.xml
  app/connector/dropbox/pom.xml
  app/connector/fhir/pom.xml
  app/connector/ftp/pom.xml
  app/connector/gmail/pom.xml
  app/connector/google-calendar/pom.xml
  app/connector/google-sheets/pom.xml
  app/connector/http/pom.xml
  app/connector/irc/pom.xml
  app/connector/kafka/pom.xml
  app/connector/log/pom.xml
  app/connector/mqtt/pom.xml
  app/connector/salesforce/pom.xml
  app/connector/servicenow/pom.xml
  app/connector/sftp/pom.xml
  app/connector/slack/pom.xml
  app/connector/sql/pom.xml
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/connector/telegram/pom.xml
  app/connector/timer/pom.xml
  app/connector/twitter/pom.xml
  app/connector/webhook/pom.xml
  app/extension/example/log-step/pom.xml
Labels: pr/approved, pr/review-requested
