Repository syndesisio/syndesis, pull requests merged in 2019-10, with the labels that each got.

#6813 fix: AWSDDBMetadataAdapterTest failures
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Labels: pr/approved, pr/review-requested

#6814 Change binary name from operator to syndesis-operator
  install/operator/.lib.sh
  install/operator/build/Dockerfile
Labels: backport 1.8.x, group/operator, pr/approved, pr/review-requested, size/s

#6780 feat: support a `—source-gen skip` option in the operator build…
  install/operator/.lib.sh
  install/operator/build.sh
  tools/bin/commands/build
Labels: pr/approved, size/m

#6809 ENTESB-11790: pick latest s2i image for building
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
Labels: pr/approved, pr/review-requested, size/XS

#6818 ENTESB-11643 Revert all DV buttons to pf3
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/m

#6821 user doc: remove duplicated content for developing extensions
  doc/assemblies/customizing/as_developing-extensions.adoc
  doc/developing_extensions/assemblies/customizing
  doc/developing_extensions/attributes-links.adoc
  doc/developing_extensions/attributes.adoc
  doc/developing_extensions/docinfo.xml
  doc/developing_extensions/images/customizing
  doc/developing_extensions/images/integrating-applications
  doc/developing_extensions/master.adoc
  doc/developing_extensions/modules/customizing
  doc/developing_extensions/topics/developing_extensions.adoc
  doc/developing_extensions/topics/shared
  doc/managing_environments/topics/admin_tasks.adoc
  doc/managing_environments/topics/logs.adoc
  doc/managing_environments/topics/user_admin.adoc
Labels: size/XXL

#6806 ENTESB-11789 Resolves issue with create virtualization
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6784 fix(ci): ignore `cherry-pick-backport` branches
  .circleci/config.yml
Labels: pr/approved, pr/review-requested, size/s

#6819 chore(ui): description for the Specify Security
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
Labels: pr/approved, pr/review-requested, size/XS

#6827 (operator) Check in forgotten template cache
  install/operator/go.mod
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, pr/review-requested, size/XS

#6833 chore: adding a --source-gen verify-none option that the CI build can use to validate that no generated sources need to be checked in.
  .circleci/config.yml
  install/operator/.lib.sh
  install/operator/build.sh
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets_vfsdata.go
  tools/bin/commands/build
Labels: size/m

#6834 add short to test for release
  .circleci/config.yml
Labels: group/operator, pr/approved, pr/review-requested, size/XS

#6842 Preview results in view editor are not horizontally scrollable
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/l

#6836 fix for ENTESB-11787 - Reconfiguration of SQL query step changes text to dropdown
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Labels: pr/approved

#6848 user doc: Updates to tutorials for 7.5
  doc/images/integrating-applications/CombineMapping.png
  doc/images/integrating-applications/SeparateMapping.png
  doc/images/tutorials/CopyCallback.png
  doc/images/tutorials/t2sf-mappings.png
  doc/modules/tutorials/p_amq2api-create-rest-api-connector.adoc
  doc/modules/tutorials/p_t2sf-add-filter-step.adoc
Labels: backport 1.8.x

#6845 ENTESB-11772: Generate a template from the operator configuration
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/vendor/github.com/spf13/cast/LICENSE
  install/operator/vendor/github.com/spf13/cast/Makefile
  install/operator/vendor/github.com/spf13/cast/README.md
  install/operator/vendor/github.com/spf13/cast/cast.go
  install/operator/vendor/github.com/spf13/cast/caste.go
  install/operator/vendor/github.com/spf13/cast/go.mod
  install/operator/vendor/github.com/spf13/cast/go.sum
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/xl

#6847 Fix for ENTESB 11633 - setting limit to prevent timeout.
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
Labels: pr/approved

#6843 fix(connector): converting all results in the same format
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
Labels: pr/approved, pr/review-requested

#6854 TEIIDTOOLS-783 Adjusts DV Connection card formatting
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsGrid.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsGridCell.tsx
Labels: pr/approved, pr/review-requested, size/m

#6855 TEIIDTOOLS-797 Remove unused DV pages
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: pr/approved, pr/review-requested, size/l

#6853 change syndesis installation to use the operator binary for crc
  .gitignore
  doc/sdh/cli/cmd_crc.adoc
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/binaries/README.md
  tools/bin/commands/crc
  tools/bin/commands/util/operator_func.bats
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested, size/l

#6857 chore: Update to AtlasMap 1.42.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/s

#6862 fix(connector): adapting producer input
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerCustomizer.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
Labels: group/connector, pr/approved, pr/review-requested

#6841 Release syndesis binaries for real
  .circleci/config.yml
Labels: backport 1.8.x, size/XS

#6864 chore: Update to AtlasMap 1.42.6
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved

#6867 surround upgrade syndesis version with quotes
  .gitignore
  install/operator/go.mod
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/upgrade.go
Labels: pr/approved, pr/review-requested, size/s

#6869 fix(TEIIDTOOLS-792) - Virtualization Description Issues
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.css
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.css
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6870 fix: dependency issues in integration tests
  app/test/integration-test/pom.xml
Labels: pr/approved, pr/review-requested, size/s

#6873 fix: suppress examining data shapes for extensions,
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: pr/approved, size/XS

#6879 chore: Update Minishift installation scripts to use the new operator binary
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/crc
  tools/bin/commands/minishift
Labels: pr/approved, size/m

#6888 fix(ENTESB-11787): Reconfiguration of SQL query step changes text to dropdown
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/sql/src/test/resources/sql/name_sql_batch_update_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_no_param_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_update_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_update_no_param_metadata.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Labels: backport 1.8.x, pr/approved, pr/review-requested

#6885 fix(connector): embedded mongo align version
  app/connector/mongodb/pom.xml
Labels: dependencies, group/connector, pr/approved, pr/review-requested, size/s

#6883 chore: remove remnants of OpenShift templates
  .pre-commit-config.yaml
  install/README.md
  install/support/validate-generated-templates.sh
  install/syndesis.yml
Labels: pr/approved, size/XXL

#6887 TEIIDTOOLS-801 disables create virtualization button if name is empty
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationCreateForm.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6881 fix(connector): default authentication database
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
Labels: group/connector, pr/approved, pr/review-requested

#6886 fix(TEIIDTOOLS-799) - Remove usage of style={} on react components
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ViewEditorNavBar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ViewEditorNavBar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListSkeleton.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListSkeleton.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListSkeleton.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListSkeleton.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListSkeleton.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsToolbarSkeleton.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.css
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: pr/approved, pr/review-requested, size/l

#6874 ENTESB-11911 - FHIR- create: Error retrieving resource schema for type
  app/ui-react/packages/auto-form/src/utils.ts
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6894 fix(TEIIDTOOLS-800) - cleanup of i18n files
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ViewEditorNavBar.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewCreateSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewsImportSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/xl

#6823 fix(cards): update static use of pf3 cards to pf4 react components
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActionSelectorCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSetInfo.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceCardHeader.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
  app/ui-react/packages/ui/src/Integration/Editor/shared/EditorPageCard.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/index.css
Labels: pr/approved, size/l

#6865 [ENTESB-11971] Fixing configuration of AWS DDB
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6891 syndesis crc/minishift command download latest binary
  doc/sdh/cli/cmd_crc.adoc
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/crc
  tools/bin/commands/minishift
  tools/bin/commands/util/operator_func.bats
  tools/bin/commands/util/operator_funcs
  tools/bin/commands/util/operator_funcs.bats
Labels: pr/approved, pr/review-requested, size/l

#6893 fix(ENTESB-11945): roll back to use Json schema draft 4
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ResponseCustomizer.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/ResponseCustomizerTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/JsonSchemaHelper.java
  app/server/api-generator/src/test/resources/swagger/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonSchemaInspector.java
  app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonSchemaInspectorTest.java
  app/server/inspector/src/test/resources/petstore-unified-schema.json
Labels: pr/approved, pr/review-requested

#6899 fix release script
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/release
Labels: pr/approved, size/l

#6896 TEIIDTOOLS-803 Redirect to editor after view creation
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6828 bump prometheus version
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/generator_test.go
Labels: pr/approved, size/s

#6901 Do not force specific camel versions to camel k in product releases
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport master, pr/approved, size/XS

#6903 chore: Update to AtlasMap 1.42.9
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/s

#6890 Replace pre-commit with Husky
  .pre-commit-config.yaml
  app/pom.xml
  package.json
  tools/misc/format-license.sh
  yarn.lock
Labels: size/XXL

#6907 chore: Update to AtlasMap 1.42.9
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/yarn.lock
Labels: pr/approved, size/s

#6910 fix(release): remove git commit for OpenShift templates
  tools/bin/commands/release
Labels: size/XS

#6913 fix(release): tagging moving version of operator image
  tools/bin/commands/release
Labels: size/XS

#6912 [Prometheus] Fix docker tag for Prometheus
  install/operator/build/conf/config.yaml
Labels: pr/approved, size/XS

#6904 TEIIDTOOLS-770 Resolve issue with init of view editor results
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
Labels: pr/approved, pr/review-requested, size/m

#6915 fix: unbreak the connection name validation
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
Labels: pr/approved, size/m

#6917 TEIIDTOOLS-807 Adapt DV UI for service endpoint refactor
  app/ui-react/packages/api/src/useViewDefinition.tsx
  app/ui-react/packages/api/src/useViewDefinitionDescriptors.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/api/src/useVirtualizations.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6924 user doc: Typo fix. Three instances. I'm consistent.
  doc/modules/tutorials/p_amq2api-name-and-publish.adoc
  doc/modules/tutorials/p_sf2db-name-and-publish.adoc
  doc/modules/tutorials/p_t2sf-name-and-publish.adoc
Labels: backport 1.8.x, size/XS

#6925 user doc: Correct a typo - changes "contain" to "contains"
  doc/modules/tutorials/p_t2sf-add-filter-step.adoc
Labels: size/XS

#6916 ENTESB-11970: adding a cpu request for teiid-syndesis
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6930 [ENTESB-12018] Re-Add missing integrationLivenessProbeInitialDelaySeconds
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/XS

#6921 Release fixes
  .circleci/config.yml
  app/pom.xml
  install/operator/pkg/generator/assets_vfsdata.go
  tools/bin/commands/release
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6923 fix: tidy up the api provider response error handling form thingy
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
Labels: backport 1.8.x, pr/approved, size/m

#6938 fix: fetch updates on the detail page when change events are received
  app/ui-react/packages/api/src/useConnection.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
Labels: pr/approved, size/s

#6935 Fix release on 1.8.x
  .circleci/config.yml
  app/pom.xml
  tools/bin/commands/release
Labels: size/l

#6931 [ENTESB-12018] Add missing integrationLivenessProbeInitialDelaySeconds
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/XS

#6920 chore: add Gitter.im badge (#6920)yujjjjj
  README.md
Labels: pr/approved, size/XS

#6922 BACKPORT ENTESB-11772: Generate a template from the operator configuration
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/vendor/github.com/spf13/cast/LICENSE
  install/operator/vendor/github.com/spf13/cast/Makefile
  install/operator/vendor/github.com/spf13/cast/README.md
  install/operator/vendor/github.com/spf13/cast/cast.go
  install/operator/vendor/github.com/spf13/cast/caste.go
  install/operator/vendor/github.com/spf13/cast/go.mod
  install/operator/vendor/github.com/spf13/cast/go.sum
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/xl

#6940 chore: add `go generate` hook
  .lintstagedrc.js
  package.json
  yarn.lock
Labels: pr/approved, pr/review-requested, size/l

#6943 chore(dev-workflow): add support for rebase
  .github/workflows/rebase.yml
Labels: size/s

#6929 Adding a Code of Conduct
  CODE_OF_CONDUCT.md
Labels: pr/approved, size/m

#6928 Adding a PR template
  .github/PULL_REQUEST_TEMPLATE/complete.md
Labels: pr/approved, size/m

#6942 fix(release): non-staging profile
  app/pom.xml
  tools/bin/commands/release
Labels: backport 1.8.x, size/s

#6937 TEIIDTOOLS-812 adapts DV UI for service naming changes
  app/ui-react/packages/api/src/useViewDefinition.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6949 Bump db to 9.6
  install/operator/build/conf/config.yaml
Labels: backport master, pr/approved, size/XS

#6939 ENTESB-11772: Fixes for outstanding errors
  install/operator/pkg/cmd/internal/install/install_forge.go
Labels: pr/approved, pr/review-requested, size/s

#6789 ENTESB-11573 add external database support in operator
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
Labels: pr/approved, pr/review-requested, size/m

#6953 user doc: Updated doc for 7.5 Conditional flows
  doc/assemblies/integrating-applications/as_creating-integrations.adoc
  doc/assemblies/integrating-applications/as_evaluating-integration-data-to-determine-execution-flow.adoc
  doc/assemblies/integrating-applications/as_how-to-process-a-collection-in-a-flow.adoc
  doc/modules/integrating-applications/c_behavior-of-conditional-flows-step.adoc
  doc/modules/integrating-applications/p_adding-conditional-execution-flows.adoc
  doc/modules/integrating-applications/p_adding-steps-to-conditional-flows.adoc
  doc/modules/integrating-applications/p_procedure-for-creating-an-integration.adoc
  doc/modules/integrating-applications/p_using-advanced-expression-builder.adoc
  doc/modules/integrating-applications/p_using-basic-expression-builder.adoc
  doc/modules/integrating-applications/r_example-of-a-conditional-flows-step.adoc
  doc/modules/integrating-applications/r_general-procedure-for-configuring-conditional-flows-step.adoc
Labels: backport 1.8.x, size/xl

#6951 fix(#6948): Jackson version clash between compile and integration runtime
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
Labels: pr/approved

#6952 [ENTESB-11634] Adding AWS-DDB icon for the connector
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
  app/ui-react/syndesis/public/icons/aws-ddb.svg
  ux/connections_icons/svg/connectionicons_AWS-DDB.svg
  ux/connections_icons/svg/mapping.json
Labels: pr/approved, size/XS

#6954 user doc: New doc for the Box connector
  doc/assemblies/connecting/as_connecting-to-box.adoc
  doc/connecting/master.adoc
  doc/modules/connecting/p_adding-box-connection-finish.adoc
  doc/modules/connecting/p_adding-box-connection-middle.adoc
  doc/modules/connecting/p_creating-box-connections.adoc
  doc/modules/connecting/p_register-with-box.adoc
  doc/modules/connecting/r_supported-connectors.adoc
Labels: backport 1.8.x, size/l

#6958 fix(connector): default admin db for mongo
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
Labels: pr/approved

#6950 some fixes to install scripts
  install/operator/.lib.sh
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  tools/bin/commands/crc
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
Labels: pr/review-requested, size/l

#6959 refactor: remove unsafe usage of SimpleDateFormat
  app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationDeploymentMetrics.java
  app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/extension/maven-plugin/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/metrics/SQLMetricsProviderImpl.java
  app/server/metrics/jsondb/pom.xml
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/IntegrationMetricsHandler.java
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/JsonDBRawMetrics.java
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/PodMetricsReader.java
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/RawMetrics.java
  app/server/metrics/jsondb/src/test/java/io/syndesis/server/metrics/jsondb/MetricsCollectorTest.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
Labels: pr/approved

#6961 refactor: use proper constant naming
  app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/AMQToHttp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/amq/HttpToAMQ_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpSplitToDB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpTestSupport.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpToDB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/WebHookToFtp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/http/HttpToHttp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/mail/SendMail_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBSplitToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/GoogleSheetsTestSupport.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/MultiSqlToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/SheetsToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
Labels: pr/approved

#6968 Updated doc for the data mapper
  doc/assemblies/integrating-applications/as_mapping-data.adoc
  doc/images/integrating-applications/Example-Adding-Padding-Mapping-2.png
  doc/images/integrating-applications/Example-Adding-Padding-Mapping-3.png
  doc/images/integrating-applications/Example-Adding-Padding-Mapping.png
  doc/modules/connecting/p_adding-odata-connections-write.adoc
  doc/modules/integrating-applications/p_applying-conditions-to-mappings.adoc
  doc/modules/integrating-applications/p_combine-multiple-source-fields-into-one-target-field.adoc
  doc/modules/integrating-applications/p_separate-one-source-field-into-multiple-target-fields.adoc
  doc/modules/integrating-applications/r_about-transformations-on-multiple-source-values.adoc
  doc/modules/integrating-applications/r_mapping-between-collections-and-non-collections.adoc
Labels: backport 1.8.x

#6970 user doc: Remove Tech Preview note
  doc/assemblies/connecting/as_connecting-to-jira.adoc
Labels: backport 1.8.x, size/s

#6964 chore: Make Maven quiet option optional on release scripts
  tools/bin/commands/release
Labels: backport 1.8.x, pr/approved, size/XS

#6963 ENTESB-12048 Jira connector is Technical Preview
  app/connector/jira/src/main/resources/META-INF/syndesis/connector/jira.json
Labels: backport 1.8.x, pr/approved, size/XS

#6965 BACKPORT - ENTESB-11639: Adds the deploymentconfigs/finalizers permissions to op…
  install/operator/deploy/role.yaml
  install/operator/pkg/generator/assets/infrastructure/05-syndesis-security.yml.tmpl
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/review-requested, size/s

#6908 [ENTESB-11767] Fixing PutItem returning an empty json
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizerQuery.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertItemTest.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBQueryItemTest.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBRawOptionsTest.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
  app/connector/aws-ddb/src/test/resources/logback-test.xml
Labels: pr/approved

#6983 user doc: Update to indicate that a db name in the Administration database field is required
  doc/modules/connecting/p_creating-mongodb-connections.adoc
Labels: backport 1.8.x, size/s

#6988 fix(release): build the UI
  app/pom.xml
Labels: backport 1.8.x, pr/approved, size/XS

#6990 refactor: remove needless exception declaration
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/environment/EnvironmentHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportHandler.java
  app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/FileStoreSupport.java
Labels: pr/approved

#6991 refactor: remove needless else
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetaDataExtension.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java
Labels: pr/approved

#6992 refactor: remove unused imports
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java
Labels: pr/approved

#6994 fix: warnings in Maven POM
  app/common/pom.xml
  app/connector/mqtt/pom.xml
  app/connector/pom.xml
  app/extension/bom/pom.xml
  app/server/pom.xml
Labels: pr/approved, size/XS

#6996 user doc: DynamoDB connector doc
  doc/assemblies/connecting/as_connecting-to-amazon-dynamodb.adoc
  doc/assemblies/connecting/as_connecting-to-aws.adoc
  doc/modules/connecting/p_adding-dynamodb-connection-put.adoc
  doc/modules/connecting/p_adding-dynamodb-connection-query.adoc
  doc/modules/connecting/p_adding-dynamodb-connection-remove.adoc
  doc/modules/connecting/p_creating-amazon-dynamodb-connections.adoc
  doc/modules/connecting/r_supported-connectors.adoc
Labels: size/l

#6998 user doc: Corrects a copy/paste mistake
  doc/assemblies/connecting/as_connecting-to-amazon-dynamodb.adoc
Labels: size/XS

#7002 user doc: Replace numbered instructions with a workflow diagram
  doc/images/integrating-applications/WorkflowForConfiguringConditionalFlowsStep.png
  doc/modules/integrating-applications/r_general-procedure-for-configuring-conditional-flows-step.adoc
Labels: backport 1.8.x

#6995 fix(release): don't perform Java release for UI
  app/ui-react/pom.xml
Labels: backport 1.8.x, pr/approved, size/m

#7004 chore: fix the ui dev proxy mode
  app/ui-react/syndesis/src/setupProxy.js
Labels: pr/approved, size/XS

#6947 ENTESB-12038 credentials of a connector attached to a connection are plain text
  app/server/credential/src/main/java/io/syndesis/server/credential/CredentialFlowState.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialFlowState.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialFlowState.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
Labels: pr/approved

#7008 chore: upgrade basepom to 30 (from 29)
  app/pom.xml
Labels: pr/approved, size/XS

#7006 Bump camel version to 2.21.0.fuse-750033
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-750033.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/s

#7009 fix(release): exclude ui-react module from nexus
  tools/bin/commands/release
Labels: backport 1.8.x, size/XS

#7011 fix(connector): polish label hints
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
Labels: group/connector, pr/approved, pr/review-requested, size/s

#7013 fix(release): perform remote staging
  app/ui-react/pom.xml
  tools/bin/commands/release
Labels: backport 1.8.x, size/s

#7015 fix: tighten up the layout for the conditional flow form
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: pr/approved, size/s

#7022 fix(release): dist attachment and POM signature
  app/ui-react/pom.xml
Labels: size/s

#7020 fix(connector): mongodb connector json
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
Labels: group/connector, pr/approved, pr/review-requested, size/XS

#7019 fix: dvconnectionSkeleton is not sized well TEIIDTOOLS784
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsToolbarSkeleton.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
Labels: pr/approved, pr/review-requested, size/m

#6985 feat: add semantics for actions with 'Pipe' pattern
  app/ui-react/packages/api/src/WithConnection.tsx
  app/ui-react/packages/api/src/helpers/connectionFunctions.ts
  app/ui-react/packages/api/src/useConnection.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: pr/approved, size/l

#7024 chore(hooks): upgrade commitlint
  package.json
  yarn.lock
Labels: size/l

#7028 user doc: Email connector
  doc/assemblies/connecting/as_connecting-to-email-servers.adoc
  doc/connecting/master.adoc
  doc/modules/connecting/p_creating-a-connection-to-an-imap-or-pop3-email-server.adoc
  doc/modules/connecting/p_creating-a-connection-to-an-smtp-email-server.adoc
  doc/modules/connecting/p_obtaining-email-to-trigger-integration-execution.adoc
  doc/modules/connecting/p_sending-email-from-an-integration.adoc
  doc/modules/connecting/r_supported-connectors.adoc
Labels: backport 1.8.x, size/l

#7027 Do some documentation cleanup for install
  doc/sdh/cli/cmd_install.adoc
  tools/bin/commands/install
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved, size/XXL

#7000 feat(connector): Adding "strict mode" connector validation
  app/connector/support/maven-plugin/src/main/resources/connector-schema.json
Labels: group/connector, pr/approved, pr/review-requested, size/l

#7033 feat(connector): mongodb operation validity check
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
Labels: group/connector, pr/approved, pr/review-requested

#7036 user doc: Add operation descriptions for MongoDB connection producer action
  doc/modules/connecting/p_adding-mongodb-connections-write.adoc
  doc/modules/connecting/p_creating-mongodb-connections.adoc
Labels: backport 1.8.x, size/m

#7026 Publish operator binaries from release script
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/release
  tools/bin/commands/release.bats
  tools/bin/commands/util/operator_funcs
Labels: cat/build, pr/approved, pr/review-requested, size/xl

#7040 user doc: Add instructions for rebranding the UI
  doc/customizing/master.adoc
  doc/modules/customizing/p_rebranding-the-user-interface.adoc
Labels: size/l

#7039 More refactorings and stricter errorprone
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/TrustAllTrustManager.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/IntegrationRuntimeAutoConfiguration.java
  app/meta/src/main/java/io/syndesis/connector/meta/Application.java
  app/pom.xml
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/util/IconGeneratorTest.java
  app/server/credential/src/main/java/io/syndesis/server/credential/salesforce/SalesforceConfiguration.java
  app/server/credential/src/test/java/io/syndesis/server/credential/CredentialsIntegrationTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandler.java
Labels: pr/approved

#7041 fix(TEIIDTOOLS-595) - Import/Export of Virtualization
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationImporter.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationImportPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
Labels: pr/approved, pr/review-requested, size/l

#7048 chore: Update to AtlasMap 1.42.10
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/s

#7050 fix: Flaky integration test on nightly CI
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sql/DBToHttp-export/model.json
Labels: pr/approved

#7046 ENTESB-11433 Box - no property for fileName in upload action
  app/connector/box/src/main/java/io/syndesis/connector/box/BoxConnector.java
Labels: pr/approved

#6956 fix(TEIIDTOOLS-786) - Click publish should immediately change virt status to 'in-progress'
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/models.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatus.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: pr/approved, pr/review-requested, size/XXL

#7053 fix(TEIIDTOOLS-813) - Indicate results loading in-progress on SQL client page
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/l

#7049 TEIIDTOOLS-743 removing komodo and vdb-builder terms
  app/ui-react/syndesis/config.minishift.json
  app/ui-react/syndesis/config.proxy.json
  app/ui-react/syndesis/config.staging.json
  app/ui-react/syndesis/src/app/__mocks__/WithConfig.tsx
  app/ui-react/syndesis/src/setupProxy.js
  install/operator/README.md
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/tests/e2e/utils.go
Labels: size/l

#7056 Move operator tagging section
  tools/bin/commands/release
Labels: pr/review-requested, size/XS

#7057 Grant permissions to syndesis-editor
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/05-syndesis-security.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, pr/review-requested, size/XS
