Repository syndesisio/syndesis, pull requests merged in 2019-06, with the labels that each got.

#5546 fix(5386): Correct disparity between odata meta schema and processed …
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataPatchCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1.json
Labels: pr/approved, pr/review-requested

#5544 chore: add addon for installing legacy UI
  install/addons/syndesis-legacy-ui-serviceaccount.yml
  install/addons/syndesis-legacy-ui.yml
Labels: pr/approved, pr/review-requested

#5538 fix(openapi): don't remove security requirements
  app/common/util/src/test/java/io/syndesis/common/util/openapi/OpenApiHelperTest.java
  app/server/api-generator/pom.xml
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
Labels: pr/approved

#5550 syndesis-react, sync
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
Labels: pr/approved

#5561 syndesis-react, sync
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved

#5557 fix(ui): update integration on changes
  app/ui-angular/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#5554 fix: Support conditional flows in API provider integrations
  app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationActivityTrackingPolicyFactory.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
  app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.scss
  app/ui-angular/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.ts
  app/ui-angular/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.ts
  app/ui-angular/src/app/integration/edit-page/current-flow.service.ts
  app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui-angular/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
  app/ui-angular/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved, pr/review-requested

#5567 fix for ENTESB-10721 - Add winelist table to Fuse Online sample
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#5570 Fixes #5296, added aggregate function parameter to handle integration replicas when creating list of top integrations
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5569 syndesis-react, sync
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.css
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved

#5574 leftvers, removed wrong icons
  .gitignore
  syndesis/public/icons/fhir.connection.png
  syndesis/public/icons/fhir.integration.png
  syndesis/public/icons/steps/aggregate.svg
  syndesis/public/icons/steps/split.svg
Labels: pr/approved

#5580 Merge react/master
  app/ui-react/syndesis/config.staging.json
Labels: pr/approved

#5581 UI, fix bug with required hidden fields
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/utils/src/autoformHelpers.ts
Labels: pr/approved

#5517 user doc for minor updates to doc for FHIR connector
  doc/connecting/topics/as_connecting-to-fhir.adoc
  doc/connecting/topics/p_adding-fhir-connection-create.adoc
  doc/connecting/topics/p_adding-fhir-connection-patch.adoc
  doc/connecting/topics/p_adding-fhir-connection-update.adoc
  doc/integrating-applications/topics/p_add-aggregate-step.adoc
Labels: pr/approved

#5562 fix(ui): make sure `Integration.flows` is never null
  app/ui-angular/src/app/integration/list/list.component.html
  app/ui-angular/src/app/store/integration/integration.service.ts
Labels: pr/review-requested

#5587 chore(openapi): better error for unsupported versions
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
Labels: pr/approved

#5588 fix(build): increase `craco build` memory to 2GB
  app/ui-react/syndesis/package.json
Labels: pr/approved, pr/review-requested

#5591 fix for 5528 - Wrong schema in the default postgres connection
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#5594 Removed app/ui-react husky hooks.
  app/ui-react/package.json
Labels: pr/approved, pr/review-requested

#5590 fix(5560): Ensure a default value is set for email-send's protocol
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
Labels: pr/approved, pr/review-requested

#5596 react, enables CBR + fixes
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useApiConnector.tsx
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.css
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownHeader.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.css
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.css
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceCardHeader.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/index.ts
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepExpanderBody.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
Labels: pr/approved

#5597 fix: Add simple language syntax examples in conditional flows config page
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved

#5601 Revert "fix: Add simple language syntax examples in conditional flows config page"
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, pr/review-requested

#5606 Excluded tests from -Pflash UIs builds.
  .gitignore
  app/ui-angular/pom.xml
  app/ui-react/pom.xml
Labels: pr/review-requested

#5613 React, sync
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/app/locales/app-translations.en.json
  app/ui-react/syndesis/src/app/locales/app-translations.it.json
Labels: pr/approved

#5610 Build, added maven extension to keep track of build time per module
  .mvn/extensions.xml
Labels: pr/approved, pr/review-requested

#5614 fix #5219: [camel-k] NPE thrown by CamelKIntegrationController
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKIntegrationController.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
Labels: pr/approved, pr/review-requested

#5617 React, sync
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/tests/helpers/integrationFunctions.spec.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Import/ImportPageUI.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationIcon.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Connection/ConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Connection/ConnectionDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Connection/ConnectionsListView.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionImportCard.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionListView.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionsPage.stories.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
  app/ui-react/packages/ui/tests/ConnectionCard.spec.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionDetail.spec.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionImportCard.spec.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionListItem.spec.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionListView.spec.tsx
  app/ui-react/syndesis/public/icons/unknown.svg
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
  app/ui-react/syndesis/src/shared/EntityIcon.tsx
  app/ui-react/syndesis/src/shared/index.ts
Labels: pr/approved

#5611 chore: set Content-Type to text/plain for simple bodies
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessor.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestUnwrapperProcessorTest.java
Labels: pr/approved

#5620 Incremental build option in Syndesis CLI
  .circleci/config.yml
  tools/bin/commands/build
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/maven_funcs
Labels: pr/approved, pr/review-requested

#5618 Fixes #5015 ExpressionChangedAfterItHasBeenCheckedError when creating…
  app/ui-angular/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#5624 fix(ci): consider changes on `master` for commit
  tools/bin/commands/util/common_funcs
Labels: pr/approved, pr/review-requested

#5621 fix(ci): don't try to push images that do not exist
  .circleci/config.yml
Labels: pr/review-requested

#5623 fix(5599): Fix handling of options in email and odata connectors
  .gitignore
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailUtil.java
  app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailSendCustomizer.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/AbstractEMailVerifier.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/EMailVerifierExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/receive/ReceiveEMailVerifier.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/receive/ReceiveEMailVerifierExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/send/SendEMailVerifier.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/send/SendEMailVerifierExtension.java
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/verifier/email-receive
  app/connector/email/src/main/resources/META-INF/syndesis/connector/verifier/email-send
  app/connector/email/src/test/java/io/syndesis/connector/email/meta/EMailMetaDataTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataExtension.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/ConnectorOptions.java
Labels: pr/review-requested

#5629 fix for #5603 SQL connector cannot access the sampledb tables
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
Labels: pr/approved

#5631 fix(ci): disable incremental build
  .circleci/config.yml
Labels: pr/approved

#5630 fix(connector): validation failed at Box connection details
  app/connector/box/src/main/java/io/syndesis/connector/box/verifier/BoxVerifierExtension.java
Labels: pr/approved

#5635 fix(connector): remove tags from rest-swagger
  app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/customizer/OpenApiCustomizerTest.java
Labels: pr/approved

#5637 docs: Fix permission grant command line on arbitrary cluster install
  doc/sdh/cli/cmd_install.adoc
Labels: pr/approved

#5646 fix: Add liveness check to Spring Boot integrations
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#5645 fixes #5625 Improve descriptions of timer actions
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: pr/approved, pr/review-requested

#5644 fix(5512): Fixes 500 response failure in odata queries
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1-expanded-trips.json
Labels: pr/approved, pr/review-requested

#5654 fix(5526): Regression in template step editor updating
  app/ui-angular/src/app/integration/edit-page/step-configure/templater/templater.component.ts
Labels: pr/approved, pr/review-requested

#5655 fix(5273): Mustache errors showing wrong line number
  app/ui-angular/src/app/integration/edit-page/step-configure/templater/codemirror/mustache-mode-lint.ts
Labels: pr/approved, pr/review-requested

#5664 chore: Update to AtlasMap 1.40.0-beta1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-angular/package.json
  app/ui-angular/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
Labels: pr/approved

#5659 fixes #5625 partially - updates field labels for Red Hat AMQ connector
  app/connector/activemq/src/main/resources/META-INF/syndesis/connector/activemq.json
Labels: pr/approved

#5666 Fixes #5657 Remove Tech Preview banner from OData and FHIR connector …
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
Labels: pr/approved

#5667 React, sync
  app/ui-react/packages/api/src/WithUserHelpers.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.css
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/public/logout.html
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/setupProxy.js
Labels: pr/approved

#5634 Add olm integration files for syndesis
  install/operator/deploy/manifests/1.7.x/syndesis.crd.yaml
  install/operator/deploy/manifests/1.7.x/syndesisoperator.1.7.x.clusterserviceversion.yaml
  install/operator/deploy/manifests/syndesis.package.yaml
Labels: pr/approved, pr/review-requested

#5680 fixes #5626 partially. Updates UI text for AMQP connector.
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
Labels: pr/approved

#5674 Syndesis camel upgrade
  app/connector/google-sheets/pom.xml
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/BatchGoogleSheetsClientFactory.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsClientFactory.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsComponent.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsConfiguration.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsConsumer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsEndpoint.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsProducer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsVerifierExtension.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsConstants.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsPropertiesHelper.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamComponent.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConfiguration.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConstants.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConsumer.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamEndpoint.java
  app/connector/google-sheets/src/main/resources/META-INF/services/org/apache/camel/component/google-sheets
  app/connector/google-sheets/src/main/resources/META-INF/services/org/apache/camel/component/google-sheets-stream
  app/connector/google-sheets/src/main/resources/org/apache/camel/catalog/components/google-sheets-stream.json
  app/connector/google-sheets/src/main/resources/org/apache/camel/catalog/components/google-sheets.json
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/GoogleSheetsVerifierExtensionTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsConfigurationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsIntegrationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsValuesIntegrationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServer.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerAssert.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerRule.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/AbstractGoogleSheetsStreamTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
  app/connector/google-sheets/src/test/resources/googleapis.jks
  app/connector/google-sheets/src/test/resources/test-options.properties
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#5683 fix(server): disregard unsupported OAuth methods
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SupportedAuthenticationTypes.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.swagger.yaml
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
Labels: pr/approved

#5684 fixes: #4878 Correct description of Periodic SQL invocation action
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved, pr/review-requested

#5688 chore: refine description and labelHint
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved, pr/review-requested

#5687 fix: db schema property for stored procedures
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementMetaData.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java
Labels: pr/approved, pr/review-requested

#5694 Merge on react
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx
  app/ui-react/syndesis/config.staging.json
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx
Labels: pr/approved

#5696 Change olm csv version from 1.7.x to 1.7.0
  install/operator/deploy/manifests/1.7.0/syndesis.crd.yaml
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.x.clusterserviceversion.yaml
  install/operator/deploy/manifests/syndesis.package.yaml
Labels: pr/approved

#5695 fix: missing db schema handling in sql connector customizer
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlConnectorMetaDataExtension.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlSupport.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbDerby.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbOracle.java
Labels: pr/approved, pr/review-requested

#5700 react, sync
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/abstract-language-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/freemarker-mode-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/index.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/mustache-mode-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/template-symbol.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/velocity-lint.ts
  app/ui-react/packages/ui/stories/Integration/Editor/steps/TemplateStep.stories.tsx
  app/ui-react/packages/utils/package.json
  app/ui-react/packages/utils/src/index.ts
  app/ui-react/packages/utils/src/lintHelpers.ts
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved

#5708 fix(5533): Fix OData Read Customizer in the event of null message body
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
Labels: pr/approved, pr/review-requested

#5705 Merge on react
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/syndesis/src/app/App.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: pr/approved

#5709 Fixes #5263, fixes #5266, adds support for creating unassigned environment names cached in memory, managed across integrations and removed with the delete environment endpoint
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved, pr/review-requested

#5713 React, sync
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.css
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.tsx
  app/ui-react/packages/ui/src/Layout/Breadcrumb.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
Labels: pr/approved

#5703 fix: Add db schema support to sample todo app
  install/generator/04-todo-example.yml.mustache
  install/syndesis.yml
Labels: pr/review-requested

#5717 React, sync
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
Labels: pr/approved

#5706 Replace ClusterRoles for Roles in syndesis operator
  install/generator/05-syndesis-security.yml.mustache
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
  install/operator/syndesis-privileged.yml
  install/operator/syndesis.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#5723 fix(connector): Box - OutputDataShape java.io.OutputStream not needed as it can't be mapped to anything
  app/connector/box/src/main/java/io/syndesis/connector/box/BoxFile.java
  app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizer.java
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
  app/connector/box/src/test/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizerTest.java
Labels: pr/approved

#5728 Fix image for syndesis operator olm integration
  install/operator/.gitignore
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
Labels: pr/approved

#5735 Fixes #5420, import extensions by extensionId instead of id, take highest extension version
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved, pr/review-requested

#5736 Fixes #5263, changed create environment api verb to POST
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: pr/approved

#5739 Merge on react
  app/ui-react/packages/api/src/WithEnvironmentHelpers.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/atlasmap-assembly/src/app/app.component.css
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/config.minishift.json
  app/ui-react/syndesis/config.proxy.json
  app/ui-react/syndesis/config.staging.json
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/app/WithConfig.tsx
  app/ui-react/syndesis/src/app/__mocks__/WithConfig.tsx
  app/ui-react/syndesis/src/app/index.ts
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Labels: pr/approved

#5741 fix: Make split step work with ftp connector
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
Labels: pr/approved, pr/review-requested

#5726 Fixes #5475 Disable DataVirt UI when Komodo server isn't present
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/cmd_minishift.adoc
  install/generator/03-syndesis-ui.yml.mustache
  install/operator/pkg/syndesis/template/install.go
  install/syndesis.yml
  tools/bin/commands/build
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved

#5743 chore: make en the fallback language always, to avoid any issue in prod
  app/ui-react/syndesis/src/i18n/index.ts
Labels: pr/approved

#5742 feat: set the initial name and description for new connections as the connector
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
Labels: pr/approved

#5740 chore(ui): update OpenAPI documents
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/models/src/models-internal.d.ts
  app/ui-react/packages/models/swagger.internal.json
  app/ui-react/packages/models/swagger.json
Labels: pr/approved

#5749 fix: make a nice new step object and ensure we use that when creating…
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: pr/approved, pr/review-requested

#5751 fix for 5493 - also return keys when start connector
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
Labels: pr/approved

#5748 TT-624 Fix Connector selection in DV wizard
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
Labels: pr/approved, pr/review-requested

#5752 fix #4234 kafka validation kills meta pod
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Labels: pr/approved

#5758 chore: Update to AtlasMap 1.40.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-angular/package.json
  app/ui-angular/yarn.lock
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: pr/approved

#5757 fix(integrationdetails): various UI fixes
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.css
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
Labels: pr/approved, pr/review-requested

#5760 Fixes #5267, added support for withUses parameter to getReleaseEnvironments API
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: pr/approved, pr/review-requested

#5745 fix(box connector): Add Technology Preview label for Box connector
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
Labels: pr/approved

#5765 Partial fix for #4248, strips external hidden secrets when importing connections
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved, pr/review-requested

#5770 ui text update for Twitter displayNames and hints
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
Labels: pr/approved, pr/review-requested

#5764 ui text updates to replace placeholder descriptions
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/settings/locales/settings-translations.en.json
Labels: pr/review-requested

#5769 required update of project.version to 7.4 in dictionary file
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Labels: pr/approved, pr/review-requested

#5774 Pin operator image to 1.7.1-20190617
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
Labels: pr/approved

#5775 fix: remove rxjava from update handler
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
  app/server/update-controller/pom.xml
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/usage/UsageUpdateHandler.java
Labels: pr/approved

#5779 Fixes #5777 Operator image is not being pushed to dockerhub (2nd atte…
  .circleci/config.yml
Labels: pr/approved

#5781 fix: show the right description for the select connection page
  app/ui-react/package.json
  app/ui-react/packages/api/src/WithConnections.tsx
  app/ui-react/packages/api/src/WithExtensions.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useConnections.tsx
  app/ui-react/packages/api/src/useExtensions.tsx
  app/ui-react/packages/api/src/useServerEvents.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, pr/review-requested

#5761 ENTESB-10724 - adds Publish and delete to virtualization detail
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested

#5783 updates Twitter search Keyword field to Query field
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
Labels: backport 1.7.x, pr/approved

#5782 fix(5715,5729) and add empty state components for integration-related components
  app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsEmptyState.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListView.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationsEmptyState.stories.tsx
  app/ui-react/packages/ui/stories/Integration/Metrics/IntegrationDetailsMetrics.stories.tsx
  app/ui-react/packages/utils/src/dateHelpers.ts
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.it.json
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5738 chore(dev): improve dev experience with Camel K
  tools/bin/commands/kamel
  tools/bin/commands/util/camel_k_funcs
Labels: pr/approved, pr/review-requested

#5793 fix: update the validity function to the new values returned by the BE
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5756 Auto form adjustments
  app/ui-react/packages/.storybook/vendor.css
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/helpers.ts
  app/ui-react/packages/auto-form/src/widgets/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/yarn.lock
Labels: cat/enhancement, group/ui, pr/approved, pr/review-requested

#5802 fix: deepmerge the returned resource with the defaultValue to cleanly deal with no-data responses
  app/ui-react/packages/api/src/useApiResource.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5806 user doc: Correct Query input field description for SQL connection
  doc/connecting/topics/p_adding-db-connection-start.adoc
Labels: backport 1.7.x

#5813 user doc: Add SSL limitation to doc for Kafka connector
  doc/connecting/topics/p_creating-kafka-connections.adoc
Labels: backport 1.7.x

#5786 Fixes #5777 Operator image is not being pushed to dockerhub (3rd atte…
  .circleci/config.yml
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5810 Fixes: problem with privileges during installation
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved

#5798 chore: removed rogue exit 1 statement in the has_changes function
  tools/bin/commands/util/common_funcs
Labels: pr/approved

#5801 Fixes #4112 Add install maven mirror to syndesis scripts
  tools/bin/commands/build
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved

#5799 fix: do not show a trailing arrow in the breadcrumb
  app/ui-react/packages/ui/src/Layout/Breadcrumb.tsx
Labels: pr/approved

#5791 fix: duplicated attributed "required"
  install/generator/01-header.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#5785 fix(5780): Remove email metadata retrieval
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataRetrieval.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetadata.java
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/meta/email-receive
  app/connector/email/src/main/resources/META-INF/syndesis/connector/meta/email-send
  app/connector/email/src/test/java/io/syndesis/connector/email/meta/EMailMetaDataTest.java
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5808 Fixes: problem with privileges during installation
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved

#5818 fix: remove the flaky bit from ExtensionsITCase
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
Labels: pr/approved

#5817 Fixes #4112 Add docs for --maven-mirror install script
  doc/sdh/cli/cmd_build.adoc
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved

#5788 TTOOLS-658 Fix issue with view deletion
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: backport 1.7.x, pr/approved

#5767 user doc: Updated doc for new Twitter actions
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  doc/connecting/topics/as_connecting-to-twitter.adoc
  doc/connecting/topics/p_adding-twitter-connection-finish-middle.adoc
  doc/connecting/topics/p_adding-twitter-connection-start.adoc
  doc/connecting/topics/p_adding-twitter-connections.adoc
Labels: backport 1.7.x, pr/approved

#5826 user doc: Really add the updates for Twitter start connection actions
  doc/connecting/topics/p_adding-twitter-connection-start.adoc
Labels: backport 1.7.x

#5827 TT-669: Moves virtualization header above tabs on views page.
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested

#5821 fix: make sure that operation and label are unique
  app/common/model/pom.xml
  app/common/model/src/main/java/io/syndesis/common/model/filter/Op.java
  app/common/model/src/test/java/io/syndesis/common/model/filter/OpTest.java
Labels: pr/approved

#5834 fix: connection creation issue
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5823 fix: refines description for periodic SQL invocation
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5829 Fixes #5828, move deleted environment tags to unused list
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: backport 1.7.x, pr/approved

#5841 Minor UI changes to filter options
  app/ui-react/packages/api/src/WithFilterOptions.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5747 feat: require OAuth settings for connection creation
  app/server/credential/src/main/java/io/syndesis/server/credential/AcquisitionMethod.java
  app/server/credential/src/main/java/io/syndesis/server/credential/CredentialProviderRegistry.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialProvider.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialProvider.java
  app/server/credential/src/main/java/io/syndesis/server/credential/UnconfiguredProperties.java
  app/server/credential/src/main/java/io/syndesis/server/credential/generic/OAuth2CredentialProviderFactory.java
  app/server/credential/src/main/java/io/syndesis/server/credential/salesforce/SalesforceCredentialProviderFactory.java
  app/server/credential/src/main/java/io/syndesis/server/credential/twitter/TwitterCredentialProviderFactory.java
  app/server/credential/src/test/java/io/syndesis/server/credential/OAuth1CredentialProviderTest.java
  app/server/credential/src/test/java/io/syndesis/server/credential/OAuth2CredentialProviderTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
  app/ui-react/packages/models/swagger.internal.json
  app/ui-react/packages/models/swagger.json
  app/ui-react/packages/ui/src/Connection/ConnectionSetupOAuthCard.tsx
  app/ui-react/packages/ui/src/Connection/index.ts
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
Labels: pr/review-requested

#5844 Fix toast notification for uploading extension shows ID
  app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.en.json
  app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.it.json
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
Labels: pr/approved, pr/review-requested

#5755 fix(5321): Actually delete integrations and connections on delete
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationDeployment.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
Labels: pr/approved, pr/review-requested

#5845 fix: save the updated connection on OAuth reconnect
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/credential/CredentialHandler.java
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
Labels: pr/approved, pr/review-requested

#5849 TT-647 Enabled horizontal scrolling on query results table
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
Labels: backport 1.7.x

#5842 fix(5721) - Missing space in the ErrorsFound label
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.it.json
Labels: pr/approved, pr/review-requested

#5851 TT-660 Fixed preview to use view defined sql (rebased)
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.7.x

#5852 fix: handle credentials response without transformation
  app/ui-react/packages/api/src/useConnectorCredentials.tsx
Labels: pr/approved, pr/review-requested

#5858 fix: honor both syntaxes for authenticationType
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SupportedAuthenticationTypes.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SupportedAuthenticationTypesTest.java
Labels: backport 1.7.x, pr/approved

#5864 feat: show environment usage
  app/ui-react/packages/api/src/WithEnvironments.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
Labels: pr/approved, pr/review-requested

#5862 fix: extensions can have no actions
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
Labels: pr/approved, pr/needs-backport, pr/review-requested

#5863 fix: add validation/initial validation
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
Labels: pr/approved, pr/review-requested

#5865 fix(4562): Shore up odata update tests
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
Labels: pr/approved, pr/review-requested

#5861 Add --deploy-latest to 'syndesis minshift' command
  doc/sdh/cli/cmd_minishift.adoc
  tools/bin/commands/build
  tools/bin/commands/minishift
  tools/bin/commands/util/common_funcs
Labels: pr/approved

#5867 fix: Data Mapper host component should pass inspectionResult to suppo…
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5871 fix: not all extensions have actions (the sequel)
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: backport 1.7.x, pr/approved

#5875 fix: provide better error descriptions in gmail customizer
  app/connector/gmail/pom.xml
  app/connector/gmail/src/main/java/io/syndesis/connector/gmail/GmailSendEmailCustomizer.java
Labels: pr/approved, pr/review-requested

#5874 ui text: Updates text strings that appear in the UI (fixes #5869)
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5877 TTOOLS-661 resolve issue with view name validation
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5880 ENTESB-10884: fixed camel-k-runtime version and dependencies.
  app/integration/runtime-camelk/pom.xml
  app/pom.xml
  app/server/api-generator/pom.xml
Labels: pr/approved

#5893 fix: links in the logout.html
  app/ui-react/syndesis/public/logout.html
Labels: backport 1.7.x, pr/approved

#5894 fix: pass `configuredProperties` from connector in OAuth flow
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5898 fix: suppress showing editor warning icons for the conditional flow step
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: pr/approved, pr/review-requested

#5907 Fixes #5888: Only compile in the dev mode logic if you build with “-—tags dev”
  install/operator/.lib.sh
  install/operator/pkg/generator/assets/assets_generate.go
  install/operator/pkg/generator/dev/dev.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/generator/mode_dev.go
  install/operator/pkg/generator/mode_prod.go
Labels: cat/bug

#5903 fix: use the right array of items for ci/cd dialog
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogBody.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5902 chore(dev): add a update-manifest dev command
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/actuator/ConnectorsEndpoint.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/actuator/ConnectorsMvcEndpoint.java
  app/server/endpoint/src/main/resources/META-INF/spring.factories
  tools/bin/commands/dev
  tools/bin/commands/kamel
Labels: pr/approved, pr/review-requested

#5913 fix: use the right datashape when reconciling flows
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#5911 fix(connector): support named authentication type
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizer.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java
Labels: backport 1.7.x

#5915 Allow syndesis-server to manage routes
  install/generator/05-syndesis-security.yml.mustache
Labels: backport 1.7.x, pr/approved

#5882 WIP: user doc: Add query examples. Remove repetitive text. Update Count param description
  doc/connecting/topics/p_adding-twitter-connection-finish-middle.adoc
  doc/connecting/topics/p_adding-twitter-connection-start.adoc
Labels: backport 1.7.x
