Repository syndesisio/syndesis, pull requests merged in 2019-01, with the labels that each got.

#4264 feat(integration): add step icons to integration details and editor IVP
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/integration_detail/integration-description.component.html
  app/ui/src/app/integration/integration_detail/integration-description.component.scss
  app/ui/src/assets/icons/steps/expressionFilter.svg
  app/ui/src/assets/icons/steps/log.svg
  app/ui/src/assets/icons/steps/mapper.svg
  app/ui/src/assets/icons/steps/ruleFilter.svg
  app/ui/src/assets/icons/steps/template.svg
Labels: pr/approved

#4250 chore: version upgrades import cleanups
  app/ui/package.json
  app/ui/patches/codemirror+5.42.2.patch
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/common/card-tech-preview.component.scss
  app/ui/src/app/common/modal/modal.models.ts
  app/ui/src/app/common/modal/modal.service.ts
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.spec.ts
  app/ui/src/app/core/providers/i18n-provider.service.ts
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-detail/api-connector-detail.component.ts
  app/ui/src/app/customizations/api-connector/api-connector-lazy-loader.guard.ts
  app/ui/src/app/customizations/api-connector/api-connector-list/api-connector-list.component.ts
  app/ui/src/app/customizations/api-connector/api-connector.effects.ts
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard.component.ts
  app/ui/src/app/integration/api-provider/api-provider.effects.ts
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts
  app/ui/src/app/integration/edit-page/edit-page.component.spec.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/integration_detail/integration_activity/integration-activity.component.ts
  app/ui/src/app/integration/list/list.component.spec.ts
  app/ui/src/app/platform/types/i18n/i18n.effects.ts
  app/ui/src/app/platform/types/integration/integration.effects.ts
  app/ui/src/app/platform/types/platform.effects.ts
  app/ui/src/app/store/integration/integration.service.ts
  app/ui/src/app/vendor/index.ts
  app/ui/src/app/vendor/vendor.module.ts
  app/ui/src/polyfills.ts
  app/ui/src/scss/utils/_overrides.scss
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#4267 #4266 Fix unstable build
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerAssert.java
Labels: cat/build, pr/approved, pr/review-requested

#4240 [#3655] Tune IRC connector
  app/connector/irc/pom.xml
  app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcConnector.java
  app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcConnectorFactory.java
  app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifier.java
  app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifierAutoConfiguration.java
  app/connector/irc/src/main/java/io/syndesis/connector/irc/IrcVerifierExtension.java
  app/connector/irc/src/main/resources/META-INF/spring.factories
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
Labels: pr/approved, pr/review-requested

#4251 Kudu: Fix component scheme using wrong name and old parameters
  app/connector/kudu/pom.xml
  app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
  app/connector/kudu/src/main/resources/org/apache/camel/catalog/components/kudu.json
  tools/misc/build_s2i_locally.sh
Labels: pr/approved

#4276 #4229 Auto fill missing values in value ranges
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetaDataExtension.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConfiguration.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsMetadataAdapterTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
Labels: group/connector, pr/approved, pr/review-requested

#4282 Upgrade to Camel 2.21.0.fuse-730026
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#4285 chore: update productized app name
  install/generator/03-syndesis-ui.yml.mustache
Labels: pr/approved

#4286 chore: update productized app name (1.5.x)
  install/generator/03-syndesis-ui.yml.mustache
Labels: pr/approved

#4293 WIP: user doc: Update to refer to Red Hat AMQ (#4183)
  doc/connecting/topics/adding_amq_connection_finish.adoc
  doc/connecting/topics/adding_amq_connection_middle.adoc
  doc/connecting/topics/adding_amq_connection_start.adoc
  doc/connecting/topics/connecting_to_amq.adoc
  doc/connecting/topics/connecting_to_amqp.adoc
  doc/connecting/topics/create_amq_connection.adoc
  doc/connecting/topics/supported_connectors.adoc
Labels: pr/approved, pr/review-requested

#4277 feat: Add Grafana to syndesis install #3918.
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/07-syndesis-grafana.yml.mustache
  install/generator/08-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/syndesis-privileged.yml
  install/syndesis.yml
Labels: pr/approved

#4305 Upgrade to Camel 2.21.0.fuse-730029
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#4296 chore: refactor out the meat of the event handlers in current flow service
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved, pr/review-requested

#4310 chore: test commit
  README.md
Labels: pr/approved

#4313 failing pom
  README.md
Labels: pr/approved

#4314 chore: Additional current flow refactoring
  app/ui/src/app/integration/edit-page/current-flow.service.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/index.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
Labels: pr/approved, pr/review-requested

#4247 Fix #4246 Support Delete and Create FHIR actions
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetadataRetrieval.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirResourceId.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirUpdateCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirCreateCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirCreateUpdateBaseCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirDeleteCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirReadCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirReadDeleteBaseCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirUpdateCustomizer.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/verifier/FhirVerifier.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/verifier/FhirVerifierAutoConfiguration.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/verifier/FhirVerifierExtension.java
  app/connector/fhir/src/main/resources/META-INF/spring.factories
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
Labels: pr/approved

#4325 feat(monitoring): Add postgres exporter to expose metrics from syndesis-db #4316
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-db-metrics.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/syndesis-template.go
  install/syndesis-privileged.yml
  install/syndesis.yml
Labels: pr/approved

#4333 fix(build) Build on master fails with an empty m2 repository
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#4339 fix(#4301): Fix de-duplification of OData consumer results
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataConstants.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Configuration.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Index.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataReadRouteTest.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/test-server-data-empty.json
Labels: pr/approved, pr/review-requested

#4343 fix(meta): Monitoring - Instrument Syndesis Meta API
  app/meta/pom.xml
  app/meta/src/main/java/io/syndesis/connector/meta/EndpointMetricsFilter.java
  app/meta/src/main/resources/application.yml
  app/pom.xml
Labels: pr/approved

#4342 chore: Update to AtlasMap 1.39.0
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/processor/FhirResourceProcessorTest.java
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateResourceInspectionsMojo.java
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4351 fix(server): Monitoring - Instrument Syndesis Server API
  app/server/runtime/pom.xml
  app/server/runtime/src/main/java/io/syndesis/server/runtime/EndpointMetricsFilter.java
  app/server/runtime/src/main/resources/application.yml
Labels: pr/approved, pr/review-requested

#4360 Typo fix: Make description of log step consistent with other step descriptions
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved

#4371 fix(server): optimize database reset
  app/common/util/src/main/java/io/syndesis/common/util/cache/CacheManager.java
  app/common/util/src/main/java/io/syndesis/common/util/cache/LRUCacheManager.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java
Labels: pr/approved

#4352 #4229 Refactor Google Sheets meta data shapes
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAppendValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
  app/connector/google-sheets/src/test/resources/meta/append_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/append_rows_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_columns_split_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_rows_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_rows_split_metadata.json
  app/connector/google-sheets/src/test/resources/meta/update_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/update_rows_metadata.json
Labels: pr/approved, pr/review-requested

#4373 Match ascii-doctor-version with the version in app/pom.xml
  doc/pom.xml
Labels: pr/approved

#4376 [fix] Remove 1GB attachment limit on Help -> Support page #4208
  app/ui/src/app/support/support.component.html
Labels: pr/approved

#4328 Fix #4278 Support basic and bearer token authentication in FHIR
  app/connector/fhir/pom.xml
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/verifier/FhirVerifierExtension.java
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateWithBasicAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirCreateWithBearerTokenAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteWithBasicAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteWithBearerTokenAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadWithBasicAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirReadWithBearerTokenAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirTestBase.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateWithBasicAuthTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateWithBearerTokenAuthTest.java
  app/connector/fhir/src/test/resources/io/syndesis/connector/fhir/metadata_response.xml
Labels: pr/approved

#4379 [Tooltip] Remove unnecessary comma in import extension tooltip
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved

#4384 fix: Show n/a if there's no lastProcessed value for an integration
  app/ui/src/app/common/date.pipe.ts
Labels: pr/approved

#4377 fix: revert Grafana install configs
  install/dashboards/infrastructure-dashbard-syndesis-db.json
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-grafana.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
  install/operator/pkg/apis/syndesis/v1alpha1/types.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/syndesis-privileged.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4390 fix: Add upgrade script to create ConfigMap for postgres exporter
  tools/upgrade/migration/resource/1.6/01_db_metrics_config_map.sh
Labels: pr/approved

#4382 feat: Combine step/connection selection into one page
  app/ui/src/app/connections/list/list.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/action-select/action-select.component.ts
  app/ui/src/app/integration/edit-page/connection-resolver.service.ts
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.html
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.scss
  app/ui/src/app/integration/edit-page/connection-select/connection-select.component.ts
  app/ui/src/app/integration/edit-page/connection-select/index.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/edit-page.component.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/edit-page/index.ts
  app/ui/src/app/integration/edit-page/integration-resolver.service.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/integration/edit-page/step-select/index.ts
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.scss
  app/ui/src/app/integration/edit-page/step-select/step-select.component.ts
  app/ui/src/app/integration/integration.module.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/platform/types/platform.models.ts
  app/ui/src/app/store/entity/entity.store.ts
  app/ui/src/app/store/integration/integration.store.ts
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved, pr/review-requested

#4391 Fix #4389 flaky message capture processor unit test
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
Labels: pr/approved, pr/review-requested

#4383 feat(newSyndesisLogo): adding new Syndesis logo to masthead
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.ts
  app/ui/src/assets/images/syndesis_logo_icon_darkbkg.png
Labels: pr/approved, pr/review-requested

#4401 fix: ensure the flow ID is set properly
  app/ui/src/app/integration/edit-page/edit-page.component.ts
Labels: pr/approved
