Repository syndesisio/syndesis, pull requests merged in 2019-11, with the labels that each got.

#7058 Push tags at the end of the release
  tools/bin/commands/release
Labels: size/XS

#7060 fix(install): operator permissions
  install/operator/pkg/generator/assets/install/cluster.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, pr/review-requested, size/XS

#7062 chore(deps): upgrade kubernetes/openshift client to 4.6.1
  app/connector/knative/pom.xml
  app/pom.xml
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: pr/approved

#7073 chore(deps): camel fuse bump
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: dependencies, pr/approved, pr/review-requested, size/s

#7074 refactor: more use of the Threads utility class
  app/common/util/src/main/java/io/syndesis/common/util/thread/Threads.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
Labels: pr/approved

#7064 refactor: cleanup exception handling
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataExtension.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/OpenApiCustomizer.java
  app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
Labels: pr/approved

#7072 fix: maintain selection in create view wizard TEIIDTOOLS-681
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
Labels: pr/approved, pr/review-requested, size/l

#7076 bash script to change camel version
  tools/misc/syndesisCamelVersion.sh
Labels: pr/approved, pr/review-requested, size/m

#7077 Fix camel version bump to 2.21.0.fuse-760006
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-760006.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/s

#7083 chore: add `--nodev` option to README
  README.md
Labels: pr/approved, pr/review-requested, size/XS

#7038 chore: security policy and GPG key
  SECURITY.md
  security.asc
Labels: pr/approved, pr/review-requested, size/m

#7093 refactor: sane description for the SQL connector
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved, size/XS

#7096 Fix script to generate operator assets and display a message for the user to add/commit the changes
  tools/misc/syndesisCamelVersion.sh
Labels: pr/approved, size/XS

#7095 feat(connector): mongodb metadata
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoConfiguration.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoCustomizersUtil.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/meta/MongoDBMetadataRetrieval.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoDBVerifier.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/meta/mongodb3
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/MongoDBMetadataTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
Labels: group/connector, pr/approved, pr/review-requested

#7059 Enable addons from `install app` command
  install/operator/go.mod
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_app.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/generator/assets/install/app.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
Labels: pr/review-requested, size/m

#7084 fix(install): platform and binary name
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested, size/XS

#7101 chore(connector/sql): workaround for Oracle
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
Labels: pr/approved, pr/review-requested

#7082 fix: thrift dependency issues (again)
  install/operator/go.mod
  install/operator/go.sum
  install/operator/vendor/github.com/google/btree/btree_mem.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/l

#7092 fix: maintain list item selections on back/next TEIIDTOOLS-679
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Labels: pr/approved, pr/review-requested, size/l

#7094 Create common virtualization editor component
  app/ui-react/packages/api/src/useViewDefinitionDescriptors.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.css
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.css
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
Labels: pr/approved, pr/review-requested, size/XXL

#7103 ENTESB-12170 Integration metrics don't work
  app/server/metrics/prometheus/pom.xml
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
Labels: pr/approved

#7104 Fix #7100: allow to run integrations again with camel k
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved

#7105 TEIIDTOOLS-824 Hide list toolbar if no views
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
Labels: pr/approved, pr/review-requested, size/m

#7112 fix(TEIIDTOOLS-827) - Cut/Paste URL of virtualization views page or SQL client page does not work
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#7110 ENTESB-12070: add knative as addon
  app/connector/knative/src/main/java/io/syndesis/connector/knative/KnativeComponentProxyFactory.java
  install/operator/go.sum
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets/addons/knative/empty.yml
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/go-openapi/spec/bindata.go
  install/operator/vendor/github.com/go-openapi/spec/ref.go
  install/operator/vendor/github.com/google/btree/btree_mem.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: pr/approved

#7109 fix: selection allowed for source of active status even for loading
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Labels: pr/approved, pr/review-requested, size/s

#7118 feat(connector): mongodb change stream consumer
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/meta/MongoDBMetadataRetrieval.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/resources/mongodb-clustered.json
Labels: group/connector, pr/approved, pr/review-requested

#7122 ENTESB-12204 Unable to authenticate Twitter OAuth connection
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
Labels: pr/approved

#7126 TEIIDTOOLS-829 Adds details tab to virtualization page
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: pr/approved, pr/review-requested, size/l

#7119 feat(integration): dependency version override BOM
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
Labels: group/integration, pr/approved, pr/review-requested, size/m

#7128 chore(cli): add option to reset everything
  tools/bin/commands/dev
Labels: pr/approved, size/s

#7132 Fix: Remove invalid pkg from e2e testing
  install/operator/tests/e2e/install_with_defaults_test.go
Labels: pr/approved, pr/review-requested

#7131 fix(connector/mongodb): flaky test cases fix
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
Labels: group/connector, pr/approved

#7134 feat(ui): change vertical navigation to dark nav
  app/ui-react/package.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/yarn.lock
Labels: pr/approved, pr/review-requested, size/s

#7139 Add env support for TestSupport
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: pr/approved, size/XS

#7141 Set routeHostname from env if available
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/go.mod
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/vendor/github.com/spf13/cast/LICENSE
  install/operator/vendor/github.com/spf13/cast/Makefile
  install/operator/vendor/github.com/spf13/cast/README.md
  install/operator/vendor/github.com/spf13/cast/cast.go
  install/operator/vendor/github.com/spf13/cast/caste.go
  install/operator/vendor/github.com/spf13/cast/go.mod
  install/operator/vendor/github.com/spf13/cast/go.sum
  install/operator/vendor/modules.txt
Labels: group/operator, pr/approved, size/m

#7154 fix(connector/mongodb): embedded mongo refactory
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorMissingDatabaseOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorProducerTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/MongoDBMetadataTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
Labels: group/connector, pr/approved, pr/review-requested

#7130 enh: fix build log levels for react-ui module
  app/pom.xml
Labels: pr/approved, size/XS

#7102 chore: Improve docs about creating a JDBC driver library extension
  doc/modules/customizing/p_creating-jdbc-driver-library-extensions.adoc
Labels: pr/approved, size/m

#7155 refactor(connector/mongodb): static method
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/meta/MongoDBMetadataRetrieval.java
Labels: pr/approved, pr/review-requested

#7160 feat(connector/mongodb): polish update operation
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerUpdateCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/meta/MongoDBMetadataRetrieval.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/DataShapeConnectorTest.java
Labels: group/connector, pr/approved

#7158 Camel fuse 2.23.x
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/go.mod
  install/operator/vendor/github.com/google/btree/btree_mem.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: pr/review-requested

#7163 user doc: State that raw version of task-api.json is required
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
Labels: backport 1.8.x, size/XS

#7117 chore(install): remove `--nodev` from `syndesis install`
  doc/sdh/cli/cmd_install.adoc
  tools/bin/commands/install
Labels: pr/approved, size/m

#7166 fix(ENTESB-12127): (camel-fuse-2.23.x) Fix divergence in google-sheets
  app/connector/google-sheets/pom.xml
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnectorHelper.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
Labels: pr/approved

#7133 chore(deps): upgrade Camel to 2.21.0.fuse-760011
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config.yaml
  install/operator/go.mod
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-760011.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/s

#7042 fix: added vertical max height and scroll TEIIDTOOLS-784
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
Labels: pr/approved, pr/review-requested, size/s

#7167 fix for Community install is broken #7157
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, size/XS

#7165 fix: ensure we apply the updated descriptor
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
Labels: pr/approved, size/XS

#7168 grant permissions
  tools/bin/commands/minishift
Labels: pr/review-requested, size/XS

#7169 remove black bar when a breadcrumb dropdown overflows the viewport
  app/ui-react/packages/ui/src/Integration/ApiProviderDropdownItem.tsx
  app/ui-react/packages/ui/src/Integration/BreadcrumbDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdown.tsx
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.css
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/l

#7176 fix(TEIIDTOOLS-833) - Adapt Virtualization breadcrumb controls for different states
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: pr/approved, pr/review-requested, size/XXL

#7194 feat: add a create OpenAPI 3.x option to the API provider wizard
  app/ui-react/packages/ui/src/Shared/DndFileChooser.css
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/stories/Integration/Editor/ApiProvider.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/l

#7164 user doc: Update release number to 7.5 in UI links to downstream doc
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Labels: pr/approved, pr/review-requested, size/XS

#7171 Set operand images to right tag when building
  tools/bin/commands/release
Labels: cat/bug, pr/review-requested, size/s

#7196 fix for Community install is broken #7157 on windows using mingw64
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, size/XS

#7204 refactor(mongodb): database directory and output
  .gitignore
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/DataShapeConnectorTest.java
  app/connector/mongodb/src/test/resources/logback-test.xml
Labels: pr/approved, pr/review-requested

#7205 refactor(connector/mail): redirect test output
  app/connector/email/src/test/resources/logback-test.xml
Labels: pr/approved, size/s

#7211 user doc: Add downstream prereq for eval version or sample data installed
  doc/assemblies/tutorials/as_amq2api-intro.adoc
  doc/assemblies/tutorials/as_sf2db-intro.adoc
Labels: size/s

#7207 Update dv build to integrate with syndesis a little better, still more to do
  .circleci/config.yml
  app/dv/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested, size/m

#7212 chore(build): speed up git-commit-id-plugin
  app/pom.xml
Labels: size/s

#7203 chore(build): Maven settings support
  tools/bin/commands/build
  tools/bin/commands/util/maven_funcs
Labels: pr/approved, size/s

#7215 Align (remove) dv properties so that it uses parent pom properties
  app/dv/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested, size/XS

#7216 fix(ENTESB-12310): Fix spelling of API provider flow descriptions
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/OpenApiGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/OpenApiGeneratorTest.java
Labels: pr/approved

#7222 user doc: Correct a broken link and conditionalize it to appear only downstream
  doc/assemblies/integrating-applications/as_trigger-integrations-with-api-calls.adoc
Labels: size/XS

#7223 fix(TEIIDTOOLS-846) - Add a page for virtualization metrics
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: pr/approved, pr/review-requested, size/xl

#7225 TEIIDTOOLS-830, TEIIDTOOLS-831 Add virtualization details page content
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationEditions.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/xl

#7234 fix(#7214): spring cannot choose the correct constructor
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
Labels: pr/approved, pr/review-requested

#7237 fix(TEIIDTOOLS-809) - ViewListItem should show icon indicating if the view is invalid
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#7233 Run configuration tests using a test file
  install/operator/build/conf/config-test.yaml
  install/operator/go.mod
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: pr/approved, size/m

#7236 fix: improve error reporting and hook up undo/redo handlers in apicurio assembly
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useApiProviderIntegration.tsx
  app/ui-react/packages/apicurio-assembly/package.json
  app/ui-react/packages/apicurio-assembly/src/app/apicurio-host.component.ts
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/stories/Integration/Editor/ApiProvider.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/yarn.lock
Labels: size/l

#7249 chore: update integration test README
  app/test/integration-test/README.md
Labels: pr/approved, pr/review-requested, size/s

#7251 Russian translation + fix small type in English translation
  app/ui-react/syndesis/src/app/locales/app-translations.ru.json
  app/ui-react/syndesis/src/i18n/index.ts
  app/ui-react/syndesis/src/i18n/locales/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.ru.json
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.ru.json
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.ru.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/extensions/locales/extensions-translations.ru.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.ru.json
  app/ui-react/syndesis/src/modules/settings/locales/settings-translations.ru.json
Labels: pr/approved, size/xl

#7235 Fix install not taking the tag
  tools/bin/commands/crc
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested, size/s

#7250 Revert Google Calendar API upgrade
  app/connector/google-calendar/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/googlecalendar/WebhookToGoogleCalendar_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/googlecalendar/webhook-to-google-calendar-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/googlecalendar/webhook-to-google-calendar-export/model.json
Labels: pr/approved

#7252 Teiidtools 849
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
Labels: pr/approved, pr/review-requested, size/l

#7254 chore: fix the alignment of the dashboard cards
  app/ui-react/packages/ui/src/Dashboard/Dashboard.css
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
Labels: pr/approved, size/s

#7257 fix(TEIIDTOOLS-853) - Disable delete action in virtualization details kebab if running or in-progress
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/xl

#7258 TEIIDTOOLS-834 Refine VirtualizatonListItem actions
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#7280 Moving backporting bot to use actions
  .github/workflows/backport.yml
Labels: pr/approved, size/s

#7281 fix(ENTESB-12218): Wrong usage of Optional.of() in server-api-generator
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiFlowGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
Labels: pr/approved

#7282 fix: revert `google-api-services-gmail` upgrade
  app/connector/gmail/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/gmail/WebhookToGMail_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/gmail/webhook-to-gmail-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/gmail/webhook-to-gmail-export/model.json
Labels: pr/approved

#7283 fix(ENTESB-12218): Fix request body extraction for OpenAPI 3.x
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/DataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedJsonDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedXmlDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ModelHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
Labels: pr/approved
