Repository syndesisio/syndesis, pull requests merged in 2019-12, with the labels that each got.

#7260 TTOOLS-857 Adds toast notification on revert success
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/m

#7267 Teiidtools 855
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#7255 Change database ImageStream and delete komodo resources
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr.yaml
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
Labels: pr/approved, pr/review-requested, size/l

#7289 Aligning DV with syndesis parent properties and cleaning up no longer used properties
  app/dv/pom.xml
  app/dv/src/test/resources/generated-pom.xml
Labels: pr/approved, pr/review-requested, size/s

#7290 More updates regarding DV alignment with syndesis
  app/dv/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested, size/s

#7302 fix: TEIIDTOOLS-846 DV Metrics Layout improvements
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
Labels: pr/approved, pr/review-requested, size/m

#7303 fix(TEIIDTOOLS-858, 863, and 864) - Changes to virtualization versions table layout and story
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#7308 TEIIDTOOLS-819 DV Breadcrumb improvements
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationBreadcrumb.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationImportPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/m

#7309 TEIIDTOOLS-870 removing the credentialsprovider
  app/dv/src/main/java/io/syndesis/dv/openshift/PublishConfiguration.java
  app/dv/src/main/java/io/syndesis/dv/server/AuthHandlingFilter.java
  app/dv/src/main/java/io/syndesis/dv/server/CredentialsProvider.java
  app/dv/src/main/java/io/syndesis/dv/server/DvService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/openshift/TestVDBPublisher.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
Labels: group/datavirt, pr/approved, pr/review-requested, size/s

#7311 ENTESB-11703 Update to Jaeger 1.0.0 & OpenTracing API 0.33.0
  app/common/jaeger-spring-boot-starter/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/activity/ActivityHandler.java
  app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java
  app/server/logging/jaeger/src/test/resources/expected-activities.json
Labels: pr/approved

#7307 Remove .bats files
  tools/bin/commands/release.bats
  tools/bin/commands/util/openshift_funcs.bats
  tools/bin/commands/util/operator_funcs.bats
Labels: pr/approved, size/l

#7305 feat: better error page for the action configuration form when the connection is misconfigured
  app/ui-react/packages/ui/src/Shared/UnrecoverableError.tsx
  app/ui-react/packages/ui/stories/Shared/UnrecoverableError.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ActionDescriptorFetchError.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/shared/ApiError.tsx
Labels: pr/approved, size/l

#7153 Rework some configuration fields
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/route/route.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/vendor/github.com/go-openapi/spec/bindata.go
  install/operator/vendor/github.com/go-openapi/spec/ref.go
  install/operator/vendor/modules.txt
Labels: group/operator, pr/approved, pr/review-requested, size/l

#7318 Put back upgrade pod creation
  install/operator/pkg/syndesis/action/upgrade.go
Labels: pr/approved, pr/review-requested, size/s

#7312 Adding dv module to build
  app/pom.xml
  tools/bin/commands/build
Labels: pr/approved, pr/review-requested, size/XS

#7324 user doc: updates to the api-provider doc
  doc/assemblies/integrating-applications/as_trigger-integrations-with-api-calls.adoc
  doc/images/integrating-applications/ThreeVerticalDotsKebab.png
  doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
Labels: pr/review-requested

#7310 Backport fix for thrift dependency issue & fix for ENTESB-12350
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/vendor/github.com/google/btree/btree_mem.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: pr/review-requested, size/xl

#7224 add red hat font to UI
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/public/index.html
  app/ui-react/syndesis/src/app/App.css
Labels: pr/approved, pr/review-requested, size/XS

#7328 ENTESB-12380 Webhook step in activity log causes NPE on the server when Jaeger addon is enabled
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingInterceptStrategy.java
  app/server/logging/jaeger/pom.xml
  app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java
  app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java
  app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json
  app/server/logging/jaeger/src/test/resources/expected-activities.json
Labels: pr/approved

#7322 Change DisableSarCheck name for CR
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
Labels: pr/review-requested, size/XS

#7320 Entesb 12077
  app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/s

#7323 feat: add a mechanism to hide top-level nav items
  app/ui-react/packages/ui/src/Layout/PfVerticalNavItem.tsx
  app/ui-react/syndesis/config.minishift.json
  app/ui-react/syndesis/config.proxy.json
  app/ui-react/syndesis/config.staging.json
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/app/WithConfig.tsx
Labels: size/m

#7326 fix: fix typo and fix a related issue with the error code gathering
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: size/s

#7333 chore(deps): upgrade Maven version to 3.6.3
  app/.mvn/wrapper/maven-wrapper.properties
  tools/bin/commands/build
Labels: size/XS

#7325 fix(TEIIDTOOLS-856) - Revert button/action does not display for virtualizaton running - modified
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/s

#7321 TEIIDTOOLS-862 adding revision based export
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTestPublish.java
Labels: group/datavirt, pr/approved, pr/review-requested

#7335 TEIIDTOOLS-818 ensuring the modified flag is flipped
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTestPublish.java
Labels: group/datavirt, pr/approved, pr/review-requested

#7327 fix(TEIIDTOOLS-867) - Preview query fails when view name has a dash
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/s

#7319 Teiidtools 810
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor-styling.css
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
Labels: pr/approved, pr/review-requested, size/m

#7347 TEIIDTOOLS-875 Improve DV versions table component
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.tsx
  app/ui-react/packages/ui/stories/Data/Metrics/MetricsTab.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailHistoryTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDetailsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#7346 Add dv to images and change namespace from teiid to syndesis
  app/pom.xml
  install/operator/build/conf/config.yaml
  tools/bin/commands/build
Labels: pr/approved, pr/review-requested, size/XS

#7349 Removed release and core-release profiles, repo settings, scm settings, and other plugins inherited from parent
  app/dv/pom.xml
Labels: pr/approved, pr/review-requested, size/l

#7350 TEIIDTOOLS-878 fixing swagger regression
  app/dv/src/main/java/io/syndesis/dv/server/OpenAPIConfig.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
  app/dv/src/test/resources/application.properties
Labels: group/datavirt, pr/approved, pr/review-requested

#7356 fix Use GnuGrep on OS X #7355
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested, size/s

#7351 TEIIDTOOLS-876 Rename DV Version component
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/VirtualizationDetailHistoryTable.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Details/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Versions/VirtualizationVersionsTable.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Versions/VirtualizationVersionsTable.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Versions/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationVersionsTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/l

#7359 TEIIDTOOLS-848 adding a service call for metrics
  app/dv/src/main/java/io/syndesis/dv/openshift/PublishConfiguration.java
  app/dv/src/main/java/io/syndesis/dv/openshift/SyndesisHttpUtil.java
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/PodMetrics.java
  app/dv/src/test/java/io/syndesis/dv/openshift/TestVDBPublisher.java
Labels: group/datavirt, pr/approved, pr/review-requested

#7360 Add syndesis-dv image to be built
  tools/bin/commands/release
  tools/bin/commands/util/maven_funcs
Labels: pr/approved, pr/review-requested, size/XS

#7362 fix(TEIIDTOOLS-862) - Export action only exports latest version
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/s

#7361 TEIIDTOOLS-877 Adjusts DV action availability and arrangement
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, pr/approved, pr/review-requested, size/m

#7287 fix(build): s2i build within a container
  app/s2i/copy_mvn_repo.sh
  app/s2i/pom.xml
  app/s2i/src/main/assembly/repository.xml
  app/s2i/src/main/docker/Dockerfile
  app/s2i/src/main/resources/license-custom-assembly.xml
  app/s2i/src/main/resources/licenses/.gitkeep
  app/s2i/src/main/resources/settings.xml
  app/s2i/src/main/resources/settings_local.xml
  app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
Labels: pr/approved, pr/review-requested, size/XS

#7363 Update doc's based on dv usage
  doc/sdh/cli/cmd_build.adoc
  doc/sdh/cli/cmd_release.adoc
Labels: pr/approved, pr/review-requested, size/s

#7259 ENTESB-12090: Fix addons parameter when executing app
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/generator/assets/install/app.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/xl

#7371 TEIIDTOOLS-866 dv rest changes for the ui
  app/dv/src/main/java/io/syndesis/dv/RepositoryManager.java
  app/dv/src/main/java/io/syndesis/dv/repository/EditionRepository.java
  app/dv/src/main/java/io/syndesis/dv/repository/RepositoryManagerImpl.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/RestDataVirtualization.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/DataVirtualizationSerializerTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTestPublish.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/RestDataserviceTest.java
Labels: pr/approved, pr/review-requested

#7239 ENTESB-12262: Expose pvc name, access mode, storage-class & labels
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: pr/review-requested, size/XXL

#7373 TEIIDTOOLS-848 using a jolokia service
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
Labels: pr/approved, pr/review-requested

#7368 fix(connector/aws): align sdk version
  app/pom.xml
Labels: group/connector, pr/approved, size/XS

#7380 fix TechDebt - Remove Guava as direct dependency #7379
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/cache/GuavaSoftCache.java
  app/common/util/src/main/java/io/syndesis/common/util/cache/LRUCacheManager.java
  app/common/util/src/test/java/io/syndesis/common/util/cache/LRUSoftCacheTest.java
Labels: pr/approved

#7382 fix(ENTESB-12353): Fix response definition support in API provi…
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/DataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedXmlDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/util/OasModelHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20DataShapeGeneratorHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.yaml
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.yaml
Labels: pr/approved

#7381 fix: rework VirtualizationListItem
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
Labels: pr/approved, pr/review-requested, size/s

#7389 fix(ENTESB-12218): Add support for request body definitions in OpenAPI 3.x
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/DataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedJsonDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedXmlDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.yaml
Labels: backport 1.9.x, pr/approved

#7387 fix(ENTESB-12218): Fix OpenAPI auth validation rules
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSecurityScheme.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Labels: backport 1.9.x, pr/approved, pr/review-requested

#7386 Dynamic connection properties retrieval
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/SalesforceMetadataRetrievalTest.java
  app/connector/support/verifier/pom.xml
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/MetadataRetrieval.java
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadata.java
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/SyndesisMetadataProperties.java
  app/connector/support/verifier/src/test/java/io/syndesis/connector/support/verifier/api/ConnectorMetadataTest.java
  app/connector/support/verifier/src/test/java/io/syndesis/connector/support/verifier/api/sample/SampleConnectorMetaDataRetrieval.java
  app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java
  app/meta/src/test/java/io/syndesis/connector/meta/v1/ActionDefinitionEndpointTest.java
  app/meta/src/test/java/io/syndesis/connector/meta/v1/PetstoreMetadataRetrieval.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorPropertiesHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Labels: group/connector, group/meta, group/server, pr/approved, pr/review-requested

#7391 fix: Fix integration runtime health checks in nightly integration tests
  app/test/integration-test/src/test/java/io/syndesis/test/itest/gmail/WebhookToGMail_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/googlecalendar/WebhookToGoogleCalendar_IT.java
Labels: pr/approved

#7395 fix: Remove embedded camel-jira component
  app/connector/jira/pom.xml
  app/connector/jira/src/main/java/org/apache/camel/component/jira/FileConverter.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraComponent.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraConfiguration.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraConstants.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraEndpoint.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraType.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/JiraVerifierExtension.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/consumer/AbstractJiraConsumer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/consumer/NewCommentsConsumer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/consumer/NewIssuesConsumer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/oauth/JiraOAuthAuthenticationHandler.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/oauth/JiraOAuthGetAccessToken.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/oauth/OAuthAsynchronousHttpClientFactory.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/oauth/OAuthAsynchronousJiraRestClientFactory.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/oauth/OAuthHttpClientDecorator.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/AddCommentProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/AddIssueProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/AttachFileProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/DeleteIssueProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/IssueProducerHelper.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/TransitionIssueProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/UpdateIssueProducer.java
  app/connector/jira/src/main/java/org/apache/camel/component/jira/producer/WatcherProducer.java
  app/connector/jira/src/main/resources/META-INF/services/org/apache/camel/component.properties
  app/connector/jira/src/main/resources/META-INF/services/org/apache/camel/component/jira
  app/connector/jira/src/main/resources/org/apache/camel/catalog/components/jira.json
  app/connector/jira/src/main/resources/services/org/apache/camel/TypeConverter
  app/connector/jira/src/main/resources/services/org/apache/camel/component/jira
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760009.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: backport 1.9.x, pr/approved

#7397 TEIIDTOOLS-883, TEIIDTOOLS-865: Fixing the resource leak for http con…
  app/dv/pom.xml
  app/dv/src/main/java/io/syndesis/dv/openshift/HttpClientUtils.java
  app/dv/src/main/java/io/syndesis/dv/openshift/SyndesisHttpClient.java
  app/dv/src/main/java/io/syndesis/dv/openshift/SyndesisHttpUtil.java
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationPublishTest.java
Labels: backport 1.9.x, pr/approved, pr/review-requested

#7403 fix(ENTESB-12222): Fixed operator build on CircleCi
  install/operator/pkg/syndesis/action/install.go
Labels: pr/approved, pr/review-requested, size/XS

#7404 [Backport 1.9.x]: Fix OpenAPI auth validation rules
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSecurityScheme.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Labels: pr/approved

#7405 [Backport 1.9.x]: Add support for request body definitions in OpenAPI 3.x
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/DataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedJsonDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/UnifiedXmlDataShapeSupport.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30DataShapeGeneratorHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.yaml
Labels: pr/approved

#7396 Fix syndesisCamelVersion.sh script to change camel version on additional files.
  tools/misc/syndesisCamelVersion.sh
Labels: pr/approved, size/XS

#7412 TEIIDTOOLS-861 removing duplicate entries
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
Labels: backport 1.9.x, group/datavirt, pr/approved, pr/review-requested

#7398 TEIIDTOOLS-879 Connects DV metrics page to backend
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualizationMetrics.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainerSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/index.ts
  app/ui-react/packages/ui/stories/Data/Metrics/DvMetricsContainerSkeleton.stories.tsx
  app/ui-react/packages/ui/stories/Data/Metrics/MetricsTab.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
Labels: backport 1.9.x, group/datavirt, pr/approved, pr/review-requested, size/xl

#7409 [ENTESB-12331] Adding auto-discovery for strimzi kafka/AMQ brokers
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
Labels: backport 1.9.x, cat/feature, pr/approved

#7410 ENTESB-12330: Allow for specifying a custom resource on install
  install/operator/pkg/cmd/internal/install/custom_app_test.yml
  install/operator/pkg/cmd/internal/install/default_app_test.yml
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_app.go
  install/operator/pkg/cmd/internal/install/install_app_test.go
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: backport 1.9.x, pr/approved, pr/review-requested, size/l

#7394 Teiidtools 874
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: backport 1.9.x, group/datavirt, pr/approved, pr/review-requested, size/m

#7427 chore: configure syndesisio/backport-action
  .github/workflows/backport.yml
Labels: pr/approved, size/s

#7424 TEIIDTOOLS-890 changing publishing to a single service
  app/dv/src/main/java/io/syndesis/dv/openshift/ProtocolType.java
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
Labels: group/datavirt, pr/approved, pr/review-requested

#7422 TEIIDTOOLS-861 removing duplicate entries
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
Labels: pr/approved, pr/review-requested

#7429 chore(build): setup maven-buildtime-extension
  .mvn/extensions.xml
  app/.mvn/extensions.xml
  app/.mvn/maven.config
Labels: size/m

#7421 TEIIDTOOLS-879 Connects DV metrics page to backend
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualizationMetrics.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvCacheHitMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainerSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/index.ts
  app/ui-react/packages/ui/stories/Data/Metrics/DvMetricsContainerSkeleton.stories.tsx
  app/ui-react/packages/ui/stories/Data/Metrics/MetricsTab.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
Labels: pr/approved, pr/review-requested, size/xl

#7423 TEIIDTOOLS-874 backport
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#7430 TEIIDTOOLS-854 improving error reporting on publish
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationPublishTest.java
Labels: backport 1.9.x, pr/approved, pr/review-requested

#7437 Back port of TEIIDTOOLS-890
  app/dv/src/main/java/io/syndesis/dv/openshift/ProtocolType.java
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
Labels: pr/approved, pr/review-requested

#7431 chore(test): exclude ServiceVdbGeneratorTest
  app/.mvn/maven.config
  app/excluded_tests.txt
Labels: size/XS

#7435 refactor(ENTESB-12218): Use camel-rest-openapi components
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/openapi/OpenApiHelper.java
  app/common/util/src/test/java/io/syndesis/common/util/openapi/OpenApiHelperTest.java
  app/connector/rest-swagger/pom.xml
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizer.java
  app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizerTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponentTest.java
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/pom.xml
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorHelperTest.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRoute.java
  app/pom.xml
  app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/server/controller/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/OpenApiCustomizer.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiClientV2_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiClientV3_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV2-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV2-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV3-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV3-export/model.json
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760011.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: pr/approved

#7439 [Backport-1.9.x] Use camel-rest-openapi components
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/openapi/OpenApiHelper.java
  app/common/util/src/test/java/io/syndesis/common/util/openapi/OpenApiHelperTest.java
  app/connector/rest-swagger/pom.xml
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizer.java
  app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizerTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponentTest.java
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/pom.xml
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorHelperTest.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateApplicationWithRestDSL/RestRoute.java
  app/pom.xml
  app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/server/controller/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/OpenApiCustomizer.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiClientV2_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/TodoApiClientV3_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV2-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV2-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV3-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiClientV3-export/model.json
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760011.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: pr/approved

#7440 chore(c/kafka): change brokers type to `typeahead`
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
Labels: pr/approved, pr/review-requested, size/XS

#7443 ENTESB-12385: Disable extensions if camelk addon is enabled
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport 1.9.x, pr/approved, pr/review-requested, size/XS

#7436 TEIIDTOOLS-890 the route needs to use the new service name
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
Labels: group/datavirt, pr/approved, pr/review-requested

#7444 TEIIDTOOLS-896 including more information in the dv-info file
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationPublishTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
Labels: pr/approved, pr/review-requested

#7442 [FUSEQE-12554] Change DDB connector name to be the same style as othe…
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: backport 1.9.x, pr/approved, size/XS

#7454 chore(build): enable proxy.golang.org
  .circleci/config.yml
Labels: pr/approved, size/XS

#7445 Teiidtools 880
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/CreateViewHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/CreateViewHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewCreateSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: backport 1.9.x, group/datavirt, pr/approved, pr/review-requested, size/xl

#7457 TEIIDTOOLS-811 DV SQL Result table update to pf4 component
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/src/Shared/GenericTable.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
  app/ui-react/packages/ui/stories/Shared/GenericTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.9.x, group/datavirt, pr/approved, pr/review-requested, size/xl

#7438 refactor(ENTESB-12218): Minimize 3.x specifications for generated API connector
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/util/SpecificationOptimizer.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/util/OasModelHelperTest.java
  app/server/api-generator/src/test/resources/openapi/v2/todo.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
Labels: backport 1.9.x, pr/review-requested

#7449 feature(server): enrich connector with dynamic properties
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
Labels: backport 1.9.x, group/connector, group/server, pr/approved, pr/review-requested

#7455 fix(ENTESB-12218): Add OpenAPI 3.x specific validation rule
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ModelHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30PropertyGenerators.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Labels: backport 1.9.x, pr/approved

#7458 feat: add full keywords and functions to editor code completion list
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DvAutocomplete.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: backport 1.9.x, pr/approved, pr/review-requested, size/l

#7472 TEIIDTOOLS-840 TEIIDTOOLS-891 syndesisio#7393
  app/dv/pom.xml
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/ServiceVdbGenerator.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/EditorServiceTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceVdbGeneratorTest.java
  app/dv/src/test/resources/generated-pom.xml
  app/excluded_tests.txt
  app/pom.xml
Labels: pr/approved, pr/review-requested

#7467 feat(connector/debezium): first commit, POC
  .circleci/config.yml
  app/connector/debezium/pom.xml
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizer.java
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrieval.java
  app/connector/debezium/src/main/resources/META-INF/syndesis/connector/debezium.json
  app/connector/debezium/src/main/resources/META-INF/syndesis/connector/meta/debezium
  app/connector/debezium/src/main/resources/META-INF/syndesis/connector/verifier/debezium
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
  app/ui-react/syndesis/public/icons/debezium.png
Labels: group/connector, pr/approved, pr/review-requested

#7475 chore(build): make buildtime extension opt-in
  app/.mvn/maven.config
Labels: size/XS

#7477 fix for ENTESB-11675 to add errorHandler field to the schema
  app/connector/support/maven-plugin/src/main/resources/connector-schema.json
Labels: pr/approved, size/XS
