Repository syndesisio/syndesis, pull requests merged in 2019-07, with the labels that each got.

#5993 #5992: Correcting the ENV variable BUILD_IMAGE_STREAM in deploymentco…
  install/generator/04-teiid-komodo-server.yml.mustache
Labels: pr/approved

#5991 Remove example/log-step and example/simple-action (#5906)
  app/extension/example/log-step/pom.xml
  app/extension/example/log-step/src/main/java/io/syndesis/extension/example/log/LogStep.java
  app/extension/example/log-step/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json
  app/extension/example/simple-action-step/pom.xml
  app/extension/example/simple-action-step/src/main/java/io/syndesis/extension/example/simple/ActionStep.java
  app/extension/example/simple-action-step/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json
  app/extension/pom.xml
Labels: pr/approved, pr/review-requested

#5997 [Backport 1.7.x] fix: remove karma-jasmine-jquery and therefore the transitive bower dependencies
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: pr/approved

#6011 fix: AcquisitionMethod JSON serialization
  app/server/credential/pom.xml
  app/server/credential/src/main/java/io/syndesis/server/credential/AcquisitionMethod.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth1CredentialProvider.java
  app/server/credential/src/main/java/io/syndesis/server/credential/OAuth2CredentialProvider.java
  app/server/credential/src/test/java/io/syndesis/server/credential/AcquisitionMethodTest.java
  app/server/credential/src/test/java/io/syndesis/server/credential/OAuth1CredentialProviderTest.java
  app/server/credential/src/test/java/io/syndesis/server/credential/OAuth2CredentialProviderTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/SetupITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/credential/CredentialITCase.java
  app/ui-react/packages/models/swagger.internal.json
  app/ui-react/packages/models/swagger.json
Labels: pr/approved, pr/review-requested

#6008 [Backport 1.7.x] manual backport of #5990
  app/ui-react/README.md
  app/ui-react/packages/ui/src/Shared/UnrecoverableError.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/shared/ExtensionIntegrations.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
  app/ui-react/syndesis/src/setupProxy.js
  app/ui-react/syndesis/src/shared/ApiError.tsx
Labels: pr/approved, pr/review-requested

#6019 fix(operator): Fixes to operator compilation
  install/operator/.lib.sh
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: pr/approved, pr/review-requested

#5952 Fixes #5917, handle environment tags appropriately on integration delete
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
Labels: backport 1.7.x, pr/review-requested

#6000 #5999 Adding the CONTROLLERS_EXPOSE_VIA3SCALE ENV variable to komodo-…
  install/generator/04-teiid-komodo-server.yml.mustache
  install/operator/pkg/generator/assets/install/04-teiid-komodo-server.yml.mustache
Labels: backport 1.7.x, pr/approved

#6018 fix(server): multiple authentication methods clash
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
Labels: pr/approved

#6023 Fix the merge removal of tough-cookie version
  app/ui-react/yarn.lock
Labels: pr/approved

#6021 #5992: Correcting the ENV variable BUILD_IMAGE_STREAM in deploymentco…
  install/generator/04-teiid-komodo-server.yml.mustache
Labels: pr/approved

#6016 Remove cypress from dev-dependencies
  app/ui-react/syndesis/package.json
Labels: pr/approved, pr/review-requested

#6020 Changes to ui poms (phases, node-sass/iltorb) for proxies
  app/pom.xml
  app/ui-angular/pom.xml
  app/ui-react/pom.xml
Labels: pr/approved, pr/review-requested

#6029 chore: add branch protection rules
  RELEASING.adoc
Labels: pr/approved

#5805 fix: get an updated integration when editing its definition using the new API introduced in #5724
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useApiProviderIntegration.tsx
  app/ui-react/packages/api/src/useApiProviderSpecification.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#6031 fix: re-render the connection edit form on location change
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
Labels: backport 1.7.x, pr/approved

#6037 TT-691: Removes un-needed Alert dialog.
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested

#6043 user doc: Add doc for collections of input parameters
  doc/connecting/topics/as_connecting-to-databases.adoc
  doc/connecting/topics/c_about-parameter-placeholders-and-values.adoc
  doc/connecting/topics/p_adding-db-connection-finish-middle.adoc
  doc/connecting/topics/p_adding-db-connection-start.adoc
Labels: backport 1.7.x

#6045 user doc: Minor grammar fixes
  doc/connecting/topics/c_about-parameter-placeholders-and-values.adoc
Labels: backport 1.7.x

#6046 user doc: Updates for API key
  doc/connecting/master.adoc
  doc/connecting/topics/p_creating-rest-api-connections.adoc
  doc/integrating-applications/master.adoc
  doc/integrating-applications/topics/as_copying-integrations-to-other-environments.adoc
  doc/integrating-applications/topics/as_managing-integrations.adoc
  doc/integrating-applications/topics/c_about-api-connectors.adoc
  doc/integrating-applications/topics/c_guidelines-for-openapi-documents.adoc
  doc/integrating-applications/topics/p_creating-api-connectors.adoc
  doc/shared/attributes-links.adoc
  doc/shared/attributes.adoc
  doc/tutorials/master.adoc
Labels: backport 1.7.x

#6042 fix: use separate Spring Boot management port for liveness probe
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: backport 1.7.x, pr/approved

#6048 TTOOLS-695 Conversion of DV components
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
Labels: pr/approved, pr/review-requested

#6058 Upgrade spring-security to 4.2.13
  app/pom.xml
Labels: backport 1.7.x, pr/approved, pr/review-requested

#6041 Backport 5998 to 1.7.x - TT-668
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.7.x, pr/approved, pr/review-requested

#6035 Upgrade to most current atlasmap
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport master, pr/approved, pr/review-requested

#6061 chore: Update to AtlasMap 1.40.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.7.x, pr/approved

#6060 fixes(5890): Improves detailed comparison messaging on integration ch…
  app/common/model/src/main/java/io/syndesis/common/model/support/EquivContext.java
  app/common/model/src/main/java/io/syndesis/common/model/support/Equivalencer.java
  app/common/model/src/test/java/io/syndesis/common/model/support/EquivalencerTest.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
Labels: pr/approved, pr/review-requested

#6050 chore: some unit tests for the UI
  app/ui-react/README.md
  app/ui-react/package.json
  app/ui-react/packages/api/__tests__/Fetch.spec.tsx
  app/ui-react/packages/ui/__tests__/AppLayout.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectionCard.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectionDetailsForm.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectionsListView.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectorConfigurationForm.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionDetail.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionImportCard.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionImportReview.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionIntegrationsTable.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionListItem.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionListView.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionOverview.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ExtensionSupports.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationStatus.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationStatusDetail.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationsListItem.spec.tsx
  app/ui-react/packages/ui/__tests__/ProgressWithLink.spec.tsx
  app/ui-react/packages/ui/__tests__/Shared/AggregatedMetricCard.spec.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/packages/ui/tests/ConnectionCard.spec.tsx
  app/ui-react/packages/utils/__tests__/WithRouter.spec.tsx
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/tsconfig.test.json
Labels: pr/approved, pr/review-requested

#6075 Master security fix
  install/generator/05-syndesis-security.yml.mustache
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
  install/operator/deploy/syndesis-operator.yml
  install/syndesis.yml
Labels: pr/approved

#6082 user doc: add xref from general json def file info to ui details
  doc/integrating-applications/topics/c_about-extension-definitions.adoc
  doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
Labels: backport 1.7.x, size/s

#5947 user doc: Adds doc for supported functions and operations in conditional mapping expressions
  doc/integrating-applications/topics/p_applying-conditions-to-mappings.adoc
  doc/integrating-applications/topics/p_combine-multiple-source-fields-into-one-target-field.adoc
  doc/integrating-applications/topics/p_separate-one-source-field-into-multiple-target-fields.adoc
  doc/integrating-applications/topics/r_find-data-field-you-want-to-map.adoc
Labels: backport 1.7.x, size/l

#6073 Change phases of iltorb/node-sass download to generate-sources
  app/ui-angular/pom.xml
  app/ui-react/pom.xml
Labels: backport master, pr/approved, pr/review-requested

#6038 6017 - Twitter direct message doesn't work
  app/connector/twitter/pom.xml
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/DirectMessage.java
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/RetrieveDirectMessageCustomizer.java
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
Labels: pr/approved

#6089 user doc: Add Tech Preview note to doc for conditional flows.
  doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
Labels: size/s

#6074 Fix syndesis permissions and legacy mode
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/generator/05-syndesis-security.yml.mustache
  install/operator/deploy/manifests/1.7.0/syndesisoperator.1.7.0.clusterserviceversion.yaml
  install/operator/deploy/syndesis-operator.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#6097 Bump camel and camel-k to pinned versions
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved, size/s

#6092 Fixes #6069 Add ui and server config map migration from 1.6.x to 1.7.x
  tools/upgrade/migration/resource/02_ui_config_map_upgrade.sh
  tools/upgrade/migration/resource/03_server_config_map_upgrade.sh
Labels: pr/1.7.x, pr/approved, pr/review-requested, size/m

#6105 user doc: Add doc for specifying ui properties in Java class files
  doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
  doc/integrating-applications/topics/r_example-camel-bean.adoc
  doc/integrating-applications/topics/r_example-route-builder-spring-boot.adoc
  doc/integrating-applications/topics/r_example-route-builder.adoc
  doc/integrating-applications/topics/r_example-route-xml-fragment.adoc
  doc/integrating-applications/topics/r_example-step-api.adoc
Labels: backport 1.7.x, size/l

#6106 user doc: Updates to doc for API key security based on QA review
  doc/integrating-applications/topics/c_guidelines-for-openapi-documents.adoc
  doc/integrating-applications/topics/p_creating-api-connectors.adoc
  doc/integrating-applications/topics/r_refreshing-access-tokens.adoc
Labels: backport 1.7.x, size/s

#6091 fix(datavirt): add tech preview popover to title text
  app/ui-react/packages/ui/src/Shared/SimplePageHeader.css
  app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSteps.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/m

#6098 chore: mark the conditional flow as tech preview
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/m

#6103 Fixes #6015 Deploy Komodo
  install/operator/pkg/generator/assets/install/03-syndesis-ui.yml.mustache
  install/operator/pkg/generator/assets/install/04-teiid-komodo-server.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
Labels: pr/approved, size/s

#6090 TTOOLS-695 Converting DV pages to FunctionComponent
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewCreateSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewsImportSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/XXL

#6070 fix(5955): Error after change of template step language type
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplater.tsx
Labels: pr/approved, pr/review-requested

#6120 user doc: Updates based on Michael Cada review
  doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
Labels: backport 1.7.x, size/m

#6095 fix: DB procedure name changed to text input instead of dropdown #5690
  install/operator/pkg/generator/assets/install/04-syndesis-db.yml.mustache
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/m

#6115 fix: disable the next button on the Api Provider review page in case of errors in the definition
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Labels: pr/approved, size/XS

#5303 chore: use SCLs Nginx base image
  app/ui-angular/docker/Dockerfile
  app/ui-angular/docker/nginx-syndesis.conf
  app/ui-angular/docker/nginx.repo
  app/ui-angular/pom.xml
  app/ui-react/docker/Dockerfile
  app/ui-react/docker/nginx-syndesis.conf
  app/ui-react/docker/nginx.repo
  app/ui-react/pom.xml
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/syndesis-template.go
  install/syndesis.yml
Labels: pr/review-requested

#6124 TTOOLS-659 Consolidate virtualization handlers
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: pr/approved, pr/review-requested, size/l

#6128 fix(server): handle unsupported security definitions
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/PropertyGeneratorsTest.java
Labels: backport 1.7.x, pr/approved

#6104 fix(6085): Email verification needs to fail-fast to avoid request tim…
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/AbstractEMailVerifier.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/receive/ReceiveEMailVerifierExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/send/SendEMailVerifierExtension.java
  app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java
Labels: pr/approved, pr/review-requested

#6130 fix permission issues on master
  install/operator/pkg/generator/assets/install/05-syndesis-security.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/l

#6133 chore: update UI setup against local Syndesis
  app/ui-react/syndesis/src/setupProxy.js
  doc/sdh/development/local.adoc
Labels: pr/approved, pr/review-requested, size/XS

#6121 Fixes #6111 Komodo server doesn't start
  install/generator/04-teiid-komodo-server.yml.mustache
  install/syndesis.yml
Labels: backport 1.7.x, size/XS

#6138 fix: merge the previous step to the new one when updating a connection
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: backport 1.7.x, pr/approved, size/s

#6136 Create infrastructure home dashboard / Create integrations home dashboard
  install/operator/build/conf/addons/syndesis-infra-api-dashboard.yml
  install/operator/build/conf/addons/syndesis-infra-db-alerting-rules.yml
  install/operator/build/conf/addons/syndesis-infra-db-dashboard.yml
  install/operator/build/conf/addons/syndesis-infra-home-dashboard.yml
  install/operator/build/conf/addons/syndesis-infra-jvm-dashboard.yml
  install/operator/build/conf/addons/syndesis-infra-meta-alerting-rules.yml
  install/operator/build/conf/addons/syndesis-infra-server-alerting-rules.yml
  install/operator/build/conf/addons/syndesis-infra-servicemonitor.yml
  install/operator/build/conf/addons/syndesis-integrations-camel-dashboard.yml
  install/operator/build/conf/addons/syndesis-integrations-home-dashboard.yml
  install/operator/build/conf/addons/syndesis-integrations-jvm-dashboard.yml
  install/operator/build/conf/addons/syndesis-rest-api-dashboard.yml
Labels: pr/approved, pr/review-requested

#6140 fix: Support unified json bodies with aggregate steps
  app/common/model/src/main/java/io/syndesis/common/model/integration/Step.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AggregateStepHandlerTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-unified-response-schema.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-unified-response-schema.json
Labels: backport 1.7.x, pr/approved

#6142 Fixes #6111 Komodo server doesn't start
  install/generator/04-teiid-komodo-server.yml.mustache
  install/syndesis.yml
Labels: pr/1.7.x, pr/approved, size/XS

#6144 Fixes #5917 Circular dependency issue
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved

#6152 AWS-SQS MetaData Extension
  app/connector/aws-sqs/pom.xml
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataExtension.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataRetrieval.java
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/meta/aws-sqs
  app/connector/aws-sqs/src/test/java/io/syndesis/connector/aws/sqs/AWSSQSMetaDataExtensionTest.java
Labels: pr/approved

#6151 fix: when updating a connection, check if the previous step exist and has a valid id, else create a new one
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/XS

#6134 Backport documentation changes to 1.7.x
  doc/integrating-applications/topics/c_about-extension-definitions.adoc
  doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
  doc/integrating-applications/topics/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
  doc/integrating-applications/topics/r_example-camel-bean.adoc
  doc/integrating-applications/topics/r_example-route-builder-spring-boot.adoc
  doc/integrating-applications/topics/r_example-route-builder.adoc
  doc/integrating-applications/topics/r_example-route-xml-fragment.adoc
  doc/integrating-applications/topics/r_example-step-api.adoc
Labels: pr/1.7.x, pr/approved, pr/review-requested, size/l

#6156 fix: Fuse online documentation links to 7.4
  app/ui-react/syndesis/src/app/UI.tsx
Labels: backport 1.7.x, pr/approved, size/XS

#6155 Box - no property for fileName in upload action #5233
  app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxUploadCustomizer.java
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
Labels: pr/approved

#6150 fix: InlineTextEdit shows the controlled value in read mode
  app/ui-react/packages/api/src/useApiResource.tsx
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Labels: pr/approved, size/m

#6161 [Backport 1.7.x] fix: disable the next button on the Api Provider and Api Connector view page in case of errors in the definition
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Labels: pr/approved, size/m

#6164 user doc: new doc for the AWS SNS and SQS connectors
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-amazon-s3.adoc
  doc/connecting/topics/as_connecting-to-amazon-sns.adoc
  doc/connecting/topics/as_connecting-to-amazon-sqs.adoc
  doc/connecting/topics/as_connecting-to-aws.adoc
  doc/connecting/topics/p_adding-amazon-sns-connection-send.adoc
  doc/connecting/topics/p_adding-amazon-sqs-connection-retrieve.adoc
  doc/connecting/topics/p_adding-amazon-sqs-connection-send.adoc
  doc/connecting/topics/p_create-s3-connection.adoc
  doc/connecting/topics/p_creating-amazon-sns-connections.adoc
  doc/connecting/topics/p_creating-amazon-sqs-connections.adoc
  doc/connecting/topics/p_obtaining-aws-credentials.adoc
  doc/connecting/topics/r_prerequisites-for-creating-s3-connection.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: backport 1.7.x, size/xl

#6166 Convert remaining DV syndesis and api files to hooks
  app/ui-react/packages/api/src/WithViewEditorStates.tsx
  app/ui-react/packages/api/src/WithVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/WithVirtualizationConnectionStatuses.tsx
  app/ui-react/packages/api/src/WithVirtualizations.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useApiResource.tsx
  app/ui-react/packages/api/src/usePolling.tsx
  app/ui-react/packages/api/src/useViewEditorStates.tsx
  app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/useVirtualizationConnectionStatuses.tsx
  app/ui-react/packages/api/src/useVirtualizations.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Labels: pr/approved, pr/review-requested, size/XXL

#6167 fix: use band-aid to discard old action definition when a new connection is set
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/s

#6171 fix(6149): Improve the robustness of template step pre-processor
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/AbstractTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/FreeMarkerTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/MustacheTemplatePreProcessor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/step/template/VelocityTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestFreeMarkerTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestMustacheTemplatePreProcessor.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/step/template/TestVelocityTemplatePreProcessor.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/AbstractTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/FreeMarkerTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/MustacheTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/AbstractVelocityTemplateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/template/velocity/VelocityFormalSyntaxTest.java
Labels: pr/approved, pr/review-requested

#6175 AWS SNS MetaData Extension
  app/connector/aws-sns/pom.xml
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataExtension.java
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataRetrieval.java
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/meta/aws-sns
  app/connector/aws-sns/src/test/java/io/syndesis/connector/aws/sns/AWSSNSMetaDataExtensionTest.java
Labels: pr/approved

#6174 TTOOLS-688 Enable tables for SQL auto complete
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewEditContent.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6178 fix: propagate data shape changes to all subsequent steps
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
Labels: backport 1.7.x, pr/approved

#6181 fix: quick band-aid to bring back empty states
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
Labels: backport 1.7.x, size/l

#6180 fix: No artifact attached build error for test module
  app/test/pom.xml
Labels: pr/approved, size/s

#6182 fix: quick band-aid to bring back empty states (1.7.x)
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
Labels: pr/approved, size/l

#6183 chore: Update to AtlasMap 1.41.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/yarn.lock
Labels: pr/approved, size/m

#6184 fix(cli help): fixed the camel-snapshot <version> help message
  tools/bin/commands/build
Labels: pr/approved, size/XS

#6076 fix(5607): Unify template step naming
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplate.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, pr/review-requested

#6169 #6100 - create cacheable intermediate layer for S2I image
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/s2i/copy_mvn_repo.sh
  app/s2i/pom.xml
  app/s2i/src/main/docker/Dockerfile
Labels: pr/approved, pr/review-requested, size/s

#6190 user doc: new doc for Jira connector
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-jira.adoc
  doc/connecting/topics/p_adding-jira-connection-add-comment.adoc
  doc/connecting/topics/p_adding-jira-connection-add-issue.adoc
  doc/connecting/topics/p_adding-jira-connection-attach-file.adoc
  doc/connecting/topics/p_adding-jira-connection-start.adoc
  doc/connecting/topics/p_adding-jira-connection-transition-issue.adoc
  doc/connecting/topics/p_adding-jira-connection-update-issue.adoc
  doc/connecting/topics/p_adding-jira-connection-watchers.adoc
  doc/connecting/topics/p_creating-jira-connections.adoc
  doc/connecting/topics/p_registering-with-jira.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: backport 1.7.x, size/xl

#6189 Dont use the same file that is used by template install
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
Labels: backport master, pr/approved, pr/review-requested

#6193 fix: explicitly set IDs for steps too; add comments
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: backport 1.7.x, pr/approved

#6192 Fix for TEIIDTOOLS-683 Initialization of the Import Datasource wizard flashes "No connections available"
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionSkeleton.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsToolbarSkeleton.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/index.ts
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsWithToolbarSkeleton.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
Labels: pr/approved, pr/review-requested, size/l

#6195 user doc: update to SQL batch update parameter
  doc/connecting/topics/p_adding-db-connection-finish-middle.adoc
Labels: backport 1.7.x

#6198 bug: fixes #5959 release script stopped working.
  tools/bin/commands/release
Labels: pr/approved, size/l

#6137 Changes the pod names in the templates to match the actual container names
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/syndesis-template.go
  install/operator/build/conf/template-config.yaml
  install/operator/pkg/generator/assets/install/03-syndesis-ui.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-meta.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-oauth-proxy.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-server.yml.mustache
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.mustache
  install/operator/pkg/generator/generator.go
Labels: pr/approved, pr/review-requested, size/s

#6197 TTOOLS-685 Adding virtualization status to details header
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/xl

#6204 user doc: Adding a missing format symbol to fix step number
  doc/connecting/topics/p_adding-jira-connection-transition-issue.adoc
Labels: backport 1.7.x, size/XS

#6206 user doc: Updates based on QA review.
  doc/connecting/topics/p_adding-amazon-sqs-connection-retrieve.adoc
Labels: backport 1.7.x, size/m

#6172 fix for DB procedure name changed to text input instead of dropdown
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/server/endpoint/kurt
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
Labels: pr/approved, pr/review-requested, size/XS

#6210 user doc: Update tutorials to reflect React UI changes
  doc/shared/p_create-sf-connection.adoc
  doc/shared/p_create-twitter-connection.adoc
  doc/shared/p_register-with-sf.adoc
  doc/shared/p_register-with-twitter.adoc
  doc/tutorials/topics/as_amq2api-intro.adoc
  doc/tutorials/topics/images/t2sf-mappings.png
  doc/tutorials/topics/p_amq2api-add-damage-reporter-step.adoc
  doc/tutorials/topics/p_amq2api-add-mapping-step.adoc
  doc/tutorials/topics/p_amq2api-choose-finish.adoc
  doc/tutorials/topics/p_amq2api-choose-start.adoc
  doc/tutorials/topics/p_amq2api-confirm-works.adoc
  doc/tutorials/topics/p_amq2api-create-amq-connection.adoc
  doc/tutorials/topics/p_amq2api-create-custom-step.adoc
  doc/tutorials/topics/p_amq2api-create-rest-api-connection.adoc
  doc/tutorials/topics/p_amq2api-create-rest-api-connector.adoc
  doc/tutorials/topics/p_amq2api-name-and-publish.adoc
  doc/tutorials/topics/p_amq2api-upload-todo-app-icon.adoc
  doc/tutorials/topics/p_sf2db-add-mapping-step.adoc
  doc/tutorials/topics/p_sf2db-choose-finish.adoc
  doc/tutorials/topics/p_sf2db-choose-start.adoc
  doc/tutorials/topics/p_sf2db-confirm-works.adoc
  doc/tutorials/topics/p_sf2db-name-and-publish.adoc
  doc/tutorials/topics/p_t2sf-add-filter-step.adoc
  doc/tutorials/topics/p_t2sf-add-mapping-step.adoc
  doc/tutorials/topics/p_t2sf-choose-finish.adoc
  doc/tutorials/topics/p_t2sf-choose-start.adoc
  doc/tutorials/topics/p_t2sf-confirm-working.adoc
  doc/tutorials/topics/p_t2sf-name-and-publish.adoc
Labels: backport 1.7.x

#6212 user doc: Missed a field name update
  doc/tutorials/topics/p_amq2api-create-amq-connection.adoc
Labels: backport 1.7.x, size/XS

#6213 Simplify DV packages/ui index files
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6217 #6209 - Replacing xargs -a to make it compatible with MacOS
  app/s2i/copy_mvn_repo.sh
Labels: pr/approved, pr/review-requested, size/XS

#6187 fix(6141): FTP Verifier handles empty username & password properties
  app/connector/ftp/pom.xml
  app/connector/ftp/src/main/java/io/syndesis/connector/ftp/FtpVerifierExtension.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/ConnectorOptions.java
Labels: pr/approved, pr/review-requested

#6219 Rewrite of polling function
  app/ui-react/packages/api/src/usePolling.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizations.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: pr/approved, pr/review-requested, size/m

#6216 Remove wrong ocp4 permission from install resources
  install/generator/05-syndesis-security.yml.mustache
  install/operator/deploy/syndesis-operator.yml
  install/operator/pkg/generator/assets/install/05-syndesis-security.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
  install/syndesis.yml
Labels: pr/approved, pr/review-requested, size/s

#6233 [Upgrade] Link the secret back to SAs after re-creation
  tools/upgrade/steps/upgrade_40_update_resources
Labels: backport master, pr/approved, pr/review-requested, size/s

#6236 Fix syndesis dev --cleanup: Force the removal of images when oc adm prune failed to remove
  tools/bin/commands/dev
Labels: pr/approved, size/s

#6235 fix: revisit fix for #6118, ensure step IDs are only overridden when undefined
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: backport 1.7.x, pr/approved, pr/review-requested, size/s

#6238 chore: Add CircleCi job for integration tests
  .circleci/config.yml
Labels: pr/approved, size/s

#6245 user doc: Updates tutorial procedure for creating an api connector
  doc/tutorials/topics/p_amq2api-create-rest-api-connection.adoc
  doc/tutorials/topics/p_amq2api-create-rest-api-connector.adoc
Labels: backport 1.7.x, size/s

#6247 user doc: Updates to the integration guide to reflect React UI changes
  doc/connecting/topics/p_adding-amq-connection-finish.adoc
  doc/connecting/topics/p_adding-amq-connection-middle.adoc
  doc/connecting/topics/p_adding-amq-connection-start.adoc
  doc/connecting/topics/p_adding-amqp-connection-middle.adoc
  doc/connecting/topics/p_adding-amqp-connection-start.adoc
  doc/connecting/topics/p_adding-jira-connection-add-issue.adoc
  doc/connecting/topics/p_adding-jira-connection-update-issue.adoc
  doc/connecting/topics/p_adding-jira-connection-watchers.adoc
  doc/connecting/topics/p_create-amq-connection.adoc
  doc/connecting/topics/p_create-amqp-connection.adoc
  doc/integrating-applications/topics/as_creating-integrations.adoc
  doc/integrating-applications/topics/as_trigger-integration-with-timer.adoc
  doc/integrating-applications/topics/as_triggering-integrations-with-http-requests.adoc
  doc/integrating-applications/topics/c_about-adding-steps.adoc
  doc/integrating-applications/topics/c_about-integration-lifecycle-handling.adoc
  doc/integrating-applications/topics/p_add-advanced-filter-step.adoc
  doc/integrating-applications/topics/p_add-aggregate-step.adoc
  doc/integrating-applications/topics/p_add-basic-filter-step.adoc
  doc/integrating-applications/topics/p_add-custom-step.adoc
  doc/integrating-applications/topics/p_add-data-mapping-step.adoc
  doc/integrating-applications/topics/p_add-log-step.adoc
  doc/integrating-applications/topics/p_add-split-step.adoc
  doc/integrating-applications/topics/p_add-template-step.adoc
  doc/integrating-applications/topics/p_add-timer-connection.adoc
  doc/integrating-applications/topics/p_configure-publish-api-provider-quickstart.adoc
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
  doc/integrating-applications/topics/p_create-integration-operation-flows.adoc
  doc/integrating-applications/topics/p_create-timer-connection.adoc
  doc/integrating-applications/topics/p_create-webhook-connection.adoc
  doc/integrating-applications/topics/p_creating-api-connectors.adoc
  doc/integrating-applications/topics/p_deleting-api-connectors.adoc
  doc/integrating-applications/topics/p_deleting-extensions.adoc
  doc/integrating-applications/topics/p_general-procedure-for-obtaining-authorization.adoc
  doc/integrating-applications/topics/p_identify-where-data-mapping-is-needed.adoc
  doc/integrating-applications/topics/p_identifying-extension-use.adoc
  doc/integrating-applications/topics/p_importing-integrations.adoc
  doc/integrating-applications/topics/p_making-extensions-available.adoc
  doc/integrating-applications/topics/p_procedure-for-creating-an-integration.adoc
  doc/integrating-applications/topics/p_start-with-webhook-connection.adoc
  doc/integrating-applications/topics/p_starting-integrations.adoc
  doc/integrating-applications/topics/p_stopping-integrations.adoc
  doc/integrating-applications/topics/p_updating-api-connectors.adoc
  doc/integrating-applications/topics/p_updating-extensions.adoc
  doc/integrating-applications/topics/p_updating-integrations.adoc
  doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
  doc/integrating-applications/topics/p_viewing-integration-activity.adoc
  doc/integrating-applications/topics/p_viewing-integration-history.adoc
  doc/integrating-applications/topics/p_viewing-integration-metrics.adoc
  doc/integrating-applications/topics/r_example-processing-collection.adoc
  doc/integrating-applications/topics/r_find-data-field-you-want-to-map.adoc
  doc/integrating-applications/topics/r_how-to-specify-data-shapes.adoc
  doc/integrating-applications/topics/r_publishing-integrations.adoc
  doc/integrating-applications/topics/r_troubleshooting-integration-execution.adoc
  doc/integrating-applications/topics/r_viewing-and-editing-connection-information.adoc
Labels: backport 1.7.x, size/xl

#6250 chore: enable strict checksums for integration builds
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
Labels: cat/enhancement, pr/approved

#6258 fix: Make sure split data shape lookup adapts previous step
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
Labels: pr/approved

#6218 #6117 Last Processed shows the actual date when no messages were processed yet.
  app/ui-react/packages/api/src/WithIntegrationMetrics.tsx
  app/ui-react/packages/api/src/WithIntegrationsMetrics.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
Labels: pr/approved, size/XS

#6256 feat: #3422 Update of Syndesis CR or syndesis-global-config secret is now applied to the deployed resources.
  install/operator/build/conf/addons/syndesis-legacy-ui-serviceaccount.yml
  install/operator/build/conf/addons/syndesis-legacy-ui.yml
  install/operator/build/conf/template-config.yaml
  install/operator/cmd/manager/main.go
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/install/02-syndesis-secrets.yml.mustache
  install/operator/pkg/generator/assets/install/02-syndesis-service-accounts.yml.mustache
  install/operator/pkg/generator/assets/install/03-syndesis-ui.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-db.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/install/04-syndesis-oauth-proxy.yml.mustache
  install/operator/pkg/generator/assets/install/04-syndesis-server.yml.mustache
  install/operator/pkg/generator/assets/install/06-syndesis-prometheus.yml.mustache
  install/operator/pkg/generator/assets/install/07-syndesis-jaeger.yml.mustache
  install/operator/pkg/generator/assets/install/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/install/addon-legacyui.yml
  install/operator/pkg/generator/assets/install/addon-ops-api-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-camel-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets/install/addon-ops-db-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-home-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-integrations-home-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-integrations-jvm-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-integrations-service.yml
  install/operator/pkg/generator/assets/install/addon-ops-integrations-servicemonitor.yml
  install/operator/pkg/generator/assets/install/addon-ops-jvm-dashboard.yml
  install/operator/pkg/generator/assets/install/addon-ops-meta-alerting-rules.yml
  install/operator/pkg/generator/assets/install/addon-ops-server-alerting-rules.yml
  install/operator/pkg/generator/assets/install/addon-ops-servicemonitor.yml
  install/operator/pkg/generator/assets/route/route.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/addons/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/operation/utils.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/vendor/modules.txt
  install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/doc.go
Labels: pr/approved, pr/review-requested

#6261 Fix knative metadata retrieval logic on master
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataExtension.java
Labels: pr/approved

#6253 fix(basicfilter): rework condition set form UI
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
Labels: pr/approved, pr/review-requested, size/m

#6274 #5640 MongoDB connector first iteration
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoConfiguration.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoDBVerifier.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/verifier/mongodb3
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindyAllTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/application.properties.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application.properties
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#6288 user doc: Updates flagged by the translator
  doc/connecting/topics/p_adding-fhir-connection-read.adoc
  doc/connecting/topics/p_create-gmail-connection.adoc
  doc/connecting/topics/p_create-google-calendar-connection.adoc
  doc/connecting/topics/p_create-google-sheets-connection.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: size/s

#6249 fix: CircleCi integration-test config
  .circleci/config.yml
  app/test/integration-test/pom.xml
Labels: pr/review-requested, size/m

#6289 TTOOLS-715 Adapt to backend changes
  app/ui-react/packages/api/src/useViewEditorStates.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
Labels: pr/approved, pr/review-requested, size/s

#6262 TTOOLS-719 Convert view editor to tabbed display
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ViewEditContent.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/ViewEditorNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: pr/approved, pr/review-requested, size/xl
