Repository syndesisio/syndesis, pull requests merged in 2019-08, with the labels that each got.

#6241 chore: Update CircleCi config to use parallel connector jobs
  .circleci/config.yml
Labels: pr/approved, pr/review-requested, size/l

#6295 TTOOLS-725 Resolve invalid service call in DV
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested, size/XS

#6305 Fix #6281: Broken Integration grafana dashboard
  install/addons/syndesis-integration-dashboard.yml
Labels: pr/approved, pr/review-requested, size/m

#6312 user doc: Add info about body.body in unified json data shapes (fixes 6226)
  doc/integrating-applications/topics/p_add-advanced-filter-step.adoc
  doc/integrating-applications/topics/p_adding-conditional-execution-flows.adoc
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
Labels: backport 1.7.x, size/m

#6287 chore(cards): replace dashboard/connection pf3 cards/layout with pf4
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionsGrid.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionsGridCell.tsx
  app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.tsx
  app/ui-react/packages/ui/src/Dashboard/Dashboard.css
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/packages/ui/src/Dashboard/IntegrationBoard.tsx
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesCard.tsx
  app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
  app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/app/App.css
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/index.css
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/yarn.lock
Labels: group/ui, pr/approved, pr/review-requested, size/l

#6308 chore: fix hot-reload for the UI dev server
  app/ui-react/syndesis/src/setupProxy.js
Labels: ignore/qe, pr/approved, size/XS

#6320 user doc: Correct the description of Google Sheets, get values, Max results parameter
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
Labels: backport 1.7.x, size/s

#6324 user doc: Add info about behavior of Max results setting
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
Labels: backport 1.7.x, size/s

#6332 user doc: Localization updates required for translation
  doc/connecting/topics/as_connecting-to-rest-apis.adoc
  doc/connecting/topics/p_add-slack-connection-middle-finish.adoc
  doc/connecting/topics/p_adding-http-connections.adoc
  doc/connecting/topics/p_create-concur-connection.adoc
  doc/connecting/topics/p_create-database-connection.adoc
  doc/connecting/topics/p_creating-http-connections.adoc
  doc/connecting/topics/p_registering-with-rest-api.adoc
  doc/shared/p_create-sf-connection.adoc
Labels: size/s

#6337 fix: add connector-parent module to connector-support job
  .circleci/config.yml
Labels: pr/approved, size/XS

#6335 chore: Add some more tests and refactoring in autoform, re-order some stories
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/AutoFormHelpBlock.tsx
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/stories/Array.stories.tsx
  app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
  app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx
  app/ui-react/packages/auto-form/stories/StoryWrapper.tsx
  app/ui-react/packages/auto-form/tests/FormArrayComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormCheckboxComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormDurationComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormInputComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormSelectComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormTextAreaComponent.spec.tsx
Labels: pr/approved, pr/review-requested, size/XXL

#6325 Fix #6292 : exclude org.json:json from openshift-client
  app/pom.xml
Labels: pr/approved, pr/review-requested, size/s

#6346 Fetch ImageStreams tag from CR
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr_minimal.yaml
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster.yml
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/install_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/inspect.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/vendor/github.com/mcuadros/go-version/LICENSE
  install/operator/vendor/github.com/mcuadros/go-version/README.md
  install/operator/vendor/github.com/mcuadros/go-version/compare.go
  install/operator/vendor/github.com/mcuadros/go-version/constraint.go
  install/operator/vendor/github.com/mcuadros/go-version/doc.go
  install/operator/vendor/github.com/mcuadros/go-version/group.go
  install/operator/vendor/github.com/mcuadros/go-version/normalize.go
  install/operator/vendor/github.com/mcuadros/go-version/sort.go
  install/operator/vendor/github.com/mcuadros/go-version/stability.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/xl

#6343 Enable komodo addon in CR
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, size/XS

#6345 [operator] Fix datavirt installation
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/template/install.go
Labels: pr/approved, pr/review-requested, size/s

#6331 Final step doesn't show error in the activity log #4192
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
  app/server/logging/jsondb/src/test/resources/logs-controller-db.json
  app/server/logging/jsondb/src/test/resources/test-pod-x23x.txt
Labels: pr/approved

#6348 chore(tool): configure devImages: true
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, size/s

#6296 Fix #6185 - adding a local repo in custom settings
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/s2i/copy_mvn_repo.sh
  app/s2i/src/main/docker/Dockerfile
  app/s2i/src/main/resources/settings.xml
Labels: pr/approved, pr/review-requested, size/l

#6350 user doc: Another batch of updates for translation/localization
  doc/connecting/topics/c_about-parameter-placeholders-and-values.adoc
  doc/connecting/topics/p_add-slack-connection-middle-finish.adoc
  doc/connecting/topics/p_connecting-to-proprietary-databases.adoc
  doc/connecting/topics/p_creating-rest-api-connections.adoc
  doc/integrating-applications/topics/p_start-with-webhook-connection.adoc
  doc/integrating-applications/topics/r_guidelines-for-service-sending-requests.adoc
  doc/shared/p_create-twitter-connection.adoc
Labels: size/s

#6352 [chore] Add --nodev flag to syndesis minishift --install
  tools/bin/commands/minishift
Labels: pr/approved, pr/review-requested, size/XS

#6334 First cut at view output table toolbar
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewOutputToolbar.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
Labels: pr/approved, pr/review-requested, size/xl

#6355 Fixes view header display issue when navigating back and forth from view output tab to SQL tab
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContentSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContentSkeleton.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested, size/xl

#6359 fix #5493: SQL connector doesn't return generated IDs when added as start step
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlStartConnectorTest.java
Labels: pr/approved

#6322 Fixes for #6231 & #6315
  install/operator/.lib.sh
  install/operator/build.sh
  tools/bin/commands/build
  tools/bin/commands/tests/test-oc-version.sh
  tools/bin/commands/util/camel_k_funcs
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/maven_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested, size/xl

#6365 TTOOLS-696 Adapt to komodo updates
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useViewDefinition.tsx
  app/ui-react/packages/api/src/useViewDefinitionDescriptors.tsx
  app/ui-react/packages/api/src/useViewEditorStates.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/shared/ViewEditorNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/xl

#6349 chore: update form widgets to pf4; api provider return form definition and related enhancements
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/auto-form/src/AutoFormContext.tsx
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/packages/auto-form/src/models.ts
  app/ui-react/packages/auto-form/src/useFormBuilder.tsx
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/AutoFormHelpBlock.tsx
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/helpers.ts
  app/ui-react/packages/auto-form/src/widgets/index.ts
  app/ui-react/packages/auto-form/stories/Array.stories.tsx
  app/ui-react/packages/auto-form/stories/FormWrapper.tsx
  app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
  app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx
  app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
  app/ui-react/packages/auto-form/tests/FormCheckboxComponent.spec.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/Editor/shared/EditorPageCard.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
  app/ui-react/yarn.lock
Labels: pr/approved, pr/review-requested, size/XXL

#6351 fix(monitoring): "Top 5 by messages errors" panel doesn't show data
  install/operator/pkg/generator/assets/addons/ops/addon-ops-integrations-home-dashboard.yml
Labels: size/s

#6370 TEIIDTOOLS-726 Adapt to teiid backend changes
  app/ui-react/packages/api/src/useViewDefinition.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6367 fix(monitoring): Create Prometheus alerts for integration apps
  doc/managing_environments/topics/alerting_sop.adoc
  install/operator/pkg/generator/assets/addons/ops/addon-ops-integrations-alerting-rules.yml
  install/operator/pkg/generator/assets/addons/ops/addon-ops-integrations-camel-dashboard.yml
Labels: pr/approved, pr/review-requested

#6363 fix(6316): Removes acceptance criteria on template editor file upload
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
Labels: pr/approved, pr/review-requested, size/XS

#6369 5886 - Box icon in the integration summary not centered
  app/ui-react/syndesis/public/icons/box.png
Labels: pr/approved

#6366 chore(auto-form): update auto-form array layout
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/stories/Array.stories.tsx
  app/ui-react/packages/auto-form/stories/FormWrapper.tsx
  app/ui-react/yarn.lock
Labels: pr/approved, pr/review-requested, size/l

#6377 bump operator-sdk to v0.10.0
  install/operator/go.mod
Labels: size/XS

#6376 Move service accounts to service-account file
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-service-accounts.yml.mustache
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-service-accounts.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.mustache
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, pr/review-requested

#6374 TEIIDTOOLS-731 changing image name to syndesis-dv
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-teiid-komodo-server.yml.mustache
  install/generator/syndesis-template.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/addons/legacyui/addon-legacyui.yml
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
  install/syndesis.yml
Labels: pr/approved, size/m

#6383 fix: avoid undefined initial value
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
Labels: size/XS

#6386 feat: expand any extended properties into the property definition
  app/ui-react/packages/utils/src/autoformHelpers.ts
Labels: size/XS

#6387 Make the operator docker build more reliable by using the vendored dependencies.
  install/operator/.dockerignore
  install/operator/.gitignore
  install/operator/.lib.sh
Labels: pr/approved, size/s

#6388 Fix(TEIIDTOOLS-699) Fixes issues with inline edit of Virtualization descriptions
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContentSkeleton.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#6391 TEIIDTOOLS-726 adapt to change in teiid source path specification
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6394 fix(build): Make operator docker build work on fresh clone
  install/operator/.lib.sh
Labels: pr/approved, pr/review-requested, size/XS

#6395 fix(build): Further increase memory for craco build
  app/ui-react/syndesis/package.json
Labels: pr/approved, pr/review-requested, size/XS

#6385 feat: Update the CR with the default values more quickly than before.
  install/operator/pkg/syndesis/action/install.go
Labels: pr/approved, size/m

#6400 #6399: correcting the docker name reference for the sysdesis-dv
  install/operator/build/conf/config.yaml
Labels: pr/approved, pr/review-requested, size/XS

#6396 fix(basicfilter): rework UI for bordered sections and sticky top condition
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.css
Labels: pr/approved, pr/review-requested, size/m

#6404 feat: use the action descriptor in the integration definition for the API provider end connection
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: pr/approved, size/s

#6402 A few Operator fixes
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/util/errors.go
  install/operator/pkg/util/resources.go
Labels: size/m

#6408 fix: let dev mode also apply to the s2i image so that we can easily pick up local updates to it
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
Labels: size/XS

#6403 fix: [6068] Configuration required warnings for conditional flows steps
  app/connector/flow/src/main/resources/META-INF/syndesis/connector/flow.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/ChoiceMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
Labels: pr/approved, pr/review-requested

#6371 fix(core): overriding integration name
  app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationTest.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/integration/api/src/test/java/io/syndesis/integration/api/IntegrationResourceManagerTest.java
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/integration.json
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml
Labels: pr/review-requested

#6409 fix for #6318 Invoke stored procedure action dropdown is empty
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
  app/connector/sql/src/test/resources/sql/demo_add_metadata.json
Labels: pr/approved

#6397 fix: use the appropriate icons for an API provider integration
  app/ui-react/packages/ui/src/Integration/ApiProviderIcon.tsx
  app/ui-react/packages/ui/src/Integration/MultiFlowIcon.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailApiProviderSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: pr/approved, pr/review-requested, size/xl

#6407 TTOOLS-709 Addition of Preview component
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/shared/ViewEditorNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/review-requested, size/xl

#6358 #6344 - operation refinement and #6323 - meta exception
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoConfiguration.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoProducerOperation.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedCamelOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorNotSupportedSyndesisOperationTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
  app/meta/src/main/resources/application.yml
  app/server/cli/src/main/resources/application.yml
Labels: pr/review-requested

#6412 fix: Reintroduce Firefox login fix
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.mustache
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, pr/review-requested, size/s

#6415 feat: extract standardized errors from the flow and supply it to the error mapping form
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/auto-form/src/widgets/FormMapsetComponent.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, size/l

#6392 Add grant --user $USER --cluster to operator
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_operator.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/generator/assets/install/grant_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant_role.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/util/os.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/xl

#6419 fix(operator) Set the name on the s2i image stream
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/XS

#6421 fix(s2i): copy maven repo regression
  app/s2i/copy_mvn_repo.sh
Labels: pr/approved, pr/review-requested, size/XS

#6437 chore: don’t build camel-k. use camel-k build systems and instructions to develop/build camel-k. we should only build projects in this repo.
  tools/bin/commands/build
  tools/bin/commands/util/camel_k_funcs
Labels: pr/approved, size/l

#6442 ENTESB-11274 change image versions in operator for daily builds
  tools/bin/commands/release
Labels: pr/approved, pr/review-requested, size/s

#6446 fix: ensure api provider return page can still work with the old form definition
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: pr/approved, size/XS

#6447 fix: ensure the view updates when you click the move buttons
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
Labels: size/l

#6455 chore: enable incremental builds again using SNAPSHOT deployments to a git based mvn GitHub mvn repo. fixes #5632
  .circleci/config.yml
  app/pom.xml
Labels: size/l

#6459 fix: better fix for move buttons and some cleanup here and there
  app/ui-react/packages/auto-form/src/models.ts
  app/ui-react/packages/auto-form/src/useFormBuilder.tsx
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/packages/auto-form/stories/Array.stories.tsx
  app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/l

#6461 fix: concatenate validation text instead of replacing field help text
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/helpers.ts
  app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
Labels: size/m

#6420 chore: fix wrong tag error log in operator
  install/operator/pkg/syndesis/action/install.go
Labels: pr/approved, pr/review-requested, size/XS

#6422 add uninstall command
  install/operator/go.sum
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/operator.go
  install/operator/pkg/cmd/internal/uninstall/uninstall.go
  install/operator/pkg/cmd/internal/uninstall/uninstall_test.go
  install/operator/pkg/cmd/public.go
Labels: pr/approved, pr/review-requested, size/m

#6445 TEIIDTOOLS-751: correcting the link for modified backend
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
Labels: pr/approved, pr/review-requested, size/XS

#6411 TEIIDTOOLS-746 DdlEditor improvements
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#6476 Box - no property for fileName in upload action / remove spring-boot
  app/connector/box/pom.xml
  app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxUploadCustomizer.java
  app/connector/box/src/main/java/io/syndesis/connector/box/verifier/BoxVerifierAutoConfiguration.java
  app/connector/box/src/main/resources/META-INF/spring.factories
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
  app/connector/box/src/main/resources/META-INF/syndesis/connector/verifier/box
Labels: pr/approved

#6416 Fixes #3708 Allow the citizen integrator to choose how the integratio…
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationOverview.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/integration/IntegrationWithDomain.java
  app/server/controller/src/main/java/io/syndesis/server/controller/ControllersConfigurationProperties.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/ControllersConfigurationPropertiesTest.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/online/customizer/ExposureDeploymentDataCustomizerTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
  app/server/openshift/pom.xml
  app/server/openshift/src/main/java/io/syndesis/server/openshift/ExposureHelper.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfiguration.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
  app/test/test-support/src/main/java/io/syndesis/test/integration/project/CamelKProjectBuilder.java
  app/ui-react/packages/models/swagger.internal.json
  app/ui-react/packages/models/swagger.json
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationExposeVia.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  doc/integrating-applications/topics/p_configure-publish-api-provider-quickstart.adoc
  doc/integrating-applications/topics/p_create-integration-operation-flows.adoc
  install/generator/01-header.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-teiid-komodo-server.yml.mustache
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/template/install.go
  install/syndesis.yml
Labels: pr/approved, pr/review-requested
