Repository syndesisio/syndesis, pull requests merged in 2019-03, with the labels that each got.

#4689 chore(ui): upgrade bootstrap to ~3.4
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4709 chore(operator, syndesis): Fixed permissions for operator setup
  install/operator/deploy/syndesis-operator.yml
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved

#4712 Fixes #4711 FHIR connector fixes for field ordering, collections and …
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/FhirMetadataRetrieval.java
  app/connector/fhir/src/main/java/io/syndesis/connector/fhir/customizer/FhirTransactionCustomizer.java
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/fhir/src/main/resources/META-INF/syndesis/schemas/dstu3/fhir-base-template.xml
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirTransactionTest.java
Labels: pr/approved

#4695 fix(overrides): remove glyphicon from overrides
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#4699 chore(#4693): sync up odata forked code with 2.x branch of upstream
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Index.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
Labels: pr/review-requested

#4720 fix(#4459): Add names to java data shapes
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
  app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json
Labels: pr/approved, pr/review-requested

#4706 fix: Google sheets chart target position
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizer.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddChartCustomizerTest.java
Labels: pr/approved, pr/review-requested

#4727 chore(version): Update camel to version 2.21.0.fuse-730054
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#4715 fix: Ensure consistent split/aggregate steps in UI
  app/ui/src/app/store/step/step.store.ts
Labels: pr/approved, pr/review-requested

#4725 Install db-metrics as sidecar
  install/addons/syndesis-db-dashboard.yml
  install/addons/syndesis-db-prometheus-rule.yml
  install/addons/syndesis-db-servicemonitor.yml
  install/generator/04-syndesis-db-metrics.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#4694 fix(card-tech-preview): change container to body to prevent popover from being cut off
  app/ui/src/app/common/card-tech-preview.component.ts
Labels: pr/approved

#4730 fix: SQL connector failsafe query parameter read from body
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/JSONBeanUtilTest.java
Labels: pr/approved, pr/review-requested

#4739 Fix #4717: constrain permissions needed by the operator
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#4729 fix: Missing Json instance inspection for basic filter options
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonInstanceInspector.java
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonSchemaInspector.java
  app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonInstanceInspectorTest.java
  app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonSchemaInspectorTest.java
Labels: pr/approved

#4750 fix: add quartz2 dependency for timer connector
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
Labels: pr/approved

#4748 Fixes #4747, added current integration deployment state in state endpoint result
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: pr/approved

#4757 fix(#4756): Make UI honour default values for checkboxes
  app/ui/src/app/core/providers/form-factory-provider.service.ts
Labels: pr/approved, pr/review-requested

#4754 fix(monitoring): Syndesis DB Grafana dashboard should be resilient to pod restarts
  install/addons/syndesis-db-dashboard.yml
Labels: pr/approved, pr/review-requested

#4761 fix: google sheets connector icon
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  ux/connections_icons/svg/connectionicons_googlesheets.svg
  ux/connections_icons/svg/optimized/connectionicons_googlesheets.svg
Labels: pr/approved

#4770 fix (#4768): add start connection not working
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#4759 fix: Filter step inside split/aggregate
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerJsonTest.java
  app/integration/runtime/src/test/resources/syndesis/integration/filter-after-split.json
  app/integration/runtime/src/test/resources/syndesis/integration/filter-in-split.json
  app/integration/runtime/src/test/resources/syndesis/integration/inconsistent-split.json
  app/integration/runtime/src/test/resources/syndesis/integration/integration.json
  app/integration/runtime/src/test/resources/syndesis/integration/multiple-split.json
  app/integration/runtime/src/test/resources/syndesis/integration/nested-split.json
  app/integration/runtime/src/test/resources/syndesis/integration/split-aggregate.json
  app/integration/runtime/src/test/resources/syndesis/integration/split-chain.json
  app/integration/runtime/src/test/resources/syndesis/integration/split-to-end.json
  app/integration/runtime/src/test/resources/syndesis/integration/subsequent-split.json
Labels: pr/approved, pr/review-requested

#4774 improve fix (#4768): add start connection broken
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#4782 fix: Set proper data shape variant metadata for split/aggregate
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
Labels: pr/approved, pr/review-requested

#4779 Fixes #4385 Adding technical preview flags for odata and fhir
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
Labels: pr/approved

#4783 Fixes #4755, avoid adding duplicate tag names
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/integration/list/tag-cicd-modal.component.html
Labels: pr/approved, pr/review-requested

#4784 fix(#4758): Fix use of certificate option in odata connector
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataConstants.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataCreateTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataTestServer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-3.json
Labels: pr/approved, pr/review-requested

#4787 fix: Make sure to keep original data shape variants on metadata lookup
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
Labels: pr/approved, pr/review-requested

#4786 Fix #4781: fix bug in upgrade completion
  install/operator/pkg/syndesis/operation/attach.go
Labels: pr/approved

#4780 fix(monitoring): Fix FuseOnlineDatabaseInstanceDown alert rule
  doc/managing_environments/topics/alerting_sop.adoc
  install/addons/syndesis-db-prometheus-rule.yml
Labels: pr/approved, pr/review-requested

#4805 Fix ordering of FHIR action properties
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
Labels: pr/approved

#4812 fix: offline XML Schema validation
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/LocalResolver.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/resources/xsd/2001/XMLSchema.xsd
  app/server/api-generator/src/test/resources/xsd/2001/xml.xsd
  app/server/api-generator/src/test/resources/xsd/XMLSchema.dtd
  app/server/api-generator/src/test/resources/xsd/datatypes.dtd
Labels: pr/approved

#4798 Fixes #4702: Fixed public api proxy serviceaccount clusterrolebinding namespace
  install/support/syndesis-public-oauth-proxy.yml
Labels: pr/approved

#4815 fix: #4811 SQL DELETE as start connection not working
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
Labels: pr/approved

#4776 Graceful GOPATH checks
  tools/bin/commands/build
  tools/bin/syndesis
Labels: pr/approved

#4823 fix: force bootstrap-select version to 1.13.6
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4719 fix(#4718): Validate connector json files
  app/connector/support/maven-plugin/pom.xml
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/connector/support/maven-plugin/src/main/resources/connector-schema.json
  app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java
  app/connector/support/maven-plugin/src/test/resources/my-invalid-connector.json
  app/connector/support/maven-plugin/src/test/resources/my-test-connector.json
  app/connector/support/maven-plugin/src/test/resources/my-unformed-connector.json
Labels: pr/approved, pr/review-requested

#4832 Fixes #4789, fixed deployment status check before stopping integration
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: cat/bug

#4839 [camel k] cannot find atlas component
  app/integration/runtime-camelk/pom.xml
Labels: pr/approved

#4810 fix(#4802) remove ng2-codemirror/node_modules during build
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4844 backport #4437
  app/ui/src/app/common/button.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.ts
Labels: pr/approved

#4841 [camel k] cannot find atlas component #4834
  app/integration/runtime-camelk/pom.xml
Labels: pr/approved

#4847 Issue 4833 odata metadata ret
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
Labels: pr/approved, pr/review-requested

#4851 AtlasMap is unable to find mapping #4846
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
Labels: pr/approved

#4853 fix: suppress empty backend call to avoid HTTP 400
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#4837 Fixes #4789, fixes #4800 on 1.6.x
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: cat/bug, pr/1.6.x, pr/approved, pr/review-requested

#4861 chore: Enable debug logging for Google Sheets
  app/connector/google-sheets/src/test/resources/logback-test.xml
Labels: pr/approved, pr/review-requested

#4869 fix: Maven repository consistency
  app/extension/bom/pom.xml
  app/extension/example/log-step/pom.xml
  app/extension/example/simple-action-step/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/settings.xml
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorHelperTest.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/integration/runtime-camelk/readme.adoc
  app/pom.xml
  app/s2i/pom.xml
  app/s2i/src/main/resources/settings.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/DeploymentDescriptorIT.java
  app/server/runtime/pom.xml
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis-privileged.yml
Labels: pr/approved

#4860 Fixes #4790, added validation of tag names to avoid creating invalid tags
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved, pr/review-requested

#4859 fix(dropdowns): fix the user/help dropdown toggles
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.ts
  app/ui/src/scss/utils/_overrides.scss
Labels: group/ui, pr/approved, pr/review-requested

#4880 user doc: One small change that is needed downstream
  doc/shared/p_register-with-sf.adoc
Labels: pr/needs-backport

#4882 user doc: Updates for downstream directory reorg - 3
  doc/connecting/topics/images/SF-message-to-wait-a-few-minutes.png
  doc/shared/p_register-with-sf.adoc
Labels: pr/needs-backport

#4884 Fixes #4789, fixed public API deployment search when stopping integrations
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved, pr/review-requested

#4887 Fusedoc 2988 apiprovider u iupdates
  doc/integrating-applications/topics/as_trigger-integrations-with-api-calls.adoc
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
  doc/integrating-applications/topics/p_create-integration-operation-flows.adoc
  doc/integrating-applications/topics/r_requirements-for-api-provider-integrations.adoc
Labels: pr/needs-backport

#4855 Fixes #4854 and #4462. Provides better OpenShift 4 compatibility.
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
Labels: pr/approved, pr/review-requested

#4856 Fixes #4854 and #4462. Provides better OpenShift 4 compatibility.
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
Labels: pr/1.6.x, pr/approved, pr/review-requested

#4872 fix: ensure the flow page service state is set properly and some refinements (1.6.x)
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/edit-page.models.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
Labels: pr/1.6.x, pr/approved

#4881 fix: tidy up a bit and ensure the aggregate step properly gets the subsequent data shape
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4892 Backporting to 1.6.x: Added test for multiple deployments
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved, pr/review-requested

#4883 Fixes #4789, fixed public API deployment search when stopping integrations
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4893 fix: tidy up a bit and ensure the aggregate step properly gets the subsequent data shape (1.6.x
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/step-configure/templater/templater.component.ts
Labels: pr/1.6.x, pr/approved

#4858 chore: Add syndesis build script option to only build Maven submodules
  doc/sdh/cli/cmd_build.adoc
  tools/bin/commands/build
  tools/bin/commands/util/maven_funcs
Labels: pr/approved, pr/review-requested

#4852 fix(#4848): Odata Connector to handle more complex predicates
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax-location.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax.json
Labels: pr/approved

#4894 Fix for #4182 Insertion to DB inserts empty strings when a step with …
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
Labels: pr/approved

#4896 chore(syndesis): Some cleanup + updated standalone script
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved

#4909 chore(install-syndesis): Update documentation for --camel-k options
  tools/bin/install-syndesis
Labels: pr/approved

#4886 backport fix(#4833): modify odata out-data-shape if using split
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
Labels: pr/1.6.x, pr/review-requested

#4915 fix: Partial revert of 53d5aadc2bc5f999fd6c08cd1fd92bf50237068b
  app/s2i/src/main/resources/settings.xml
Labels: pr/approved, pr/review-requested

#4921 Fusedoc 3002 collections
  doc/connecting/topics/p_add-kudu-connection-add-records.adoc
  doc/integrating-applications/topics/c_about-processing-collections.adoc
  doc/integrating-applications/topics/c_workflow-api-providers.adoc
  doc/integrating-applications/topics/p_add-aggregate-step.adoc
  doc/integrating-applications/topics/p_add-split-step.adoc
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
  doc/integrating-applications/topics/p_create-integration-operation-flows.adoc
  doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
  doc/integrating-applications/topics/r_example-processing-collection.adoc
  doc/integrating-applications/topics/r_requirements-for-api-provider-integrations.adoc
  doc/tutorials/topics/p_sf2db-choose-finish.adoc
  doc/tutorials/topics/p_t2sf-choose-start.adoc
Labels: pr/needs-backport

#4891 refactor: cleanup OpenShiftConfigurationProperties
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4922 fix: Update version number in dictionary
  app/ui/src/assets/dictionary/en-GB.json
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4918 fix: bring the user back to the regular editor if cancel is clicked
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.ts
Labels: pr/approved

#4917 fix: only try and refresh data shapes for dynamic actions
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#4928 Some runtime fixes for 1.6.x
  app/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/CamelKIntegrationCustomizer.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/TemplatingCamelKIntegrationCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/syndesis-template.go
  install/syndesis.yml
Labels: pr/approved

#4929 fix: #4905 #4879 Data shapes for aggregate step mixed up
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved

#4930 Add default SA for DeploymentConfigs that don't have one
  install/generator/02-syndesis-service-accounts.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4936 refactor: remove tech preview tag for API provider
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
Labels: pr/approved, pr/needs-backport

#4927 Some runtime fixes
  app/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/CamelKIntegrationCustomizer.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/TemplatingCamelKIntegrationCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/syndesis-template.go
  install/syndesis.yml
Labels: pr/approved

#4932 fix: #4905 #4879 Data shapes for aggregate step mixed up
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/1.6.x, pr/approved

#4940 fix: #4933 Error in UI when adding connections not providing any tags
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4946 fix: prevent the user from moving on until a mapping file is produced
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
  app/ui/src/app/integration/edit-page/edit-page.models.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/approved, pr/needs-backport

#4947 Fix #4781: fix upgrade termination
  install/operator/pkg/controller/syndesis/syndesis_controller.go
Labels: pr/approved

#4948 Fix #4781: fix upgrade termination
  install/operator/pkg/controller/syndesis/syndesis_controller.go
Labels: pr/approved

#4950 Remove duplicate service accounts
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4952 fix(styles): ensure main page section container applies correct bg color
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4957 fix(masthead): remove masthead bg image
  app/ui/src/app/app.component.html
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#4949 fix: prevent the user from moving on until a mapping file is produced (1.6.x)
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
  app/ui/src/app/integration/edit-page/edit-page.models.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/1.6.x, pr/approved

#4954 fix(styles): ensure main page section container applies correct bg color
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/1.6.x, pr/approved, pr/review-requested

#4958 fix(masthead): remove masthead bg image
  app/ui/src/app/app.component.html
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#4963 Link pull image secret to service accounts
  install/operator/deploy/role.yaml
  install/operator/pkg/syndesis/action/install.go
  install/operator/syndesis-privileged.yml
  install/operator/syndesis.yml
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4964 Add default SA for DeploymentConfigs that dont have one
  install/generator/02-syndesis-service-accounts.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/needs-backport

#4956 fix: hide the log connection in favor of the log step
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/connection/connection.store.ts
  app/ui/src/app/store/connector/connector.store.ts
Labels: pr/approved

#4968 refactor(monitoring): Use targetPort instead of port for Prometheus ServiceMonitor resources
  install/addons/syndesis-db-servicemonitor.yml
  install/addons/syndesis-meta-servicemonitor.yml
  install/addons/syndesis-server-servicemonitor.yml
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#4962 fix: #4879 Data shape meta lookup (split/aggregate) for user defined specs
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
Labels: pr/approved, pr/needs-backport

#4972 fix: #4879 Data shape meta lookup (split/aggregate) for user defined specs
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
Labels: pr/1.6.x, pr/approved

#4970 Fix #4966: prepend a i- to the integration name
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/BaseCamelKHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKUnpublishHandler.java
Labels: pr/approved

#4973 fix: hide the log connection in favor of the log step; fixes issue-4935
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/app/store/connection/connection.store.ts
  app/ui/src/app/store/connector/connector.store.ts
Labels: pr/1.6.x, pr/approved

#4971 fix: #4969 Handle aggregate step when no input data shape is provided
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4979 fix: don't trigger data shape reconciliation when the mapper initializes
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved

#4959 Lib alignment errors in Camel K mode
  app/integration/bom-camel-k/pom.xml
  app/integration/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4980 Lib alignment errors in Camel K mode #4926
  app/integration/bom-camel-k/pom.xml
  app/integration/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
Labels: pr/1.6.x, pr/approved, pr/review-requested

#4975 fix: #4167 Integration Details History - old version's 'last publishe…
  app/pom.xml
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandlerTest.java
  app/ui/src/app/integration/integration_detail/integration_history/integration-history.component.html
Labels: pr/approved, pr/review-requested

#4955 fix(#4889): Redo input DataShape of OData Delete
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataDeleteCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
Labels: pr/approved, pr/review-requested

#4985 Fix #4966: prepend a i- to the integration name
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/BaseCamelKHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKUnpublishHandler.java
Labels: pr/1.6.x, pr/approved

#4983 fix: #4969 Handle aggregate step when no input data shape is provided
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/1.6.x

#4974 Link pull image secret to service accounts (1.6.x backport)
  install/operator/deploy/role.yaml
  install/operator/pkg/syndesis/action/install.go
  install/operator/syndesis-privileged.yml
  install/operator/syndesis.yml
Labels: pr/1.6.x

#4987 fix(#4889): Redo input DataShape of OData Delete
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataDeleteCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
Labels: pr/1.6.x

#4988 Image pull secret link / mount fixes
  install/operator/pkg/syndesis/action/install.go
Labels: pr/approved, pr/needs-backport, pr/review-requested

#4990 feat: add OpenAPI validation that at least one path and operation are given
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRulesTest.java
Labels: pr/needs-backport

#4993 (Test) Update README.md
  README.md
Labels: backport 1.6.x

#4999 fix: #4994 Fix data mapping when split option on GoogleSheets is enabled
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesSplitResultsCustomizerTest.java
Labels: pr/approved, pr/needs-backport

#5008 fix: #4997 Apply max results option to all value range results
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConfiguration.java
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/stream/GoogleSheetsStreamConsumer.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/main/resources/org/apache/camel/catalog/components/google-sheets-stream.json
Labels: pr/approved, pr/review-requested

#5012 Fixes #4981, undelete existing extensions from an import that have Deleted status
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5011 fix: Call saveCurrentMapping() in atlasmap mapping service from the d…
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved, pr/needs-backport, pr/review-requested

#5023 Unable to use fetches a record from Salesforce by external id
  app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/SalesforceIdentifier.java
  app/connector/salesforce/src/main/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizer.java
  app/connector/salesforce/src/test/java/io/syndesis/connector/salesforce/customizer/DataShapeCustomizerTest.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5020 fix: #5016 Support predicates in combination with parameters in SQL select
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementParser.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorInputParamTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlStartConnectorTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/util/SqlConnectorTestSupport.java
Labels: backport 1.6.x, pr/approved, pr/needs-backport, pr/review-requested

#5030 Image secret link / mount operator improvements
  install/operator/pkg/syndesis/action/install.go
Labels: backport 1.6.x

#5035 fix: Data Mapper Transformation is unexpectedly duplicated
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: backport 1.6.x, pr/approved, pr/needs-backport

#5025 feat: add a 'ui' command to 'syndesis'
  app/ui/package.json
  app/ui/proxy.conf.js
  app/ui/scripts/get-login-cookie.js
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/connections/list-page/list-page.component.spec.ts
  app/ui/src/app/connections/list/list.component.spec.ts
  app/ui/src/app/dashboard/dashboard.component.spec.ts
  app/ui/src/app/dashboard/dashboard_metrics/dashboard-metrics.component.spec.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.spec.ts
  app/ui/src/app/integration/edit-page/current-flow.service.spec.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.spec.ts
  app/ui/src/app/store/entity/events.service.spec.ts
  app/ui/src/config.json.staging
  app/ui/yarn.lock
  doc/sdh/cli/cmd_ui.adoc
  tools/bin/commands/ui
Labels: pr/approved, pr/review-requested

#5028 feature(update): Update service accounts if not existing
  tools/upgrade/migration/resource/REDME.adoc
  tools/upgrade/migration/resource/any/03_ensure_service_account_setup.sh
Labels: backport 1.6.x, pr/approved

#5034 fix: #5017 Enable split step to handle unified Json body
  app/common/model/src/main/java/io/syndesis/common/model/DataShape.java
  app/common/model/src/main/java/io/syndesis/common/model/DataShapeMetaData.java
  app/common/model/src/test/java/io/syndesis/common/model/DataShapeBuilderTest.java
  app/common/util/src/main/java/io/syndesis/common/util/json/JsonUtils.java
  app/common/util/src/test/java/io/syndesis/common/util/json/JsonUtilsTest.java
  app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-unified-schema.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-unified-schema.json
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonInstanceInspector.java
  doc/connecting/topics/r_about-json-schema-for-http-requests.adoc
Labels: backport 1.6.x, pr/needs-backport

#5041 Backport 5034 on 1.6.x
  app/common/model/src/main/java/io/syndesis/common/model/DataShape.java
  app/common/model/src/main/java/io/syndesis/common/model/DataShapeMetaData.java
  app/common/model/src/test/java/io/syndesis/common/model/DataShapeBuilderTest.java
  app/common/util/src/main/java/io/syndesis/common/util/json/JsonUtils.java
  app/common/util/src/test/java/io/syndesis/common/util/json/JsonUtilsTest.java
  app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGenerator.java
  app/server/api-generator/src/test/resources/swagger/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-unified-schema.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-unified-schema.json
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonInstanceInspector.java
  doc/connecting/topics/r_about-json-schema-for-http-requests.adoc
Labels: pr/1.6.x

#5044 user doc: Add description of known issue
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
Labels: backport 1.6.x

#5049 chore(bgcolor): update header bg color to path latest pf4
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/needs-backport, pr/review-requested

#5051 user doc: Add troubleshooting topic to data mapper doc
  doc/integrating-applications/topics/as_mapping-data.adoc
  doc/integrating-applications/topics/p_identify-where-data-mapping-is-needed.adoc
  doc/integrating-applications/topics/r_troubleshooting-data-mapping.adoc
Labels: backport 1.6.x

#5048 fix: proper model generation for arrays of integers
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/TestHelper.java
  app/server/api-generator/src/test/resources/swagger/machine_history.swagger.json
  app/server/api-generator/src/test/resources/swagger/machine_history.unified_connector.json
Labels: backport 1.6.x

#5055 Update default camel-k version to 0.3.2
  tools/bin/commands/util/camel_k_funcs
Labels: backport 1.6.x, pr/approved

#5058 user doc: Updates to workflow diagrams for creating integrations
  doc/integrating-applications/topics/c_workflow-api-providers.adoc
  doc/integrating-applications/topics/images/ApiProviderCreateIntegrationWorkflow.png
  doc/integrating-applications/topics/images/general-workflow.png
Labels: backport 1.6.x

#5061 [Camel-K] Fix path to generated camel catalog
  app/integration/runtime-camelk/readme.adoc
Labels: pr/approved

#5062 fix: Multiple DataBuckets not accessible, source does not exist #5042
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5066 Manual Backport #5062 on 1.6.x:
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
Labels: pr/approved

#5069 user doc: Removed instruction about phantom filter
  doc/tutorials/topics/images/SF-message-to-wait-a-few-minutes.png
  doc/tutorials/topics/p_amq2api-confirm-works.adoc
Labels: backport 1.6.x

#5071 user doc: Removed phantom filter instruction from other two tutorials
  doc/tutorials/topics/p_sf2db-confirm-works.adoc
  doc/tutorials/topics/p_t2sf-confirm-working.adoc
Labels: backport 1.6.x

#5073 chore: removing dmp version
  app/pom.xml
Labels: pr/approved

#5074 chore: upgrade Spring Boot to 1.5.17.RELEASE
  app/pom.xml
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5080 fix: set the product logo wider
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.scss
Labels: pr/needs-backport

#5082 [README] Rename from REDME to README
  tools/upgrade/migration/resource/README.adoc
Labels: pr/approved, pr/review-requested

#5081 fix: set the product logo wider (1.6.x)
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.scss
Labels: pr/approved

#5085 rolling back spring-boot version to 1.5.16.RELEASE
  app/pom.xml
Labels: pr/approved

#5089 chore: Ensure spring security oauth2 2.0.16
  app/connector/google-sheets/pom.xml
Labels: pr/approved, pr/review-requested

#5083 [Upgrade] Add migration script for updating the s2i is tag
  tools/upgrade/migration/resource/1.3/01_server_config_map_upgrade.sh
Labels: pr/approved, pr/review-requested

#5087 fix: #5017 Open api formats to be compliant with json schema
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/UnifiedJsonDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/JsonSchemaHelper.java
  app/server/api-generator/src/test/resources/swagger/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/swagger/todo.unified_connector.json
Labels: backport 1.6.x, pr/approved, pr/needs-backport, pr/review-requested
