Repository syndesisio/syndesis, pull requests merged in 2019-05, with the labels that each got.

#5294 bug: Fixes #5290 Integrations do not start because ClassNotFoundException: io.opentracing.NoopTracer
  app/common/jaeger-spring-boot-starter/pom.xml
  app/integration/runtime-springboot/pom.xml
Labels: pr/approved

#5291 fix(odata): regression error on metadata retrieval
  app/connector/odata/src/main/resources/META-INF/services/org/apache/camel/component/olingo4
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/meta/odata
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
Labels: pr/approved, pr/review-requested

#5300 Fix #5298: Camel-k-bom should reference 1.6-SNAPSHOT
  app/integration/bom-camel-k/pom.xml
Labels: pr/approved

#5305 user doc: Remove incorrect config options for AMQP request/response
  doc/connecting/topics/p_adding-amqp-connection-middle.adoc
Labels: backport 1.6.x

#5315 user doc: Updates amqp connector doc for request-response action in finish connection
  doc/connecting/topics/as_connecting-to-amqp.adoc
  doc/connecting/topics/p_adding-amq-connection-finish.adoc
  doc/connecting/topics/p_adding-amq-connection-middle.adoc
  doc/connecting/topics/p_adding-amq-connection-start.adoc
  doc/connecting/topics/p_adding-amqp-connection-finish.adoc
  doc/connecting/topics/p_adding-amqp-connection-middle.adoc
  doc/connecting/topics/p_adding-amqp-connection-start.adoc
Labels: backport 1.6.x

#5329 feat(4986): Adds a generic email connector - IMAP(s)/POP3(s)/SMTP(s)
  app/connector/email/pom.xml
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailUtil.java
  app/connector/email/src/main/java/io/syndesis/connector/email/component/EMailComponent.java
  app/connector/email/src/main/java/io/syndesis/connector/email/component/EMailComponentFactory.java
  app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailReceiveCustomizer.java
  app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailSendCustomizer.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataRetrieval.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetadata.java
  app/connector/email/src/main/java/io/syndesis/connector/email/model/EMailMessageModel.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/EMailVerifier.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/EMailVerifierExtension.java
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/meta/email-receive
  app/connector/email/src/main/resources/META-INF/syndesis/connector/meta/email-send
  app/connector/email/src/main/resources/META-INF/syndesis/connector/verifier/email-receive
  app/connector/email/src/main/resources/META-INF/syndesis/connector/verifier/email-send
  app/connector/email/src/main/resources/org/apache/camel/catalog/components/email-receive.json
  app/connector/email/src/main/resources/org/apache/camel/catalog/components/email-send.json
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/consumer/EMailReadRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/meta/EMailMetaDataTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/producer/EMailSendRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/server/EMailTestServer.java
  app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataCreateTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/CertificateUtil.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/KeyStoreHelper.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/PropertyBuilder.java
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
  app/meta/pom.xml
  app/pom.xml
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
Labels: pr/approved, pr/review-requested

#5334 chore: Resolve comments outlined in PR #5329
  app/connector/email/pom.xml
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailUtil.java
  app/connector/email/src/main/java/io/syndesis/connector/email/component/EMailComponent.java
  app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailReceiveCustomizer.java
  app/connector/email/src/main/java/io/syndesis/connector/email/customizer/EMailSendCustomizer.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataExtension.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetaDataRetrieval.java
  app/connector/email/src/main/java/io/syndesis/connector/email/meta/EMailMetadata.java
  app/connector/email/src/main/java/io/syndesis/connector/email/model/EMailMessageModel.java
  app/connector/email/src/main/java/io/syndesis/connector/email/verifier/EMailVerifierExtension.java
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEMailTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/consumer/EMailReadRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/meta/EMailMetaDataTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/producer/EMailSendRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/server/EMailTestServer.java
  app/connector/email/src/test/java/io/syndesis/connector/email/verifier/EMailVerifierTest.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/CertificateUtil.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/KeyStoreHelper.java
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
Labels: pr/approved

#5335 chore: upgrade (Fuse) Camel to 2.21.0.fuse-740010
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#5246 fix: properly handle extensions change events
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/usage/UsageUpdateHandler.java
Labels: pr/wip

#5336 refactor(aws-sqs): [SQS] Use nullDeduplicationStrategy by default
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
Labels: pr/approved

#5339 [feat] UI flow navigation
  app/connector/flow/src/main/resources/META-INF/syndesis/connector/flow.json
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.ts
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.scss
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
Labels: group/ui, pr/approved, pr/review-requested

#5342 [feat] UI add flow indicator
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
Labels: group/ui, pr/approved

#5346 [fix] google-calendar adapter meta data retrieval lookup
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/meta/google-calendar
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/verifier/google-calendar
Labels: pr/approved

#5356 feature(aws-sns): Create an AWS-SNS connector
  app/connector/aws-sns/pom.xml
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSMessageCustomizer.java
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSVerifier.java
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/AWSSNSVerifierExtension.java
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/SNSMessage.java
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/verifier/aws-sns
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#5357 refactor(aws-sqs): Added the toString method to SQSMessage class
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/SQSMessage.java
Labels: pr/approved

#5353 fix(5249): Updates email connector icons
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
  ux/connections_icons/png/connectionicons_emailreceive.png
  ux/connections_icons/png/connectionicons_emailsend.png
  ux/connections_icons/svg/connectionicons_emailreceive.svg
  ux/connections_icons/svg/connectionicons_emailsend.svg
  ux/connections_icons/svg/mapping.json
  ux/connections_icons/svg/optimized/connectionicons_emailreceive.svg
  ux/connections_icons/svg/optimized/connectionicons_emailsend.svg
Labels: pr/approved, pr/review-requested

#5363 [SQS] Fix label hints on the SQS poll action
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
Labels: pr/approved, pr/review-requested

#5368 refactor(aws-sns): Added the toString method to SNSMessage class
  app/connector/aws-sns/src/main/java/io/syndesis/connector/aws/sns/SNSMessage.java
Labels: pr/approved

#5367 [closes #5364] Skip invoking migration script for current version
  app/server/cli/src/main/java/io/syndesis/server/cli/command/migrate/MigrateCommand.java
Labels: pr/approved, pr/review-requested

#5370 [Connectors] Polish connector descriptions
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
  app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/servicenow/src/main/resources/META-INF/syndesis/connector/servicenow.json
  app/connector/sftp/src/main/resources/META-INF/syndesis/connector/sftp.json
Labels: pr/approved

#5345 Knative connector: initial implementation
  app/connector/knative/pom.xml
  app/connector/knative/src/main/java/io/syndesis/connector/knative/KnativeComponentProxyFactory.java
  app/connector/knative/src/main/resources/META-INF/syndesis/connector/knative.json
  app/connector/knative/src/test/java/io/syndesis/connector/knative/KnativeComponentFactoryTest.java
  app/connector/knative/src/test/resources/logback-test.xml
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/SourceProvider.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/meta/pom.xml
  app/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/KnativeCamelKIntegrationCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java
Labels: pr/approved, pr/review-requested

#5375 Fixes #5214 Save integration when adding CBR
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.ts
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
Labels: pr/approved, pr/review-requested

#5374 fix: avoid creating request loop
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved, pr/review-requested

#5372 refactor: rename parameter to apiKey
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizer.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/AuthenticationType.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/auth/apikey/ApiKey.java
  app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/AuthenticationCustomizerTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
Labels: pr/approved

#5381 Fixes #5333 FHIR actions - increase multiselect field height
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
Labels: pr/approved

#5387 chore(aws-sqs,aws-sns): Added aws-sns and aws-sqs icon and updated js…
  app/connector/aws-sns/src/main/resources/META-INF/syndesis/connector/aws-sns.json
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/flow/src/main/resources/META-INF/syndesis/connector/flow.json
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/knative/src/main/resources/META-INF/syndesis/connector/knative.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/ui/src/assets/icons/steps/aggregate.svg
  app/ui/src/assets/icons/steps/split.svg
  ux/connections_icons/svg/connectionicons_sns.svg
  ux/connections_icons/svg/connectionicons_sqs.svg
  ux/connections_icons/svg/mapping.json
Labels: pr/approved, pr/review-requested

#5393 fix(server): NPE if no OAuth scopes defined in OpenAPI specification
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/PropertyGenerators.java
Labels: pr/approved

#5380 [feat] Enable multi flow activity logging
  app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/integration.json
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/logging/IntegrationLoggingAutoConfiguration.java
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/logging/IntegrationLoggingCamelContextConfiguration.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/ActivityTrackingPolicyFactory.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTracker.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/FlowActivityTrackingPolicy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/FlowActivityTrackingPolicyFactory.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationActivityTrackingPolicy.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationActivityTrackingPolicyFactory.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/IntegrationLoggingListener.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SimpleEndpointStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitAggregateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java
  app/integration/runtime/src/test/resources/syndesis/integration/multi-flow-integration.json
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/review-requested

#5395 [fix] Avoid duplicate activity log entries
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/ActivityLoggingWithSplitTest.java
Labels: pr/approved, pr/review-requested

#5397 fix(ui): skip over connections that do not have the embedded connector property
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#5413 Fix 5223: [camel-k] support api client
  app/integration/runtime-camelk/readme.adoc
Labels: pr/approved

#5414 fix #5394: camel-k: simple integrations without a web part have a sta…
  app/integration/runtime/pom.xml
Labels: pr/approved

#5376 Fix #5343: add knative feature toggle (disabled by default)
  app/common/model/src/main/java/io/syndesis/common/model/ModelData.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/KnativeCamelKIntegrationCustomizer.java
  app/server/dao/pom.xml
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  app/server/metrics/jsondb/src/test/java/io/syndesis/server/metrics/jsondb/MetricsCollectorTest.java
  app/server/monitoring/src/test/java/io/syndesis/server/monitoring/DeploymentStateMonitorControllerTest.java
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ConnectionsITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/KnativeITCase.java
  app/server/runtime/src/test/resources/application-test-knative.yml
  install/generator/04-syndesis-server.yml.mustache
Labels: pr/approved, pr/review-requested

#5415 fix(server): instead of `operation-NNN` use random UUID
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeConnectorGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerUnifiedShapeGeneratorExampleTests.java
Labels: pr/approved

#5418 fix(build): make sure to run cache clean and upgrade
  tools/upgrade/Dockerfile
Labels: backport 1.6.x

#5421 chore: remove unused class SpecificationContentTypeFilter
  app/connector/api-provider/pom.xml
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/SpecificationContentTypeFilter.java
  app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/SpecificationContentTypeFilterTest.java
Labels: pr/approved

#5428 Adding auto-discovery of Knative resources
  app/connector/knative/pom.xml
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataExtension.java
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataRetrieval.java
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/KnativeMetaDataSupport.java
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResource.java
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResourceDoneable.java
  app/connector/knative/src/main/java/io/syndesis/connector/knative/meta/crd/KnativeResourceList.java
  app/connector/knative/src/main/resources/META-INF/syndesis/connector/knative.json
  app/connector/knative/src/main/resources/META-INF/syndesis/connector/meta/knative
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/ComponentMetadataRetrieval.java
  app/meta/pom.xml
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/operator/deploy/syndesis-operator.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#5423 Dependency upgrades based on Snyk issues
  app/connector/box/pom.xml
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirDeleteTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirMetadataRetrievalTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirUpdateTest.java
  app/connector/fhir/src/test/java/io/syndesis/connector/fhir/processor/FhirResourceProcessorTest.java
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#5358 #4203: adding the data integration image to the syndesis build
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-teiid-komodo-server.yml.mustache
  install/generator/syndesis-template.go
Labels: pr/approved

#5434 chore(install): make Data virtualization install optional and disabled by default
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/prometheus-config.yml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/prometheus-config.yml
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-teiid-komodo-server.yml.mustache
  install/generator/syndesis-template.go
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#5440 fix: #5430 Servicenow connector meta data retrieval adapter lookup
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java
Labels: pr/approved

#5441 feat: Include first integration step in activity logs
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/ActivityTrackingInterceptStrategy.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ExtensionStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/LogStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SimpleEndpointStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitAggregateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/tracing/ActivityTracingWithSplitTest.java
  app/ui/src/app/common/duration.pipe.ts
Labels: pr/approved

#5448 chor(camel): Bump Camel to version 2.21.0.fuse-740013
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#5447 fix: DATAVIRT_ENABLED parameter use in sydesis.yml
  install/generator/04-teiid-komodo-server.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#5446 Cleanup operator logging
  install/operator/Dockerfile
  install/operator/Gopkg.lock
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/syndesis/action/startup.go
Labels: pr/approved, pr/review-requested

#5453 [SQL] Fix description of To: Stored procedure
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
Labels: pr/approved

#5454 feat: Add Google Sheets get values operation as middle step
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsRetrieveValuesCustomizer.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsRetrieveValuesCustomizerTest.java
Labels: group/connector, pr/approved

#5455 fix(5438): Add folder name as field to receive in EMail connector
  app/connector/email/src/main/java/io/syndesis/connector/email/EMailConstants.java
  app/connector/email/src/main/java/io/syndesis/connector/email/component/EMailComponent.java
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEmailServerTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/consumer/EMailReadRouteTest.java
  app/connector/email/src/test/java/io/syndesis/connector/email/server/EMailTestServer.java
Labels: pr/approved, pr/review-requested

#5439 Faux addons feature in the operator
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/openshift/template/templateprocessor.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/action/upgradebackoff.go
  install/operator/pkg/syndesis/action/upgradelegacy.go
  install/operator/pkg/syndesis/configuration/util.go
  install/operator/pkg/syndesis/legacy/controller.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
Labels: pr/approved, pr/review-requested

#5451 feat: UI is able to reorder conditional flows
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
Labels: group/ui, pr/approved, pr/review-requested

#5457 chore: upgrade Spring Security to 4.2.12.RELEASE
  app/pom.xml
Labels: pr/approved, pr/review-requested

#5461 [closes #5442] Fix double dash for operator template parameter
  tools/bin/commands/util/openshift_funcs
Labels: pr/approved, pr/review-requested

#5466 fix(5385): Fixes regression in OData Connector validation
  app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/verifier/odata
Labels: pr/approved, pr/review-requested

#5467 fix: Show cancel/done buttons also on alternate flow navigation bar
  app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
Labels: group/ui, pr/approved

#5476 fix: CircleCI build fails on the UI module
  .circleci/config.yml
Labels: pr/approved

#5477 Fix #5436 Error when installing from sydesis.yml template
  .circleci/config.yml
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved

#5452 Twitter Direct Message
  app/connector/twitter/pom.xml
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/DirectMessageText.java
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/SendDirectMessageCustomizer.java
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
  doc/connecting/topics/p_adding-twitter-connections.adoc
Labels: pr/approved

#5494 Application dashboards
  install/addons/syndesis-integration-dashboard.yml
Labels: pr/approved

#5495 syndesis-ui, add entry to ConfigMap to support DataVirt
  install/generator/03-syndesis-ui.yml.mustache
  install/operator/syndesis-privileged.yml
  install/operator/syndesis.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#5510 fix(connector): set parameters from HTTP request
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessor.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/HttpRequestWrapperProcessorTest.java
Labels: pr/approved

#5516 fix(5241): Quote string used as key predicate for update
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataPatchCustomizer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
Labels: pr/approved, pr/review-requested

#5509 [fix] Auto save changes when applying conditional flows config
  app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui-angular/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.html
  app/ui-angular/src/app/integration/edit-page/step-configure/content-based-router/content-based-router.component.ts
  app/ui-angular/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui-angular/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/approved, pr/review-requested

#5504 Add <name> to repositories
  app/connector/mqtt/pom.xml
  app/extension/bom/pom.xml
  app/extension/example/log-step/pom.xml
  app/extension/example/simple-action-step/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/pom.xml
  app/server/credential/pom.xml
  app/server/runtime/pom.xml
Labels: pr/approved

#5524 API Client not working if multiple http compatible components are found in the camel registry or classpath
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ConnectorFactory.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/RequestCustomizer.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponent.java
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SyndesisRestSwaggerComponent.java
  app/connector/rest-swagger/src/main/resources/META-INF/services/org/apache/camel/component/connector-rest-swagger-http4
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerProxyComponentTest.java
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/ConfigurationSpec.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/crd/IntegrationSpec.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/ExposureCustomizer.java
Labels: pr/approved, pr/review-requested

#5523 Migrate old style API connectors
  app/common/model/src/main/java/io/syndesis/common/model/Schema.java
  app/server/runtime/src/main/resources/migrations/up-29.js
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion29Test.java
  app/server/runtime/src/test/resources/migrations/29/connection.json
  app/server/runtime/src/test/resources/migrations/29/connector.json
  app/server/runtime/src/test/resources/migrations/29/integration.json
Labels: pr/approved, pr/review-requested

#5529 chore: ui-react add node (coming from maven frontend plugin) to .gitignore
  app/ui-react/.gitignore
Labels: pr/approved, pr/review-requested

#5531 syndesis-react, manual sync
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/src/Layout/WizardSteps.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.css
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Connection/ConnectionDetailsForm.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/syndesis/src/modules/connections/ConnectionsCreatorApp.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadSteps.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/components/index.ts
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/index.ts
  app/ui-react/syndesis/src/modules/connections/pages/index.ts
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.css
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  tools/bin/commands/ui
Labels: pr/approved

#5501 chore: Update to AtlasMap 1.40.0-alpha2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-angular/package.json
  app/ui-angular/yarn.lock
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: pr/approved, pr/review-requested

#5505 Edits field names to consistently lowercase words after the first word
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
Labels: pr/approved, pr/review-requested

#5536 chore: switch the syndesis-ui image to React
  .circleci/config.yml
  app/ui-angular/pom.xml
  app/ui-react/pom.xml
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/review-requested
