Repository syndesisio/syndesis, pull requests merged in 2019-04, with the labels that each got.

#5094 fix: Enable split step to handle input stream content
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
Labels: pr/approved

#5064 User doc for removal of log connection
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-log.adoc
  doc/connecting/topics/p_add-log-connection.adoc
  doc/connecting/topics/p_create-replacement-log-connection.adoc
  doc/connecting/topics/r_comparison-log-step-connection.adoc
  doc/connecting/topics/r_supported-connectors.adoc
  doc/integrating-applications/topics/as_creating-integrations.adoc
  doc/integrating-applications/topics/as_managing-integrations.adoc
  doc/integrating-applications/topics/images/CheckMark.png
  doc/integrating-applications/topics/p_add-log-step.adoc
  doc/integrating-applications/topics/p_procedure-for-creating-an-integration.adoc
  doc/integrating-applications/topics/p_viewing-integration-activity.adoc
Labels: backport 1.6.x

#4998 User doc for FHIR connector
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-fhir.adoc
  doc/connecting/topics/p_adding-fhir-connection-create.adoc
  doc/connecting/topics/p_adding-fhir-connection-delete.adoc
  doc/connecting/topics/p_adding-fhir-connection-patch.adoc
  doc/connecting/topics/p_adding-fhir-connection-read.adoc
  doc/connecting/topics/p_adding-fhir-connection-search.adoc
  doc/connecting/topics/p_adding-fhir-connection-transaction.adoc
  doc/connecting/topics/p_adding-fhir-connection-update.adoc
  doc/connecting/topics/p_creating-fhir-connections.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: backport 1.6.x

#5106 fix: #5096 Prevent stream already closed errors on Http based connectors
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderStartEndpointCustomizer.java
  app/connector/http/pom.xml
  app/connector/http/src/main/java/io/syndesis/connector/http/HttpConnectorCustomizer.java
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/HttpMessageToDefaultMessageProcessor.java
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java
  app/connector/webhook/src/test/java/io/syndesis/connector/webhook/WebhookConnectorCustomizerTest.java
Labels: backport 1.6.x, pr/approved, pr/needs-backport

#5095 User doc for Odata connector
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-odata.adoc
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
  doc/connecting/topics/p_adding-odata-connections-read.adoc
  doc/connecting/topics/p_adding-odata-connections-write.adoc
  doc/connecting/topics/p_creating-odata-connections.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: backport 1.6.x

#5119 fix typo
  doc/tutorials/topics/p_amq2api-create-custom-step.adoc
Labels: pr/approved

#5120 fix: #5110 Add support for Json array Strings in Google Sheets
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizerTest.java
Labels: backport 1.6.x, pr/approved, pr/needs-backport

#5124 user doc: mapping between collections and non-collections
  doc/connecting/topics/as_connecting-to-fhir.adoc
  doc/integrating-applications/topics/as_how-to-process-a-collection-in-a-flow.adoc
  doc/integrating-applications/topics/as_mapping-data.adoc
  doc/integrating-applications/topics/images/folder.png
  doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
  doc/integrating-applications/topics/r_example-processing-collection.adoc
  doc/integrating-applications/topics/r_mapping-between-collections-and-non-collections.adoc
Labels: backport 1.6.x

#5127 Fixes #5097, fixed extension import to write files with correct id, which was causing project generation to fail
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/1.6.x, pr/approved, pr/review-requested

#5126 Fixes #5097, fixed extension import to write files with correct id, which was causing project generation to fail
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandler.java
Labels: pr/approved, pr/review-requested

#5130 chore: upgrade Camel to 2.21.0.fuse-730074
  app/pom.xml
Labels: pr/approved

#5138 Added public API OAuth proxy variables for productization
  install/support/syndesis-public-oauth-proxy.yml
Labels: backport master, pr/approved, pr/review-requested

#5137 chore: set the data folder for chromium to persist the login cookies
  app/ui/.gitignore
  app/ui/scripts/get-login-cookie.js
Labels: pr/approved

#5142 Issue #5141, removed imagestream to re-use one from Syndesis oauth-proxy, changed tag to use the latest upstream imagestream tag
  install/support/syndesis-public-oauth-proxy.yml
Labels: backport master, pr/approved, pr/review-requested

#5145 issue #4926: removed unnecessary and harmful exclusions
  app/integration/bom-camel-k/pom.xml
Labels: backport master, pr/approved, pr/review-requested

#5148 Revert "chore: prepare for RESTEasy 4"
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/HttpClient.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
Labels: pr/approved

#5164 Bump to Camel 2.21.0.fuse-740001
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#5168 user doc: Updates based on Martin's QA review
  doc/connecting/topics/p_adding-fhir-connection-create.adoc
  doc/connecting/topics/p_adding-fhir-connection-update.adoc
  doc/connecting/topics/p_creating-fhir-connections.adoc
Labels: backport 1.6.x

#5176 user doc: Updates based on QA review of doc for OData connector
  doc/connecting/topics/p_adding-odata-connections-read.adoc
  doc/connecting/topics/p_adding-odata-connections-write.adoc
  doc/connecting/topics/p_creating-odata-connections.adoc
Labels: backport 1.6.x

#5178 Fixes #5078, forced excluding null values in serialized maps, changed public API get tags by integration to only return non-null values
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5159 Fix #5156: update scripts for newer versions of camel k
  tools/bin/commands/build
Labels: pr/approved

#5195 Fixes #5192, switch to deprecated older Jackson method setPropertyInclusion to remain backward compatible
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/Utils.java
Labels: backport master, pr/approved, pr/review-requested

#5191 chore: Use simple text field for single value property suggestion on meta lookup
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
Labels: cat/enhancement, pr/approved, pr/review-requested

#5188 fix(#5151): OData connector to correctly support EDM Complex Values
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientComplexValueSerializer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/EdmTypeConvertor.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataExtension.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetadata.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataServerConstants.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ProductsEdmProvider.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/Storage.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-airport-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax-location.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-data-klax.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-3.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/test-complex.json
Labels: pr/approved, pr/review-requested

#5190 [camel-k] SyndesisHeaderStrategy not loaded into the registry #5189
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizer.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/support/SyndesisHeaderStrategy.java
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/customizer/syndesis
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizerTest.java
  app/server/controller/src/main/java/io/syndesis/server/controller/ControllersConfigurationProperties.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5198 fix: #5014 Unstable Google Sheets integration tests
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsValuesIntegrationTest.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIntegrationTest.java
Labels: pr/approved

#5201 fix #5184 [camel-k] AtlasMap's multi document vs InputStream
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
Labels: backport 1.6.x, pr/approved, pr/review-requested

#5199 Related to #5194: add marker for camel k resources
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/syndesis.yml
Labels: backport master, pr/approved

#5202 [camel-k] move SyndesisHeaderStrategy to integration/runtime
  app/connector/http/pom.xml
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHttpConfiguration.java
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizer.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/support/SyndesisHeaderStrategy.java
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizerTest.java
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/SyndesisHeaderStrategy.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/util/SyndesisHeaderStrategyTest.java
Labels: pr/approved, pr/review-requested

#5209 user doc: Rewrote section about mapping from collection to collection
  doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
Labels: backport 1.6.x

#5207 Related to #5194: add marker for camel k resources on master
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/syndesis.yml
Labels: pr/approved

#5208 [camel-k] SyndesisHeaderStrategy not loaded into the registry (1.6.x)
  app/connector/http/pom.xml
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/SyndesisHttpConfiguration.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizer.java
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/customizer/syndesis
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/SyndesisContextCustomizerTest.java
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/SyndesisHeaderStrategy.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/util/SyndesisHeaderStrategyTest.java
  app/server/controller/src/main/java/io/syndesis/server/controller/ControllersConfigurationProperties.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
Labels: pr/approved, pr/review-requested

#5211 chore: Enhance google-sheets meta data with custom column names
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnector.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsConnectorHelper.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetaDataExtension.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleValueRangeMetaData.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/CellCoordinate.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/RangeCoordinate.java
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsMetadataAdapterTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsNamedColumnsTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/model/CellCoordinateTest.java
  app/connector/google-sheets/src/test/resources/meta/column_names_metadata.json
  app/connector/google-sheets/src/test/resources/meta/column_names_split_metadata.json
  app/connector/support/verifier/src/main/java/io/syndesis/connector/support/verifier/api/PropertyPair.java
Labels: pr/approved

#5212 Number of Maven issues
  app/extension/maven-plugin/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#5218 Fix #5156: fix camel k build from vanilla repo
  tools/bin/commands/build
Labels: pr/approved

#5206 fix(body): hide body vertical overflow, update content area padding
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#5229 connector: move SyndesisHttpConfiguration from connector-support to integration-runtime-sb
  app/connector/http/src/main/resources/META-INF/spring.factories
  app/connector/rest-swagger/pom.xml
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SwaggerConnectorComponentTest.java
  app/connector/support/processor/pom.xml
  app/connector/support/processor/src/main/resources/META-INF/spring.factories
  app/connector/webhook/src/main/resources/META-INF/spring.factories
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/SyndesisHttpConfiguration.java
  app/integration/runtime-springboot/src/main/resources/META-INF/spring.factories
Labels: pr/approved, pr/review-requested

#5237 Meta doesn't start on master
  app/connector/http/src/main/resources/META-INF/spring.factories
  app/connector/webhook/src/main/resources/META-INF/spring.factories
  app/meta/src/main/resources/application.yml
Labels: pr/approved

#5239 user doc: Format updates for consistent non-cap on OOTB steps
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
  doc/connecting/topics/p_adding-odata-connections-read.adoc
  doc/connecting/topics/p_adding-odata-connections-write.adoc
  doc/tutorials/topics/p_amq2api-name-and-publish.adoc
Labels: backport 1.6.x

#5230 Add a proxy profile for doing yarn build behind a firewall, add repository.xml
  app/s2i/pom.xml
  app/s2i/src/main/assembly/repository.xml
  app/ui/package.json
  app/ui/pom.xml
Labels: pr/approved, pr/review-requested

#5235 Fix #5193 Add choice step handler representing content based router
  app/common/model/src/main/java/io/syndesis/common/model/choice/FlowOption.java
  app/common/model/src/main/java/io/syndesis/common/model/expression/RuleBase.java
  app/common/model/src/main/java/io/syndesis/common/model/filter/FilterRule.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/StepKind.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java
  app/integration/runtime/src/main/resources/META-INF/services/io.syndesis.integration.runtime.IntegrationStepHandler
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
Labels: pr/approved, pr/review-requested

#5242 ENTESB-9863 Upgrade jackson-databind version to 2.8.11.3 in integration-bom
  app/integration/bom/pom.xml
Labels: backport 1.6.x, pr/approved

#5245 Integrations don't start on master
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime-springboot/src/main/resources/META-INF/spring.factories
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/ApplicationTest.java
Labels: pr/approved

#5243 #5181 Removed fetch metadata calls from reconcile cycles
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/edit-page.models.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
Labels: pr/approved, pr/review-requested

#5248 ENTESB-9863 Upgrade jackson-databind version to 2.8.11.3 in integration-bom
  app/integration/bom/pom.xml
Labels: pr/approved

#5238 integration runtime: component-proxy to support custom components
  app/integration/component-proxy/pom.xml
  app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java
  app/integration/component-proxy/src/test/java/io/syndesis/integration/component/proxy/CustomComponentTest.java
  app/integration/pom.xml
  app/integration/support/camel-acme/pom.xml
  app/integration/support/camel-acme/src/main/java/com/acme/corp/AcmeComponent.java
  app/integration/support/camel-acme/src/main/java/com/acme/corp/AcmeEndpoint.java
  app/integration/support/camel-acme/src/main/resources/META-INF/services/org/apache/camel/component/acme
Labels: pr/approved, pr/review-requested

#5251 feat(sqs-connector): AWS-SQS Connector
  app/connector/aws-sqs/pom.xml
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSBatchMessagesCustomizer.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSMessageCustomizer.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSPollMessageCustomizer.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifier.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifierAutoConfiguration.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifierExtension.java
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/SQSMessage.java
  app/connector/aws-sqs/src/main/resources/META-INF/spring.factories
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
  app/connector/pom.xml
  app/connector/support/catalog/pom.xml
  app/extension/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: pr/approved

#5257 fix(5060): Enum mapping is not correct
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientEntitySerializer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientEnumValueSerializer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientPropertySerializer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/EdmTypeConvertor.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataServerConstants.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ProductsEdmProvider.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/Storage.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/ref-server-people-data-3.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/test-enum.json
Labels: pr/approved, pr/review-requested

#5236 fix(5108): Ensure trailing slashes are removed from odata base url
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataUtil.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/verifier/ODataVerifierExtension.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
Labels: pr/approved, pr/review-requested

#5259 fix(build): Fixed Odata connector build
  app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
Labels: pr/approved

#5258 fix(build docs): Build: specify --camel-snapshot without an explicit …
  tools/bin/commands/build
Labels: pr/approved

#5252 #5181 Add bulk operation for step descriptor lookup
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHelper.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
Labels: pr/review-requested

#5261 chore: #5181 UI uses backend bulk operation for step descriptor lookup
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
  app/ui/src/app/platform/types/integration/integration.api.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
Labels: pr/approved, pr/review-requested

#5262 chore: upgrade basepom
  app/connector/google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsEndpoint.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/exception/BaseExceptionMapper.java
  ruleset.xml
Labels: pr/approved

#5270 fix(5057): Correct determination of when to show Next or Done buttons
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
Labels: pr/approved, pr/review-requested

#5271 Upgrade Camel to version 2.21.0.fuse-740005
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#5276 user doc: updates to doc for creating api provider integrations
  doc/integrating-applications/topics/as_trigger-integrations-with-api-calls.adoc
  doc/integrating-applications/topics/c_about-api-provider-flows.adoc
  doc/integrating-applications/topics/c_about-api-provider-urls.adoc
  doc/integrating-applications/topics/c_overview-benefit-api-provider-integrations.adoc
  doc/integrating-applications/topics/c_plan-integrations.adoc
  doc/integrating-applications/topics/p_configure-publish-api-provider-quickstart.adoc
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
  doc/integrating-applications/topics/p_create-integration-operation-flows.adoc
  doc/integrating-applications/topics/p_try-api-provider-quickstart.adoc
Labels: backport 1.6.x

#5279 [SQS] Add a hint about queue creation
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
Labels: pr/approved, pr/review-requested

#5272 chore(4693): Removes duplicate olingo4 component from odata
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataConstants.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataCreateCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataDeleteCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataPatchCustomizer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4AppEndpointConfiguration.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4AppWrapper.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Component.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Configuration.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Index.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4ApiCollection.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4ApiName.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4AppApiMethod.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4Constants.java
  app/connector/odata/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4PropertiesHelper.java
Labels: pr/approved, pr/review-requested

#5281 chore(aws-sqs): [SQS] QueueNameOrArn moved on action level instead of…
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSVerifierExtension.java
  app/connector/aws-sqs/src/main/resources/META-INF/syndesis/connector/aws-sqs.json
Labels: pr/approved

#5280 feat: Add jaeger support so that syndesis and integrations can be traced.
  app/common/jaeger-spring-boot-starter/pom.xml
  app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/JaegerConfiguration.java
  app/common/jaeger-spring-boot-starter/src/main/resources/META-INF/spring.factories
  app/common/pom.xml
  app/pom.xml
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
Labels: pr/approved, pr/review-requested

#5286 user doc: Format updates based on peer review
  doc/connecting/topics/p_add-gmail-connection-start.adoc
  doc/connecting/topics/p_add-google-calendar-connection-start.adoc
  doc/connecting/topics/p_add-google-calendar-connection-to-get-one-event.adoc
  doc/connecting/topics/p_add-google-sheets-connection-get-properties.adoc
  doc/connecting/topics/p_add-google-sheets-connection-get-sheet-values.adoc
  doc/connecting/topics/p_add-google-sheets-connection-update-sheet-values.adoc
  doc/connecting/topics/p_create-google-sheets-connection.adoc
  doc/connecting/topics/p_register-with-google.adoc
Labels: backport 1.6.x

#5288 user doc: Updates based on peer review
  doc/integrating-applications/topics/as_trigger-integrations-with-api-calls.adoc
  doc/integrating-applications/topics/c_workflow-api-providers.adoc
  doc/integrating-applications/topics/images/ApiProviderCreateIntegrationWorkflow.png
  doc/integrating-applications/topics/p_create-api-provider-integration.adoc
  doc/integrating-applications/topics/r_requirements-for-api-provider-integrations.adoc
Labels: backport 1.6.x

#5285 feat: Add jaeger support so that syndesis and integrations can be traced.
  app/integration/runtime-springboot/pom.xml
  app/meta/src/main/resources/application.yml
  app/pom.xml
  app/server/logging/jaeger/infinitest.filters
  app/server/logging/jaeger/pom.xml
  app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/JaegerActivityTrackingConfiguration.java
  app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingService.java
  app/server/logging/jaeger/src/main/java/io/syndesis/server/logging/jaeger/service/JaegerQueryAPI.java
  app/server/logging/jaeger/src/main/resources/META-INF/spring.factories
  app/server/logging/jaeger/src/test/java/io/syndesis/server/logging/jaeger/service/JaegerActivityTrackingServiceTest.java
  app/server/logging/jaeger/src/test/resources/example-jaeger-trace-result.json
  app/server/logging/jaeger/src/test/resources/expected-activities.json
  app/server/logging/jaeger/src/test/resources/logback-test.xml
  app/server/pom.xml
  app/server/runtime/pom.xml
Labels: pr/approved, pr/review-requested

#5284 No bean could be found in the registry for: syndesisHeaderStrategy
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/SyndesisHttpConfiguration.java
Labels: pr/approved

#5292 chore(update-camel): Bump Camel to version 2.21.0.fuse-740007
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved
