Repository syndesisio/syndesis, pull requests merged in 2019-02, with the labels that each got.

#4398 feat(newSyndesisLogo): cleaning up autogeneratred files/code for logo
  app/ui/src/android-chrome-192x192.png
  app/ui/src/android-chrome-512x512.png
  app/ui/src/app/android-chrome-192x192.png
  app/ui/src/app/android-chrome-512x512.png
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.ts
  app/ui/src/app/apple-touch-icon.png
  app/ui/src/apple-touch-icon.png
  app/ui/src/browserconfig.xml
  app/ui/src/config.json.example
  app/ui/src/config.json.minishift
  app/ui/src/config.json.staging
  app/ui/src/favicon-16x16.png
  app/ui/src/favicon-32x32.png
  app/ui/src/favicon.ico
  app/ui/src/mstile-150x150.png
  app/ui/src/safari-pinned-tab.svg
  app/ui/src/scss/utils/_overrides.scss
  install/generator/03-syndesis-ui.yml.mustache
  install/syndesis-privileged.yml
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4409 Fix #4407 Log step does not show body properly
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/logging/BodyLogger.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/logging/BodyLoggerTest.java
Labels: pr/approved

#4404 [3856] SQL connector should return all results as collection
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStoredConnectorCustomizer.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
Labels: pr/approved, pr/review-requested

#4414 feat(monitoring): Show Syndesis Server REST API metrics in a Grafana dashboard
  app/server/runtime/src/main/java/io/syndesis/server/runtime/EndpointMetricsFilter.java
  install/addons/syndesis-server-rest-api-dashboard.yml
Labels: pr/approved

#4411 [Rollback] Fix errors variable name
  tools/upgrade/upgrade.sh
Labels: pr/approved

#4423 feat(monitoring): Create Syndesis REST API dashboard
  install/addons/syndesis-rest-api-dashboard.yml
  install/addons/syndesis-server-rest-api-dashboard.yml
Labels: pr/approved, pr/review-requested

#4428 fix(monitoring): Fix indentation for syndesis-rest-api GrafanaDashboard resource
  install/addons/syndesis-rest-api-dashboard.yml
Labels: pr/approved, pr/review-requested

#4422 Add GrafanaDashboard resources for infrastructure components
  install/addons/syndesis-db-dashboard.yml
  install/addons/syndesis-jvm-dashboard.yml
Labels: pr/approved, pr/review-requested

#4430 feat(monitoring): Show Syndesis Server JDBC metrics in a Grafana dashboard
  install/addons/syndesis-jdbc-dashboard.yml
Labels: pr/approved, pr/review-requested

#4432 chore: Update to AtlasMap 1.39.1
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4438 Fix flaky out message capture unit test
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
Labels: pr/approved, pr/review-requested

#4347 feature(syndesis): Add Camel-K integration into "syndesis install" and "syndesis minishift"
  tools/bin/commands/build
  tools/bin/commands/completion
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/camel_k_funcs
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/operator_funcs
Labels: pr/approved

#4415 feat: implement the new api provider editor layout
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.html
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.ts
  app/ui/src/app/integration/api-provider/index.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.ts
  app/ui/src/app/integration/api-provider/operations-page/specification/specification-editor-page.component.ts
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/describe-data/describe-data.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.ts
  app/ui/src/app/integration/edit-page/flow-page-header/flow-page-header.component.html
  app/ui/src/app/integration/edit-page/flow-page-header/flow-page-header.component.scss
  app/ui/src/app/integration/edit-page/flow-page-header/flow-page-header.component.ts
  app/ui/src/app/integration/edit-page/flow-page-header/index.ts
  app/ui/src/app/integration/edit-page/flow-page.service.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.scss
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/flow-toolbar/index.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/edit-page/index.ts
  app/ui/src/app/integration/edit-page/integration-basics/integration-basics.component.html
  app/ui/src/app/integration/edit-page/list-actions/list-actions.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.html
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html
  app/ui/src/app/integration/edit-page/step-configure/step-configure.component.ts
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/integration.module.ts
Labels: pr/approved, pr/review-requested

#4446 fix: make the trash button work again, also expand the IVP at the save/add step page
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.ts
  app/ui/src/app/integration/edit-page/save-or-add-step/save-or-add-step.component.ts
  app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts
Labels: pr/approved

#4452 chore(deps): update camel to 2.21.0.fuse-730042
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#4448 feat: allow steps in the finish position in an integration
  app/ui/src/app/common/icon-path.pipe.ts
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/list/list.component.html
Labels: pr/approved

#4451 chore: Remove irc-notifications on build errors as nobody is using IRC anymore (and it doesn't work anyway)
  .circleci/config.yml
  .circleci/send_irc_notification.sh
Labels: pr/approved

#4456 fix(ui): switch logo width from percentage to rem
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved, pr/review-requested

#4455 Implicit split integration migration
  app/common/model/src/main/java/io/syndesis/common/model/Schema.java
  app/common/model/src/main/java/io/syndesis/common/model/Split.java
  app/common/model/src/main/java/io/syndesis/common/model/WithSplit.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/StepKind.java
  app/common/model/src/main/java/io/syndesis/common/model/support/Equivalencer.java
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
  app/connector/servicenow/src/main/resources/META-INF/syndesis/connector/servicenow.json
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlStartConnectorTest.java
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
  app/integration/runtime-springboot/src/test/resources/syndesis/integration/component/proxy/ComponentProxySplitCollectionTest.json
  app/integration/runtime-springboot/src/test/resources/syndesis/integration/component/proxy/ComponentProxySplitTokenizeTest.json
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/AggregateStepHandler.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ForeachStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SimpleEndpointStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitAggregateStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerTest.java
  app/integration/runtime/src/test/resources/syndesis/integration/SplitStepHandlerJsonTest.json
  app/integration/runtime/src/test/resources/syndesis/integration/integration.json
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/runtime/src/main/resources/migrations/common.js
  app/server/runtime/src/main/resources/migrations/up-28.js
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion28Test.java
  app/server/runtime/src/test/resources/migrations/aws-s3-integration.json
  app/server/runtime/src/test/resources/migrations/servicenow-integration.json
  app/server/runtime/src/test/resources/migrations/simple-timer-integration.json
  app/server/runtime/src/test/resources/migrations/sql-integration.json
  app/ui/src/app/store/step/step.store.ts
  app/ui/src/assets/icons/steps/aggregate.svg
  app/ui/src/assets/icons/steps/split.svg
Labels: pr/approved, pr/review-requested

#4450 fix: reduce integration definition size #4309
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/integration.json
Labels: pr/approved, pr/review-requested

#4436 [api provider - collections] enhance connector/extension maven plugin to support collections type for data shapes
  app/common/model/src/main/java/io/syndesis/common/model/DataShape.java
  app/connector/support/maven-plugin/pom.xml
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateResourceInspectionsMojo.java
  app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java
  app/connector/support/maven-plugin/src/test/resources/logback-test.xml
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/extension/annotation-processor/src/main/java/io/syndesis/extension/maven/annotation/processing/ActionProcessor.java
  app/extension/api/src/main/java/io/syndesis/extension/api/annotations/DataShape.java
  app/extension/example/log-step/src/main/java/io/syndesis/extension/example/log/LogStep.java
  app/extension/example/simple-action-step/pom.xml
  app/extension/example/simple-action-step/src/main/java/io/syndesis/extension/example/simple/ActionStep.java
  app/extension/example/simple-action-step/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json
  app/extension/maven-plugin/pom.xml
  app/extension/maven-plugin/src/it/settings.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/src/main/java/example/ActionStep.java
  app/extension/maven-plugin/src/it/with-data-shape-variants/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json
  app/extension/maven-plugin/src/it/with-data-shape-variants/verify.groovy
  app/extension/maven-plugin/src/it/with-data-shape/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape/src/main/java/example/ActionStep.java
  app/extension/maven-plugin/src/it/with-data-shape/src/main/resources/META-INF/syndesis/syndesis-extension-definition.json
  app/extension/maven-plugin/src/it/with-data-shape/verify.groovy
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/extension/pom.xml
  app/pom.xml
Labels: pr/approved, pr/review-requested

#4463 Feat(ui): integration editor UI tweaks
  app/ui/src/app/common/editable/editable-tags.component.ts
  app/ui/src/app/common/editable/editable-text.component.ts
  app/ui/src/app/common/editable/editable-textarea.component.ts
  app/ui/src/app/common/editable/editable.component.spec.ts
  app/ui/src/app/common/editable/editable.component.ts
  app/ui/src/app/common/openapi/editor/editor.component.html
  app/ui/src/app/common/openapi/editor/editor.component.scss
  app/ui/src/app/common/openapi/editor/editor.component.ts
  app/ui/src/app/integration/api-provider/creation-page/integration-api-provider-creation-page.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-editor/step-editor.component.ts
  app/ui/src/app/integration/api-provider/creation-page/step-name/step-name.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-upload/step-upload.component.html
  app/ui/src/app/integration/api-provider/creation-page/step-validate/step-validate.component.html
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.scss
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view.component.scss
  app/ui/src/scss/components/_breadcrumb.scss
  app/ui/src/scss/components/_module.scss
Labels: pr/approved

#4440 Fixes #4429 Suppport multi-selection for form fields
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/core/providers/form-factory-provider.service.ts
  app/ui/src/app/platform/types/platform.models.ts
Labels: pr/approved

#4472 refactor(monitoring): improvements to the Grafana dashboards
  install/addons/syndesis-db-dashboard.yml
  install/addons/syndesis-jdbc-dashboard.yml
  install/addons/syndesis-jvm-dashboard.yml
  install/addons/syndesis-rest-api-dashboard.yml
Labels: pr/approved, pr/review-requested

#4454 SSO Enhancements revert
  install/README.md
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/run.sh
  install/generator/syndesis-template.go
  install/operator/deploy/syndesis-operator.yml
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/reconcile.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/pkg/util/resources.go
  install/operator/pkg/util/resources_test.go
  install/syndesis-privileged.yml
  install/syndesis.yml
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
Labels: pr/approved, pr/review-requested

#4424 feat(monitoring): Create Prometheus ServiceMonitor resources for Syndesis infrastructure components
  install/addons/syndesis-db-servicemonitor.yml
  install/addons/syndesis-meta-servicemonitor.yml
  install/addons/syndesis-server-servicemonitor.yml
  install/generator/04-syndesis-db-metrics.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/syndesis.yml
Labels: pr/approved, pr/review-requested

#4481 chore(syndesis): Only install the java context for camel-k installation
  tools/bin/commands/util/camel_k_funcs
Labels: pr/approved

#4489 feat: local development
  app/server/runtime/pom.xml
  app/ui/package.json
  app/ui/proxy.conf.js
  app/ui/src/config.json.local
  doc/sdh/development/local.adoc
Labels: pr/approved

#4495 [refactoring] as part of #4232
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/MavenProperties.java
  app/common/util/src/main/java/io/syndesis/common/util/Resources.java
  app/connector/aws-s3/pom.xml
  app/connector/aws-s3/src/test/java/io/syndesis/connector/aws/s3/AWSS3RawOptionsTest.java
  app/connector/support/test/src/main/java/io/syndesis/connector/support/test/ConnectorTestSupport.java
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/IntegrationRuntimeAutoConfiguration.java
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/IntegrationTestSupport.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/main/resources/META-INF/services/io.syndesis.integration.runtime.IntegrationStepHandler
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationStepHandlersTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/SplitStepHandlerJsonTest.java
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/SpringMavenProperties.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/Application.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/SpringMavenProperties.java
Labels: pr/approved

#4497 refactor(tool): no need to list pods
  tools/misc/extract_integration.sh
Labels: pr/approved

#4478 Fixes 4429 Support multi-selection follow up fix
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.html
  app/ui/src/app/common/ui-patternfly/syndesis-form-control.component.ts
Labels: pr/approved

#4470 chore: upgrade Apicurio to 0.2.22
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/review-requested

#4447 fix(s2i): Removed unnecessary assembly
  app/s2i/copy_mvn_repo.sh
  app/s2i/pom.xml
  app/s2i/src/assembly/repository.xml
  app/s2i/src/main/docker/Dockerfile
Labels: pr/approved, pr/review-requested

#4363 [Upgrade] Fix regex in preflight.sh
  tools/upgrade/migration/preflight.sh
Labels: pr/approved, pr/review-requested

#4479 fix(server): do not add `responseSchema` to OpenAPI document
  app/server/api-generator/pom.xml
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SyndesisSwaggerValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/CapturingCodec.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorShapeValidityTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/UnifiedXmlDataShapeGeneratorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelperTest.java
  app/server/api-generator/src/test/resources/swagger/empty-summary.json
  app/server/runtime/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/ApiIntegrationUpdateITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/IntegrationSpecificationITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/integration/SwaggerHickups.java
Labels: pr/approved

#4504 Fixes #4486 Please check your sorting arguments
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Labels: pr/approved

#4498 feature(camel-k) implement camel-k runtime fix #4306
  app/integration/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-camelk/readme.adoc
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/jmx/IntegrationMetadataContextCustomizer.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/logging/IntegrationLoggingContextCustomizer.java
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/customizer/logging
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/customizer/metadata
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/loader/syndesis
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoaderTest.java
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/jmx/CamelContextMetadataMBeanTest.java
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/logging/IntegrationLoggingDisabledTest.java
  app/integration/runtime-camelk/src/test/java/io/syndesis/integration/runtime/camelk/logging/IntegrationLoggingEnabledTest.java
  app/integration/runtime-camelk/src/test/resources/logback-test.xml
  app/integration/runtime-camelk/src/test/resources/syndesis/integration/integration.syndesis
Labels: pr/approved, pr/review-requested

#4514 feat(monitoring): Create PrometheusRule resources for alerting on Syndesis infrastructure components
  install/addons/syndesis-db-prometheus-rule.yml
  install/addons/syndesis-jvm-prometheus-rule.yml
  install/addons/syndesis-rest-api-prometheus-rule.yml
Labels: pr/approved

#4513 Bump version of jackson-databind to 2.8.11.3
  app/pom.xml
Labels: pr/approved

#4524 fix(monitoring): Add missing labels to alert rules
  install/addons/syndesis-db-prometheus-rule.yml
  install/addons/syndesis-jvm-prometheus-rule.yml
  install/addons/syndesis-rest-api-prometheus-rule.yml
Labels: pr/approved

#4510 [#4405] Metadata data shapes for split/aggregate steps
  app/common/model/src/main/java/io/syndesis/common/model/DataShape.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepAction.java
  app/common/model/src/main/java/io/syndesis/common/model/action/StepDescriptor.java
  app/common/model/src/test/java/io/syndesis/common/model/DataShapeBuilderTest.java
  app/connector/support/maven-plugin/src/main/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojo.java
  app/connector/support/maven-plugin/src/test/java/io/syndesis/connector/support/maven/GenerateConnectorInspectionsMojoTest.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/GenerateMetadataMojo.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/Person.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-instance.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-instance.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-schema.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-list-spec.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-schema.json
  app/server/endpoint/src/test/resources/io/syndesis/server/endpoint/v1/handler/meta/person-spec.json
Labels: pr/approved, pr/review-requested

#4467 feat(ui): API Provider editor pane-based layout
  app/ui/src/app/common/openapi/editor/editor.component.scss
  app/ui/src/app/common/ui-patternfly/list-toolbar/list-toolbar.component.scss
  app/ui/src/app/integration/api-provider/editor-page/index.ts
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.html
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.scss
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-page.component.ts
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.scss
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.ts
  app/ui/src/app/integration/api-provider/index.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operation-description-component.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-list.component.ts
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.html
  app/ui/src/app/integration/api-provider/operations-page/integration-api-provider-operations-page.component.scss
  app/ui/src/app/integration/edit-page/action-configure/action-configure.component.html
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
  app/ui/src/app/integration/edit-page/edit-page.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.html
  app/ui/src/app/integration/edit-page/flow-toolbar/flow-toolbar.component.ts
  app/ui/src/app/integration/edit-page/list-actions/list-actions.component.html
  app/ui/src/app/integration/edit-page/list-actions/list-actions.component.spec.ts
  app/ui/src/app/integration/edit-page/step-select/step-select.component.html
  app/ui/src/app/integration/edit-page/step-select/step-select.component.scss
  app/ui/src/app/integration/integration-support.module.ts
  app/ui/src/app/integration/integration.module.ts
Labels: pr/approved, pr/review-requested

#4537 fix: avoid npe
  app/ui/src/app/integration/edit-page/action-select/action-select.component.html
Labels: pr/approved

#4550 bugfix(ui): make the customization api editor visible
  app/ui/src/app/customizations/api-connector/api-connector-create/api-connector-create.component.html
Labels: pr/approved

#4554 fix(#4543): Improve speed of odata unit tests
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataTestServer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/verifier/ODataVerifierTest.java
Labels: pr/approved, pr/review-requested

#4344 Fixes #4274, fixes #4275 Initial version of public import/export API
  app/common/model/src/main/java/io/syndesis/common/model/integration/ContinuousDeliveryEnvironment.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/ContinuousDeliveryImportResults.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
  app/ui/src/app/core/providers/integration-support-provider.service.ts
  app/ui/src/app/integration/integration-actions-provider.service.ts
  app/ui/src/app/integration/list/action-menu.component.ts
  app/ui/src/app/integration/list/index.ts
  app/ui/src/app/integration/list/list.component.spec.ts
  app/ui/src/app/integration/list/list.module.ts
  app/ui/src/app/integration/list/tag-cicd-modal.component.html
  app/ui/src/app/integration/list/tag-cicd-modal.component.scss
  app/ui/src/app/integration/list/tag-cicd-modal.component.ts
  app/ui/src/app/platform/types/integration/integration-actions.service.ts
  app/ui/src/app/platform/types/integration/integration-support.service.ts
  app/ui/src/app/platform/types/integration/integration.api.ts
  app/ui/src/app/platform/types/integration/integration.models.ts
  app/ui/src/assets/dictionary/en-GB.json
  install/README.md
  install/generator/04-syndesis-server.yml.mustache
  install/staging/README.md
  install/support/syndesis-public-oauth-proxy.yml
  install/syndesis.yml
Labels: pr/review-requested

#4551 Servicenow connector returning collection data shape
  app/connector/servicenow/pom.xml
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/ServiceNowMetadataRetrieval.java
  app/connector/servicenow/src/main/java/io/syndesis/connector/servicenow/customizers/ServiceNowTableGetCustomizer.java
Labels: pr/approved, pr/review-requested

#4548 Kudu connector returns collection data shape
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduInsertCustomizer.java
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduMetadataRetrieval.java
  app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
Labels: pr/approved, pr/review-requested

#4547 SQL connector returns collection data shape
  app/connector/sql/src/main/java/io/syndesis/connector/sql/SqlMetadataRetrieval.java
  app/connector/sql/src/test/resources/sql/demo_add_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_metadata.json
  app/connector/sql/src/test/resources/sql/name_sql_no_param_metadata.json
Labels: pr/approved, pr/review-requested

#4546 OData connector returns collection data shape
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
Labels: pr/approved, pr/review-requested

#4545 Google Sheets connector return collection data shape
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsMetadataRetrieval.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateValuesCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/meta/GoogleSheetsMetaDataHelper.java
  app/connector/google-sheets/src/test/resources/meta/append_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/append_rows_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_columns_split_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_rows_metadata.json
  app/connector/google-sheets/src/test/resources/meta/get_rows_split_metadata.json
  app/connector/google-sheets/src/test/resources/meta/update_columns_metadata.json
  app/connector/google-sheets/src/test/resources/meta/update_rows_metadata.json
Labels: pr/approved, pr/review-requested

#4561 #4406 Fixed step kind argument when fetching step descriptor
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved, pr/review-requested

#4566 chore(server): upgrade immutables
  app/common/model/src/main/java/io/syndesis/common/model/ListResult.java
  app/common/model/src/test/java/io/syndesis/common/model/api/APISummaryTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationSpecificationHandlerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ConnectionsITCase.java
Labels: pr/approved

#4549 feat(ui): add a suggested step hint over unclosed split steps
  app/ui/src/app/integration/edit-page/current-flow.service.ts
  app/ui/src/app/integration/edit-page/flow-functions.ts
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts
Labels: pr/approved, pr/review-requested

#4570 refactor(monitoring): Remove redundant alert rules
  install/addons/syndesis-db-prometheus-rule.yml
  install/addons/syndesis-jvm-prometheus-rule.yml
Labels: pr/approved

#4573 Fixed missing endpoints in PublicApi
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: pr/approved

#4576 #4405 Aggregate step should provide input shape of subsequent step
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/ui/src/app/integration/edit-page/current-flow.service.ts
Labels: pr/approved, pr/review-requested

#4575 fix: fix link to view/edit api spec
  app/ui/src/app/integration/api-provider/editor-page/integration-api-provider-editor-toolbar.component.html
Labels: pr/approved

#4577 #4586 Fix step id for split and aggregate in integration runtime
  app/integration/runtime-springboot/src/test/java/io/syndesis/integration/runtime/sb/capture/OutMessageCaptureProcessorTest.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteBuilderTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationRouteTest.java
Labels: pr/approved, pr/review-requested

#4569 Add verifier for kudu connector
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduConnectorVerifierExtension.java
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduMetadataRetrieval.java
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduVerifier.java
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/KuduVerifierAutoconfiguration.java
  app/connector/kudu/src/main/java/io/syndesis/connector/kudu/common/KuduSupport.java
  app/connector/kudu/src/main/resources/META-INF/spring.factories
  app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
  app/connector/kudu/src/test/java/io/syndesis/connector/kudu/KuduConnectorVerifierExtensionTest.java
  app/connector/kudu/src/test/java/io/syndesis/connector/kudu/KuduScanCustomizerTest.java
Labels: pr/approved

#4580 feat(monitoring): Improve Syndesis DB Grafana Dashboard
  install/addons/syndesis-db-dashboard.yml
Labels: pr/approved

#4565 feat(monitoring): Reference SOP documentation from alerts
  doc/managing_environments/topics/alerting_sop.adoc
  install/addons/syndesis-db-prometheus-rule.yml
  install/addons/syndesis-rest-api-prometheus-rule.yml
Labels: pr/approved

#4585 #4563 Update split and aggregate step icons
  app/ui/src/assets/icons/steps/aggregate.svg
  app/ui/src/assets/icons/steps/split.svg
Labels: pr/approved, pr/review-requested

#4517 feat(install): Support for addon resources in syndesis-operator
  install/operator/Dockerfile
  install/operator/Gopkg.lock
  install/operator/cmd/syndesis-operator/main.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/startup.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/action/upgradebackoff.go
  install/operator/pkg/syndesis/action/upgradelegacy.go
  install/operator/pkg/syndesis/addons/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/operation/utils.go
  install/operator/pkg/util/resources.go
  tools/bin/commands/util/operator_funcs
Labels: pr/approved

#4587 fix(#4562): Reduce flakiness of odata unit tests
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
Labels: pr/approved, pr/review-requested

#4589 Remove duplicated fields in templates
  install/operator/syndesis-privileged.yml
  install/operator/syndesis.yml
  install/syndesis.yml
Labels: pr/approved

#4592 fix(IVP): create common class for IVP step badge icons
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.html
  app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.scss
Labels: pr/approved, pr/review-requested

#4599 Fixes 4598, supports using names in addition to ids for public apis
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: pr/approved

#4574 refactor(operator): Some operator optimizations
  install/operator/Gopkg.toml
  install/operator/deploy/syndesis-crd.yml
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/openshift/serviceaccount/serviceaccount.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/startup.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/action/upgradebackoff.go
  install/operator/pkg/syndesis/action/upgradelegacy.go
  install/operator/pkg/syndesis/configuration/envvars.go
  install/operator/pkg/syndesis/configuration/secret.go
  install/operator/pkg/syndesis/configuration/version.go
  install/operator/pkg/syndesis/legacy/controller.go
  install/operator/pkg/syndesis/operation/attach.go
Labels: pr/approved, pr/review-requested

#4605 Fix #4511 include grid data option is ignored
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
Labels: pr/approved

#4526 refactor: Moved conditional to a functional
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
Labels: cat/discussion, cat/techdebt, pr/approved

#4616 Fixes #4544 pivot table not placed at the beginning of the sheet
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizer.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsAddPivotTableCustomizerTest.java
Labels: pr/approved

#4602 Fix Json type source and target conversion for topmost collection support
  app/integration/runtime/pom.xml
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
Labels: pr/approved, pr/review-requested

#4621 fix(#4590): Fix dependency on integration-runtime-tests in odata
  app/connector/odata/pom.xml
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java
Labels: pr/review-requested

#4626 chore(syndesis): Fix perms on CRDs
  install/operator/deploy/old/syndesis-crd.yml
  install/operator/deploy/old/syndesis.1.5.6.csv.yaml
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
  tools/bin/install-syndesis
Labels: pr/approved

#4623 chore: Update to AtlasMap 1.39.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui/package.json
  app/ui/yarn.lock
Labels: pr/approved

#4597 fix(masthead): add separator in masthead dropdown, align nav text with hamburger
  app/ui/src/app/app.component.html
  app/ui/src/scss/utils/_overrides.scss
Labels: pr/approved

#4632 fix(minishift): Fix issue with context
  tools/bin/commands/minishift
Labels: pr/approved

#4630 Upgrade Camel to version 2.21.0.fuse-730049
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: pr/approved

#4638 Fixes #4631 Topmost collection mapping errors
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/DataMapperStepHandlerTest.java
Labels: pr/approved, pr/review-requested

#4642 fix(server): make sure that ResourceUpdateController is ready to process events
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/ResourceUpdateController.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/ResourceUpdateControllerTest.java
Labels: pr/approved

#4647 Fixes 4617: Added check in renameEnvironment to ignore identical names
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: pr/approved

#4644 Add kudu install via openshift template
  install/extras/README.md
  install/extras/syndesis-kudu.yml
Labels: pr/approved, pr/review-requested

#4643 fix(server): robustly parse OpenAPI documents
  .gitignore
  app/common/util/src/main/java/io/syndesis/common/util/openapi/OpenApiHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseSwaggerConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/util/SwaggerHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGeneratorTest.java
  app/ui/src/app/common/openapi/review/review.component.ts
  app/ui/src/app/customizations/api-connector/api-connector.effects.ts
  app/ui/src/app/customizations/api-connector/api-connector.models.ts
  app/ui/src/app/customizations/api-connector/api-connector.reducer.ts
Labels: pr/approved, pr/review-requested

#4649 #4629 Fix collection support on filter step
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/JsonSimplePredicate.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/FilterStepHandlerTest.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/util/JsonSimplePredicateTest.java
  app/server/inspector/src/main/java/io/syndesis/server/inspector/JsonSchemaInspector.java
  app/server/inspector/src/test/java/io/syndesis/server/inspector/JsonSchemaInspectorTest.java
Labels: pr/approved

#4662 [collection support] Fix to preserve original data shapes on meta lookup
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/StepActionHandlerTest.java
Labels: pr/approved

#4663 [flaky-tests] Use JUnit4 class rule for Google Sheets test server
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/AbstractGoogleSheetsTestSupport.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerRule.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/AbstractGoogleSheetsStreamTestSupport.java
Labels: pr/approved

#4660 Project generator to report error when missing the data mapper mapping
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
Labels: pr/approved, pr/review-requested

#4666 [collection support] Update database migration for schema 28
  app/server/runtime/src/main/resources/migrations/up-28.js
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion28Test.java
  app/server/runtime/src/test/resources/migrations/aws-s3-integration.json
  app/server/runtime/src/test/resources/migrations/servicenow-integration.json
  app/server/runtime/src/test/resources/migrations/simple-timer-integration.json
  app/server/runtime/src/test/resources/migrations/sql-integration.json
Labels: pr/approved

#4645 User doc for Kudu connector
  doc/connecting/master.adoc
  doc/connecting/topics/as_connecting-to-kudu.adoc
  doc/connecting/topics/p_add-kudu-connection-add-records.adoc
  doc/connecting/topics/p_add-kudu-connection-get-records.adoc
  doc/connecting/topics/p_create-kudu-connections.adoc
  doc/connecting/topics/r_supported-connectors.adoc
Labels: pr/approved

#4667 fix(icons): update google sheets icon to a square aspect ratio SVG
  app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json
  app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/http4.json
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
  app/connector/irc/src/main/resources/META-INF/syndesis/connector/irc.json
  app/connector/kudu/src/main/resources/META-INF/syndesis/connector/kudu.json
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
  ux/connections_icons/svg/connectionicons_googlesheets.svg
  ux/connections_icons/svg/mapping.json
Labels: pr/approved, pr/review-requested, pr/wip

#4670 #4008 Avoid NPE when connection is not found in DB
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
Labels: pr/approved, pr/review-requested

#4671 [flaky test] Fighting flaky test behavior on CircleCi
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServer.java
  app/connector/google-sheets/src/test/java/org/apache/camel/component/google/sheets/server/GoogleSheetsApiTestServerRule.java
Labels: pr/approved, pr/review-requested

#4648 doc: fix list indent
  doc/developing_extensions/topics/developing_extensions.adoc
Labels: pr/wip

#4679 Add addons directory to operator S2I build archive
  tools/bin/commands/util/operator_funcs
Labels: pr/approved

#4677 chore: google sheets as an SVG icon
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  ux/connections_icons/svg/connectionicons_googlesheets.svg
  ux/connections_icons/svg/optimized/connectionicons_googlesheets.svg
Labels: pr/approved, pr/review-requested

#4678 fix: handle all sheets and its properties in a spreadsheet
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/GoogleSheetsUpdateSpreadsheetCustomizer.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSheet.java
  app/connector/google-sheets/src/main/java/io/syndesis/connector/sheets/model/GoogleSpreadsheet.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsCreateSpreadsheetCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsGetSpreadsheetCustomizerTest.java
  app/connector/google-sheets/src/test/java/io/syndesis/connector/sheets/GoogleSheetsUpdateSpreadsheetCustomizerTest.java
Labels: pr/approved, pr/review-requested

#4665 refactor(connector): update timer's `defaultValue`
  app/common/util/src/main/java/io/syndesis/common/util/Json.java
  app/connector/timer/pom.xml
  app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json
  app/connector/timer/src/test/java/io/syndesis/connector/timer/TimerIntegrationTest.java
Labels: pr/approved

#4675 fixed(masthead dropdown): Added code to handle collapsing dropdown on…
  app/ui/package.json
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.spec.ts
  app/ui/src/app/app.module.ts
  app/ui/yarn.lock
Labels: pr/approved, pr/review-requested

#4691 Odata connector
  app/connector/odata/pom.xml
  app/connector/odata/src/main/java/io/syndesis/connector/odata/ODataConstants.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/component/ODataComponent.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractProducerCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataCreateCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataDeleteCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataPatchCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadCustomizer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/json/ClientPrimitiveValueSerializer.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataExtension.java
  app/connector/odata/src/main/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrieval.java
  app/connector/odata/src/main/resources/META-INF/syndesis/connector/odata.json
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/AbstractODataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/BaseOlingo4Test.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/ODataSerializerTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/AbstractODataReadRouteTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataRetrievalTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/meta/ODataMetaDataTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataCreateTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataDeleteTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/producer/ODataUpdateTests.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ODataTestServer.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/ProductEntityProcessor.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/Storage.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/Util.java
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-1.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-2.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3-with-count.json
  app/connector/odata/src/test/resources/io/syndesis/connector/odata/consumer/test-server-data-3.json
  app/connector/odata/src/test/resources/logback-test.xml
Labels: pr/approved, pr/review-requested

#4697 Fixes #4696, Missing RestEasy annotation in public API
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
Labels: cat/bug

#4690 fix(build): restore git commit ID in META-INF/MANIFEST.MF
  app/pom.xml
Labels: pr/approved

#4700 chore(#4692): Removes old odata module
  app/connector/old-odata/create-entity/.gitignore
  app/connector/old-odata/create-entity/pom.xml
  app/connector/old-odata/create-entity/src/main/java/io/syndesis/connector/odata/ODataCreateEntityComponent.java
  app/connector/old-odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorAutoConfiguration.java
  app/connector/old-odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorConfiguration.java
  app/connector/old-odata/create-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataCreateEntityConnectorConfigurationCommon.java
  app/connector/old-odata/create-entity/src/main/resources/META-INF/services/org/apache/camel/component/odata-create-entity
  app/connector/old-odata/create-entity/src/main/resources/META-INF/spring.factories
  app/connector/old-odata/create-entity/src/main/resources/camel-connector-schema.json
  app/connector/old-odata/create-entity/src/main/resources/camel-connector.json
  app/connector/old-odata/delete-entity/.gitignore
  app/connector/old-odata/delete-entity/pom.xml
  app/connector/old-odata/delete-entity/src/main/java/io/syndesis/connector/odata/ODataDeleteEntityComponent.java
  app/connector/old-odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorAutoConfiguration.java
  app/connector/old-odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorConfiguration.java
  app/connector/old-odata/delete-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataDeleteEntityConnectorConfigurationCommon.java
  app/connector/old-odata/delete-entity/src/main/resources/META-INF/services/org/apache/camel/component/odata-delete-entity
  app/connector/old-odata/delete-entity/src/main/resources/META-INF/spring.factories
  app/connector/old-odata/delete-entity/src/main/resources/camel-connector-schema.json
  app/connector/old-odata/delete-entity/src/main/resources/camel-connector.json
  app/connector/old-odata/model/.gitignore
  app/connector/old-odata/model/pom.xml
  app/connector/old-odata/model/src/main/java/io/syndesis/connector/odata/AbstractODataConnector.java
  app/connector/old-odata/model/src/main/java/io/syndesis/connector/odata/AbstractODataEntityConnector.java
  app/connector/old-odata/model/src/main/java/io/syndesis/connector/odata/AbstractODataResourceConnector.java
  app/connector/old-odata/model/src/main/java/io/syndesis/connector/odata/ODataResource.java
  app/connector/old-odata/pom.xml
  app/connector/old-odata/replace-entity/.gitignore
  app/connector/old-odata/replace-entity/pom.xml
  app/connector/old-odata/replace-entity/src/main/java/io/syndesis/connector/odata/ODataReplaceEntityComponent.java
  app/connector/old-odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorAutoConfiguration.java
  app/connector/old-odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorConfiguration.java
  app/connector/old-odata/replace-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataReplaceEntityConnectorConfigurationCommon.java
  app/connector/old-odata/replace-entity/src/main/resources/META-INF/services/org/apache/camel/component/odata-replace-entity
  app/connector/old-odata/replace-entity/src/main/resources/META-INF/spring.factories
  app/connector/old-odata/replace-entity/src/main/resources/camel-connector-schema.json
  app/connector/old-odata/replace-entity/src/main/resources/camel-connector.json
  app/connector/old-odata/retrieve-entity/.gitignore
  app/connector/old-odata/retrieve-entity/pom.xml
  app/connector/old-odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/ODataRetrieveEntityComponent.java
  app/connector/old-odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorAutoConfiguration.java
  app/connector/old-odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorConfiguration.java
  app/connector/old-odata/retrieve-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataRetrieveEntityConnectorConfigurationCommon.java
  app/connector/old-odata/retrieve-entity/src/main/resources/META-INF/services/org/apache/camel/component/odata-retrieve-entity
  app/connector/old-odata/retrieve-entity/src/main/resources/META-INF/spring.factories
  app/connector/old-odata/retrieve-entity/src/main/resources/camel-connector-schema.json
  app/connector/old-odata/retrieve-entity/src/main/resources/camel-connector.json
  app/connector/old-odata/update-entity/.gitignore
  app/connector/old-odata/update-entity/pom.xml
  app/connector/old-odata/update-entity/src/main/java/io/syndesis/connector/odata/ODataUpdateEntityComponent.java
  app/connector/old-odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorAutoConfiguration.java
  app/connector/old-odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorConfiguration.java
  app/connector/old-odata/update-entity/src/main/java/io/syndesis/connector/odata/springboot/ODataUpdateEntityConnectorConfigurationCommon.java
  app/connector/old-odata/update-entity/src/main/resources/META-INF/services/org/apache/camel/component/odata-update-entity
  app/connector/old-odata/update-entity/src/main/resources/META-INF/spring.factories
  app/connector/old-odata/update-entity/src/main/resources/camel-connector-schema.json
  app/connector/old-odata/update-entity/src/main/resources/camel-connector.json
Labels: pr/approved, pr/review-requested

#4669 fix(fonts): consolidate font styles/sizes
  app/ui/angular.json
  app/ui/src/app/app.component.html
  app/ui/src/app/app.component.scss
  app/ui/src/scss/patternfly-base-alacarte.scss
  app/ui/src/scss/utils/_overrides.scss
  app/ui/yarn.lock
Labels: group/ui, pr/approved, pr/review-requested

#4701 chore: Make creation of metrics configmap idem potent
  tools/upgrade/common.sh
  tools/upgrade/migration/resource/any/02_db_metrics_config_map.sh
Labels: pr/approved
