Repository syndesisio/syndesis, pull requests merged in 2019-09, with the labels that each got.

#6478 feat: various conditional flow improvements based on user feedback
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormHiddenComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormLegendComponent.tsx
  app/ui-react/packages/auto-form/stories/FormWrapper.tsx
  app/ui-react/packages/auto-form/stories/SyndesisUIs.stories.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.css
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoicePageCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, pr/review-requested, size/l

#6479 feat(connector): convert input/output to json
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindByIdTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
Labels: pr/approved, pr/review-requested

#6489 fix: thrift dependency in operator
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  install/operator/vendor/golang.org/x/tools/go/packages/golist.go
  install/operator/vendor/golang.org/x/tools/go/packages/golist_overlay.go
  install/operator/vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  install/operator/vendor/golang.org/x/tools/internal/imports/fix.go
  install/operator/vendor/golang.org/x/tools/internal/imports/imports.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mod.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mod_cache.go
  install/operator/vendor/golang.org/x/tools/internal/imports/sortimports.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/XS

#6492 user doc: Correct product name to Apache ActiveMQ.
  doc/connecting/topics/r_supported-connectors.adoc
Labels: size/XS

#6494 user doc: Update Basic filter doc to reflect updated field names
  doc/integrating-applications/topics/p_add-advanced-filter-step.adoc
  doc/integrating-applications/topics/p_add-basic-filter-step.adoc
Labels: size/m

#6495 fix: hide the configure buttons for the flow start/end connections
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: pr/approved, size/m

#6498 TEIIDTOOLS-747 Improvements to ViewEditorNavBar
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ViewEditorNavBar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/ViewEditorNavBar.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewEditorNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: pr/approved, pr/review-requested, size/l

#6496 feat [6094]: Add basic condition expression builder to conditional flows step
  app/common/model/src/main/java/io/syndesis/common/model/choice/FlowOption.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandler.java
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/ChoiceStepHandlerTest.java
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepExpanderBody.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: pr/approved, pr/review-requested

#6491 [operator] take operator tag as default tag for syndesis comp
  install/operator/build.sh
  install/operator/build/conf/config.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_operator_test.go
  install/operator/pkg/constants.go
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/action.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
Labels: pr/approved, pr/review-requested, size/l

#6462 Feat #4259 API Provider: Improve Error Handling
  app/common/model/src/main/java/io/syndesis/common/model/action/ConnectorDescriptor.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java
  app/common/util/src/main/java/io/syndesis/common/util/Properties.java
  app/common/util/src/main/java/io/syndesis/common/util/SyndesisConnectorException.java
  app/connector/api-provider/pom.xml
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ErrorMapper.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ErrorStatusInfo.java
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/ErrorMapperTest.java
  app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/CamelSqlConstants.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/JSONBeanUtil.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/SqlStatementMetaData.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlErrorCategory.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
  app/connector/twitter/pom.xml
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/TwitterCustomizer.java
  app/connector/twitter/src/main/java/io/syndesis/connector/twitter/TwitterErrorCategory.java
  app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/IntegrationRouteBuilder.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/BaseDataShapeGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/HttpStatus.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/swagger/SwaggerAPIGenerator.java
Labels: pr/approved

#6510 user doc: Add requirement for setting flow to accessCode
  doc/integrating-applications/topics/c_about-api-connectors.adoc
Labels: size/s

#6497 Cards
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsOauthCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionSetupOAuthCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionSkeleton.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorAuthorization.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailCard.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorReview.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateUpload.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.tsx
  app/ui-react/packages/ui/src/Integration/Import/ImportPageUI.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
  app/ui-react/syndesis/src/app/__mocks__/App.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx
Labels: group/ui, pr/approved, pr/review-requested, size/l

#6505 fix: bring back the integration list skeleton loader
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
Labels: pr/approved, size/m

#6511 user doc: Add restriction that you cannot map from/to a nested collection
  doc/integrating-applications/topics/p_using-data-mapper-to-process-collections.adoc
Labels: size/XS

#6509 Upgrade to PF4 Card component and fix a layout issue
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: pr/approved, pr/review-requested, size/l

#6513 TTOOLS-688 Added source table/column info for code complete feature
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6517 Fix #6493: enable camel k easily
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-750007.yaml.tmpl
  install/operator/pkg/generator/assets/addons/camelk/maven-settings.yml.tmpl
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/XXL

#6515 fix: ENTESB-11245 setting the schema in the environment
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
Labels: pr/approved, size/XS

#6520 Fixes #6506 Issue trying to save an integration
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelper.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelperTest.java
Labels: pr/approved

#6521 Get default value for syndesis components from conf file
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/tests/e2e/install_with_defaults_test.go
Labels: pr/approved, pr/review-requested, size/l

#6524 chore: fix JDBC URL typo
  doc/connecting/topics/p_create-database-connection.adoc
Labels: backport 1.6.x, backport 1.7.x, pr/approved, pr/review-requested, size/XS

#6516 TEIIDTOOLS-762 Adapt UI for view definition
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, size/XS

#6514 Upgrade UI dependencies
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationExposeVia.tsx
  app/ui-react/yarn.lock
Labels: group/ui, pr/approved, pr/review-requested, size/l

#6390 feat(typescript): update loaders, tweak webpack config
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/api/package.json
  app/ui-react/packages/api/tsconfig.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/apicurio-adapter/tsconfig.json
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/tsconfig.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/tsconfig.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/tsconfig.json
  app/ui-react/packages/utils/package.json
  app/ui-react/packages/utils/tsconfig.json
  app/ui-react/yarn.lock
Labels: group/ui, pr/approved, pr/review-requested, size/l

#6534 fix [6086]: Highlight current selected flow in dropdown
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
Labels: group/ui, pr/approved, size/XS

#6518 #5978: Adding Teiid JDBC Driver to the connector-sql connector
  app/connector/sql/pom.xml
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbAdapter.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbEnum.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/db/DbTeiid.java
  app/pom.xml
Labels: group/meta, group/server, pr/approved, pr/review-requested

#6542 fix [5673]: Add back to primary flow button
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.css
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
Labels: pr/approved, size/l

#6531 fix: bring back the integration list empty state properly
  app/ui-react/packages/ui/src/Integration/IntegrationsListView.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
Labels: pr/approved, size/m

#6538 feat: add a backup and restore sub command which can eventually be used in the upgrade process.
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/backup/backup.go
  install/operator/pkg/cmd/internal/restore/restore.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/modules.txt
Labels: pr/approved, size/l

#6544 fix [5456]: Warning on conditional flow step when default flow is required
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: pr/approved, size/l

#6389 fix(6264): Links up setting --dev in syndesis script with Debug in op…
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/install/app.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/template/install.go
  tools/bin/commands/minishift
  tools/bin/commands/util/openshift_funcs
Labels: pr/review-requested, size/s

#6537 TEIIDTOOLS-761 Reorganize the ViewEditor
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
Labels: pr/approved, pr/review-requested, size/xl

#6536 Add Jaeger support to Camel K integrations
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/IntegrationRouteLoader.java
  app/integration/runtime-camelk/src/main/java/io/syndesis/integration/runtime/camelk/tracing/IntegrationTracingContextCustomizer.java
  app/integration/runtime-camelk/src/main/resources/META-INF/services/org/apache/camel/k/customizer/tracing
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/customizer/TracingCustomizer.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/camelk/CamelKPublishHandlerTest.java
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  tools/bin/commands/kamel
Labels: pr/approved, pr/review-requested

#6545 fix operator build and include the --tag option
  .circleci/config.yml
  install/operator/.lib.sh
  install/operator/build.sh
  tools/bin/commands/build
Labels: pr/approved, pr/review-requested, size/s

#6555 fix(operator): re-vendor dependencies
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/chirino/hawtgo/sh/sh.go
  install/operator/vendor/github.com/chirino/hawtgo/sh/sh_unix.go
  install/operator/vendor/github.com/chirino/hawtgo/sh/sh_windows.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/XS

#6550 TTOOLS-748 Added "Loading query results" spinner to preview results panel
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#6563 fix(server): NPE on json log lines
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java
Labels: group/server, pr/approved, pr/review-requested

#6559 #6558: correcting the Syndesis-DV template file to make use of DevToo…
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
Labels: group/operator, pr/approved, pr/review-requested, size/s

#6553 chore(ci): store docker images as artifacts
  .circleci/config.yml
Labels: cat/build, pr/approved, size/s

#6564 fix(build): add image tag via argument for release
  tools/bin/commands/release
Labels: pr/approved, pr/review-requested, size/XS

#6562 ENTESB-10826, ENTESB-11252 - DV Wizard layout fixes
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx
Labels: pr/approved, pr/review-requested, size/l

#6565 chore(ci): triggers image transfer to quay.io
  .circleci/config.yml
Labels: cat/build, pr/approved, pr/review-requested, size/s

#6561 ENTESB-11598 - fixed virtualization item kabob Publish action
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#6566 fix(ENTESB-11398): propagate datashape changes to alternate flows
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
Labels: pr/approved, pr/review-requested, size/m

#6568 chore(text): use more appropriate fallback text
  app/ui-react/packages/api/src/WithUser.tsx
Labels: group/ui, pr/approved, pr/review-requested, size/XS

#6543 Fix for syndesis upgrade
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  tools/upgrade/Dockerfile
  tools/upgrade/common.sh
  tools/upgrade/migration/resource/01_server_config_map_upgrade.sh
  tools/upgrade/steps/prep_40_process_template
  tools/upgrade/steps/upgrade_50_replace_template
  tools/upgrade/upgrade.sh
Labels: group/operator, pr/approved, pr/review-requested, size/l

#6584 chore: Update to AtlasMap 1.42.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
Labels: group/server, pr/approved, size/s

#6581 fix(ci): fix trigger image transfer on master branch
  .circleci/config.yml
Labels: pr/approved, size/XS

#6580 FUSEDOC-3425 Remove Manage in 3scale, adjust wording and fix removing…
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationExposeVia.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: pr/approved

#6589 fix wrong library in eject command
  install/operator/go.mod
  install/operator/pkg/cmd/internal/eject/eject.go
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/modules.txt
Labels: group/operator, pr/approved, pr/review-requested, size/s

#6583 fix #6077 Add support for any data source with valid JDBC Driver
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbEnum.java
Labels: pr/approved

#6590 chore(cci): Tag PR images with PR-SHA combination
  .circleci/config.yml
Labels: pr/approved, size/XS

#6293 fix(ci): nightly CircleCi integration test execution
  .circleci/config.yml
  app/test/integration-test/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/WebHookToFtp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/quickstart/Webhook2DB_IT.java
  app/test/pom.xml
  app/test/test-support/pom.xml
  app/test/test-support/src/main/java/io/syndesis/test/SyndesisTestEnvironment.java
  app/test/test-support/src/main/java/io/syndesis/test/container/dockerfile/SyndesisDockerfileBuilder.java
  app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
  app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
  app/test/test-support/src/main/java/io/syndesis/test/integration/project/AbstractMavenProjectBuilder.java
  app/test/test-support/src/main/java/io/syndesis/test/integration/source/IntegrationExportSource.java
  tools/bin/commands/integration-test
Labels: pr/approved, pr/review-requested, size/m

#6585 ENTESB-11251 Resolve connection refresh issue in import datasource wizard
  app/ui-react/packages/api/src/useVirtualizationConnectionStatuses.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: pr/approved, pr/review-requested, size/l

#6592 operator eject reads from CR
  install/operator/pkg/cmd/internal/eject/eject.go
  install/operator/vendor/modules.txt
Labels: pr/approved, pr/review-requested, size/m

#6595 feat(connector): mongoDB cluster support
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoConfiguration.java
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/verifier/MongoConnectorVerifierExtension.java
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
  app/connector/mongodb/src/test/resources/mongodb-clustered.json
Labels: group/connector, pr/approved, pr/review-requested

#6586 chore(cards): upgrade more cards to pf4
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
Labels: group/ui, pr/approved, pr/review-requested, size/l, size/m

#6512 ENTESB-11263: Add scheduled to CR for meta, server, ui and s2i
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/install/app.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
Labels: pr/approved, pr/review-requested, size/l

#6600 fix(ci): fix trigger image transfer on master branch
  .circleci/config.yml
Labels: cat/build, pr/approved, size/XS

#6587 remove generator folder, not needed anymore and can lead to confusion
  install/generator/01-header.yml.mustache
  install/generator/02-syndesis-image-streams.yml.mustache
  install/generator/02-syndesis-secrets.yml.mustache
  install/generator/02-syndesis-service-accounts.yml.mustache
  install/generator/03-syndesis-ui.yml.mustache
  install/generator/04-amq-example.yml.mustache
  install/generator/04-syndesis-db.yml.mustache
  install/generator/04-syndesis-meta.yml.mustache
  install/generator/04-syndesis-oauth-proxy.yml.mustache
  install/generator/04-syndesis-server.yml.mustache
  install/generator/04-teiid-komodo-server.yml.mustache
  install/generator/04-todo-example.yml.mustache
  install/generator/05-syndesis-security.yml.mustache
  install/generator/06-syndesis-prometheus.yml.mustache
  install/generator/07-syndesis-upgrade.yml.mustache
  install/generator/run.sh
  install/generator/syndesis-template.go
  tools/bin/commands/build
  tools/bin/commands/release
  tools/upgrade/.gitignore
  tools/upgrade/build.sh
Labels: pr/approved, pr/review-requested, size/XXL

#6508 Fix #6507: fix jaeger configuration
  app/common/jaeger-spring-boot-starter/src/main/java/io/syndesis/common/jaeger/JaegerConfiguration.java
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/application.properties.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/application-tracing.properties
Labels: group/integration, pr/approved, pr/review-requested

#6549 ENTESB-11571 Update respective fuse artifacts to 7.4 versions
  app/integration/bom-camel-k/pom.xml
  app/pom.xml
Labels: cat/build, pr/approved, size/XS

#6612 chore: cd -P to the operator directory before building so that you can checkout syndesis to the GOPATH and setup a symlink to a more convenient location and still have the go build work if you build in the symlinked path.
  install/operator/build.sh
Labels: pr/approved, size/XS

#6613 chore: remove the dead `syndesis build --ensure` option.
  .circleci/config.yml
  tools/bin/commands/build
Labels: pr/approved, size/s

#6607 ENTESB-11608 - correct inconsistent footer in DV wizards
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
Labels: pr/approved, pr/review-requested, size/s

#6601 fix(FUSEQE-6017): Add data-testid for "Add another" button
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: pr/approved, size/XS

#6617 fix(atlasmap-assembly): remove routing related console warning
  app/ui-react/packages/atlasmap-assembly/src/app/app.module.ts
  app/ui-react/syndesis/scripts/minishift-restore.sh
  app/ui-react/syndesis/scripts/minishift-setup.sh
Labels: pr/approved, size/XS

#6603 TTOOLS-753 Remove service vdb name usage
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationHandlers.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: bot-kick, pr/approved, pr/review-requested, size/m

#6621 fix: app CR template was not correct, added unit test to avoid this type of problem in the future.
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/install/install_render_test.go
  install/operator/pkg/generator/assets/install/app.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/m

#6622 chore: Improve operator debug output by showing the update diff on the resources.
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/util/create_or_update.go
  install/operator/pkg/util/debug.go
Labels: pr/approved, size/s

#6606 fix(TEIIDTOOLS-771) - View Editor - prompt user for pending changes if navigating away
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: pr/approved, pr/review-requested, size/l

#6626 chore: Update to AtlasMap 1.42.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.prod.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.ts
Labels: pr/approved, size/s

#6618 fix(build): remove template generation
  tools/bin/commands/release
Labels: size/XS

#6620 fix(ui/api): handle unrecoverable errors with the api provider/connector
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
Labels: group/ui, pr/approved, size/s

#6627 Fixes ENTESB-11653: Fixed incomplete unit test, fixed export endpoint by looking up environment ids instead of names
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: group/server, pr/approved

#6599 set upgrade pod version
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  tools/bin/commands/release
Labels: backport 1.8.x, group/operator, pr/approved, pr/review-requested, size/XS

#6630 port https://github.com/syndesisio/syndesis/pull/6599
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  tools/bin/commands/release
Labels: size/s

#6623 feat: add the go to operation list button back
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.css
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.tsx
  app/ui-react/packages/ui/src/Integration/EditorToolbarDropdownBackButtonItem.css
  app/ui-react/packages/ui/src/Integration/EditorToolbarDropdownBackButtonItem.tsx
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.css
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: backport 1.8.x, size/l

#6629 chore(connector): set the TP flag for mongo
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
  app/ui-react/syndesis/public/icons/mongodb.png
Labels: backport 1.8.x, group/connector, pr/approved

#6619 [ENTESB-11495] Mapping variables also on options, not only from the body
  app/connector/aws-ddb/pom.xml
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Labels: pr/approved

#6632 fix: don’t clear the Route spec.host field since its updated/changed by openshift.
  install/operator/pkg/util/create_or_update.go
Labels: pr/approved, size/XS

#6634 Don’t punish the default settings on the CR since this will cause problems with future updates since it locks in the default settings (like image tag names).
  install/operator/pkg/syndesis/action/install.go
Labels: size/m

#6605 fix(6347): Removes Env variable from operator templates
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-secrets.yml.mustache
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-secrets.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/05-syndesis-security.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets/route/route.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/openshift/register.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/configuration/envvars.go
  install/operator/pkg/syndesis/legacy/controller.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/util/create_or_update.go
  install/operator/vendor/github.com/hoisie/mustache/.gitignore
  install/operator/vendor/github.com/hoisie/mustache/LICENSE
  install/operator/vendor/github.com/hoisie/mustache/Makefile
  install/operator/vendor/github.com/hoisie/mustache/Readme.md
  install/operator/vendor/github.com/hoisie/mustache/mustache.go
  install/operator/vendor/modules.txt
Labels: pr/review-requested

#6641 fix(TEIIDTOOLS-769) - View Editor sizing issues
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor-styling.css
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/m

#6644 user doc: Add a readme file, asciidoc tips, and delete an unneeded file.
  doc/master.adoc
  doc/readme.adoc
  doc/tips-for-creating-asciidoc-content.adoc
Labels: size/xl

#6638 fix: update ci/cd page validation and state handling
  app/ui-react/packages/api/src/WithEnvironmentHelpers.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/l

#6637 Port from #6619
  app/connector/aws-ddb/pom.xml
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Labels: backport 1.8.x, pr/approved

#6647 fix(build): prevent staging of test modules
  app/test/pom.xml
Labels: backport 1.8.x, cat/build, pr/approved

#6640 chore: polish connection page skeleton loaders
  app/ui-react/packages/ui/src/Connection/ConnectionSkeleton.tsx
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
Labels: backport 1.8.x, group/ui, pr/approved, pr/review-requested, size/m

#6646 feat(s2i): add a PNC maven profile
  app/s2i/pom.xml
Labels: backport 1.8.x, group/s2i, pr/approved, pr/review-requested, size/s

#6643 ENTESB-11643 Rework of virtualization create form
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationCreateForm.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/l

#6655 Fixes ENTESB-11690, relaxed strict check for 1 replica to avoid incorrect Stopped status when integration is scaled
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
Labels: backport 1.8.x, pr/approved, pr/review-requested

#6654 fix: better communication between components
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/cicd/ManageCiCdPage.tsx
Labels: backport 1.8.x, group/ui, pr/approved, size/m

#6648 Add a profile to set a custom-cafile
  app/ui-react/pom.xml
Labels: backport master, cat/build, pr/approved, pr/review-requested, size/s

#6662 Fixes ENTESB-11640, Fixes ENTESB-10194, edit an existing deploy…
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: backport 1.8.x, group/server

#6636 [ENTESB-11669] Remove Syndesis registry from Prometheus image prefix
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
Labels: pr/approved, pr/review-requested, size/XS

#6664 chore: remove tooltips tooling
  doc/pom.xml
  doc/tools/pom.xml
  doc/tools/syndesis-documentation-maven-plugin/README.adoc
  doc/tools/syndesis-documentation-maven-plugin/pom.xml
  doc/tools/syndesis-documentation-maven-plugin/src/main/java/io/syndesis/server/builder/maven/TooltipExtractorMojo.java
  doc/tools/syndesis-documentation-maven-plugin/src/test/java/io/syndesis/server/builder/maven/TooltipExtractorMojoTest.java
  doc/tools/syndesis-documentation-maven-plugin/src/test/resources/model.adoc
  doc/tools/syndesis-documentation-maven-plugin/src/test/resources/model.json
  doc/tools/syndesis-documentation-maven-plugin/src/test/resources/parse.py
  doc/tooltips/README.adoc
  doc/tooltips/tooltips.json
Labels: cat/build, pr/approved, pr/review-requested

#6670 1.8.x
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr_minimal.yaml
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport master, group/operator, pr/approved, pr/review-requested, size/s

#6673 Suppress the installation of cypress binaries
  app/ui-react/pom.xml
Labels: backport master, pr/approved, pr/review-requested, size/XS

#6658 ENTESB-11607 Limits selected tables in create view wizard
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6666 fix(ENTESB-11388): Use server side calculation for integration uptime
  app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationDeploymentMetrics.java
  app/common/model/src/main/java/io/syndesis/common/model/metrics/IntegrationMetricsSummary.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/metrics/SQLMetricsProviderImpl.java
  app/server/metrics/jsondb/src/main/java/io/syndesis/server/metrics/jsondb/IntegrationMetricsHandler.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/ui-react/packages/api/src/WithIntegrationMetrics.tsx
  app/ui-react/packages/api/src/WithIntegrationsMetrics.tsx
  app/ui-react/packages/models/swagger.internal.json
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/packages/ui/stories/Integration/Metrics/IntegrationDetailsMetrics.stories.tsx
  app/ui-react/packages/utils/src/dateHelpers.ts
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
Labels: backport 1.8.x, pr/approved

#6676 fix: documentation build in the daily release
  doc/index.adoc
  doc/pom.xml
Labels: cat/build, pr/approved, pr/review-requested, size/s

#6677 fix(ENTESB-11273): Fix required column names configuration for Google Sheets
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
Labels: backport 1.8.x, pr/approved

#6657 fix(ENTESB-11247) - Detail page of Virtualization doesn't contain state of publishing
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/m

#6684 user doc: Add directory for customization content
  doc/customizing/assemblies/customizing
  doc/customizing/assemblies/integrating-applications
  doc/customizing/attributes-links.adoc
  doc/customizing/attributes.adoc
  doc/customizing/docinfo.xml
  doc/customizing/images/customizing
  doc/customizing/images/integrating-applications
  doc/customizing/master.adoc
  doc/customizing/modules/customizing
  doc/customizing/modules/integrating-applications
Labels: size/m

#6672 Fixes #6671: add check to verify tracer is given
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/tracing/TracingActivityTrackingPolicy.java
Labels: backport 1.8.x, pr/approved

#6686 chore: Update to AtlasMap 1.42.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
Labels: pr/approved, size/XS

#6688 add some documentation for syndesis CR
  install/operator/README.md
Labels: backport 1.8.x, group/operator, pr/approved, size/m

#6690 fix(ENTESB-11697): Render data testid property in text buttons
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
Labels: backport 1.8.x, pr/approved, size/XS

#6695 user doc: Fix 2 typos. Make shared images available to connector guide.
  doc/connecting/images/tutorials
  doc/customizing/images/tutorials
  doc/modules/customizing/p_using-maven-to-generate-extension-definitions.adoc
  doc/modules/customizing/r_develop-connector-extensions.adoc
Labels: pr/approved, size/XS

#6694 fix: syndesis release command
  tools/bin/commands/release
Labels: backport 1.8.x

#6698 fix: ENTESB-11711 syndesis server deployment config keeps getting upd…
  install/operator/pkg/util/create_or_update.go
Labels: backport 1.8.x, size/s

#6652 chore: remove dependency on oc for the backup and restore sub commands. Handle shrinking arrays on resource updates. Support using the NAMESPACE env var to set the default namespace commands execute against.
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/backup/backup.go
  install/operator/pkg/cmd/internal/restore/restore.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/util/create_or_update.go
  install/operator/pkg/util/kube.go
  install/operator/vendor/github.com/docker/spdystream/CONTRIBUTING.md
  install/operator/vendor/github.com/docker/spdystream/LICENSE
  install/operator/vendor/github.com/docker/spdystream/LICENSE.docs
  install/operator/vendor/github.com/docker/spdystream/MAINTAINERS
  install/operator/vendor/github.com/docker/spdystream/README.md
  install/operator/vendor/github.com/docker/spdystream/connection.go
  install/operator/vendor/github.com/docker/spdystream/handlers.go
  install/operator/vendor/github.com/docker/spdystream/priority.go
  install/operator/vendor/github.com/docker/spdystream/spdy/dictionary.go
  install/operator/vendor/github.com/docker/spdystream/spdy/read.go
  install/operator/vendor/github.com/docker/spdystream/spdy/types.go
  install/operator/vendor/github.com/docker/spdystream/spdy/write.go
  install/operator/vendor/github.com/docker/spdystream/stream.go
  install/operator/vendor/github.com/docker/spdystream/utils.go
  install/operator/vendor/github.com/sirupsen/logrus/appveyor.yml
  install/operator/vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  install/operator/vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/doc.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/reader.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/resize.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/v1.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/v2.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/v3.go
  install/operator/vendor/k8s.io/client-go/tools/remotecommand/v4.go
  install/operator/vendor/k8s.io/client-go/transport/spdy/spdy.go
  install/operator/vendor/k8s.io/client-go/util/exec/exec.go
  install/operator/vendor/modules.txt
Labels: size/XXL

#6702 fix: preserve select control semantics
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/m

#6701 fix(6535) Incorrect font type and styling for definition list on multiple pages
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewOutputToolbar.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorOutputPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/index.ts
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/xl

#6707 user doc: Rename Apicurito to API Designer
  doc/modules/customizing/c_guidelines-for-openapi-documents.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
  doc/modules/integrating-applications/p_creating-api-connectors.adoc
  doc/modules/integrating-applications/p_updating-api-connectors.adoc
  doc/modules/integrating-applications/r_requirements-for-api-provider-integrations.adoc
  doc/shared/attributes-links.adoc
  doc/shared/attributes.adoc
Labels: backport 1.8.x, pr/approved, size/m

#6669 [operator] replace eject for install standalone
  install/operator/pkg/cmd/internal/eject/eject.go
  install/operator/pkg/cmd/internal/eject/eject_test.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-service-accounts.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/serviceaccount/01-syndesis-oauth-client.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/modules.txt
Labels: backport 1.8.x, group/operator, pr/approved, pr/review-requested, size/xl

#6706 fix(ENTESB-11672) - SQL Client results are not horizontally scrollable
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/m

#6715 [ENTESB-11495] Adding Remove Operation
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizer.java
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/customizer/DDBConnectorCustomizerRemoveItem.java
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataRetrieval.java
  app/connector/aws-ddb/src/main/java/io/syndesis/connector/aws/ddb/util/Util.java
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBConfiguration.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBGenericOperation.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBInsertItemTest.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/AWSDDBQueryItemTest.java
  app/connector/aws-ddb/src/test/java/io/syndesis/connector/aws/ddb/metadata/AWSDDBMetadataAdapterTest.java
Labels: backport 1.8.x, cat/enhancement, pr/approved

#6719 chore: Update to AtlasMap 1.42.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.8.x, pr/approved, size/s

#6691 fix(ui): more user-friendly message with invalid oauth credentials
  app/ui-react/syndesis/src/modules/connections/useOAuthFlow.ts
Labels: pr/approved, size/s

#6714 fix: #6713 don't log resource diffs by default since they could conta…
  install/operator/go.mod
  install/operator/pkg/cmd/internal/backup/backup.go
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/restore/restore.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/util/create_or_update.go
  install/operator/vendor/modules.txt
Labels: backport 1.8.x, size/m

#6724 ENTESB-11282 - Google calendars select calendar dropdown changed to t…
  app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/XS

#6730 user doc: Change path for images in all books
  doc/connecting/master.adoc
  doc/customizing/master.adoc
  doc/integrating-applications/master.adoc
  doc/modules/connecting/p_add-google-calendar-connection-to-get-one-event.adoc
  doc/modules/connecting/p_add-servicenow-connection-finish.adoc
  doc/modules/connecting/p_register-with-dropbox.adoc
  doc/modules/connecting/p_register-with-google.adoc
  doc/modules/connecting/p_registering-with-jira.adoc
  doc/modules/connecting/p_registering-with-rest-api.adoc
  doc/modules/customizing/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
  doc/modules/customizing/r_how-to-specify-data-shapes.adoc
  doc/modules/integrating-applications/c_about-adding-steps.adoc
  doc/modules/integrating-applications/c_about-integration-lifecycle-handling.adoc
  doc/modules/integrating-applications/c_overview-benefit-api-provider-integrations.adoc
  doc/modules/integrating-applications/c_workflow-overview.adoc
  doc/modules/integrating-applications/p_add-advanced-filter-step.adoc
  doc/modules/integrating-applications/p_add-aggregate-step.adoc
  doc/modules/integrating-applications/p_add-basic-filter-step.adoc
  doc/modules/integrating-applications/p_add-custom-step.adoc
  doc/modules/integrating-applications/p_add-data-mapping-step.adoc
  doc/modules/integrating-applications/p_add-split-step.adoc
  doc/modules/integrating-applications/p_add-template-step.adoc
  doc/modules/integrating-applications/p_adding-conditional-execution-flows.adoc
  doc/modules/integrating-applications/p_applying-conditions-to-mappings.adoc
  doc/modules/integrating-applications/p_combine-multiple-source-fields-into-one-target-field.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
  doc/modules/integrating-applications/p_deleting-integrations.adoc
  doc/modules/integrating-applications/p_exporting-integrations.adoc
  doc/modules/integrating-applications/p_identify-where-data-mapping-is-needed.adoc
  doc/modules/integrating-applications/p_importing-integrations.adoc
  doc/modules/integrating-applications/p_map-one-source-field-to-one-target-field.adoc
  doc/modules/integrating-applications/p_procedure-for-creating-an-integration.adoc
  doc/modules/integrating-applications/p_restarting-older-integration-versions.adoc
  doc/modules/integrating-applications/p_separate-one-source-field-into-multiple-target-fields.adoc
  doc/modules/integrating-applications/p_starting-integrations.adoc
  doc/modules/integrating-applications/p_stopping-integrations.adoc
  doc/modules/integrating-applications/p_updating-integrations.adoc
  doc/modules/integrating-applications/p_using-data-mapper-to-process-collections.adoc
  doc/modules/integrating-applications/p_view-mappings-in-a-step.adoc
  doc/modules/integrating-applications/p_viewing-integration-history.adoc
  doc/modules/integrating-applications/r_find-data-field-you-want-to-map.adoc
  doc/modules/integrating-applications/r_how-to-specify-request.adoc
  doc/modules/integrating-applications/r_mapping-between-collections-and-non-collections.adoc
  doc/modules/integrating-applications/r_publishing-integrations.adoc
  doc/modules/integrating-applications/r_requirements-for-api-provider-integrations.adoc
  doc/modules/integrating-applications/r_viewing-and-editing-connection-information.adoc
  doc/modules/integrating-applications/r_workflow-example.adoc
  doc/modules/tutorials/p_amq2api-add-mapping-step.adoc
  doc/modules/tutorials/p_amq2api-name-and-publish.adoc
  doc/modules/tutorials/p_clean-up.adoc
  doc/modules/tutorials/p_register-with-sf.adoc
  doc/modules/tutorials/p_register-with-twitter.adoc
  doc/modules/tutorials/p_sf2db-name-and-publish.adoc
  doc/modules/tutorials/p_t2sf-add-mapping-step.adoc
  doc/modules/tutorials/p_t2sf-name-and-publish.adoc
  doc/tutorials/master.adoc
Labels: backport 1.8.x, pr/approved, size/l

#6727 set docker registry and prefix per image base
  install/operator/README.md
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/template/install.go
Labels: group/operator, pr/approved, pr/review-requested, size/l

#6723 ENTESB-11479 - Box - allow to map something to the fileId in box connector
  app/connector/box/src/main/java/io/syndesis/connector/box/BoxFileDownload.java
  app/connector/box/src/main/java/io/syndesis/connector/box/customizer/BoxDownloadCustomizer.java
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
Labels: backport 1.8.x, pr/approved

#6733 chore: bring in some previously written config property docs for auto-form
  app/ui-react/README.md
  app/ui-react/packages/auto-form/README.md
Labels: pr/approved

#6721 ENTESB-11720: Removes preview banner from email connector
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-receive.json
  app/connector/email/src/main/resources/META-INF/syndesis/connector/email-send.json
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/s

#6705 ENTESB-11644 and 11630 - added FQN for table names and fixed title header layout
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/l

#6718 fix(ENTESB-11647) - Preview section updates for improved usability
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/l

#6711 fix(ENTESB-11578): Improve conditional flow usability
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/DescribeChoiceDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: backport 1.8.x, group/ui, pr/approved, pr/review-requested, size/l

#6741 fix copy and paste error
  install/operator/pkg/syndesis/template/install.go
Labels: size/XS

#6742 user doc: New doc for using MongoDB connector
  doc/assemblies/connecting/as_connecting-to-mongodb.adoc
  doc/connecting/master.adoc
  doc/modules/connecting/p_add-google-calendar-connection-add-event.adoc
  doc/modules/connecting/p_adding-kafka-connection-start.adoc
  doc/modules/connecting/p_adding-mongodb-connections-read.adoc
  doc/modules/connecting/p_adding-mongodb-connections-write.adoc
  doc/modules/connecting/p_create-gmail-connection.adoc
  doc/modules/connecting/p_creating-jira-connections.adoc
  doc/modules/connecting/p_creating-mongodb-connections.adoc
  doc/modules/connecting/r_supported-connectors.adoc
Labels: backport 1.8.x, size/l

#6738 Master backport 6670
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_cr_minimal.yaml
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: pr/approved, size/m

#6728 feat: Add a CR config option to disable SAR checking in the auth proxy.
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
Labels: backport 1.8.x, pr/approved, size/XS

#6740 Backporting #6669 to 1.8.x
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/cmd/internal/eject/eject.go
  install/operator/pkg/cmd/internal/eject/eject_test.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/serviceaccount/01-syndesis-oauth-client.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/go-openapi/jsonpointer/go.mod
  install/operator/vendor/github.com/go-openapi/jsonpointer/go.sum
  install/operator/vendor/github.com/go-openapi/jsonpointer/pointer.go
  install/operator/vendor/github.com/go-openapi/spec/bindata.go
  install/operator/vendor/github.com/go-openapi/spec/go.mod
  install/operator/vendor/github.com/go-openapi/spec/go.sum
  install/operator/vendor/github.com/go-openapi/spec/schema_loader.go
  install/operator/vendor/github.com/go-openapi/swag/convert.go
  install/operator/vendor/github.com/go-openapi/swag/json.go
  install/operator/vendor/github.com/go-openapi/swag/util.go
  install/operator/vendor/github.com/go-openapi/swag/yaml.go
  install/operator/vendor/github.com/sirupsen/logrus/appveyor.yml
  install/operator/vendor/modules.txt
Labels: pr/approved, size/xl

#6746 [ENTESB-11593] Forcing the channel to be selected from a list, no free text
  app/connector/slack/src/main/resources/META-INF/syndesis/connector/slack.json
Labels: backport 1.8.x, pr/approved, size/XS

#6748 [ENTESB-11717] Adding technology preview to dynamoDB
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: backport 1.8.x, pr/approved, size/XS

#6750 (chore) Fix operator test for komodo tag
  install/operator/pkg/generator/generator_test.go
Labels: pr/approved, pr/review-requested, size/XS

#6735 ENTESB-11729: Upgrade of fuse-camel
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteNoSplitResultsTest.java
  app/connector/odata/src/test/java/io/syndesis/connector/odata/consumer/ODataReadRouteSplitResultsTest.java
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-750029.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport 1.8.x, pr/approved, pr/review-requested

#6753 [ENTESB-11704] Fixing placeholder with proper quotes
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: backport 1.8.x, pr/approved, size/XS

#6745 chore: the openapi generation is working again. Adding more comments to the api types so that the openapi docs have some more details.
  install/operator/.lib.sh
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/spf13/pflag/README.md
  install/operator/vendor/github.com/spf13/pflag/bool_slice.go
  install/operator/vendor/github.com/spf13/pflag/count.go
  install/operator/vendor/github.com/spf13/pflag/duration_slice.go
  install/operator/vendor/github.com/spf13/pflag/flag.go
  install/operator/vendor/github.com/spf13/pflag/float32_slice.go
  install/operator/vendor/github.com/spf13/pflag/float64_slice.go
  install/operator/vendor/github.com/spf13/pflag/go.mod
  install/operator/vendor/github.com/spf13/pflag/go.sum
  install/operator/vendor/github.com/spf13/pflag/int32_slice.go
  install/operator/vendor/github.com/spf13/pflag/int64_slice.go
  install/operator/vendor/github.com/spf13/pflag/int_slice.go
  install/operator/vendor/github.com/spf13/pflag/ip_slice.go
  install/operator/vendor/github.com/spf13/pflag/string_array.go
  install/operator/vendor/github.com/spf13/pflag/string_slice.go
  install/operator/vendor/github.com/spf13/pflag/string_to_int64.go
  install/operator/vendor/github.com/spf13/pflag/uint_slice.go
  install/operator/vendor/modules.txt
Labels: pr/approved, size/xl

#6756 fix(ENTESB-11578): Fix required form field validation for conditional flow
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/s

#6722 fix: #6567 Drop image streams and use direct image references. Also simplify operator config.yaml and CR by configuring full image names there.
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install_standalone.go
  install/operator/pkg/generator/assets/addons/camelk/maven-settings.yml.tmpl
  install/operator/pkg/generator/assets/addons/komodo/addon-komodo-server.yml.tmpl
  install/operator/pkg/generator/assets/addons/legacyui/addon-legacyui.yml
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-secrets.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/checkupdates.go
  install/operator/pkg/syndesis/action/initialize.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/install_test.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/template/install.go
  install/operator/pkg/syndesis/template/upgrade.go
  install/operator/pkg/util/template_functions.go
  install/operator/tests/e2e/install_with_defaults_test.go
  install/operator/tests/e2e/utils.go
Labels: pr/approved, pr/review-requested

#6731 fix: #6713 don't log resource diffs by default since they could conta…
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/backup/backup.go
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/restore/restore.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/util/create_or_update.go
Labels: size/XXL

#6759 ENTESB-11692 Disallow unpublish virtualization if used
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/l

#6653 fix(ui): show the error message on failed saves
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
Labels: backport 1.8.x, pr/approved, pr/review-requested, size/m

#6762 fix: switching between devSupport modes was not working correctly. Image name was not being set to needed value.
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/util/create_or_update.go
Labels: size/m

#6757 fix(ENTESB-11758): Fix form field rendering on metadata lookup
  app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/action/DynamicActionSalesforceITCase.java
Labels: backport 1.8.x, pr/approved, pr/review-requested

#6768 [ENTESB-11965] Fix DV UI enabled by default
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
Labels: pr/approved, pr/review-requested, size/s
