Repository syndesisio/syndesis, pull requests merged in 2020-12, with the labels that each got.

#9215 ENTESB-15364: Allow backup/restore to have images defined by config
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/backup/syndesis-backup-job.yml.tmpl
  install/operator/pkg/generator/assets/backup/syndesis-restore-job.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/backup/backup.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/m

#9221 Backport Fix for ENTESB-15145 - upgrade commons compress version
  app/pom.xml
Labels: size/XS

#9220 Fix for ENTESB-15145 - upgrade commons compress version
  app/pom.xml
Labels: size/XS

#9224 fix for ENTESB-12104 - demoData flag used to add sampledb
  install/operator/go.sum
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9243 fix: configured vs default values in API connector
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/__test__/utils.spec.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/utils.ts
Labels: size/l

#9245 refactor(ci): remove passing token
  .github/workflows/backport.yml
Labels: backport 1.12.x, size/XS

#9247 chore(sql): support UUID column type in PostgreSQL
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlMetadataRetrievalTest.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/PostgreSqlMetaDataITCase.java
Labels: backport 1.12.x
