Repository syndesisio/syndesis, pull requests merged in 2020-01, with the labels that each got.

#7487 Add option to install syndesis with options to the syndesis-operator …
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: size/s

#7493 user doc: Add xref to Syndesis community doc for developing connectors
  doc/modules/customizing/r_develop-connector-extensions.adoc
Labels: size/XS

#7495 [Backport-1.9.x]: chore(build): enable proxy.golang.org
  .circleci/config.yml
  app/connector/rest-swagger/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760016.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: size/XS

#7499 fix: Upgrades camel version to released version 2.23.2.fuse-760016
  app/connector/rest-swagger/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760016.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: size/m

#7446 feat(ENTESB-12479) - support for creatable typeahead options in autoform
  app/ui-react/packages/auto-form/src/AutoFormContext.tsx
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormTypeaheadComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/index.ts
  app/ui-react/packages/auto-form/stories/Typeahead.stories.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
Labels: size/l

#7503 1.9.x backports
  app/dv/pom.xml
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/ServiceVdbGenerator.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/EditorServiceTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationPublishTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceVdbGeneratorTest.java
  app/dv/src/test/resources/generated-pom.xml
  app/pom.xml
Labels: group/datavirt

#7506 TEIIDTOOLS-811 DV Sql results table backport
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
  app/ui-react/packages/ui/src/Shared/GenericTable.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
  app/ui-react/packages/ui/stories/Shared/GenericTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: size/xl

#7507 TEIIDTOOLS-880 Create View wizard improvements backport
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/CreateViewHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/CreateViewHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewCreateSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: size/xl

#7488 fix: multi select tables from diff connection issue
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
Labels: backport 1.9.x, group/datavirt, size/m

#7498 fix: Show the column details for selected tables
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Labels: backport 1.9.x, group/datavirt, size/m

#7505 Fixes ENTESB-12178, initial version of Public API addon
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/generator/assets/addons/publicApi/addon-public-oauthproxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/install/grant_public_api_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/support/syndesis-public-oauth-proxy.yml
Labels: size/l

#7511 Create view backports
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Labels: size/l

#7512 feat: add full keywords and functions to editor code completion list
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DvAutocomplete.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: size/l

#7414 [ENTESB-12533] Fix selecting PV by labels
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
Labels: backport 1.9.x, pr/review-requested, size/s

#7513 chore: Update to AtlasMap 1.43.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
Labels: size/XS

#7510 fix(ENTESB-12424): specification of an external database
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/envvars.go
Labels: size/l

#7517 chore(deps): update yarn.lock
  app/ui-react/yarn.lock
Labels: size/XS

#7456 chore(build): patch mirrorOf to exclude local-repository
  app/s2i/pom.xml
Labels: pr/approved, size/s

#7518 fix(ENTESB-12218): Add schema validation for OpenAPI 3.x
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiSchemaValidator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20SchemaValidator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30SchemaValidator.java
  app/server/api-generator/src/main/resources/schema/openapi-3.0-schema.json
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20SchemaValidatorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30SchemaValidatorTest.java
Labels: backport 1.9.x

#7451 [Backport-1.9.x]: Change DDB connector name
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: size/XS

#7523 chore: Update camel version to 2.23.2.fuse-760017
  app/connector/aws-sqs/src/main/java/io/syndesis/connector/aws/sqs/AWSSQSBatchMessagesCustomizer.java
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760017.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: backport 1.9.x

#7522 BACKPORT: Commits for jaeger support in the operator
  install/operator/pkg/cmd/internal/install/custom_app_test.yml
  install/operator/pkg/cmd/internal/install/default_app_test.yml
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_app.go
  install/operator/pkg/cmd/internal/install/install_app_test.go
  install/operator/pkg/cmd/internal/install/install_cluster.go
  install/operator/pkg/generator/assets/addons/jaeger/server_operator.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster/camelk.yml
  install/operator/pkg/generator/assets/install/cluster/jaeger.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: size/xl

#7525 chore(build): patch mirrorOf to exclude local-repository
  app/s2i/pom.xml
Labels: size/s

#7527 [Backport 1.9.x] fix: rework VirtualizationListItem
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
Labels: group/datavirt, size/s

#7521 [ENTESB-12533] Fix selecting PV by labels
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
Labels: size/s

#7528 BACKPORT: fix(ENTESB-12424): specification of an external datab…
  install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/envvars.go
  install/operator/vendor/github.com/robfig/cron/v3/LICENSE
  install/operator/vendor/github.com/robfig/cron/v3/README.md
  install/operator/vendor/github.com/robfig/cron/v3/chain.go
  install/operator/vendor/github.com/robfig/cron/v3/constantdelay.go
  install/operator/vendor/github.com/robfig/cron/v3/cron.go
  install/operator/vendor/github.com/robfig/cron/v3/doc.go
  install/operator/vendor/github.com/robfig/cron/v3/go.mod
  install/operator/vendor/github.com/robfig/cron/v3/logger.go
  install/operator/vendor/github.com/robfig/cron/v3/option.go
  install/operator/vendor/github.com/robfig/cron/v3/parser.go
  install/operator/vendor/github.com/robfig/cron/v3/spec.go
  install/operator/vendor/modules.txt
Labels: size/xl

#7539 fix(ui): `value` instead of `label` in typeahead
  app/ui-react/packages/auto-form/src/widgets/FormTypeaheadComponent.tsx
Labels: size/XS

#7432 [ENTESB-12331] Improved Kafka broker discovery using custom cla…
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/KafkaResource.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/KafkaResourceDoneable.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/model/crd/KafkaResourceList.java
Labels: cat/enhancement, pr/review-requested

#7540 BACKPORT: ENTESB-12385: Disable extensions if camelk addon is enabled
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7537 fix: removing the version details from the DV list view
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
Labels: size/XS

#7555 refactor: archive deployment configuration
  app/pom.xml
  app/s2i/pom.xml
  app/ui-react/pom.xml
Labels: size/XS

#7554 refactor: archive deployment configuration
  app/pom.xml
  app/s2i/pom.xml
  app/ui-react/pom.xml
Labels: size/XS

#7558 user doc: Fix two typos and clarify one sentence.
  doc/modules/connecting/p_adding-mongodb-connections-read.adoc
  doc/modules/connecting/p_obtaining-email-to-trigger-integration-execution.adoc
  doc/modules/tutorials/p_register-with-twitter.adoc
Labels: size/XS

#7562 chore: Update to AtlasMap 1.43.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: backport 1.9.x, size/s

#7559 refactor(build): archive deployment profile
  app/s2i/pom.xml
  app/ui-react/pom.xml
Labels: size/l

#7560 refactor(build): archive deployment profile
  app/s2i/pom.xml
  app/ui-react/pom.xml
Labels: size/l

#7572 user doc: Remove Tech Preview note for DynamoDB connector
  doc/assemblies/connecting/as_connecting-to-amazon-dynamodb.adoc
Labels: size/s

#7561 TEIIDTOOLS-899 fix virtualization status init issue with VirtualizationEditorPage
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.9.x, group/datavirt, size/m

#7570 ENTESB-12070: fix knative activation
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport master, size/XS

#7574 user doc: update Box connector doc
  doc/assemblies/connecting/as_connecting-to-box.adoc
  doc/modules/connecting/p_adding-box-connection-finish.adoc
  doc/modules/connecting/p_adding-box-connection-middle.adoc
  doc/modules/connecting/r_how-to-specify-the-schema-in-a-database-connection.adoc
Labels: size/m

#7575 Connector consolidation. AWS Dynamo DB, Mongo DB and Box are no longer Tech Preview.
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
Labels: size/XS

#7573 ENTESB-12070: fix knative activation
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7576 Connector consolidation. AWS Dynamo DB, Mongo DB and Box are no longer Tech Preview.
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
  app/connector/box/src/main/resources/META-INF/syndesis/connector/box.json
  app/connector/mongodb/src/main/resources/META-INF/syndesis/connector/mongodb3.json
Labels: size/XS

#7592 TEIIDTOOLS-837 fix connection display with Create View Wizard
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualizationRuntimeMetadata.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.9.x, group/datavirt, size/l

#7606 chore: Update to AtlasMap 1.43.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7607 chore: Update to AtlasMap 1.43.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7604 fix: Use the connection name instead of the connector name in t…
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/XS

#7605 DV backports
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useVirtualizationRuntimeMetadata.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: group/datavirt, size/l

#7614 fix: Use the connection name instead of the connector name in t…
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/XS

#7625 fix(tools): fix pre-commit configuration
  package.json
Labels: size/XS

#7627 Issue #7616 aligned all jackson components for DV to the 2.9.x versions
  app/dv/pom.xml
Labels: size/XS

#7603 TEIIDTOOLS-909 minimizing datasource creation
  app/dv/src/main/java/io/syndesis/dv/datasources/DefaultSyndesisDataSource.java
  app/dv/src/main/java/io/syndesis/dv/metadata/TeiidDataSource.java
  app/dv/src/main/java/io/syndesis/dv/metadata/internal/TeiidDataSourceImpl.java
  app/dv/src/main/java/io/syndesis/dv/openshift/SyndesisConnectionSynchronizer.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
Labels: backport 1.9.x, group/datavirt

#7640 ENTESB-12459 Translation fixes to conform with style guidelines
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
Labels: backport 1.9.x, group/datavirt, size/l

#7651 Revert "chore(deps): bump aws-java-sdk-core from 1.11.415 to 1.11.712 in /app"
  app/pom.xml
Labels: size/XS

#7589 TEIIDTOOLS-545 removing publishing options
  app/dv/src/main/java/io/syndesis/dv/openshift/PublishConfiguration.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/PublishRequestPayload.java
Labels: group/datavirt

#7633 Teiidtools 678
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Labels: backport 1.9.x, group/datavirt, size/l

#7660 DV backports for 1.9.x
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: group/datavirt, size/xl

#7659 TEIIDTOOLS-913 Display DV connection status errors
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.9.x, group/datavirt, size/m

#7653 fix: unable to set memory limits for syndesis components in CR
  install/operator/.gitignore
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: backport 1.9.x, cat/bug, group/operator, size/s

#7667 fix(ENTESB-12545): Revert workaround due to missing camel-rest-openapi in Camel BOMs
  app/connector/rest-swagger/pom.xml
  app/connector/rest-swagger/src/main/resources/META-INF/syndesis/connector/rest-swagger.json
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/DescriptorTest.java
  app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV2Connector-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV3Connector-export/model.json
Labels: backport 1.9.x

#7668 fix(ENTESB-12610): Fix API connector description …
  app/ui-react/packages/ui/stories/Customization/ApiConnectorListView.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.it.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.ru.json
Labels: backport 1.9.x, size/XS

#7675 user doc: Fix issues identified by localization
  doc/assemblies/integrating-applications/as_adding-api-connectors.adoc
  doc/modules/customizing/c_about-api-connectors.adoc
  doc/modules/customizing/r_develop-connector-extensions.adoc
  doc/modules/integrating-applications/p_add-custom-step.adoc
  doc/modules/integrating-applications/p_add-data-mapping-step.adoc
  doc/modules/integrating-applications/p_add-split-step.adoc
  doc/modules/integrating-applications/p_add-template-step.adoc
  doc/modules/integrating-applications/p_adding-steps-to-conditional-flows.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_creating-api-connectors.adoc
  doc/modules/integrating-applications/p_general-procedure-for-obtaining-authorization.adoc
  doc/modules/integrating-applications/p_using-advanced-expression-builder.adoc
  doc/modules/integrating-applications/p_using-basic-expression-builder.adoc
  doc/modules/integrating-applications/r_about-json-schema-for-http-requests.adoc
  doc/modules/integrating-applications/r_available-transformations.adoc
  doc/modules/integrating-applications/r_example-missing-unwanted-data.adoc
  doc/modules/integrating-applications/r_example-processing-collection.adoc
  doc/modules/integrating-applications/r_how-requests-are-handled.adoc
  doc/modules/integrating-applications/r_workflow-example.adoc
Labels: size/l

#7673 fix: Fix nightly integration tests
  app/test/integration-test/pom.xml
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoApi-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoListApi-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoOpenApiV3-export/model.json
Labels: size/m

#7670 fix: unable to set memory limits for syndesis components in CR (#7653)
  install/operator/.gitignore
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/l

#7671 fix(ENTESB-12352) api provider integration step can be replaced
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/ConfigureStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
Labels: size/m

#7693 fix(c/kafka): remove SQL connector references
  app/connector/kafka/src/test/resources/logback-test.xml
  app/connector/kafka/src/test/resources/sql/demo_add_metadata.json
  app/connector/kafka/src/test/resources/sql/name_sql_metadata.json
  app/connector/kafka/src/test/resources/sql/name_sql_no_param_metadata.json
  app/connector/kafka/src/test/resources/sql/stored_procedure_list.json
  app/connector/kafka/src/test/resources/sql/stored_start_procedure_list.json
  app/connector/kafka/src/test/resources/test-options.properties
Labels: size/l

#7688 refactor(deps): remove dependency on glassfish-el
  app/common/model/pom.xml
  app/common/model/src/main/resources/META-INF/validation.xml
  app/connector/activemq/pom.xml
  app/connector/api-provider/pom.xml
  app/connector/aws-ddb/pom.xml
  app/connector/aws-s3/pom.xml
  app/connector/aws-sns/pom.xml
  app/connector/aws-sqs/pom.xml
  app/connector/debezium/pom.xml
  app/connector/email/pom.xml
  app/connector/fhir/pom.xml
  app/connector/flow/pom.xml
  app/connector/gmail/pom.xml
  app/connector/google-calendar/pom.xml
  app/connector/google-sheets/pom.xml
  app/connector/http/pom.xml
  app/connector/irc/pom.xml
  app/connector/kafka/pom.xml
  app/connector/log/pom.xml
  app/connector/mongodb/pom.xml
  app/connector/odata/pom.xml
  app/connector/rest-swagger/pom.xml
  app/connector/salesforce/pom.xml
  app/connector/sql/pom.xml
  app/connector/support/maven-plugin/pom.xml
  app/connector/telegram/pom.xml
  app/connector/timer/pom.xml
  app/connector/webhook/pom.xml
  app/extension/converter/pom.xml
  app/extension/maven-plugin/pom.xml
  app/integration/api/pom.xml
  app/integration/project-generator/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime/pom.xml
  app/server/api-generator/pom.xml
  app/server/builder/image-generator/pom.xml
  app/server/builder/maven-plugin/pom.xml
  app/server/cli/pom.xml
  app/server/controller/pom.xml
  app/server/credential/pom.xml
  app/server/dao/pom.xml
  app/server/endpoint/pom.xml
  app/server/jsondb/pom.xml
  app/server/logging/jaeger/pom.xml
  app/server/logging/jsondb/pom.xml
  app/server/metrics/jsondb/pom.xml
  app/server/monitoring/pom.xml
  app/server/openshift/pom.xml
  app/server/update-controller/pom.xml
  app/test/integration-test/pom.xml
  app/test/test-support/pom.xml
Labels: size/l

#7687 chore: add metrics for product and operator version
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1beta1/register.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/generator.go
Labels: size/m

#7708 chore(backport): add metrics for product and operator version (#7687)
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1beta1/register.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/generator.go
Labels: size/l

#7709 fix(ENTESB-12793): Add warnings when using unsupported OpenAPI 3.x features
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRules.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v2/Oas20ValidationRulesTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRulesTest.java
Labels: backport 1.9.x

#7712 chore: Update to AtlasMap 1.43.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7714 user doc: Updates for OpenAPI 3 support
  doc/assemblies/customizing/as_developing-rest-api-client-connectors.adoc
  doc/assemblies/tutorials/as_amq2api-intro.adoc
  doc/modules/integrating-applications/c_how-it-works.adoc
  doc/modules/integrating-applications/c_overview-benefit-api-provider-integrations.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/r_access-token-strategy.adoc
  doc/modules/integrating-applications/r_alternatives-for-triggering-integration-execution.adoc
  doc/modules/integrating-applications/r_requirements-for-api-provider-integrations.adoc
  doc/modules/tutorials/p_amq2api-create-rest-api-connector.adoc
  doc/modules/tutorials/p_amq2api-upload-todo-app-icon.adoc
  doc/modules/tutorials/p_sf2db-confirm-works.adoc
Labels: size/l

#7711 chore: Update to AtlasMap 1.43.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7722 user doc: Update Knative connector doc
  doc/connecting/master.adoc
  doc/integrating-applications/master.adoc
  doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc
  doc/shared/attributes.adoc
  doc/tutorials/master.adoc
Labels: size/l

#7684 Fix: virtualization state not geting updated
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: backport 1.9.x, group/datavirt, size/s

#7672 Fixes ENTESB-12608, add support for using integration name instead of ID for ALL public API endpoints
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/environment/EnvironmentHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
Labels: backport 1.9.x

#7733 fix(ENTESB-12325): mv edit action to int list row, rm check for canEdit
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
Labels: size/l

#7689 [ENTESB-12785] Align MongoDB versions
  app/connector/mongodb/pom.xml
  app/dv/pom.xml
  app/dv/src/main/resources/s2i/template-pom.xml
  app/dv/src/test/resources/generated-pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/s

#7724 fix: Hide steps that can't be used at the end of a flow
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/XS

#7738 chore: fix permissions for batch.jobs
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport 1.9.x, group/operator, size/XS

#7723 ENTESB-12785 removing the explicit mongodb version
  app/dv/pom.xml
  app/dv/src/main/resources/s2i/template-pom.xml
  app/dv/src/test/resources/generated-pom.xml
Labels: size/XS

#7737 chore: add missing content to vendor folder
  .circleci/config.yml
  install/operator/.lib.sh
  install/operator/go.sum
  install/operator/vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  install/operator/vendor/github.com/operator-framework/operator-sdk/version/version.go
  install/operator/vendor/modules.txt
Labels: backport 1.9.x, group/operator, size/s

#7739 chore: amq, fix replicas set to 0 in dc
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport 1.9.x, group/operator, size/s

#7742 refactor(server): do not log 404 errors
  app/server/runtime/src/main/resources/application.yml
Labels: size/XS

#7743 Revert "fix: Hide steps that can't be used at the end of a flow"
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/XS

#7729 fix(ENTESB-12659): integration editor list misalignment
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#7745 fix(ENTESB-12793): Add unsupported OpenAPI 3.x feature warnings for provided APIs
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ValidationRules.java
Labels: backport 1.9.x

#7752 Fix: virtualization state not geting updated
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: size/s

#7746 chore(backport): #7737 #7738 #7739 to 1.9.x
  .circleci/config.yml
  install/operator/.lib.sh
  install/operator/go.sum
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  install/operator/vendor/github.com/operator-framework/operator-sdk/version/version.go
  install/operator/vendor/modules.txt
Labels: size/s

#7748 fix: multiple restarts in amq DeploymentConfig
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7747 fix: adapt build script for operator-sdk v0.15.0 onwards
  install/operator/.lib.sh
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.openapi.go
Labels: size/xl

#7749 chore(backport): #7748 to 1.9.x
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7755 fix: adapt build script for operator-sdk v0.15.0 onwards (#7747)
  install/operator/.lib.sh
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.openapi.go
Labels: size/l

#7756 chore: remove ImageStreamNamespace from CR
  install/operator/README.md
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/deploy/syndesis.yml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/l

#7750 fix: Properly exclude the start/finish step when figuring out v…
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/s

#7751 fix: Properly exclude the start/finish step when figuring out v…
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/s

#7754 fix list style for integration editor (backport)
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#7761 fix(ENTESB-12736): Update Camel version to 2.23.2.fuse-760024
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/test/resources/petstore-v3.json
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760024.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: backport 1.9.x, size/m

#7741 [ENTESB-12785] Align MongoDB version. Now also using the same version Camel uses.
  app/connector/mongodb/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/s

#7760 [operator] Replace ImageStream with Image for database dc
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7762 [Backport-1.9.x] Update Camel version to 2.23.2.fuse-760024
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/test/resources/petstore-v3.json
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-760024.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/misc/syndesisCamelVersion.sh
Labels: size/m

#7767 Merge pull request #7767 from gashcrumb/pf3-pre-refactor
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposeVia.tsx
  app/ui-react/packages/ui/src/Integration/Details/index.ts
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationExposeVia.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: size/l

#7777 Fix: route param being directly used without resolving value
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: backport 1.9.x, group/datavirt, size/XS

#7779 DV backport for TEIIDTOOLS-924
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: group/datavirt, size/XS
