Repository syndesisio/syndesis, pull requests merged in 2020-08, with the labels that each got.

#8883 Change additional maven args to Maven configuration in syndesis CR
  install/operator/build/conf/config-test.yaml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/go.sum
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/vendor/github.com/lib/pq/README.md
  install/operator/vendor/github.com/lib/pq/conn.go
  install/operator/vendor/github.com/lib/pq/connector.go
  install/operator/vendor/github.com/lib/pq/copy.go
  install/operator/vendor/github.com/lib/pq/doc.go
  install/operator/vendor/github.com/lib/pq/encode.go
  install/operator/vendor/github.com/lib/pq/go.mod
  install/operator/vendor/github.com/lib/pq/krb.go
  install/operator/vendor/github.com/lib/pq/notify.go
  install/operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/json/json.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/net/http.go
  install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  install/operator/vendor/modules.txt
Labels: size/m

#8886 Change additional maven args to Maven configuration in syndesis CR (1.11.x)
  install/operator/build/conf/config-test.yaml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.deepcopy.go
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/vendor/modules.txt
Labels: size/l

#8885 Operator changes
  install/operator/.lib.sh
  install/operator/build.sh
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
  tools/bin/commands/build
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/openshift_funcs
  tools/bin/commands/util/operator_funcs
Labels: size/l

#8899 chore: Update to AtlasMap 2.1.0-M.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8890 chore: Remove CircleCi nightly job
  .circleci/config.yml
Labels: size/l

#8898 fix(server): remove try-with-resource
  app/server/filestore/src/main/java/io/syndesis/server/filestore/impl/SqlFileStore.java
Labels: group/server

#8889 chore: Skip syndesis-parent tools assembly with flash option
  app/pom.xml
  tools/bin/commands/build
  tools/bin/commands/integration-test
Labels: size/XS

#8914 [backport 1.11.x] - fix for SOAP url handling (ENTESB-14025)
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
Labels: size/s

#8913 fix(build): Allows pushing of images to quay.io
  app/meta/pom.xml
  app/pom.xml
  app/s2i/pom.xml
  app/server/runtime/pom.xml
  app/test/s2i-camelk/pom.xml
  app/ui-react/pom.xml
  install/operator/.lib.sh
  install/operator/build.sh
  tools/bin/commands/build
Labels: size/l

#8901 fix(server): include building kit phases
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
Labels: group/server

#8918 remove data virtualization doc content
  doc/assemblies/connecting/assembly-connecting-to-virtual-databases.adoc
  doc/connecting/master.adoc
  doc/modules/connecting/proc-vdbs-adding-a-view.adoc
  doc/modules/connecting/proc-vdbs-creating.adoc
  doc/modules/connecting/proc-vdbs-deleting.adoc
  doc/modules/connecting/proc-vdbs-editing-the-ddl.adoc
  doc/modules/connecting/proc-vdbs-previewing-by-submitting-queries.adoc
  doc/modules/connecting/proc-vdbs-publishing.adoc
  doc/modules/connecting/ref-how-to-specify-the-schema-in-a-database-connection.adoc
  doc/modules/connecting/ref-supported-connectors.adoc
Labels: size/l

#8927 ENTESB-14410: Stops erroneous OLM subscriptions with no package defined
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/vendor/modules.txt
Labels: size/m

#8928 BACKPORT: ENTESB-14410: Stops erroneous OLM subscriptions with no package defined
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
Labels: size/s

#8917 apicurio: 1.1.2 -> 1.1.4
  app/pom.xml
Labels: size/XS

#8946 chore(ui): remove dv stories
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionStatus.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsListView.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionsToolbarSkeleton.stories.tsx
  app/ui-react/packages/ui/stories/Data/Metrics/DvMetricsContainerSkeleton.stories.tsx
  app/ui-react/packages/ui/stories/Data/Metrics/MetricsTab.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/ExpandablePreview.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/PreviewResults.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContentSkeleton.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationCreateForm.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationVersionsTable.stories.tsx
Labels: group/ui, size/XXL

#8929 Reduce log output when installing addons
  install/operator/pkg/syndesis/action/install.go
Labels: size/XS

#8953 fix(ENTESB-13779): Fix connector-odata-v2 unit test
  app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/AbstractODataRouteTest.java
  app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/odata-v2/src/test/resources/io/syndesis/connector/odata2/consumer/ref-server-supplier-data-2.json
Labels: backport 1.11.x

#8973 chore: clean up some monaco/dv removal leftovers for ENTESB-14421
  app/ui-react/syndesis/craco.config.js
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/s

#8974 (backport) chore: clean up some monaco/dv removal leftovers for ENTESB-14421
  app/ui-react/syndesis/craco.config.js
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/s

#8975 (backport 1.11.x) - ENTESB-14024 - SOAP Connector Show Address Field
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useApiConnectorCreator.tsx
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/soap.js
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfoForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/models.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
Labels: size/XXL

#8978 Reduce log output when installing addons.
  install/operator/pkg/syndesis/action/install.go
Labels: size/XS

#8980 Backport #8979
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
Labels: size/XXL

#8979 Remove Spec.Components.Prometheus.Rules which is not used
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
Labels: size/XXL

#8981 Remove backslashes from prometheus rule
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8982 Backport #8981
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8983 fix: correct value evaluation for select controls
  app/ui-react/packages/auto-form/src/utils.ts
Labels: size/s

#8984 fix: correct value evaluation for select controls
  app/ui-react/packages/auto-form/src/utils.ts
Labels: size/s

#8986 minor doc fix
  doc/modules/integrating-applications/proc-create-api-provider-integration.adoc
Labels: size/XS
