Repository syndesisio/syndesis, pull requests merged in 2020-09, with the labels that each got.

#8994 Added DataTestIds for ApiConnectorDetalConfig page
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
Labels: size/s

#8995 (backport-1.11.x) Added DataTestIds for ApiConnectorDetalConfig page
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
Labels: size/s

#9004 chore: Update to AtlasMap 2.0.6
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9005 Set the jackson 2.11 to integration-bom
  app/integration/bom/pom.xml
Labels: size/XS

#9007 chore: Update to AtlasMap 2.1.0-M.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9002 Adds pvc configuration options to syndesis components
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/l, size/xl

#9000 [ENTESB-13846] Adding extra options to Kafka
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/connector/debezium/pom.xml
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizer.java
  app/connector/debezium/src/test/java/io/syndesis/connector/debezium/DebeziumConsumerCustomizerTest.java
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectionCustomizer.java
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/connections/utils.ts
Labels: backport 1.11.x, cat/enhancement

#9015 Generate Dockerfile and container.yaml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/go.mod
  install/operator/pkg/cmd/internal/olm/olm.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/annotations.go
  install/operator/pkg/syndesis/olm/container.go
  install/operator/pkg/syndesis/olm/container_test.go
  install/operator/pkg/syndesis/olm/docker.go
  install/operator/pkg/syndesis/olm/docker_test.go
  install/operator/pkg/syndesis/olm/olm.go
  install/operator/vendor/github.com/rogpeppe/go-internal/LICENSE
  install/operator/vendor/github.com/rogpeppe/go-internal/semver/semver.go
  install/operator/vendor/modules.txt
Labels: size/l

#9016 fix(ENTESB-13779): Add entity provider write properties
  app/connector/email/src/test/java/io/syndesis/connector/email/AbstractEmailTest.java
  app/connector/flow/pom.xml
  app/connector/kudu/pom.xml
  app/connector/odata-v2/src/main/java/io/syndesis/connector/odata2/component/ODataComponent.java
  app/connector/odata-v2/src/main/resources/META-INF/syndesis/connector/odata-v2.json
  app/connector/odata-v2/src/test/java/io/syndesis/connector/odata2/consumer/ODataReadRouteSplitResultsTest.java
  app/connector/soap/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: backport 1.11.x

#9021 fix(ui) - [ENTESB-14056] update inline editing to better reflect pf4
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.css
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Labels: size/s

#9020 Upgrade Camel to 2.23.2.fuse-780022
  app/extension/bom/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.23.2.fuse-780022.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/m

#9023 [backport 1.11.x] - ENTESB-14056 - inline editing
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.css
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Labels: size/s

#9017 Backport ENTESB-13622 & ENTESB-13623
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: backport 1.11.x, size/xl

#9024 Fixes ENTESB-14542, explicitly set disableReplyTo to true for AMQP Publish messages action
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
Labels: backport 1.11.x, size/XS

#9025 Fixes ENTESB-14542, explicitly set disableReplyTo to true for AMQP Publish messages action
  app/connector/amqp/src/main/resources/META-INF/syndesis/connector/amqp.json
Labels: size/XS

#9031 Upgrade fabric8 k8s client
  app/pom.xml
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: size/XS

#9030 fix(ui): Disable/enable array fields in Kafka Connector
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: size/m

#9039 [BACKPORT 1.11.x] - fix(ui) - kafka connector disable fields
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: size/m

#9042 update-autodiscover-kafka-broker - no longer need to enable it
  doc/assemblies/connecting/assembly-connecting-to-kafka.adoc
  doc/modules/connecting/proc-creating-kafka-connections.adoc
  doc/modules/connecting/proc-enabling-auto-discovery-of-kafka-brokers.adoc
Labels: size/l

#9044 (backport) feat: don't show successful validation for unknown connectors
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/utils.ts
Labels: size/m

#9053 chore: Update to AtlasMap 2.0.7 on 1.11.x
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9043 fix(ui-react): change oauth cookie name
  app/ui-react/docker/nginx-syndesis.conf
  app/ui-react/nginx-syndesis.conf
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/XS

#9060 fix(ui-react): change oauth cookie name
  app/ui-react/docker/nginx-syndesis.conf
  app/ui-react/nginx-syndesis.conf
  app/ui-react/syndesis/src/setupProxy.js
Labels: backport 1.11.x, size/XS

#9062 doc-update-odata-v2
  doc/assemblies/connecting/assembly-connecting-to-odata.adoc
  doc/modules/connecting/proc-adding-odata-connections-write.adoc
  doc/modules/connecting/proc-creating-odata-connections.adoc
Labels: size/s

#9064 ENTESB-14015: Restore missing fields for prometheus and meta
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9065 BACKPORT ENTESB-14015: Restore missing fields for prometheus and meta
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9066 Doc update odata v2 2
  doc/modules/connecting/proc-adding-odata-connections-write.adoc
Labels: size/s

#9067 chore: Update to AtlasMap 2.0.8
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9049 ENTESB-14596 / ENTESB-13234: Addresses cluster roles and their bindings
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/install/install_operator.go
  install/operator/pkg/cmd/internal/install/install_render_test.go
  install/operator/pkg/generator/assets/install/cluster_role_jaeger.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster_role_kafka.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster_role_olm.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster_role_public_api.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_camelk_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_jaeger.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_kafka.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_olm.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_public_api.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_jaeger_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_kafka_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_public_api_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_role.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
Labels: size/xl

#9075 ENTESB-14780: Revert RoleBindings to ClusterRoleBindings
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_kafka.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_public_api.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9087 BACKPORT ENTESB-14780: Revert RoleBindings to ClusterRoleBindings
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_kafka.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_public_api.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9061 doc update for memory and cpu feature
  doc/assemblies/integrating-applications/assembly-managing-integrations.adoc
  doc/modules/integrating-applications/proc-adjusting-integration-configuration.adoc
  doc/modules/integrating-applications/ref-troubleshooting-integration-execution.adoc
Labels: backport 1.11.x, size/m
