Repository syndesisio/syndesis, pull requests merged in 2020-10, with the labels that each got.

#9093 doc-update-memory-cpu-11 - same as master
  doc/assemblies/integrating-applications/assembly-managing-integrations.adoc
  doc/modules/integrating-applications/proc-adjusting-integration-configuration.adoc
  doc/modules/integrating-applications/ref-troubleshooting-integration-execution.adoc
Labels: size/m

#9088 fix(ui): ENTESB-13846 - kafka validate + add button fix
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: backport 1.11.x, size/XS

#9090 ENTESB-14768: Stop the migration routine creating a custom resource
  install/operator/pkg/syndesis/versions/versions.go
Labels: size/XS

#9095 [backport 1.11.x] - fix(ui) - ENTESB-13846 kafka connector
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: size/XS

#9094 Ability to configure the server DB connection pool from the custom resource
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta2/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/l

#9092 Ability to configure the server DB connection pool from the custom resource (1.11.x)
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta2/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/l

#9102 Expose JAVA_OPTIONS for syndesis server/meta components (1.11.x)
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/m

#9096 [backport 1.11.x] - fix(ui) - ENTESB-14562
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/s

#9086 fix(ui) - ENTESB-14562 - select first option in array for ports + services
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/s

#9107 fix(ui) - ENTESB-14905 - SOAP address not showing in detail page
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: size/l

#9103 [fix] ENTESB-14258 overriding the postgres driver version from spring boot
  app/pom.xml
Labels: backport 1.11.x, pr/approved, size/s

#9110 [backport 1.11.x] - ENTESB-14905 - ui(fix) address SOAP connector detail page
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: size/l

#9109 Expose JAVA_OPTIONS for syndesis server/meta components
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/SoapConnector_IT.java
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/m

#9105 chore: fix image in deployment
  install/operator/pkg/syndesis/olm/csv.go
Labels: size/XS

#9114 backport ENTESB-14258 overriding the postgres driver version from spring boot
  app/pom.xml
Labels: size/s

#9115 chore: include repository replacement for each fuse component
  install/operator/pkg/syndesis/olm/container.go
Labels: size/s

#9116 doc update to kafka connector topic
  doc/modules/connecting/proc-creating-kafka-connections.adoc
Labels: backport 1.11.x, size/s

#9104 ENTESB-14866: Improve logic of OLM Operator-Group installed for jaeger addon
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/go.mod
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/clienttools/clienttools.go
  install/operator/pkg/syndesis/olm/subscription.go
  install/operator/pkg/syndesis/olm/subscription_test.go
  install/operator/pkg/syndesis/testing/utils.go
  install/operator/vendor/modules.txt
Labels: size/xl

#9117 doc update to kafka connector topic - 1.11.x
  doc/modules/connecting/proc-creating-kafka-connections.adoc
Labels: size/s

#9121 ENTESB-14866: Fixes subscription logging errors while waiting on creation
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_olm.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/subscription.go
  install/operator/pkg/syndesis/olm/subscription_test.go
Labels: size/l

#9119 fix(ui): ENTESB-14753 - show WSDL timeout error
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#9120 [backport 1.11.x] - fix(ui) - ENTESB-14753 - show loader for SOAP + error on timeout
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#9125 fix(meta): managed mongodb drivers
  app/connector/mongodb/pom.xml
  app/pom.xml
Labels: group/meta

#9126 chore: Update to AtlasMap 2.1.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9127 chore: Update to AtlasMap 2.0.9
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9123 BACKPORT ENTESB-14866: Changes to jaeger subscriptions
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/go.mod
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_olm.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/startup.go
  install/operator/pkg/syndesis/clienttools/clienttools.go
  install/operator/pkg/syndesis/olm/subscription.go
  install/operator/pkg/syndesis/olm/subscription_test.go
  install/operator/pkg/syndesis/testing/utils.go
  install/operator/vendor/modules.txt
Labels: size/xl

#9129 BACKPORT ENTESB-13275: Updates OLM csv generator to latest permission…
  install/operator/pkg/syndesis/capabilities/capabilities.go
  install/operator/pkg/syndesis/olm/assets/alm-examples
  install/operator/pkg/syndesis/olm/assets/productized/description
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
Labels: size/m

#9128 ENTESB-13275: Updates OLM csv generator to latest permissions & settings
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/syndesis/capabilities/capabilities.go
  install/operator/pkg/syndesis/olm/assets/alm-examples
  install/operator/pkg/syndesis/olm/assets/productized/description
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
Labels: size/m

#9130 Fixes for CSV generation and remove camelk from CRd
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta2/zz_generated.deepcopy.go
  install/operator/pkg/syndesis/olm/assets/alm-examples
  install/operator/pkg/syndesis/olm/container.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/s

#9131 Doc update fhir json patch
  doc/modules/connecting/proc-adding-fhir-connection-patch.adoc
  doc/modules/connecting/proc-adding-http-connections.adoc
Labels: backport 1.11.x, size/m

#9133 chore: use config for amq image
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9132 ENTESB-14873: Cleanup standalone jaeger operator upgrading from 7.7 t…
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/upgrade/addons.go
  install/operator/pkg/syndesis/upgrade/cleanup.go
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
  install/operator/pkg/syndesis/upgrade/migrations.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
Labels: size/xl

#9136 Compress the data stored in the sessionStorage
  app/ui-react/packages/history/modules/LocationUtils.js
  app/ui-react/packages/history/modules/createBrowserHistory.js
  app/ui-react/packages/history/package.json
Labels: size/s

#9137 Doc update fhir json patch 1.11.x
  doc/modules/connecting/proc-adding-fhir-connection-patch.adoc
  doc/modules/connecting/proc-adding-http-connections.adoc
Labels: size/m

#9118 Update dependencies ENTESB-10454
  app/connector/amqp/pom.xml
  app/connector/gmail/pom.xml
  app/connector/google-calendar/pom.xml
  app/connector/google-sheets/pom.xml
  app/connector/pom.xml
  app/extension/bom/pom.xml
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/RepackageExtensionMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/SupportMojo.java
  app/integration/bom/pom.xml
  app/integration/runtime-springboot/pom.xml
  app/pom.xml
  app/server/jsondb/src/test/java/io/syndesis/server/jsondb/dao/JsonDbDaoTest.java
  app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/JsonDBTest.java
  app/server/jsondb/src/test/java/io/syndesis/server/jsondb/impl/SqlJsonDBIntegrationTest.java
  install/operator/vendor/github.com/spf13/afero/README.md
  install/operator/vendor/github.com/spf13/afero/appveyor.yml
  install/operator/vendor/github.com/spf13/afero/basepath.go
  install/operator/vendor/github.com/spf13/afero/const_bsds.go
  install/operator/vendor/github.com/spf13/afero/const_win_unix.go
  install/operator/vendor/github.com/spf13/afero/copyOnWriteFs.go
  install/operator/vendor/github.com/spf13/afero/go.mod
  install/operator/vendor/github.com/spf13/afero/go.sum
  install/operator/vendor/github.com/spf13/afero/ioutil.go
  install/operator/vendor/github.com/spf13/afero/match.go
  install/operator/vendor/github.com/spf13/afero/mem/file.go
  install/operator/vendor/github.com/spf13/afero/memmap.go
  install/operator/vendor/github.com/spf13/afero/os.go
  install/operator/vendor/github.com/spf13/afero/readonlyfs.go
  install/operator/vendor/github.com/spf13/afero/regexpfs.go
  install/operator/vendor/github.com/spf13/afero/symlink.go
  install/operator/vendor/github.com/spf13/afero/unionFile.go
  install/operator/vendor/modules.txt
Labels: pr/wip

#9138 fix: align server and pg_dump versions
  install/operator/pkg/generator/assets/backup/syndesis-backup-job.yml.tmpl
  install/operator/pkg/generator/assets/backup/syndesis-restore-job.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9134 use config for amq image
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/container.go
  install/operator/pkg/syndesis/olm/container_test.go
  install/operator/pkg/syndesis/olm/docker.go
  install/operator/pkg/syndesis/olm/docker_test.go
  install/operator/pkg/syndesis/olm/olm.go
Labels: size/l

#9139 ENTESB-15027 role permissions - Operator Hub
  install/operator/pkg/build/pkg.go
  install/operator/pkg/generator/dev/dev.go
  install/operator/pkg/syndesis/olm/assets.go
  install/operator/pkg/syndesis/olm/assets/assets_generate.go
  install/operator/pkg/syndesis/olm/assets_test.go
  install/operator/pkg/syndesis/olm/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
  install/operator/pkg/syndesis/olm/olm.go
  install/operator/pkg/syndesis/olm/olm_test.go
Labels: size/l, size/xl

#9147 chore: upgrade Camel to 2.23.2.fuse-780030
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9148 fix: s2i image build
  app/s2i/pom.xml
Labels: backport 1.11.x, size/XS

#9149 fix: s2i image build
  app/s2i/pom.xml
Labels: size/XS

#9151 Fix ignored modules
  app/pom.xml
Labels: size/XS

#9153 added missing graphic and fixed format typo
  doc/images/integrating-applications/TODOtoTASK.png
  doc/modules/integrating-applications/proc-map-one-source-field-to-one-target-field.adoc
Labels: backport 1.11.x

#9157 chore: Update to AtlasMap 2.0.10 for 1.11.x
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9159 fix(connector/api): check for error handling
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
Labels: group/connector

#9162 Fixing dependencies versions: netty, tomcat, kafka-clients (1.11.x)
  app/connector/aws-ddb/pom.xml
  app/connector/pom.xml
  app/meta/pom.xml
  app/pom.xml
  app/server/cli/pom.xml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
Labels: size/m

#9164 Set AWS dependencies to 1.11.714
  app/connector/pom.xml
  app/meta/pom.xml
  app/pom.xml
Labels: size/m
