Repository syndesisio/syndesis, pull requests merged in 2020-07, with the labels that each got.

#8706 #8704: Uses 'latest' builder image stream if running with dev
  install/operator/go.sum
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/satori/go.uuid/LICENSE
  install/operator/vendor/github.com/satori/go.uuid/README.md
  install/operator/vendor/github.com/satori/go.uuid/codec.go
  install/operator/vendor/github.com/satori/go.uuid/generator.go
  install/operator/vendor/github.com/satori/go.uuid/sql.go
  install/operator/vendor/github.com/satori/go.uuid/uuid.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/README.md
  install/operator/vendor/github.com/testcontainers/testcontainers-go/compose.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/container.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/docker.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/generic.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/go.mod
  install/operator/vendor/github.com/testcontainers/testcontainers-go/go.sum
  install/operator/vendor/github.com/testcontainers/testcontainers-go/reaper.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/wait/errors.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/wait/errors_windows.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/wait/host_port.go
  install/operator/vendor/modules.txt
Labels: size/s

#8777 Script to change camel and syndesis version
  tools/bin/commands/dev
  tools/misc/syndesisCamelVersion.sh
Labels: size/l

#8781 Fix: Interactive read fails with -s switch for password
  tools/bin/commands/util/client_funcs
  tools/bin/commands/util/kube_funcs
  tools/bin/commands/util/openshift_funcs
Labels: size/s

#8780 feature(e2e): Run integration tests as github actions
  .github/workflows/e2e.yml
  .github/workflows/e2e_mainbranch.yml
  README.md
Labels: size/m

#8785 fix: Downloading platform-detect correctly
  tools/bin/commands/build
  tools/bin/commands/release
  tools/bin/commands/util/common_funcs
Labels: size/m, size/s

#8786 fix: Adds remaining ::init functions to syndesis command scripts
  tools/bin/commands/completion
  tools/bin/commands/integration-test
  tools/bin/commands/release
  tools/bin/commands/system-test
  tools/bin/commands/ui
Labels: size/s

#8794 Fix over #8791
  app/server/cli/pom.xml
  app/server/monitoring/pom.xml
  install/operator/.lib.sh
  tools/bin/commands/util/openshift_funcs
Labels: size/s

#8791 Fix: More changes to get the release build working
  app/server/cli/pom.xml
  app/server/monitoring/pom.xml
  install/operator/.lib.sh
  tools/bin/commands/util/openshift_funcs
Labels: size/s

#8795 fix: remove tags only if they exists
  tools/bin/commands/release
Labels: size/s

#8778 added consolelink for namespacedashboard
  install/operator/deploy/cluster_role.yaml
  install/operator/deploy/cluster_role_binding.yaml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/vendor/github.com/openshift/api/apps/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/apps/v1/types.go
  install/operator/vendor/github.com/openshift/api/apps/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
  install/operator/vendor/github.com/openshift/api/authorization/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/authorization/v1/types.go
  install/operator/vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/build/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/build/v1/types.go
  install/operator/vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/console/v1/0000_10_consoleclidownload.crd.yaml
  install/operator/vendor/github.com/openshift/api/console/v1/0000_10_consoleexternalloglink.crd.yaml
  install/operator/vendor/github.com/openshift/api/console/v1/0000_10_consolelink.crd.yaml
  install/operator/vendor/github.com/openshift/api/console/v1/0000_10_consolenotification.crd.yaml
  install/operator/vendor/github.com/openshift/api/console/v1/0000_10_consoleyamlsample.crd.yaml
  install/operator/vendor/github.com/openshift/api/console/v1/doc.go
  install/operator/vendor/github.com/openshift/api/console/v1/register.go
  install/operator/vendor/github.com/openshift/api/console/v1/types.go
  install/operator/vendor/github.com/openshift/api/console/v1/types_console_cli_download.go
  install/operator/vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  install/operator/vendor/github.com/openshift/api/console/v1/types_console_link.go
  install/operator/vendor/github.com/openshift/api/console/v1/types_console_notification.go
  install/operator/vendor/github.com/openshift/api/console/v1/types_console_yaml_sample.go
  install/operator/vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  install/operator/vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/image/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/image/v1/types.go
  install/operator/vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/oauth/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/oauth/v1/types.go
  install/operator/vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/project/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/project/v1/types.go
  install/operator/vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/route/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/route/v1/types.go
  install/operator/vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/github.com/openshift/api/template/v1/generated.proto
  install/operator/vendor/github.com/openshift/api/template/v1/types.go
  install/operator/vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  install/operator/vendor/modules.txt
Labels: size/XXL

#8800 fix: Updates the download of platform-detect binary
  tools/bin/commands/util/common_funcs
  tools/bin/commands/util/operator_funcs
Labels: size/l

#8797 fix(itest): Build docker images too
  .github/workflows/e2e.yml
  .github/workflows/e2e_mainbranch.yml
Labels: size/s

#8802 fixing broken links in two doc files
  doc/modules/integrating-applications/proc-creating-soap-api-connectors.adoc
  doc/modules/integrating-applications/proc-updating-api-connectors.adoc
Labels: size/XS

#8803 fix(8801): address availability of consolev1 on all platforms
  install/operator/cmd/detect/main.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
  install/operator/pkg/generator/assets/install/grant/grant_olm_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/olm_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/capabilities/capabilities.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/vendor/github.com/beorn7/perks/LICENSE
Labels: size/l

#8813 Fix syndesis script
  tools/bin/commands/completion
  tools/bin/commands/ui
Labels: size/XS

#8805 update filter with correct apps for cross-console navigation
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
Labels: size/XS

#8817 fixes and updates to minikube installation
  install/kubernetes/README.md
  tools/bin/commands/build
  tools/bin/commands/minikube
  tools/bin/commands/util/kube_funcs
Labels: size/l

#8833 fix(test): exclude citrus-validation-xml
  app/pom.xml
Labels: size/XS

#8810 chore: Fix build CLI on MacOS
  tools/bin/commands/util/common_funcs
Labels: size/XS

#8851 fix for 8811 - SendMail integration test by fixing the default
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/mail/SendMail-export/model.json
Labels: size/XS

#8852 Allow user to set additional maven arguments for integration builds #8674
  install/operator/build/conf/config-test.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  tools/bin/commands/util/operator_funcs
Labels: size/m

#8853 Add field to CR to overwrite maven repos
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/deploy/crds/syndesis.io_syndesis_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/addons/camelk/maven-settings.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/l

#8842 Fix for the incorrect query in FuseOnlinePostgresExporterDown alert.
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8837 (backport) fix: ensure we massage a mapset value to an object properly
  app/ui-react/packages/auto-form/src/utils.ts
Labels: size/m

#8838 (backport) fix: bring back the green check
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
Labels: size/s

#8839 doc fix - downstream link to dv doc
  doc/assemblies/connecting/assembly-connecting-to-virtual-databases.adoc
Labels: size/XS

#8857 Fix for the incorrect query in FuseOnlinePostgresExporterDown alert. (1.11.x)
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8867 Bankport 1.11.x: ENTESB-12840 Enable including error messages in API Provider …
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiFlowGenerator.java
Labels: pr/approved

#8859 Backports ENTESB-13110 but with additional fixes
  install/operator/build/conf/config.yaml
  install/operator/go.mod
  install/operator/pkg/cmd/internal/install/install_defaults.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/upgrade/backup.go
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
  install/operator/pkg/util/postgresql.go
  install/operator/pkg/util/postgresql_test.go
  install/operator/vendor/github.com/spf13/afero/LICENSE.txt
  install/operator/vendor/github.com/spf13/afero/README.md
  install/operator/vendor/github.com/spf13/afero/afero.go
  install/operator/vendor/github.com/spf13/afero/appveyor.yml
  install/operator/vendor/github.com/spf13/afero/basepath.go
  install/operator/vendor/github.com/spf13/afero/cacheOnReadFs.go
  install/operator/vendor/github.com/spf13/afero/const_bsds.go
  install/operator/vendor/github.com/spf13/afero/const_win_unix.go
  install/operator/vendor/github.com/spf13/afero/copyOnWriteFs.go
  install/operator/vendor/github.com/spf13/afero/go.mod
  install/operator/vendor/github.com/spf13/afero/go.sum
  install/operator/vendor/github.com/spf13/afero/httpFs.go
  install/operator/vendor/github.com/spf13/afero/ioutil.go
  install/operator/vendor/github.com/spf13/afero/lstater.go
  install/operator/vendor/github.com/spf13/afero/match.go
  install/operator/vendor/github.com/spf13/afero/mem/dir.go
  install/operator/vendor/github.com/spf13/afero/mem/dirmap.go
  install/operator/vendor/github.com/spf13/afero/mem/file.go
  install/operator/vendor/github.com/spf13/afero/memmap.go
  install/operator/vendor/github.com/spf13/afero/os.go
  install/operator/vendor/github.com/spf13/afero/path.go
  install/operator/vendor/github.com/spf13/afero/readonlyfs.go
  install/operator/vendor/github.com/spf13/afero/regexpfs.go
  install/operator/vendor/github.com/spf13/afero/unionFile.go
  install/operator/vendor/github.com/spf13/afero/util.go
  install/operator/vendor/k8s.io/api/admission/v1/doc.go
  install/operator/vendor/k8s.io/api/admission/v1/generated.pb.go
  install/operator/vendor/k8s.io/api/admission/v1/generated.proto
  install/operator/vendor/k8s.io/api/admission/v1/register.go
  install/operator/vendor/k8s.io/api/admission/v1/types.go
  install/operator/vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  install/operator/vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/doc.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/generated.pb.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/generated.proto
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/register.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/types.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/types_swagger_doc_generated.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/zz_generated.deepcopy.go
  install/operator/vendor/k8s.io/client-go/rest/fake/fake.go
  install/operator/vendor/k8s.io/kubectl/pkg/scheme/install.go
  install/operator/vendor/k8s.io/kubectl/pkg/scheme/scheme.go
  install/operator/vendor/modules.txt
  tools/bin/commands/util/operator_funcs
Labels: size/XXL

#8841 fix(UI): [ENTESB-14025] - fix handling of ?WSDL urls for SOAP
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
Labels: size/s

#8862 Update Camel K CRDs
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/camelk/CamelKSupport.java
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster/camelk.yml
  install/operator/pkg/generator/assets_vfsdata.go
  tools/bin/commands/util/camel_k_funcs
Labels: group/camel-k, pr/review-requested
