Repository syndesisio/syndesis, pull requests merged in 2020-02, with the labels that each got.

#7783 chore: Update to AtlasMap 1.43.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7784 Merge pull request #7784 from igarashitm/atlasmap-1.43.4-1.9.x
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7764 [operator] Backport #7760, #7756
  install/operator/README.md
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/deploy/syndesis.yml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.openapi.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: size/l

#7793 feat(release): upload the syndesis-cli to GitHub
  tools/bin/commands/release
Labels: size/s

#7796 user doc: Ensure "1.9" in URLs, and "Edit flow" where needed.
  doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
  doc/modules/integrating-applications/p_updating-integrations.adoc
Labels: size/XS

#7802 user doc: Updates to doc for DynamoDB connector based on comments from Tomas
  doc/assemblies/connecting/as_connecting-to-aws.adoc
  doc/modules/connecting/p_creating-amazon-dynamodb-connections.adoc
  doc/modules/connecting/p_obtaining-aws-credentials.adoc
Labels: size/s

#7803 user doc: Add note about source fields in data mapper - might not contain data
  doc/assemblies/integrating-applications/as_mapping-data.adoc
  doc/modules/integrating-applications/p_add-data-mapping-step.adoc
  doc/modules/integrating-applications/p_map-one-source-field-to-one-target-field.adoc
Labels: size/s

#7797 ENTESB-11791 Dropbox upload mode looks initialized in the UI but isn't
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: size/XS

#7798 ENTESB-11791 Dropbox upload mode looks initialized in the UI but isn't - backport 1.9.x
  app/connector/dropbox/src/main/resources/META-INF/syndesis/connector/dropbox.json
Labels: size/XS

#7799 fix: Update template to use links from locale
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Labels: size/m

#7800 fix: Update template to use links from locale (backport)
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Labels: size/m

#7813 feat(release): upload the syndesis-cli to GitHub
  tools/bin/commands/release
Labels: size/s

#7801 fix: If a step has no configurable properties, show that and don't error out
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/m

#7795 Add option to install syndesis with options to the syndesis-operator …
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: size/s

#7815 fix: If a step has no configurable properties, show that and don't error out (backport)
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/m

#7816 chore: minor patternfly 4 upgrade and related changes
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/yarn.lock
Labels: size/m

#7830 fix: failing operator backup test
  install/operator/pkg/syndesis/backup/backup_test.go
Labels: size/s

#7829 fix: failing operator backup test
  install/operator/pkg/syndesis/backup/backup_test.go
Labels: size/s

#7820 chore: migrate files from patternfly-react Icon to their pf4 equivalents
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx
  app/ui-react/packages/ui/src/Shared/ConfirmationDialog.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
  app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
Labels: size/l

#7848 chore: clean up UI prerequisite commands to minimize naming explicit packages
  .circleci/config.yml
Labels: size/XS

#7841 chore: migrate recent updates card and integration detail history list view
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesCard.tsx
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItem.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: size/l

#7850 chore: clean up UI prerequisite commands to minimize naming explicit packages (on 1.9.x)
  .circleci/config.yml
Labels: size/XS

#7861 BACKPORT fix: Removes deficient backup test
  install/operator/pkg/syndesis/backup/backup_test.go
Labels: size/s

#7863 chore: migrate integration flow step and integrations empty state
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStep.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsEmptyState.tsx
Labels: size/m

#7860 fix: Removes deficient backup test
  install/operator/pkg/syndesis/backup/backup_test.go
Labels: size/s

#7859 fix: Adds in GOPROXY environment variable for operator building with go
  install/operator/.lib.sh
  install/operator/build.sh
Labels: size/XS

#7856 Update to productised Jaeger 1.13 - ENTESB-12909
  install/operator/pkg/generator/assets/addons/jaeger/server_operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7857 Update to productised Jaeger 1.13 - ENTESB-12909
  install/operator/pkg/generator/assets/addons/jaeger/server_operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7862 fix: Conditionalise jaeger collector uri to align with logic in meta
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7855 Fix: DV create a view step 1 UX/UI issues
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Labels: size/m

#7870 Fix syndesis minishift install and dev --cleanup
  tools/bin/commands/crc
  tools/bin/commands/dev
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/operator_funcs
Labels: size/m

#7867 chore(ui): update patternfly to the latest version
  app/ui-react/package.json
  app/ui-react/packages/apicurio-assembly/package.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/utils/package.json
  app/ui-react/syndesis/package.json
  app/ui-react/yarn.lock
Labels: size/xl

#7868 chore: drop pf-react dep from ApiConnectorListView
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Labels: size/m

#7871 chore: drop patternfly-react from connection/connector form cards & refactor
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Shared/models.ts
Labels: size/xl

#7846 fix(deps): exclude javax.annotation-api
  app/pom.xml
Labels: size/s

#7874 chore: migrate integration list from ListView to DataList
  app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsList.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItemUnreadable.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
Labels: size/l, size/xl

#7869 Fix: DV create a view step 1 UX/UI issues
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Labels: size/m

#7873 [operator] Fix for install option --dev
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7879 Teiidtools 943
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/models.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
Labels: size/m

#7882 fix: make storybook work again by bringing in the right babel polyfill (1.9.x only)
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/syndesis/package.json
  app/ui-react/yarn.lock
Labels: size/s

#7880 chore: migrate the tabbar component to pf4
  app/ui-react/packages/ui/src/Layout/PfNavLink.tsx
  app/ui-react/packages/ui/src/Layout/TabBar.tsx
Labels: size/s

#7878 chore: migrate loader to use pf4 spinner
  app/ui-react/packages/ui/src/Integration/Editor/shared/PageSectionLoader.tsx
  app/ui-react/packages/ui/src/Integration/Editor/shared/index.ts
  app/ui-react/packages/ui/src/Layout/Loader.css
  app/ui-react/packages/ui/src/Layout/Loader.tsx
  app/ui-react/packages/ui/src/Layout/PageLoader.tsx
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: size/m

#7881 chore: migrate confirmation dialog to use pf4 modal
  app/ui-react/packages/ui/src/Shared/ConfirmationDialog.tsx
  app/ui-react/packages/ui/src/Shared/Dialog.tsx
Labels: size/l

#7888 chore: migrate API connector list item
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
Labels: size/l

#7889 chore: migrate the aggregated metric card and resulting dashboard tweaks
  app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.tsx
  app/ui-react/packages/ui/src/Dashboard/Dashboard.css
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
Labels: size/l

#7895 user doc: Data mapper doc updates
  doc/modules/integrating-applications/p_applying-conditions-to-mappings.adoc
  doc/modules/integrating-applications/p_using-data-mapper-to-process-collections.adoc
  doc/modules/integrating-applications/r_troubleshooting-data-mapping.adoc
Labels: size/m

#7896 user doc: Updated text in heading links to be consistent with the actual headings
  doc/modules/tutorials/p_register-with-sf.adoc
Labels: size/XS

#7891 fix(ENTESB-12960): Missing version placeholder.
  app/integration/bom/pom.xml
Labels: size/XS

#7897 Fix Typo on EOT keyword build script
  tools/bin/commands/build
Labels: size/XS

#7898 Fix Typo on EOT keyword build script - 1.9.x
  tools/bin/commands/build
Labels: size/XS

#7892 chore: migrate inline text edit to pf4
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
Labels: size/l

#7899 [ENTESB-12846] Fix permissions for jobs
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7900 [ENTESB-12846] Fix permissions for jobs
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7906 Teiidtools 943 m
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/models.ts
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
Labels: size/m

#7908 chore: force the version of terser to the current latest (4.6.3) to see if it sorts UI CI build issue
  app/ui-react/package.json
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/yarn.lock
Labels: size/m

#7905 ENTESB-12645: Fixes issues with scheduled backups of external database
  install/operator/pkg/apis/syndesis/v1beta1/object.go
  install/operator/pkg/syndesis/backup/backup.go
Labels: size/s

#7904 ENTESB-12645: Fixes issues with scheduled backups of external database
  install/operator/pkg/apis/syndesis/v1beta1/object.go
  install/operator/pkg/syndesis/backup/backup.go
Labels: size/s

#7912 chore: Extensions List Migration
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.css
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionListView.tsx
Labels: size/l

#7914 user doc: updates to Mongodb connector doc
  doc/assemblies/connecting/as_connecting-to-mongodb.adoc
  doc/modules/connecting/p_adding-mongodb-connections-read.adoc
  doc/modules/connecting/p_adding-mongodb-connections-write.adoc
  doc/modules/connecting/p_creating-mongodb-connections.adoc
Labels: size/l

#7893 chore: migrate list view toolbar to pf4
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
  app/ui-react/packages/ui/src/Shared/ListViewToolbar.css
  app/ui-react/packages/ui/src/Shared/ListViewToolbar.tsx
Labels: size/l

#7890 fix(ENTESB-12960): Missing version placeholder.
  app/integration/bom/pom.xml
Labels: size/XS

#7915 ENTESB-12570: Modify jaeger role bindings to allow multi namespaces
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/generator/assets/install/cluster/camelk.yml
  install/operator/pkg/generator/assets/install/cluster/jaeger.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_camelk_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_jaeger_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/l, size/m

#7913 chore: bump yarn and add terser workaround
  .circleci/config.yml
  app/pom.xml
  app/ui-react/package.json
  app/ui-react/pom.xml
  app/ui-react/syndesis/craco.config.js
  app/ui-react/yarn.lock
Labels: size/m

#7923 chore: remove javax/org.jboss.spec dependency declarations
  test.py
Labels: size/l

#7925 [ENTESB-13019] Use 9.6 image version for backup and restore
  install/operator/pkg/generator/assets/backup/syndesis-backup-job.yml.tmpl
  install/operator/pkg/generator/assets/backup/syndesis-restore-job.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7929 chore: migrate some labels, revisit some label colors, migrate detail header dropdown
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailBreadcrumb.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
Labels: size/l

#7926 [ENTESB-13019] Use 9.6 image version for backup and restore
  install/operator/pkg/generator/assets/backup/syndesis-backup-job.yml.tmpl
  install/operator/pkg/generator/assets/backup/syndesis-restore-job.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#7916 ENTESB-12570: Modify jaeger role bindings to allow multi namespaces
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/generator/assets/install/cluster/camelk.yml
  install/operator/pkg/generator/assets/install/cluster/jaeger.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_camelk_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets/install/grant/grant_jaeger_cluster_role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/l, size/m

#7930 TEIIDTOOLS-925 DV pf3-pf4 spinner and label updates
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvClientSessionMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvRequestMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvUptimeMetric.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Versions/VirtualizationVersionsTable.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/PreviewResults.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
Labels: group/datavirt, size/m

#7938 Set jaeger images as parameters ENTESB-12909
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/generator/assets/addons/jaeger/server_operator.yml.tmpl
  install/operator/pkg/generator/assets/addons/jaeger/syndesis-jaeger.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/m

#7939 Set jaeger images as parameters 1.9.x ENTESB-12909
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/generator/assets/addons/jaeger/server_operator.yml.tmpl
  install/operator/pkg/generator/assets/addons/jaeger/syndesis-jaeger.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/m

#7927 chore: extensions list migration part II
  app/ui-react/packages/ui/__tests__/Customization/ExtensionDetail.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.css
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionDetail.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.tsx
  app/ui-react/yarn.lock
Labels: size/l

#7942 Fix: showing error msg for API failed in connectionschemalist
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
Labels: group/datavirt, size/XS

#7941 DV pf3-4 conversion, tooltip and emptystate - ENTESB-12896, TEIIDTOOLS-925
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListEmptyState.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogEmptyState.tsx
Labels: group/datavirt, size/l

#7943 pf3-pf4 DV buttons and removal of unused component - TEIIDTOOLS-925, ENTESB-12896
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/ExpandablePreview.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeaderBreadcrumb.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationCreateForm.tsx
Labels: group/datavirt, size/l

#7950 fix: rework the state managment for the API client security form
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
Labels: size/l

#7951 chore: drop pf-react support for extension integrations table
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionIntegrationsTable.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorListView.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionIntegrationsTable.stories.tsx
Labels: size/l

#7954 user doc: Updates to fix out of date links.
  doc/assemblies/customizing/as_developing-extensions.adoc
  doc/assemblies/integrating-applications/as_creating-integrations.adoc
  doc/modules/integrating-applications/c_description-of-constructs.adoc
  doc/modules/integrating-applications/c_workflow-overview.adoc
  doc/modules/integrating-applications/p_add-log-step.adoc
  doc/modules/integrating-applications/p_creating-api-connectors.adoc
  doc/modules/integrating-applications/p_deleting-extensions.adoc
  doc/modules/integrating-applications/p_importing-integrations.adoc
  doc/modules/integrating-applications/p_start-with-webhook-connection.adoc
  doc/modules/integrating-applications/p_viewing-integration-activity.adoc
  doc/modules/integrating-applications/r_alternatives-for-triggering-integration-execution.adoc
  doc/shared/attributes-links.adoc
Labels: size/s

#7955 Update DV ViewList to pf4 - TEIIDTOOLS-925, ENTESB-12896
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
Labels: group/datavirt, size/l

#7953 feat(operator): postgresql database upgrade
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/l

#7962 feat(operator): postgresql database upgrade
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/l

#7961 (backport): fix to make editing a more obvious choice in integration list (ENTESB-12325)
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
Labels: size/l

#7963 user doc: updates to doc for Mongodb connector
  doc/modules/connecting/p_adding-mongodb-connections-read.adoc
  doc/modules/connecting/p_adding-mongodb-connections-write.adoc
  doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc
  doc/modules/integrating-applications/r_guidelines-for-service-sending-requests.adoc
  doc/modules/tutorials/p_amq2api-create-custom-step.adoc
Labels: size/m

#7964 Update DV SchemaLists to pf4 - TEIIDTOOLS-925, ENTESB-12896
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
Labels: group/datavirt, size/l

#7968 user doc: New doc for enabling auto-discovery of Kafka brokers
  doc/assemblies/connecting/as_connecting-to-kafka.adoc
  doc/modules/connecting/p_creating-kafka-connections.adoc
  doc/modules/connecting/p_enabling-auto-discovery-of-kafka-brokers.adoc
  doc/modules/connecting/p_enabling-connections-to-knative-resources.adoc
Labels: size/l

#7969 Update DV VirtualizationList to pf4 - TEIIDTOOLS-925, ENTESB-12896
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: group/datavirt, size/xl

#7976 [operator] include permissions for operator-sdk metrics
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/m

#7918 Teiidtools 894
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/PreviewData.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionTables.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: group/datavirt, size/xl

#7977 mflinn - updates to the API integration files to facilitate reuse in …
  doc/modules/integrating-applications/c_overview-benefit-api-provider-integrations.adoc
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
Labels: size/m

#7978 integration-updates fixing the conditionalized text in the creating A…
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
Labels: size/XS

#7981 [operator] Add label name: syndesis-operator
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7982 [operator] backport #7981 #7976
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/m

#7985 update cicd components for pf4 - ENTESB-12896
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdEditDialog.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdList.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.css
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListView.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdManagePageUI.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialog.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationDialogBody.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.css
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx
  app/ui-react/packages/ui/stories/Integration/CiCd/CiCdEditDialog.stories.tsx
  app/ui-react/packages/ui/stories/Integration/CiCd/CiCdListItem.stories.tsx
  app/ui-react/packages/ui/stories/Integration/CiCd/TagIntegrationDialog.stories.tsx
  app/ui-react/packages/ui/stories/Integration/CiCd/TagIntegrationListItem.stories.tsx
Labels: size/XXL

#7940 chore: bring back the ui-doc build step
  .circleci/config.yml
Labels: size/XS

#7984 updating with fixes for two typos found downstream
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
Labels: size/XS

#7983 [operator] Run install phase also when Installed
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: backport master, cat/bug, group/operator, size/m, size/s

#7992 [ENTESB-13103] Add patch permission to syndesis resource
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7952 Fix for ENTESB 12972 - Todo pod does not deploy on OCP 4.4
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7991 [ENTESB-13103] Add patch permission to syndesis resource
  install/operator/pkg/generator/assets/install/role.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS
