Repository syndesisio/syndesis, pull requests merged in 2020-06, with the labels that each got.

#8595 fix: re-align the detail page nav
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
Labels: size/XS

#8589 fix: ensure we preserve any previous mapping document when revisiting the data mapper
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Labels: size/s

#8590 (backport) fix: ensure we preserve any previous mapping document when revisiting the data mapper
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Labels: size/s

#8593 fix: rework the validation checking and tidy up
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#8599 doc update for feature - select library extension at integration save
  doc/modules/customizing/proc-creating-jdbc-driver-library-extensions.adoc
  doc/modules/customizing/ref-develop-library-extensions.adoc
  doc/modules/integrating-applications/proc-making-extensions-available.adoc
  doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
Labels: size/m

#8598 edit the message in UI about library extensions
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/XS

#8594 (backport) fix: rework the validation checking and tidy up
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#8596 (backport) fix: re-align the detail page nav
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
Labels: size/XS

#8611 fix: adjust PageTitle to use the right branding variable
  app/ui-react/syndesis/src/shared/PageTitle.tsx
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8612 (backport) fix: adjust PageTitle to use the right branding variable
  app/ui-react/syndesis/src/shared/PageTitle.tsx
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8613 (backport) edit the message in UI about library extensions
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/XS

#8614 fix: use the right type for the 'min' property
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#8615 (backport) fix: use the right type for the 'min' property
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#8619 Add field to CR to overwrite maven repos
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/deploy/crds/syndesis.io_syndeses_crd.yaml
  install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta1/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/addons/camelk/maven-settings.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/versions/versions.go
  install/operator/pkg/syndesis/versions/versions_test.go
Labels: cat/enhancement, cat/feature, group/operator, size/l

#8587 fix(connector/rest-swagger): update security definition
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizer.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/RestSwaggerConnectorIntegrationTest.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizerTest.java
  app/connector/rest-swagger/src/test/resources/apikey-security-updated.json
  app/connector/rest-swagger/src/test/resources/apikey.json
Labels: backport 1.10.x, group/connector

#8620 chore(ui): rename API client connector & update stories
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorService.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/2-ImportedOperations.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#8616 Fix: role permission dropdown issue and metadata tree spacing
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
Labels: backport 1.10.x, group/datavirt, size/l, size/m

#8625 (fix) TEIIDTOOLS-765 Allows layering of views in CreateView wizard
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.10.x, group/datavirt, size/l

#8629 [backport 1.10.x] - rename api client connector
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorService.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/2-ImportedOperations.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/l

#8632 (backport 1.10.x) fix: TEIIDTOOLS-1021, TEIIDTOOLS-1026, TEIIDTOOLS-765
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionListView.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/SelectedConnectionTables.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: size/l

#8623 ENTESB-13074: Adjust path of pg_ctl
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8635 fix: TEIIDTOOLS-1036 Add Publish messages
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: backport 1.10.x, group/datavirt, size/s

#8636 Backport ENTESB-13074: fixes for pg_ctl
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#8634 fix: TEIIDTOOLS-1040 Fix wizard issue removing tables with same name
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
Labels: backport 1.10.x, group/datavirt, size/s

#8643 (backport) fix: DV UI backports
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationActions.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: size/m

#8639 chore: adjust java & node heap setting for ui
  .circleci/config.yml
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/ui/package.json
  app/ui-react/syndesis/craco.config.js
  app/ui-react/syndesis/package.json
Labels: backport 1.10.x, size/s

#8647 (backport) chore: adjust java and node heap for ui
  .circleci/config.yml
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/ui/package.json
  app/ui-react/syndesis/craco.config.js
  app/ui-react/syndesis/package.json
Labels: size/s

#8650 Fixes ENTESB-14002, added endpoint to list API connectors
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/operations/PaginationOptionsFromQueryParams.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Labels: backport master

#8665 fix(ui): [ENTESB-13977] - list all api client connectors
  app/ui-react/packages/api/src/WithApiConnectors.tsx
Labels: size/XS

#8661 runtime-libraries-doc-update3
  doc/modules/customizing/ref-develop-library-extensions.adoc
  doc/modules/integrating-applications/proc-making-extensions-available.adoc
  doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
Labels: size/s

#8653 fix: ensure the min property is properly overridden
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#8654 (backport) fix: ensure the min property is properly overridden
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
Labels: size/XS

#8561 Cross console updates for fuse
  .circleci/config.yml
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/__tests__/AppLayout.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/utils/package.json
  app/ui-react/syndesis/.env.development
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/yarn.lock
Labels: size/l

#8651 chore: Update to AtlasMap 2.0.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8652 chore: Update to AtlasMap 2.0.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8645 ENTESB-13992: Series of fixes addressing addons & crc script
  install/operator/build.sh
  install/operator/build/conf/config.yaml
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/constants.go
  install/operator/pkg/syndesis/action/install.go
  tools/bin/commands/build
  tools/bin/commands/crc
  tools/bin/commands/minishift
  tools/bin/commands/util/common_funcs
Labels: size/l

#8681 TEIIDTOOLS-1044 Remove duplicate connection from Create View wizard
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Labels: group/datavirt, size/s

#8688 fix for #8687 Webhook value setting incorrect when using default values
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
Labels: size/XS

#8597 fix(server): skip connection properties comparison when dynamic
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandlerTest.java
Labels: group/server

#8698 Fix: view permissions to be managed via row expansion
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/xl

#8702 webhook error handling doc update
  doc/modules/integrating-applications/proc-create-integration-operation-flows.adoc
  doc/modules/integrating-applications/proc-start-with-webhook-connection.adoc
  doc/modules/integrating-applications/proc-viewing-integration-activity.adoc
  doc/modules/integrating-applications/ref-how-requests-are-handled.adoc
Labels: size/m

#8703 TEIIDTOOLS-1043 Use source specific icon in CreateView wizard selections
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SelectedConnectionListView.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionTables.tsx
Labels: group/datavirt, size/m

#8708 fix: calculate the appropriate defaultValue setting from the current available error keys
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: size/m

#8709 added data virtualization doc
  doc/assemblies/connecting/assembly-connecting-to-virtual-databases.adoc
  doc/connecting/master.adoc
  doc/images/tutorials/ThreeVerticalDotsKebab.png
  doc/modules/connecting/proc-enabling-auto-discovery-of-kafka-brokers.adoc
  doc/modules/connecting/proc-register-with-dropbox.adoc
  doc/modules/connecting/proc-vdbs-adding-a-view.adoc
  doc/modules/connecting/proc-vdbs-creating.adoc
  doc/modules/connecting/proc-vdbs-deleting.adoc
  doc/modules/connecting/proc-vdbs-editing-the-ddl.adoc
  doc/modules/connecting/proc-vdbs-previewing-by-submitting-queries.adoc
  doc/modules/connecting/proc-vdbs-publishing.adoc
  doc/modules/connecting/ref-how-to-specify-the-schema-in-a-database-connection.adoc
  doc/modules/connecting/ref-supported-connectors.adoc
  doc/modules/integrating-applications/proc-deleting-integrations.adoc
Labels: size/l

#8710 datavirt doc minor update
  doc/assemblies/connecting/assembly-connecting-to-virtual-databases.adoc
Labels: size/XS

#8699 Remove old unmaintained templates
  install/support/product-version-map.yml
  install/support/serviceaccount-as-oauthclient-restricted.yml
  install/support/syndesis-amq.yml
Labels: size/l

#8712 Upgrade undertow to 2.0.30 to fix CVE
  app/pom.xml
Labels: size/s

#8714 Upgrade undertow to 2.0.30 to fix CVE (1.10.x)
  app/pom.xml
Labels: size/s

#8713 TEIIDTOOLS-1051 DV routing cleanup
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/resolvers.ts
Labels: group/datavirt, size/s

#8715 TEIIDTOOLS-1036 Updates publish button tooltip
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
Labels: group/datavirt, size/XS

#8701 fix(ui): ENTESB-14048 validate api client connector security fields
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/securityValidation.ts
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/soap.js
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
Labels: group/ui, size/l

#8716 Fix: specific source icon in Create View wizard Preview table
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/PreviewData.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
Labels: group/datavirt, size/s

#8718 chore: Update to AtlasMap 2.0.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8719 chore: Update to AtlasMap 2.0.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8720 data virt doc minor fix
  doc/modules/connecting/ref-how-to-specify-the-schema-in-a-database-connection.adoc
Labels: size/XS

#8724 fix(dv) ENTESB-14057 addressing scenarios that create invalid metadata
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/EditorService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/EditorServiceTest.java
Labels: backport 1.10.x, group/datavirt, size/s

#8727 Fix: Improvements for DataPermissions display
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/RolePermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionToolbar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/index.ts
Labels: group/datavirt

#8728 Revert of [ENTESB-12963] Upgrade Spring to 5.1.13
  app/pom.xml
Labels: size/XS

#8673 ENTESB-12104 demoData flag for adding sampledb connection
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/demo-data.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: pr/wip

#8730 TEIIDTOOLS-1053 Adding tabs for the policies modal
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/l

#8749 Fix: UI components for row based filtering
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringTab.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringTab.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/index.ts
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/l

#8748 fix(integration): align camel-k runtime dependencies
  app/integration/bom-camel-k/pom.xml
Labels: size/XS

#8753 fix: ensure we massage a mapset value to an object properly
  app/ui-react/packages/auto-form/src/utils.ts
Labels: size/XS

#8746 updated service metrics & monitoring logic generated by sdk
  install/operator/pkg/cmd/internal/run/run.go
Labels: size/l

#8755 fix: bring back the green check
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
Labels: size/s

#8732 soap connector doc updates
  doc/assemblies/connecting/assembly-connecting-to-api-clients.adoc
  doc/assemblies/customizing/assembly-customizing.adoc
  doc/assemblies/integrating-applications/assembly-adding-api-connectors.adoc
  doc/connecting/master.adoc
  doc/modules/connecting/proc-add-api-client-connection.adoc
  doc/modules/connecting/proc-creating-rest-api-connections.adoc
  doc/modules/connecting/proc-creating-soap-api-connections.adoc
  doc/modules/connecting/ref-supported-connectors.adoc
  doc/modules/integrating-applications/proc-creating-rest-api-connectors.adoc
  doc/modules/integrating-applications/proc-creating-soap-api-connectors.adoc
  doc/modules/integrating-applications/proc-updating-api-connectors.adoc
Labels: size/l

#8750 Fix:Add support for Set type operation
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
Labels: group/datavirt, size/m

#8757 Teiidtools 1058
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionTab.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionTab.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringTab.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/index.ts
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/l

#8758 soap-connector-doc-2 update table of connectors
  doc/modules/connecting/ref-supported-connectors.adoc
Labels: size/XS

#8761 TEIIDTOOLS-1059 Modify DV roles logic for empty privileges
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationRolesTest.java
Labels: group/datavirt

#8760 soap connector fix typo
  doc/modules/connecting/proc-creating-soap-api-connections.adoc
Labels: size/XS

#8774 ui(fix): ENTESB-14064 - api connector details
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailHeader.spec.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailCard.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailCard.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorReview.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailHeader.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailHeader.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/index.ts
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/index.ts
  app/ui-react/packages/ui/stories/Customization/api-connector-create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Customization/api-connector-create/2-ImportedOperations.stories.tsx
  app/ui-react/packages/ui/stories/Customization/api-connector-create/3-Security.stories.tsx
  app/ui-react/packages/ui/stories/Customization/api-connector-create/4-Details.stories.tsx
  app/ui-react/packages/ui/stories/Customization/api-connector-detail/ApiConnectorDetailView.stories.tsx
  app/ui-react/packages/ui/stories/Customization/icons.js
  app/ui-react/packages/ui/stories/Customization/openapi-connector.js
  app/ui-react/packages/ui/stories/Customization/soap-connector.js
  app/ui-react/packages/ui/stories/Shared/icons.js
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: group/ui

#8775 chore: add UI components for column masking
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingItemsContitions.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingItemsContitions.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingTab.css
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnMaskingTab.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/ColumnPermissionTab.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/EditPoliciesModal.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/Policies/RowFilteringItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/DataPermission/index.ts
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/xl
