Repository syndesisio/syndesis, pull requests merged in 2020-05, with the labels that each got.

#8380 chore: Update to AtlasMap 2.0.0-M.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8381 chore: Update to AtlasMap 2.0.0-M.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8393 (backport 1.10.x)Added test-ids to conditional flows elements
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
Labels: size/s

#8297 Fix to prevent className in the name field on a standardizedError configuration.
  app/common/model/src/main/java/io/syndesis/common/model/Schema.java
  app/common/util/src/main/java/io/syndesis/common/util/CamelCase.java
  app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
  app/connector/api-provider/src/test/java/io/syndesis/connector/apiprovider/OnExceptionHandlerTest.java
  app/connector/sql/pom.xml
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlConnectorCustomizer.java
  app/connector/sql/src/main/java/io/syndesis/connector/sql/customizer/SqlStartConnectorCustomizer.java
  app/connector/sql/src/main/resources/META-INF/syndesis/connector/sql.json
  app/connector/sql/src/test/java/io/syndesis/connector/sql/SqlConnectorQueryTest.java
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/ErrorMapper.java
  app/connector/support/processor/src/main/java/io/syndesis/connector/support/processor/ErrorStatusInfo.java
  app/connector/support/processor/src/test/java/io/syndesis/connector/support/processor/ErrorMapperTest.java
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookOnExceptionHandler.java
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/migrations/up-42.js
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/MigrationsHelper.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion42Test.java
  app/server/runtime/src/test/resources/migrations/42/integration.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoOpenApiV3-export/model.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/s

#8308 Fix for ENTESB-12840 Enable including error messages in API Provider …
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
Labels: backport 1.10.x, size/XS

#8397 ENTESB-13188: adding the dependencies that were accidentally removed
  app/dv/pom.xml
Labels: size/m

#8290 Teiidtools 979
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: backport 1.10.x, group/datavirt, size/XXL

#8395 Fix: UI inconsistency by removing white background
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
Labels: group/datavirt, size/XS

#8401 BACKPORT: fix(ENTESB-13518): Fix upgrading syndesis installed with an external db
  install/operator/.lib.sh
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/backup/backup.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/s

#8402 BACKPORT fix(ENTESB-13518): Fix upgrading syndesis installed with an external db
  install/operator/.lib.sh
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/backup/backup.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/s

#8400 [ENTESB-13000] Adding "update" to description of put aws-ddb operation
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: backport 1.10.x, size/XS

#8410 fix(operator): nil pointer dereference in upgrade
  install/operator/pkg/syndesis/upgrade/backup.go
Labels: size/XS

#8406 [ENTESB-130000] Backport to 1.10.x
  app/connector/aws-ddb/src/main/resources/META-INF/syndesis/connector/aws-ddb.json
Labels: size/XS

#8408 fix for ENTESB-13104 addon fix
  app/common/util/src/main/java/io/syndesis/common/util/ErrorCategory.java
Labels: backport 1.10.x

#8411 [backport] UI inconsistency by removing white background
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
Labels: group/datavirt, size/XS

#8405 fix for ENTESB-12840 - removing quotes
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
Labels: backport 1.10.x, size/XS

#8055 Allowing for the absence of the pg_up metric
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8415 Entesb 12840 backport
  app/connector/api-provider/src/main/resources/META-INF/syndesis/connector/api-provider.json
Labels: size/XS

#8370 fix for ENTESB-13431, SQL connector exceptions are visible only in DEBUG mode
  app/connector/api-provider/pom.xml
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderOnExceptionHandler.java
Labels: backport 1.10.x

#8407 fix(test): explicit copy of S2I assembly project
  app/test/test-support/src/main/java/io/syndesis/test/container/s2i/S2iProjectBuilder.java
Labels: group/test

#8409 feat(UI): integration extension UI work for ENTESB-13249
  app/ui-react/packages/api/src/useExtensions.tsx
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorExtensionTable.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorExtensionTableRows.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/packages/ui/stories/Integration/Editor/IntegrationEditorExtensionTable.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: cat/feature, group/ui, size/xl

#8416 doc(test): adding a note with the usage of skip variable
  app/test/integration-test/README.md
Labels: group/test, size/XS

#8417 Allowing for the absence of the pg_up metric
  install/operator/pkg/generator/assets/addons/ops/addon-ops-db-alerting-rules.yml
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8412 chore: Update to AtlasMap 2.0.0-M.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8413 chore: Update to AtlasMap 2.0.0-M.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8355 kafka-connector-mf update for TLS option
  doc/modules/connecting/proc-creating-kafka-connections.adoc
Labels: size/s

#8425 Teiidtools 980
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useDVRoles.tsx
  app/ui-react/packages/api/src/useDVStatus.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/api/src/useVirtualizationRoles.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: group/datavirt, size/XXL

#8428 chore: Use no-transfer-progress option on integration-test builds [ci skip]
  tools/bin/commands/integration-test
Labels: size/XS

#8426 roles backport and minor teiid version bump
  app/dv/src/main/java/io/syndesis/dv/RepositoryManager.java
  app/dv/src/main/java/io/syndesis/dv/metadata/internal/DefaultMetadataInstance.java
  app/dv/src/main/java/io/syndesis/dv/model/TablePrivileges.java
  app/dv/src/main/java/io/syndesis/dv/model/export/v1/BaseEntityAdapter.java
  app/dv/src/main/java/io/syndesis/dv/model/export/v1/DataVirtualizationV1Adapter.java
  app/dv/src/main/java/io/syndesis/dv/model/export/v1/TablePrivilegeV1Adapter.java
  app/dv/src/main/java/io/syndesis/dv/openshift/PublishConfiguration.java
  app/dv/src/main/java/io/syndesis/dv/openshift/TeiidOpenShiftClient.java
  app/dv/src/main/java/io/syndesis/dv/repository/RepositoryManagerImpl.java
  app/dv/src/main/java/io/syndesis/dv/repository/TablePrivilegesRepository.java
  app/dv/src/main/java/io/syndesis/dv/server/DvAutoConfiguration.java
  app/dv/src/main/java/io/syndesis/dv/server/SSOConfigurationProperties.java
  app/dv/src/main/java/io/syndesis/dv/server/V1Constants.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DataVirtualizationService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/DvStatus.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/EditorService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/RestDataVirtualization.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/RoleInfo.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/ServiceVdbGenerator.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/StatusService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/ViewListing.java
  app/dv/src/main/resources/db/migration/V8__roles.sql
  app/dv/src/main/resources/io/syndesis/dv/server/messages.properties
  app/dv/src/test/java/io/syndesis/dv/model/export/TablePrivilegeExportTest.java
  app/dv/src/test/java/io/syndesis/dv/openshift/TeiidOpenShiftClientTest.java
  app/dv/src/test/java/io/syndesis/dv/openshift/TestVDBPublisher.java
  app/dv/src/test/java/io/syndesis/dv/repository/TablePrivilegesTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/DataVirtualizationSerializerTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationRolesTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceTestConfiguration.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/ServiceVdbGeneratorTest.java
  app/dv/src/test/resources/generated-pom-security.xml
  app/pom.xml
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8429 [backport 1.10.x] Backport of DV permissions work
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useDVRoles.tsx
  app/ui-react/packages/api/src/useDVStatus.tsx
  app/ui-react/packages/api/src/useVirtualization.tsx
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/api/src/useVirtualizationRoles.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/setupProxy.js
Labels: group/datavirt, size/XXL

#8399 Fixes ENTESB-13717: Initial version of integration test for SOAP Connector
  app/connector/soap/src/test/java/io/syndesis/connector/soap/cxf/IntegrationTestBase.java
  app/pom.xml
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
  app/test/integration-test/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/SoapConnector_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/HelloWorld.wsdl
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/HelloWorldSoapConnector-export/model-info.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/HelloWorldSoapConnector-export/model.json
Labels: backport master

#8421 Refactor of database upgrade
  install/operator/build/conf/config.yaml
  install/operator/go.mod
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/upgrade.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
  install/operator/vendor/github.com/spf13/afero/LICENSE.txt
  install/operator/vendor/github.com/spf13/afero/README.md
  install/operator/vendor/github.com/spf13/afero/afero.go
  install/operator/vendor/github.com/spf13/afero/appveyor.yml
  install/operator/vendor/github.com/spf13/afero/basepath.go
  install/operator/vendor/github.com/spf13/afero/cacheOnReadFs.go
  install/operator/vendor/github.com/spf13/afero/const_bsds.go
  install/operator/vendor/github.com/spf13/afero/const_win_unix.go
  install/operator/vendor/github.com/spf13/afero/copyOnWriteFs.go
  install/operator/vendor/github.com/spf13/afero/go.mod
  install/operator/vendor/github.com/spf13/afero/go.sum
  install/operator/vendor/github.com/spf13/afero/httpFs.go
  install/operator/vendor/github.com/spf13/afero/ioutil.go
  install/operator/vendor/github.com/spf13/afero/lstater.go
  install/operator/vendor/github.com/spf13/afero/match.go
  install/operator/vendor/github.com/spf13/afero/mem/dir.go
  install/operator/vendor/github.com/spf13/afero/mem/dirmap.go
  install/operator/vendor/github.com/spf13/afero/mem/file.go
  install/operator/vendor/github.com/spf13/afero/memmap.go
  install/operator/vendor/github.com/spf13/afero/os.go
  install/operator/vendor/github.com/spf13/afero/path.go
  install/operator/vendor/github.com/spf13/afero/readonlyfs.go
  install/operator/vendor/github.com/spf13/afero/regexpfs.go
  install/operator/vendor/github.com/spf13/afero/unionFile.go
  install/operator/vendor/github.com/spf13/afero/util.go
  install/operator/vendor/k8s.io/api/admission/v1/doc.go
  install/operator/vendor/k8s.io/api/admission/v1/generated.pb.go
  install/operator/vendor/k8s.io/api/admission/v1/generated.proto
  install/operator/vendor/k8s.io/api/admission/v1/register.go
  install/operator/vendor/k8s.io/api/admission/v1/types.go
  install/operator/vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  install/operator/vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/doc.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/generated.pb.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/generated.proto
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/register.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/types.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/types_swagger_doc_generated.go
  install/operator/vendor/k8s.io/api/imagepolicy/v1alpha1/zz_generated.deepcopy.go
  install/operator/vendor/k8s.io/client-go/rest/fake/fake.go
  install/operator/vendor/k8s.io/kubectl/pkg/scheme/install.go
  install/operator/vendor/k8s.io/kubectl/pkg/scheme/scheme.go
  install/operator/vendor/modules.txt
Labels: size/XXL

#8443 docs-administrative-updates cleanup doc files
  doc/connecting/master-docinfo.xml
  doc/connecting/master.adoc
  doc/customizing/master-docinfo.xml
  doc/customizing/master.adoc
  doc/developing_extensions/master-docinfo.xml
  doc/developing_extensions/master.adoc
  doc/integrating-applications/master-docinfo.xml
  doc/integrating-applications/master.adoc
  doc/managing_environments/master-docinfo.xml
  doc/managing_environments/master.adoc
  doc/shared/attributes-links.adoc
  doc/shared/attributes.adoc
  doc/tutorials/master-docinfo.xml
  doc/tutorials/master.adoc
Labels: size/l

#8441 chore: rollback #8181
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/go.sum
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets/addons/publicApi/addon-public-oauthproxy.yml.tmpl
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  install/operator/vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  install/operator/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  install/operator/vendor/github.com/aws/aws-sdk-go/aws/version.go
  install/operator/vendor/github.com/aws/aws-sdk-go/service/s3/statusok_error.go
  install/operator/vendor/github.com/aws/aws-sdk-go/service/s3/unmarshal_error.go
  install/operator/vendor/modules.txt
Labels: group/operator

#8447 [backport 1.10.x] integration extension library ui work
  app/ui-react/packages/api/src/useExtensions.tsx
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorExtensionTable.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorExtensionTableRows.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/packages/ui/stories/Integration/Editor/IntegrationEditorExtensionTable.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/xl

#8446 [backport 1.10.x] api client connector PF upgrade
  app/server/runtime/src/main/resources/migrations/common.js
  app/server/runtime/src/main/resources/migrations/up-30.js
  app/server/runtime/src/main/resources/migrations/up-32.js
  app/ui-react/craco.config.js
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorCreatorLayout.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailCard.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorBreadSteps.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorBreadcrumb.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorFooter.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorToggleList.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/ApiConnectorCreatorApp.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorWizardSteps.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfoForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorSecurityForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/index.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/XXL

#8440 Fix: Link metadata tree component action with ddl editor
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeTableNodeComponent.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: backport 1.10.x, group/datavirt, size/l

#8459 Only delete tags when there are versions to discard
  tools/bin/commands/release
Labels: size/s

#8460 Revert "Use the Tag instead of Image for database image"
  install/operator/pkg/cmd/internal/install/generator/generator.go
Labels: size/XS

#8462 Revert "Use the Tag instead of Image for database image" (1.10.x branch)
  install/operator/pkg/cmd/internal/install/generator/generator.go
Labels: size/XS

#8457 Fixes ENTESB-13789, JSON list must use []
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/SoapApiConnectorGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/SoapApiConnectorGeneratorExampleTest.java
Labels: backport 1.10.x

#8455 Fix: role row remove and multi role set fix along with UI fixes
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.css
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: backport 1.10.x, group/datavirt, size/l

#8475 Fix: Sync the toolbar checkbox with rest of page view checkbox
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: size/m

#8477 fixes - DV Data Permission requested fixes
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: backport 1.10.x, group/datavirt, size/l

#8473 Backport 1.10.x
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeTableNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.css
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: size/l

#8476 doc updates related to UI updates
  doc/modules/connecting/proc-create-amq-connection.adoc
  doc/modules/connecting/proc-create-amqp-connection.adoc
  doc/modules/connecting/proc-create-concur-connection.adoc
  doc/modules/connecting/proc-create-database-connection.adoc
  doc/modules/connecting/proc-create-dropbox-connection.adoc
  doc/modules/connecting/proc-create-gmail-connection.adoc
  doc/modules/connecting/proc-create-google-calendar-connection.adoc
  doc/modules/connecting/proc-create-google-sheets-connection.adoc
  doc/modules/connecting/proc-create-kudu-connections.adoc
  doc/modules/connecting/proc-create-s3-connection.adoc
  doc/modules/connecting/proc-create-servicenow-connection.adoc
  doc/modules/connecting/proc-creating-a-connection-to-an-imap-or-pop3-email-server.adoc
  doc/modules/connecting/proc-creating-a-connection-to-an-smtp-email-server.adoc
  doc/modules/connecting/proc-creating-amazon-dynamodb-connections.adoc
  doc/modules/connecting/proc-creating-amazon-sns-connections.adoc
  doc/modules/connecting/proc-creating-amazon-sqs-connections.adoc
  doc/modules/connecting/proc-creating-fhir-connections.adoc
  doc/modules/connecting/proc-creating-ftp-connections.adoc
  doc/modules/connecting/proc-creating-http-connections.adoc
  doc/modules/connecting/proc-creating-irc-connections.adoc
  doc/modules/connecting/proc-creating-jira-connections.adoc
  doc/modules/connecting/proc-creating-mongodb-connections.adoc
  doc/modules/connecting/proc-creating-mqtt-connections.adoc
  doc/modules/connecting/proc-creating-odata-connections.adoc
  doc/modules/connecting/proc-creating-rest-api-connections.adoc
  doc/modules/connecting/proc-creating-slack-connections.adoc
  doc/modules/connecting/proc-creating-telegram-connections.adoc
  doc/modules/integrating-applications/proc-add-timer-connection.adoc
  doc/modules/integrating-applications/proc-create-api-provider-integration.adoc
  doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
  doc/modules/tutorials/proc-amq2api-create-amq-connection.adoc
  doc/modules/tutorials/proc-amq2api-create-rest-api-connection.adoc
  doc/modules/tutorials/proc-create-sf-connection.adoc
  doc/modules/tutorials/proc-create-twitter-connection.adoc
  doc/modules/tutorials/proc-t2sf-choose-start.adoc
Labels: size/m

#8479 [backport 1.10.x] Backport DV permission fixes
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionToolbar.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
Labels: size/l

#8478 [ENTESB-13786] Add delay option to s3 getObject action
  app/connector/aws-s3/src/main/resources/META-INF/syndesis/connector/aws-s3.json
Labels: size/s

#8469 chore: Update to AtlasMap 2.0.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
  app/ui-react/yarn.lock
Labels: size/XXL

#8467 [operator] Prepare the changes for CLOUDBLD-26
  install/operator/pkg/cmd/internal/olm/olm.go
  install/operator/pkg/generator/assets/install/deployment.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/olm.go
Labels: cat/enhancement, group/operator, size/l

#8492 Added classname to OpenApiSelectMethod
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
Labels: size/XS

#8491 Added classname to OpenApiSelectMethod
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
Labels: backport 1.10.x, size/XS

#8497 Fixes ENTESB-13164, changed dom4j version to 2.1.1
  app/server/api-generator/pom.xml
Labels: size/XS

#8494 Fix: Sync issue of rolepermissionmodel in viewpermissionlist
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: backport 1.10.x, group/datavirt, size/m

#8472 fix(dv) TEIIDTOOLS-1016 filtering swagger warnings
  app/dv/src/main/resources/application.properties
Labels: size/XS

#8490 [ResetDB] Check if syndesis-dv svc is present before trying to reset it
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java
Labels: backport 1.10.x

#8468 chore: Update to AtlasMap 2.0.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
  app/ui-react/yarn.lock
Labels: size/m

#8499 [backport 1.10.x] TEIIDTOOLS-1018
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: group/datavirt, size/m

#8495 backport: Prepare the changes for CLOUDBLD-26
  install/operator/pkg/generator/assets/install/deployment.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/olm.go
Labels: size/l

#8500 DV permission component stories
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
Labels: size/l

#8480 feat(ui): support for SOAP connector
  app/ui-react/packages/api/src/useApiConnectorCreator.tsx
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateUpload.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreateService.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/2-ImportedOperations.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/4-Details.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
Labels: group/ui, size/XXL

#8506 Upgrade iltorb to 2.4.5, skip PUPPETEER CHROMIUM DOWNLOAD
  app/pom.xml
  app/ui-react/pom.xml
Labels: size/XS

#8502 fix(server): merge existing and new configured properties on server load
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/test/java/io/syndesis/server/dao/DataManagerTest.java
Labels: group/server

#8507 (backport) Upgrade iltorb to 2.4.5, skip PUPPETEER CHROMIUM DOWNLOAD
  app/pom.xml
  app/ui-react/pom.xml
Labels: size/XS

#8504 [backport 1.10.x] support for SOAP connector #8480
  app/ui-react/craco.config.js
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/api/src/useApiConnectorCreator.tsx
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateUpload.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreateService.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/2-ImportedOperations.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/3-Security.stories.tsx
  app/ui-react/packages/ui/stories/Customization/create/4-Details.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/XXL

#8508 chore(operator): fast database shutdown
  install/operator/go.sum
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/go-openapi/spec/contact_info.go
  install/operator/vendor/github.com/go-openapi/spec/expander.go
  install/operator/vendor/github.com/go-openapi/spec/license.go
  install/operator/vendor/github.com/go-openapi/spec/schema_loader.go
  install/operator/vendor/modules.txt
Labels: size/s

#8510 feat(connector/debezium): kafka broker autodiscovery
  app/connector/debezium/src/main/resources/META-INF/syndesis/connector/debezium.json
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java
Labels: group/connector

#8515 Fix: dublicate permission role row
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
Labels: backport 1.10.x, group/datavirt, size/m

#8505 fixes issue with webhook error loading
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: size/l

#8514 (fix) TEIIDTOOLS-1028 DV confirmation dialog fixes
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: size/m

#8520 [backport 1.10.x] ENTESB-13527 webhook error + token fix
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: group/ui, size/l

#8518 fix(server): user properties to override configuredProperties
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Labels: group/server

#8521 Fix: Stories fixes
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
Labels: backport 1.10.x, group/datavirt, size/m

#8523 [PF4 migration] Added DataTestIds to OpenApiReviewActionsPage
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Labels: size/XS

#8528 Backport 1.10.x
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/RolePermissionListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/DataPermission/ViewPermissionListItems.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionList.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/RolePermissionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/ViewsPermissions/ViewPermissionListItems.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: size/l

#8526 TEIIDTOOLS-1016 switching the probes to actuator/health
  app/dv/pom.xml
  app/dv/src/main/resources/application.properties
  app/dv/src/test/resources/application-test.properties
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#8524 [PF4 migration] Added DataTestIds to OpenApiReviewActionsPage
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Labels: size/XS

#8534 Fix for #8325 adding missing migration function
  app/server/runtime/src/main/resources/migrations/up-42.js
Labels: size/s

#8529 TTOOLS-1025 Adds popover details to virtualization status
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: group/datavirt, size/l

#8536 [ENTESB-13434] removes ability to review/edit for SOAP connector
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
Labels: cat/bug, group/ui, size/s

#8555 refactor(connector/debezium): mysql metadata retrieval
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/DebeziumMetaDataRetrieval.java
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/metadata/DebeziumDatashapeStrategy.java
  app/connector/debezium/src/main/java/io/syndesis/connector/debezium/metadata/DebeziumMySQLDatashapeStrategy.java
  app/connector/debezium/src/test/java/io/syndesis/connector/debezium/metadata/DebeziumMySQLDatashapeStrategyTest.java
Labels: group/connector

#8532 Fix for Entesb 13816 - The defaultValue should be object not string
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConfigurationProperty.java
  app/connector/webhook/src/main/resources/META-INF/syndesis/connector/webhook.json
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiConnectorGenerator.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthApp.java
  app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/AbstractResourceUpdateHandler.java
Labels: backport 1.10.x

#8557 Fix OLM subcommand to use correct property for operator-image parameter
  install/operator/pkg/cmd/internal/olm/olm.go
Labels: size/XS

#8558 Fix OLM subcommand to use correct property for operator-image parameter (1.10.x)
  install/operator/pkg/cmd/internal/olm/olm.go
Labels: size/XS

#8537 [backport 1.10.x] removes ability to review/edit for SOAP connector
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
Labels: size/s

#8538 mongo-db-connector-doc-update add ID field req for upsert
  doc/modules/connecting/proc-adding-mongodb-connections-write.adoc
Labels: size/s

#8541 (backport) fix: add missing PageTitle component to pages
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
Labels: size/xl

#8539 fix: add missing PageTitle component to pages
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
Labels: size/xl

#8563 chore: adjust version in doc links for 7.7
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#8560 Fix: console errors and create view loading.
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
Labels: backport 1.10.x, group/datavirt, size/s

#8564 fix: polish up the oauth settings page and expander
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
Labels: size/m

#8565 (backport) fix: polish up the oauth settings page and expander
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
Labels: size/m

#8568 TEIIDTOOLS-1031 Add DV page titles
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationImportPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: group/datavirt, size/l

#8574 Fixes ENTESB-13911, added default value of authenticationType and passwordType properties of SOAP connector
  app/connector/soap/src/main/resources/META-INF/syndesis/connector/soap.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: size/XS

#8579 (backport 1.10.x) Backport DV fixes
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationDetailsHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationDetailsHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationDataPermissionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationImportPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: size/l

#8572 fix(ui): [ENTESB-13841] - fix API provider step not working
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/index.ts
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Integration/Editor/ApiProvider.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SelectMethodPage.tsx
Labels: cat/bug, group/ui, size/l

#8571 (backport) fix: update template type selector to use the right markup
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
Labels: size/l

#8575 [backport 1.10.x] [ENTESB-13841] - fix API provider step not working
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderSelectMethod.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/index.ts
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/stories/Customization/create/1-ProvideDocument.stories.tsx
  app/ui-react/packages/ui/stories/Integration/Editor/ApiProvider.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SelectMethodPage.tsx
Labels: cat/bug, group/ui, size/l

#8570 fix: update template type selector to use the right markup
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
Labels: size/l

#8567 fix #8566 Log Error in the WebHook when exception happens
  app/connector/webhook/pom.xml
  app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookOnExceptionHandler.java
Labels: backport 1.10.x

#8569 ENTESB-13802: Fixes syntax error in addon-dv-server yaml config
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: backport 1.10.x, size/XS

#8578 chore: Update to AtlasMap 2.0.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/m

#8576 chore: Update to AtlasMap 2.0.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/m

#8577 Fix install operator feedback output
  install/operator/pkg/cmd/internal/install/install.go
Labels: size/XS

#8582 BACKPORT ENTESB-13802: Fixes syntax error in addon-dv-server yaml config
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8573 Fixes ENTESB-13911, added default value of authenticationType and passwordType properties of SOAP connector
  app/connector/soap/src/main/resources/META-INF/syndesis/connector/soap.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: size/XS

#8583 fix(dv) ENTESB-13939 related to the refactor backport
  app/dv/pom.xml
Labels: size/s

#8588 fix(integration): align mongodb integration bom deps
  app/integration/bom/pom.xml
Labels: dependencies, group/integration, size/XS

#8591 Fixes ENTESB-13911, default values for SOAP connector properties
  app/connector/soap/src/main/resources/META-INF/syndesis/connector/soap.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: size/m

#8592 Fixes ENTESB-13911, default values for SOAP connector properties
  app/connector/soap/src/main/resources/META-INF/syndesis/connector/soap.json
  app/server/dao/src/main/resources/io/syndesis/server/dao/deployment.json
Labels: size/m
