Repository syndesisio/syndesis, pull requests merged in 2020-04, with the labels that each got.

#8158 [operator] lower log output for race condition
  install/operator/pkg/syndesis/action/install.go
Labels: size/XS

#8167 fix(build): error handling in release command
  tools/bin/commands/release
Labels: size/s

#8168 fix(build): error handling in release command
  tools/bin/commands/release
Labels: size/s

#8169 chore: migrate create connection wizard to pf4
  app/ui-react/packages/ui/__tests__/Connection/ConnectorConfigurationForm.spec.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorBreadSteps.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorBreadcrumb.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorFooter.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorToggleList.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Connection/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadSteps.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/connections/components/index.ts
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorStepsWithToolbar.tsx
Labels: size/XXL

#8170 fix(build): git style remote in release command
  tools/bin/commands/release
Labels: size/s

#8173 fix(build): git style remote in release command
  tools/bin/commands/release
Labels: size/s

#8174 chore: Update to AtlasMap 1.44.0-M1
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml
  app/integration/runtime-camelk/pom.xml
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime/pom.xml
  app/pom.xml
  app/test/test-support/src/main/resources/io/syndesis/test/integration/project/template/pom.xml.mustache
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8172 fix: remove test tapes causing issue with running syndesis on windows
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LkiT24SvERwF0KppRNIz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/74.json5
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LkiT24SvERwF0KppRNIz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/75.json5
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LmdWeJSHdpg6ZYZNwxAz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/184.json5
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LmdWeJSHdpg6ZYZNwxAz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/185.json5
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LmeHA-kHdpg6ZYZNwxUz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/189.json5
  app/ui-react/syndesis/tapes/create-integration.spec.js/api/v1/connections/i-LmeHA-kHdpg6ZYZNwxUz/actions/i-LkAI0ut-OrgXelAq8JAz:4babf99c-6287-47bb-862c-da7d053338af/190.json5
Labels: size/xl

#8175 fix(build): pom_version in release
  tools/bin/commands/release
Labels: size/s

#8185 user doc: Make it crystal clear that the toplevel "properties" attribute is required
  doc/modules/customizing/c_about-extension-definitions.adoc
  doc/modules/customizing/r_descriptions-of-user-interface-properties-in-extension-definitions.adoc
Labels: size/XS

#8187 fix(build): pom_version in release
  tools/bin/commands/release
Labels: size/s

#8186 TEIIDTOOLS-962 Resolve wizard issue with connection schema init
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Labels: group/datavirt, size/s

#8184 Using memo for performance
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeTableNodeComponent.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: size/xl

#8192 user doc: Correct a broken link
  doc/modules/connecting/c_about-parameter-placeholders-and-values.adoc
Labels: size/XS

#8190 fix(build): release tagging
  tools/bin/commands/release
Labels: size/XS

#8194 fix(build): release tagging
  tools/bin/commands/release
Labels: size/XS

#8181 [operator] Add configuration field to swap between tag and sha references
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/generator/assets/addons/camelk/platform.yml.tmpl
  install/operator/pkg/generator/assets/addons/dv/addon-dv-server.yml.tmpl
  install/operator/pkg/generator/assets/addons/publicApi/addon-public-oauthproxy.yml.tmpl
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-image-streams.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets/upgrade/07-syndesis-upgrade.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/util/template_functions.go
Labels: cat/enhancement, cat/feature, group/operator

#8211 TTOOLS-962 combine dv schema services
  app/dv/src/main/java/io/syndesis/dv/server/V1Constants.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/IntegrationTest.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/MetadataServiceTest.java
  app/ui-react/packages/api/src/useVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/useVirtualizationConnectionStatuses.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: group/datavirt

#8213 fix(integration-test): adapting to Camel3 (version and http4)
  app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/SyndesisHttpConfiguration.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiprovider/TodoApi_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiprovider/TodoListApi_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiprovider/TodoOpenApiV3_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/conditional/ConditionalFlows_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpSplitToDB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpTestSupport.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/FtpToDB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/ftp/WebHookToFtp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/mail/SendMail_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/quickstart/Webhook2DB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBSplitToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/DBToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/GoogleSheetsTestSupport.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sheets/MultiSqlToSheets_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/sql/DBToHttp_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/webhook/WebHookSplitToDB_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/webhook/WebHookToDB_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInHeader-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2ApiKeyInQuery-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoApiV2BasicAuth-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV2Connector-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/TodoOpenApiV3Connector-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoApi-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoListApi-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoOpenApiV3-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/googlecalendar/webhook-to-google-calendar-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/http/HttpToHttp-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/mail/SendMail-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/quickstart/Webhook2Db-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sheets/DBSplitToSheets-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sheets/DBToSheets-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sheets/MultiSqlToSheets-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sheets/SheetsToSheets-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/sql/DBToHttp-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/webhook/WebhookSplitToDB-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/webhook/WebhookToDB-export/model.json
Labels: pr/wip

#8000 chore: add OLM manifests for version 1.9
  install/operator/deploy/manifests/1.9.0/syndesis.crd.yaml
  install/operator/deploy/manifests/1.9.0/syndesisoperator.1.9.0.clusterserviceversion.yaml
  install/operator/deploy/manifests/syndesis.package.yaml
Labels: size/l

#8221 chore: fix typo for create connection string
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
Labels: size/XS

#8222 user doc: Emphasize that Query field accepts standard SQL only
  doc/modules/connecting/p_adding-db-connection-start.adoc
Labels: size/XS

#8224 Fix Camel Version to 3.1.0 on some diverging files
  app/integration/bom-camel-k/pom.xml
  app/pom.xml
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/go.sum
  install/operator/pkg/generator/assets/addons/camelk/camel-catalog-3.1.0.yaml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/expectations.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/expectations_before_go18.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/expectations_go18.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/options.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/rows.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/sqlmock.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/sqlmock_before_go18.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/sqlmock_go18.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/sqlmock_go18_19.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/sqlmock_go19.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/statement.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/statement_before_go18.go
  install/operator/vendor/github.com/DATA-DOG/go-sqlmock/statement_go18.go
  install/operator/vendor/github.com/spf13/cobra/Makefile
  install/operator/vendor/github.com/spf13/cobra/README.md
  install/operator/vendor/github.com/spf13/cobra/bash_completions.go
  install/operator/vendor/github.com/spf13/cobra/cobra.go
  install/operator/vendor/github.com/spf13/cobra/command.go
  install/operator/vendor/github.com/spf13/cobra/go.mod
  install/operator/vendor/github.com/spf13/cobra/go.sum
  install/operator/vendor/github.com/testcontainers/testcontainers-go/docker.go
  install/operator/vendor/github.com/testcontainers/testcontainers-go/reaper.go
  install/operator/vendor/modules.txt
Labels: size/m

#8228 Use the Tag instead of Image for database image
  install/operator/pkg/cmd/internal/install/generator/generator.go
Labels: size/XS

#8225 feat(server): extension filter
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ExtensionsITCase.java
Labels: group/server

#8251 feat(connector/mongodb): Fix flaky test
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
Labels: group/connector

#8250 chore: Update to AtlasMap 1.44.0-M1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8253 Added data-testids
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Labels: size/XS

#8259 [backport] Added testids to API Provider components
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
Labels: size/XS

#8260 feature(server): extensions list explicit type
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/extension/ExtensionHandler.java
Labels: group/server, size/XS

#8262 [HTTPS] Fix id of periodic url invoke
  app/connector/http/src/main/resources/META-INF/syndesis/connector/https4.json
Labels: size/XS

#8264 Fix daily builds on ci.fabric8.io
  app/ui-react/pom.xml
  app/ui-react/syndesis/craco.config.js
Labels: size/s

#8193 Dv ls UI integration part 1
  app/ui-react/craco.config.js
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/ui/__tests__/AppLayout.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationsListItem.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/syndesis/craco.config.js
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/app/App.test.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
  app/ui-react/yarn.lock
Labels: size/l

#8266 [Backport 1.10.x] Backport TEIIDTOOLS-898
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
Labels: group/datavirt, size/s

#8280 chore: update README
  README.md
Labels: backport 1.10.x, size/XS

#8279 fix(test): maven debug option fix
  app/test/test-support/src/main/java/io/syndesis/test/container/integration/SyndesisIntegrationRuntimeContainer.java
Labels: group/test

#8283 fix(deps): exclude javax.activation:activation
  app/pom.xml
Labels: size/XS

#8284 chore(build): remove Maven repositories
  app/connector/mqtt/pom.xml
  app/extension/bom/pom.xml
  app/extension/maven-plugin/src/it/repackage/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape/pom.xml
  app/integration/bom-camel-k/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/l

#8282 [PF4 migration] Added test-ids to API connector page
  app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Labels: size/s

#8285 (backport 1.10.x)[PF4 migration] Added test-ids to API connector page
  app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListView.tsx
Labels: size/s

#8293 Backport: Use the Tag instead of Image for database image
  install/operator/pkg/cmd/internal/install/generator/generator.go
Labels: size/XS

#8298 Replaced old references of CreateConnection translation
  app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorStepsWithToolbar.tsx
Labels: size/s

#8305 (fix) ENTESB-13271 makes translation files consistent
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#8291 [PF4 migration] Added DataTestIds to activity, metrics and cicd pages
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Labels: size/m

#8299 [operator] Fix for ops addon
  install/operator/go.mod
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/vendor/modules.txt
Labels: backport 1.10.x, cat/bug, group/operator, size/m

#8302 [operator] --user is mandatory when calling grant
  install/operator/pkg/cmd/internal/grant/grant.go
Labels: backport 1.10.x, group/operator, size/XS

#8310 refactor(ci): PR number from CI_PULL_REQUEST env
  .circleci/config.yml
Labels: backport 1.10.x, size/XS

#8319 [PF4 migration] Added DataTestIds to DataVirtualization pages
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
Labels: size/s

#8320 (backport-1.10.x)[PF4 migration] Added DataTestIds to DataVirtualization pages
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
Labels: size/s

#8242 upgrade API client connector for PF
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorCreatorLayout.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailCard.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorBreadSteps.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorBreadcrumb.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorFooter.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorToggleList.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/ApiConnectorCreatorApp.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorWizardSteps.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfoForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorSecurityForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/index.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/XXL

#8292 (backport-1.10.x)[PF4 migration] Added DataTestIds to activity, metrics and cicd pages
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListItem.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/TagIntegrationListItem.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Labels: size/m

#8323 [backport to 1.10.x] [security] bump request from 2.42.0 to 2.88.0 in /app/ui-react
  app/ui-react/packages/atlasmap-assembly/yarn.lock
Labels: dependencies, group/ui, security, size/XS

#8322 chore: turn down parallelism to 1 for CI
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/syndesis/craco.config.js
Labels: backport 1.10.x, size/XS

#8324 refactor(ci): PR number from CI_PULL_REQUEST env
  .circleci/config.yml
Labels: size/XS

#8306 (backport) ENTESB-13271 sync translation key usage
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorStepsWithToolbar.tsx
Labels: size/s

#8341 [PF4 migration] Added test-ids to integration editor step item
  app/ui-react/packages/ui/src/Integration/BreadcrumbDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
Labels: size/s

#8343 fix(build): perform a `git fetch --tags --prune`
  tools/bin/commands/release
Labels: backport 1.10.x, size/XS

#8345 (backport 1.10.x)[PF4 migration] Added test-ids to integration editor step item
  app/ui-react/packages/ui/src/Integration/BreadcrumbDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
Labels: size/s

#8315 (backport) fix for ENTESB-11675 to add errorHandler field to the schema
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: size/XS

#8347 fix(build): perform a `git fetch --tags --prune`
  tools/bin/commands/release
Labels: size/XS

#8314 fix(ENTESB-13518): Fix upgrading syndesis installed with an external db
  install/operator/.lib.sh
  install/operator/pkg/cmd/internal/operator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/backup/backup.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/util/postgresql.go
  install/operator/pkg/util/postgresql_test.go
Labels: backport 1.10.x, group/operator, size/l, size/s

#8351 Fix: https-proxy-middleware pkg after update
  app/ui-react/syndesis/src/setupProxy.js
Labels: size/XS

#8356 fix: update the form array widget to use the pf4 button link and fix icons
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.css
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/packages/auto-form/src/widgets/index.ts
Labels: backport 1.10.x, size/m

#8353 (backport 1.10.x)[PF4 migration] Added test-ids to ApiClientConnectorSecurity
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: size/XS

#8357 fix: use a different character sequence for interpolation for template editor
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplate.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: backport 1.10.x, size/s

#8352 [PF4 migration] Added test-ids to ApiClientConnectorSecurity
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: size/XS

#8358 fix: move the special classname to the dropdown item so the logout entry is hidden
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
Labels: backport 1.10.x, size/XS

#8359 fix: define table column widths, make data display size constrained
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
Labels: backport 1.10.x, size/m

#8362 (backport) fix: define table column widths, make data display size constrained
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
Labels: size/m

#8361 fix: bring over CI fixes for the UI jobs
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/syndesis/craco.config.js
Labels: size/m

#8363 chore: Update to AtlasMap 2.0.0-M.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8364 chore: Update to AtlasMap 2.0.0-M.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/yarn.lock
Labels: size/s

#8372 fix(build): quay.io transfer for dependabot PRs
  .circleci/config.yml
Labels: backport 1.10.x, size/XS

#8371 (backport) fix: move the special classname to the dropdown item so the logout entry is hidden
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
Labels: size/XS

#8376 fix(build): remove quotes around tags to delete
  tools/bin/commands/release
Labels: backport 1.10.x, size/XS

#8377 [skip ci] fix(build): remove quotes around tags to delete
  tools/bin/commands/release
Labels: size/XS

#8375 fix(build): quay.io transfer for dependabot PRs
  .circleci/config.yml
Labels: size/XS

#8360 (backport) fix: use a different character sequence for interpolation for template editor
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplate.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/s

#8369 (backport) fix: update the form array widget to use the pf4 button link and fix icons
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.css
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/packages/auto-form/src/widgets/index.ts
Labels: size/m

#8378 Added test-ids to conditional flows elements
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
Labels: size/s
