Repository syndesisio/syndesis, pull requests merged in 2020-03, with the labels that each got.

#7996 fix: Todo pod does not deploy on OCP 4.4 https://issues.redhat.com/browse/ENTESB-12972
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#7541 fix for ENTESB-11675 to add errorHandler field to the schema
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: size/XS

#7994 Improve DV metrics cards
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvMetricsContainer.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Metrics/DvResultSetCacheMetric.tsx
Labels: group/datavirt, size/s

#7993 Improve DV connection status display
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.css
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionCard.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionStatus.css
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionStatus.tsx
  app/ui-react/packages/ui/src/Data/DvConnection/index.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Data/DvConnection/DvConnectionStatus.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnections.tsx
Labels: group/datavirt, size/l

#8002 user doc: QA updates for doc for enabling auto-discovery of Kafka brokers
  doc/modules/connecting/p_adding-kafka-connection-start.adoc
  doc/modules/connecting/p_enabling-auto-discovery-of-kafka-brokers.adoc
Labels: size/XS

#8004 DV details page updates
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.css
  app/ui-react/packages/ui/src/Data/Virtualizations/PublishStatusWithProgress.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.css
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationEditorPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationVersionsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, size/m

#8014 user doc: Add note that recommends specifying data type
  doc/modules/connecting/p_adding-amq-connection-finish.adoc
  doc/modules/connecting/p_adding-amq-connection-middle.adoc
  doc/modules/connecting/p_adding-amq-connection-start.adoc
  doc/modules/connecting/p_adding-amqp-connection-middle.adoc
  doc/modules/connecting/p_adding-amqp-connection-start.adoc
  doc/modules/connecting/p_adding-dropbox-connection-finish.adoc
  doc/modules/connecting/p_adding-dropbox-connection-middle.adoc
  doc/modules/connecting/p_adding-dropbox-connection-start.adoc
  doc/modules/connecting/p_adding-ftp-finish-middle-connection.adoc
  doc/modules/connecting/p_adding-ftp-start-connection.adoc
  doc/modules/connecting/p_adding-http-connections.adoc
  doc/modules/connecting/p_adding-irc-connection-receive.adoc
  doc/modules/connecting/p_adding-irc-connection-send.adoc
  doc/modules/connecting/p_adding-kafka-connection-finish-middle.adoc
  doc/modules/connecting/p_adding-kafka-connection-start.adoc
  doc/modules/connecting/p_adding-mongodb-connections-read.adoc
  doc/modules/connecting/p_adding-mqtt-connection-finish-middle.adoc
  doc/modules/connecting/p_adding-mqtt-connection-start.adoc
  doc/modules/connecting/p_adding-s3-connection-finish.adoc
  doc/modules/connecting/p_adding-s3-connection-middle.adoc
  doc/modules/connecting/p_adding-s3-connection-start.adoc
  doc/modules/connecting/p_calling-a-knative-service-from-a-simple-integration.adoc
  doc/modules/connecting/p_sending-messages-to-a-knative-channel.adoc
  doc/modules/connecting/p_subscribing-to-a-knative-channel-to-obtain-messages.adoc
  doc/modules/connecting/r_how-to-specify-the-schema-in-a-database-connection.adoc
  doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc
  doc/modules/integrating-applications/p_try-api-provider-quickstart.adoc
Labels: size/l

#8015 user doc: Typo fix
  doc/modules/integrating-applications/p_configure-publish-api-provider-quickstart.adoc
Labels: size/XS

#8011 operator: Move resources cleanup from install to upgrade
  install/operator/go.mod
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/upgrade/cleanup.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
Labels: size/l

#8018 [backport] move resources cleanup from install to upgrade
  install/operator/go.mod
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/upgrade/cleanup.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
Labels: size/l

#8019 [backport] #7983 fix parse and install resources also in installing phase
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/s

#8013 fix(operator): provide default database image
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/install/generator/generator.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/vendor/gopkg.in/yaml.v2/decode.go
  install/operator/vendor/gopkg.in/yaml.v2/scannerc.go
  install/operator/vendor/gopkg.in/yaml.v2/yaml.go
  install/operator/vendor/gopkg.in/yaml.v2/yamlh.go
  install/operator/vendor/modules.txt
Labels: size/m

#8025 fix(operator): provide default database image
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/install/generator/generator.go
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/vendor/gopkg.in/yaml.v2/decode.go
  install/operator/vendor/gopkg.in/yaml.v2/scannerc.go
  install/operator/vendor/gopkg.in/yaml.v2/yaml.go
  install/operator/vendor/gopkg.in/yaml.v2/yamlh.go
  install/operator/vendor/modules.txt
Labels: size/m

#8030 Backport -> fix: Conditionalise jaeger collector uri to align with logic in meta
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/vendor/github.com/docker/docker/pkg/archive/example_changes.go
  install/operator/vendor/github.com/lib/pq/oid/gen.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: size/XS

#8028 fix for issue #8027, where the operator binary download url cannot be constructed
  tools/bin/commands/minishift
  tools/bin/commands/util/operator_funcs
Labels: size/s

#8031 [operator] fix for copy and paste mess
  install/operator/pkg/syndesis/upgrade/cleanup.go
  install/operator/vendor/github.com/docker/docker/pkg/archive/example_changes.go
  install/operator/vendor/github.com/lib/pq/oid/gen.go
  install/operator/vendor/golang.org/x/sys/unix/mkasm_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/mkpost.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  install/operator/vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  install/operator/vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/mksysnum.go
  install/operator/vendor/golang.org/x/sys/unix/types_aix.go
  install/operator/vendor/golang.org/x/sys/unix/types_darwin.go
  install/operator/vendor/golang.org/x/sys/unix/types_dragonfly.go
  install/operator/vendor/golang.org/x/sys/unix/types_freebsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_netbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_openbsd.go
  install/operator/vendor/golang.org/x/sys/unix/types_solaris.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  install/operator/vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  install/operator/vendor/golang.org/x/text/unicode/norm/maketables.go
  install/operator/vendor/golang.org/x/text/unicode/norm/triegen.go
  install/operator/vendor/golang.org/x/text/width/gen.go
  install/operator/vendor/golang.org/x/text/width/gen_common.go
  install/operator/vendor/golang.org/x/text/width/gen_trieval.go
  install/operator/vendor/golang.org/x/tools/go/gcexportdata/main.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkindex.go
  install/operator/vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  install/operator/vendor/modules.txt
Labels: size/l

#8042 chore: migrate open API select method page; remove unused component
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/packages/ui/src/Shared/LogViewer.css
  app/ui-react/packages/ui/src/Shared/LogViewer.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
Labels: size/xl

#8016 Improves handling of DV view version conflicts
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: group/datavirt, size/m

#8044 chore: migrate progress with link and syndesis alert to pf4
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
  app/ui-react/packages/ui/src/Shared/SyndesisAlert.tsx
Labels: size/m

#8040 chore(docs): remove Software Developer Handbook
  .circleci/config.yml
  doc/sdh/.gitignore
  doc/sdh/cli/cmd_build.adoc
  doc/sdh/cli/cmd_crc.adoc
  doc/sdh/cli/cmd_dev.adoc
  doc/sdh/cli/cmd_doc.adoc
  doc/sdh/cli/cmd_install.adoc
  doc/sdh/cli/cmd_minishift.adoc
  doc/sdh/cli/cmd_release.adoc
  doc/sdh/cli/cmd_system_test.adoc
  doc/sdh/cli/cmd_ui.adoc
  doc/sdh/cli/index.adoc
  doc/sdh/development/comms.adoc
  doc/sdh/development/groups.adoc
  doc/sdh/development/index.adoc
  doc/sdh/development/labels.adoc
  doc/sdh/development/local.adoc
  doc/sdh/development/rest.adoc
  doc/sdh/development/troubleshooting.adoc
  doc/sdh/development/ui.adoc
  doc/sdh/index.adoc
  doc/sdh/introduction.adoc
  tools/bin/commands/build
  tools/bin/commands/completion
  tools/bin/commands/doc
  tools/bin/syndesis
Labels: size/XXL

#8048 integration-updates-rhmi more updates for rhmi audience
  doc/modules/integrating-applications/p_create-api-provider-integration.adoc
  doc/modules/integrating-applications/p_create-integration-operation-flows.adoc
Labels: size/s

#8050 fix(table): adjust rows format for SqlResultsTable
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlResultsTable.tsx
Labels: group/ui, size/s

#8049 chore: upgrade pf for Integration Detail Activity components
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItemSteps.tsx
  app/ui-react/packages/ui/src/Integration/Activity/index.ts
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
Labels: size/l

#8057 chore: upgrade pf for OAuth components
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppList.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItem.tsx
Labels: size/l

#8060 fix(operator): use bash instead of sh
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8059 fix: fix duplicate storybook tree
  app/ui-react/packages/ui/stories/Integration/CiCd/CiCdListView.stories.tsx
Labels: size/XS

#8064 chore: remove unused ui component
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorConnectionsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
Labels: size/m

#8067 fix(operator): use bash instead of sh
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8066 Call Go generator when using docker to build operator - 1.9.x
  install/operator/.lib.sh
Labels: size/XS

#8068 Call Go generator when using docker to build operator
  install/operator/.lib.sh
Labels: size/XS

#8063 chore: migrate action select list in the editor
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorChooseAction.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/SelectChoiceConfigModePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/l

#8065 chore: migrate integration editor form alert to pf4 and functional component
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
Labels: size/l

#8073 user doc: Comment out doc for unimplemented data mapper transformations.
  doc/modules/integrating-applications/r_available-transformations.adoc
Labels: size/m

#8074 [operator] set amq and todo images via env variables
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/m

#8071 Fix: Showing toast msg immediately once user publish or stop the virt…
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationActionContainer.tsx
Labels: group/datavirt, size/s

#8077 chore: migrate the editor step list to pf4
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsList.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
Labels: size/l

#8079 chore: migrate the describe data form to pf4
  app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx
Labels: size/l

#8080 chore: migrate the api provider operation list to pf4;
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperations.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
Labels: size/l

#8082 chore: migrate API client connector security form thingie to pf4
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: size/m

#8081 chore: migrate integration detail page metrics to pf4
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
Labels: size/l

#8076 Fix: Initial view creation in a bad state
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
Labels: size/XS

#8078 fix(build): correct snapshot release version
  tools/bin/commands/release
Labels: size/XS

#8091 Fix: Handle Styling of UI Buttons in pf4
  app/ui-react/packages/ui/src/Layout/Loader.css
Labels: size/XS

#8072 Entesb 12813 n
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/DdlEditor.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/ConnectionTreeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/KababActionComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeColumnNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/MetadataTree/TreeTableNodeComponent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/ViewEditor/index.ts
  app/ui-react/packages/ui/stories/Data/ViewEditor/DdlEditor.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewEditor/ViewEditorSqlPage.tsx
Labels: group/datavirt, size/xl

#8090 fix(meta): adapt default to ExtendedCamelContext
  app/meta/src/main/java/io/syndesis/connector/meta/v1/VerifierEndpoint.java
Labels: group/meta, pr/review-requested

#8087 Add cleanup to delete old prereleases
  tools/bin/commands/release
Labels: size/m

#8092 fix(meta): Prometheus resource name change
  app/meta/src/main/java/io/syndesis/connector/meta/EndpointMetricsFilter.java
Labels: group/meta, pr/review-requested

#8084 fix(build): correct snapshot release version
  tools/bin/commands/release
Labels: size/XS

#8085 chore(build): parameterize GitHub repository
  tools/bin/commands/release
Labels: size/s

#8098 chore: upgrade pf for integration modal + dropdown components
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItemActions.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposeVia.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: size/l

#8100 Add logging to syndesis release script
  tools/bin/commands/release
Labels: size/XS

#8097 Fix:UI console warning
  app/ui-react/packages/utils/src/WithLoader.tsx
Labels: group/datavirt, size/s

#8099 fix(server): replace dynamic properties only
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
Labels: group/server

#8101 chore: migrate notifications to pf4
  app/ui-react/packages/ui/src/Shared/Notifications.tsx
  app/ui-react/packages/ui/src/Shared/TimedAlert.tsx
  app/ui-react/syndesis/src/app/UI.tsx
Labels: size/l

#8003 chore: migrate integration donut to pf4
  app/ui-react/packages/.storybook/vendor.css
  app/ui-react/packages/api/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Dashboard/IntegrationBoard.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Shared/ConfirmationDialog.stories.tsx
  app/ui-react/packages/ui/stories/Shared/Dialog.stories.tsx
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/yarn.lock
Labels: size/xl

#8102 TTOOLS-953 Resolve issue with DV table refresh
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItems.tsx
Labels: group/datavirt, size/s

#8093 Add ability to manually refresh DV source schema
  app/ui-react/packages/api/src/useVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoList.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/CreateViewWizard/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewInfoList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/PublishStatusWithProgress.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/utils/src/dateHelpers.ts
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: size/xl

#8106 TEIIDTOOLS-962 Fix import view wizard steps
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewWizardHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewWizardHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/index.ts
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewsImportSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: group/datavirt, size/l

#8105 TEIIDTOOLS-960 Resolve issue with teiid source naming
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/MetadataService.java
  app/dv/src/main/java/io/syndesis/dv/server/endpoint/RestSyndesisSourceStatus.java
  app/dv/src/test/java/io/syndesis/dv/server/endpoint/RestSyndesisSourceStatusTest.java
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.ru.json
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewInfosContent.tsx
Labels: group/datavirt

#8103 feat(connector/kafka): TLS encryption
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectionCustomizer.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerService.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerServiceException.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerServiceImpl.java
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaMetaDataRetrievalTest.java
  app/connector/support/util/src/main/java/io/syndesis/connector/support/util/KeyStoreHelper.java
Labels: group/connector, pr/review-requested

#8119 chore: migrate from jest-dom to @testing-library/jest-dom
  app/ui-react/packages/.jest/setup.ts
  app/ui-react/packages/api/package.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/__tests__/Connection/ConnectionCard.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectionDetailsForm.spec.tsx
  app/ui-react/packages/ui/__tests__/Connection/ConnectorConfigurationForm.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationStatus.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationStatusDetail.spec.tsx
  app/ui-react/packages/ui/__tests__/Integration/IntegrationsListItem.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/utils/package.json
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/setupTests.ts
  app/ui-react/yarn.lock
Labels: size/l

#8120 fix: install fontawesome free directly
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/package.json
  app/ui-react/yarn.lock
Labels: size/XS

#8121 ENTESB-12649 disabling db healthcheck to prevent session/query stats
  app/dv/src/main/resources/s2i/application.properties
Labels: size/XS

#8122 chore(build): keep up to 10 snapshot
  tools/bin/commands/release
Labels: size/m

#8124 chore(build): keep up to 10 snapshot
  tools/bin/commands/release
Labels: size/s

#8133 fix: guard against connectors that don't have properties
  app/ui-react/packages/ui/__tests__/Connection/ConnectionDetailsForm.spec.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorNothingToConfigureAlert.tsx
  app/ui-react/packages/ui/src/Connection/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorNothingToConfigureAlert.tsx
  app/ui-react/packages/ui/src/Shared/SyndesisAlert.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
Labels: size/l

#8131 fix download more releases to catch a 2.x release
  tools/bin/commands/util/operator_funcs
Labels: size/XS

#8143 fix(build): support very old git version
  tools/bin/commands/release
Labels: size/XS

#8144 fix(build): support very old git version
  tools/bin/commands/release
Labels: size/XS

#8145 fix(build): support very old git version (2)
  tools/bin/commands/release
Labels: size/XS

#8147 [operator] generate olm bundle
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/cmd/internal/install/install_render_test.go
  install/operator/pkg/cmd/internal/olm/olm.go
  install/operator/pkg/cmd/public.go
  install/operator/pkg/generator/assets/install/deployment.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
  install/operator/pkg/syndesis/olm/annotations.go
  install/operator/pkg/syndesis/olm/annotations_test.go
  install/operator/pkg/syndesis/olm/assets/alm-examples
  install/operator/pkg/syndesis/olm/assets/community/description
  install/operator/pkg/syndesis/olm/assets/icon
  install/operator/pkg/syndesis/olm/assets/productized/description
  install/operator/pkg/syndesis/olm/crd.go
  install/operator/pkg/syndesis/olm/crd_test.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
  install/operator/pkg/syndesis/olm/olm.go
  install/operator/pkg/syndesis/olm/olm_test.go
Labels: cat/enhancement, cat/feature, group/operator, size/XXL

#8129 Install forge updates
  .gitignore
  install/operator/pkg/cmd/internal/install/install.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/generator/assets/infrastructure/02-syndesis-secrets.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/l

#8153 Fix AMQ Image typo
  install/operator/.gitignore
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8148 fix: typo in todo template
  install/operator/pkg/generator/assets/addons/todo/04-todo-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#8146 fix(build): support very old git version (2)
  tools/bin/commands/release
Labels: size/XS

#8156 fix: swap out real i18n module with a dummy to help nightly build
  app/ui-react/syndesis/src/app/App.test.tsx
Labels: size/s

#8155 fix(connector/mongodb): Add a shutdown timeout
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
Labels: group/connector

#8152 feat(integration): Enable Flows dependencies
  app/common/model/src/main/java/io/syndesis/common/model/integration/Flow.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/integration/api/src/main/java/io/syndesis/integration/api/IntegrationResourceManager.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
Labels: group/integration

#8164 fix weird button issue on connection detail page
  app/ui-react/packages/auto-form/src/widgets/FormLabelHintComponent.tsx
Labels: size/XS
