Repository syndesisio/syndesis, pull requests merged in 2020-11, with the labels that each got.

#9173 fix(ui) [ENTESB-15132] - check defaultValue for address, basePath + host
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
Labels: size/s

#9174 [BACKPORT 1.11.X] - [ENTESB-15132] fix for basePath + host OpenAPI
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
Labels: size/s

#9175 ENTESB-14949: Revert jaeger-operator role-bindings to cluster-role-bi…
  install/operator/pkg/generator/assets/install/grant/grant_cluster_role_jaeger.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#9178 Cache the apache license locally
  app/pom.xml
  app/s2i/pom.xml
  app/s2i/src/main/license/apache_license_2.0.txt
Labels: size/l

#9179 fix(ui) ENTESB-15273 - API Client Connector
  app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: size/l

#9180 [BACKPORT 1.11.X] - [ENTESB-15273] API connector
  app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailBody.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfig.spec.tsx
  app/ui-react/packages/ui/__tests__/Customization/ApiConnectorDetailConfigEdit.spec.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailBody.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfig.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/detail/ApiConnectorDetailConfigEdit.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: size/l

#9177 [ENTESB-15063] Removing default maven repository
  app/server/runtime/src/main/resources/application.yml
Labels: size/XS

#9187 Cache the apache license locally
  app/pom.xml
  app/s2i/pom.xml
  app/s2i/src/main/license/apache_license_2.0.txt
Labels: size/l

#9186 Reload ConfigMaps to avoid manual pod respin
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/main/resources/bootstrap.yml
Labels: size/m

#9189 Upgrade junit to 4.13.1
  app/pom.xml
Labels: size/XS

#9190 feature(e2e): Run integration tests as github actions on each PR
  .github/workflows/e2e.yml
Labels: size/s

#9188 Backport #9177
  app/server/runtime/src/main/resources/application.yml
Labels: size/XS

#9163 fix(connector/api): check for error handling
  app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java
Labels: backport 1.11.x, group/connector

#9197 chore: Use no-transfer-progress option on integration-test Maven buil…
  tools/bin/commands/integration-test
Labels: size/XS

#9204 Change imagePullPolicy from ifNotPresent to Always
  install/operator/pkg/generator/assets/database/syndesis-db.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-ui.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-meta.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/06-syndesis-prometheus.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/m

#9212 [BACKPORT 1.11.x] - fix(ui) ENTESB-15349: update doc links to version 7.8
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#9210 [ENTESB-15296] Add missing image pull policies
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/install/deployment.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9211 fix(ui) - ENTESB-15349 - update version in doc links for 7.8
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#9213 fix: include template step dependencies in s2i
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
Labels: backport 1.11.x

#9209 [ENTESB-15296] Add missing image pull policies
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy-embedded.yml.tmpl
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy-no-embedded.yml.tmpl
  install/operator/pkg/generator/assets/install/deployment.yml.tmpl
  install/operator/pkg/generator/assets/install/operator.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9216 fix: configured vs default values in API connector
  app/ui-react/packages/history/.size-snapshot.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/__test__/utils.spec.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/utils.ts
Labels: size/l
