Repository syndesisio/syndesis, pull requests merged in 2021-05, with the labels that each got.

#9573 fix(ui) [ENTESB-16069] conditional step gets duplicated
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: group/ui, size/XS

#9572 chore: Update to AtlasMap 2.2.0
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9585 fix: specify shell in minishift oc-env
  tools/bin/commands/minishift
Labels: size/XS

#9586 fix(operator): pbt test failure with control chars
  install/operator/pkg/generator/generator_test.go
Labels: size/XS

#9589 chore(build): archive logs and test results
  .github/workflows/checks.yml
Labels: size/s

#9588 chore: Update to AtlasMap 2.2.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9590 doc-update-ftp-connector
  doc/assemblies/connecting/assembly-connecting-to-ftp.adoc
  doc/modules/connecting/proc-adding-ftp-connection-download-named.adoc
  doc/modules/connecting/proc-adding-ftp-connection-upload-named.adoc
  doc/modules/connecting/proc-adding-ftp-finish-middle-connection.adoc
Labels: size/s

#9597 fix(build): remove `paths-ignore`
  .github/workflows/checks.yml
Labels: size/XS

#9596 chore(tools): remove unused images
  tools/images/asciidoc/Dockerfile
  tools/images/godev/Dockerfile
  tools/images/godev/README.md
  tools/images/godev/build.sh
Labels: size/m

#9593 Update container images
  install/operator/build/conf/config.yaml
Labels: size/XS

#9595 ENTESB-16374 Fail to install jaeger-operator on openshift3
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/capabilities/capabilities.go
Labels: size/XS

#9603 feat: GitHub annotations for Java tests
  app/pom.xml
Labels: size/m

#9606 chore(deps): upgrade junit-github-reporter to 0.4
  app/pom.xml
Labels: size/XS

#9609 chore(deps): upgrade Immutables to 2.8.8
  app/pom.xml
Labels: size/XS

#9611 refactor(build): set `git.commit.id` in all cases
  app/pom.xml
Labels: size/XS

#9619 ENTESB-16528 Fuse Online 7.9 Dependencies aligment
  app/connector/amqp/pom.xml
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  app/server/cli/pom.xml
Labels: size/s

#9620 Clean and remove outdated and unused code and docs.
  CHANGELOG.md
  install/support/product-version-map.yml
  install/support/serviceaccount-as-oauthclient-restricted.yml
  install/support/syndesis-amq.yml
  project/DevelopersGuide.md
  project/LICENSE
  project/ReadMe.md
  project/releases/tp1_release.md
  project/releases/tp2_release.md
  project/sprints/15/script.md
  project/sprints/15/summary.md
  project/sprints/15/ui-fixes.md
  tools/bin/commands/build
  tools/bin/commands/crc
  tools/bin/commands/install
  tools/bin/commands/minishift
Labels: size/xl

#9624 Fix CXF version to the same version as defined in camel 2.23.2.fuse-790029
  app/pom.xml
Labels: size/XS
