Repository syndesisio/syndesis, pull requests merged in 2021-08, with the labels that each got.

#9699 chore(deps): upgrade to Maven 3.8.1
  app/.mvn/wrapper/maven-wrapper.properties
  app/pom.xml
Labels: size/XS

#9698 chore(deps): upgrade Camel to 2.23.2.fuse-790053
  app/extension/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9700 fix(tool): force push release tag
  tools/bin/commands/release
Labels: size/XS

#9701 fix(tool): force push release tag
  tools/bin/commands/release
Labels: size/XS

#9702 refactor(tool): use uid/gid 0 in operator tarballs
  tools/bin/commands/release
Labels: size/XS

#9703 refactor(tool): use uid/gid 0 in operator tarballs
  tools/bin/commands/release
Labels: size/XS

#9704 fix: make sure CXF version is aligned with Camel
  app/pom.xml
  app/server/runtime/pom.xml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/CxfToCamelVersionAlignementTest.java
  app/server/runtime/src/test/resources/.gitignore
Labels: size/m

#9706 fix: robustness for connection verification
  app/server/verifier/pom.xml
  app/server/verifier/src/main/java/io/syndesis/server/verifier/ExternalVerifierService.java
  app/server/verifier/src/main/java/io/syndesis/server/verifier/VerifierCommand.java
  app/ui-react/packages/api/src/useConnectionHelpers.tsx
Labels: size/l

#9710 Updates bundle generation to latest versions and ....
  install/operator/config/Makefile
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/config/dev/operator/Makefile
  install/operator/config/manager/Makefile
  install/operator/config/manifests/bases/syndesis.clusterserviceversion.yaml
  install/operator/config/rbac-grant/Makefile
  install/operator/config/release/Makefile
  install/operator/config/vars/Makefile
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
Labels: size/l

#9711 Fix: Errors in bundle generation
  install/operator/config/Makefile
  install/operator/config/samples/syndesis.io_v1beta3_syndesis_cr.yaml
  install/operator/config/vars/Makefile
Labels: size/m, size/s

#9713 ENTESB-17153 Set environment variables for syndesis-oauthproxy
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/pkg/apis/syndesis/v1beta3/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta3/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/m

#9714 ENTESB-17153 Set environment variables for syndesis-oauthproxy (1.12.x)
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/pkg/apis/syndesis/v1beta2/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta2/zz_generated.deepcopy.go
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/m

#9717 doc-update-tutorials
  doc/modules/tutorials/proc-amq2api-add-damage-reporter-step.adoc
  doc/modules/tutorials/proc-amq2api-add-mapping-step.adoc
  doc/modules/tutorials/proc-amq2api-create-rest-api-connector.adoc
  doc/modules/tutorials/proc-sf2db-add-mapping-step.adoc
  doc/modules/tutorials/proc-sf2db-choose-finish.adoc
Labels: size/m
