Repository syndesisio/syndesis, pull requests merged in 2021-04, with the labels that each got.

#9478 fix(ui) entesb-16038 - unable to delete middle integration step
  app/ui-react/packages/api/src/helpers/__test__/integrationFunctions.spec.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: size/l

#9495 chore: upgrade operator-sdk to 0.19.4
  install/operator/go.mod
  install/operator/go.sum
  install/operator/vendor/github.com/operator-framework/operator-sdk/version/version.go
  install/operator/vendor/modules.txt
Labels: size/XS

#9502 Enable unit tests
  .github/workflows/e2e.yml
Labels: size/XS

#9503 Moving sonarcloud to job with tests
  .github/workflows/e2e.yml
  .github/workflows/on_pr.yml
Labels: size/m

#9512 doc-update-sql-connector
  doc/modules/connecting/proc-adding-db-connection-finish-middle.adoc
  doc/modules/connecting/proc-adding-db-connection-start.adoc
Labels: size/XS

#9506 chore: Update to AtlasMap 2.2.0 milestone 4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9525 Including changes in the operator in the test jobs
  .github/workflows/e2e.yml
  .github/workflows/on_pr.yml
  .github/workflows/unittest.yml
Labels: size/XS

#9527 doc-update-soap-connector-ga
  doc/assemblies/customizing/assembly-customizing.adoc
  doc/assemblies/integrating-applications/assembly-adding-api-connectors.adoc
  doc/modules/connecting/proc-creating-soap-api-connections.adoc
  doc/modules/integrating-applications/proc-creating-soap-api-connectors.adoc
Labels: size/m

#9530 ENTESB-16258: Ensure that CRD is installed even if all versions present
  install/operator/pkg/cmd/internal/install/install_cluster.go
  install/operator/pkg/cmd/internal/run/run.go
Labels: size/l, size/m

#9531 chore: Update to AtlasMap 2.2.0-M.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9528 refactor(github): redo GitHub workflow definitions
  .github/workflows/checks.yml
  .github/workflows/e2e.yml
  .github/workflows/on_pr.yml
  .github/workflows/on_push.yml
  .github/workflows/unittest.yml
  app/.mvn/extensions.xml
  app/pom.xml
  tools/bin/commands/build
Labels: size/s

#9533 fix(build): restore image transfer invocation & Sonar analysis
  .github/workflows/checks.yml
Labels: size/XS

#9534 fix(build): more workflow fixes
  .github/workflows/checks.yml
Labels: size/XS

#9541 fix(build): make sure pull request code
  .github/workflows/checks.yml
Labels: size/s

#9542 Revert "chore(deps-dev): bump guava from 27.0.1-jre to 29.0-jre in /app"
  app/pom.xml
Labels: size/XS

#9544 chore: Update to AtlasMap 2.2.0 milestone 6
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9547 ENTESB-16284 NoClassDefFoundError in ServiceNow integration
  app/connector/servicenow/pom.xml
Labels: size/XS

#9551 fix: don't use `pull_request_target`
  .github/workflows/checks.yml
Labels: size/s

#9549 chore: Update to AtlasMap 2.2.0 milestone 7
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9554 refactor(build): remove the images job
  .github/workflows/checks.yml
Labels: size/m

#9553 chore(dep): upgrade Olingo to 4.8.0
  app/connector/odata/pom.xml
  app/connector/odata/src/test/java/io/syndesis/connector/odata/server/FilterExpressionVisitor.java
Labels: size/XS

#9568 doc-update-fhir-jason-patch
  doc/modules/connecting/proc-adding-fhir-connection-patch.adoc
Labels: size/m

#9570 fix(operator): pbt test failure with control chars
  install/operator/pkg/generator/generator_test.go
Labels: size/s
