Repository syndesisio/syndesis, pull requests merged in 2021-12, with the labels that each got.

#9828 doc-update-csv-support-3 adding TP note for downstream
  doc/modules/connecting/proc-adding-amq-connection-finish.adoc
  doc/modules/connecting/proc-adding-amq-connection-middle.adoc
  doc/modules/connecting/proc-adding-amq-connection-start.adoc
  doc/modules/connecting/proc-adding-amqp-connection-middle.adoc
  doc/modules/connecting/proc-adding-amqp-connection-start.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-finish.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-middle.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-start.adoc
  doc/modules/connecting/proc-adding-ftp-finish-middle-connection.adoc
  doc/modules/connecting/proc-adding-ftp-start-connection.adoc
  doc/modules/connecting/proc-adding-http-connections.adoc
  doc/modules/connecting/proc-adding-irc-connection-receive.adoc
  doc/modules/connecting/proc-adding-irc-connection-send.adoc
  doc/modules/connecting/proc-adding-kafka-connection-finish-middle.adoc
  doc/modules/connecting/proc-adding-kafka-connection-start.adoc
  doc/modules/connecting/proc-adding-mongodb-connections-read.adoc
  doc/modules/connecting/proc-adding-mqtt-connection-finish-middle.adoc
  doc/modules/connecting/proc-adding-mqtt-connection-start.adoc
  doc/modules/connecting/proc-adding-s3-connection-finish.adoc
  doc/modules/connecting/proc-adding-s3-connection-middle.adoc
  doc/modules/connecting/proc-adding-s3-connection-start.adoc
  doc/modules/customizing/ref-how-to-specify-data-shapes.adoc
  doc/modules/integrating-applications/proc-how-to-use-webhook.adoc
Labels: size/l

#9829 doc-update-custom-env-vars
  doc/modules/integrating-applications/con-how-it-works.adoc
  doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
  doc/modules/integrating-applications/proc-start-with-webhook-connection.adoc
  doc/modules/tutorials/proc-amq2api-name-and-publish.adoc
  doc/modules/tutorials/proc-t2sf-name-and-publish.adoc
Labels: size/XS

#9831 doc-update-slack-scope
  doc/modules/connecting/proc-creating-slack-connections.adoc
Labels: size/XS

#9832 chore(deps): upgrade log4j to 2.15.0
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/s

#9834 chore(deps): upgrade logback to 1.2.8
  app/pom.xml
Labels: size/XS

#9833 chore: configure CodeQL security analysis
  .github/codeql/codeql-config.yml
  .github/workflows/checks.yml
  .github/workflows/codeql-analysis.yml
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
  app/common/util/src/test/java/io/syndesis/common/util/KeyGeneratorTest.java
  app/meta/src/main/java/io/syndesis/connector/meta/v1/DriverUploadEndpoint.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/SoapApiModelParser.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/ClientSideStateProperties.java
  app/server/metrics/prometheus/src/main/java/io/syndesis/server/metrics/prometheus/PrometheusMetricsProviderImpl.java
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
  install/operator/.lib.sh
  install/operator/pkg/syndesis/backup/test_evilbackup.zip
  install/operator/pkg/syndesis/backup/zip.go
  install/operator/pkg/syndesis/backup/zip_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
Labels: size/l, size/m

#9835 chore(deps): upgrade log4j to 2.16.0
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9836 chore(dep): upgrade Camel
  app/connector/mongodb/src/main/java/io/syndesis/connector/mongo/MongoClientCustomizer.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  tools/bin/commands/dev
Labels: size/m

#9837 Refactors bump-version script to utilise downstream
  tools/misc/bump-version-functions.sh
  tools/misc/bump-version.sh
Labels: size/l

#9838 chore(deps): upgrade Log4J to 2.17.0
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9839 chore(deps): upgrade Log4J to 2.17.0 (1.13.x)
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9840 refactor(ci): refine checks workflow
  .github/workflows/checks.yml
Labels: size/XS

#9841 fix(ci): checks workflow GITHUB_REF check
  .github/workflows/checks.yml
Labels: size/XS

#9842 refactor(ci): refine checks workflow
  .github/workflows/checks.yml
Labels: size/XS

#9843 fix(ci): github.ref instead of default branch
  .github/workflows/checks.yml
Labels: size/XS

#9844 Revert "chore(ci): remove unused profiles"
  .github/workflows/checks.yml
Labels: size/XS

#9846 chore(deps): upgrade logback to 1.2.9
  app/pom.xml
Labels: size/XS

#9847 chore(deps): upgrade logback to 1.2.9 (1.13.x)
  app/pom.xml
Labels: size/XS

#9848 doc-update-minor-tutorials
  doc/modules/tutorials/proc-register-with-sf.adoc
  doc/modules/tutorials/proc-register-with-twitter.adoc
Labels: size/s

#9849 doc-update-minor-tutorials-1.14.x
  doc/modules/tutorials/proc-register-with-sf.adoc
  doc/modules/tutorials/proc-register-with-twitter.adoc
Labels: size/s

#9850 chore: release staging robustness
  app/pom.xml
Labels: size/s

#9851 chore: release staging robustness
  app/pom.xml
Labels: size/s

#9852 chore: release of staging at end, retry 10 times
  tools/bin/commands/release
Labels: size/s

#9853 chore: release of staging at end, retry 10 times
  tools/bin/commands/release
Labels: size/s
