Repository syndesisio/syndesis, pull requests merged in 2021-01, with the labels that each got.

#9257 ENTESB-14875 Reload ConfigMaps to avoid manual pod respin
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/main/resources/bootstrap.yml
Labels: size/m

#9258 Update operator build script to use v1beta2 package
  install/operator/.lib.sh
Labels: size/XS

#9259 doc-tutorials-update-1.11.x
  doc/assemblies/tutorials/assembly-amq2api-intro.adoc
  doc/assemblies/tutorials/assembly-sf2db-intro.adoc
  doc/images/tutorials/t2sf-mappings.png
  doc/modules/tutorials/proc-amq2api-create-rest-api-connector.adoc
  doc/modules/tutorials/proc-amq2api-upload-todo-app-icon.adoc
  doc/modules/tutorials/proc-register-with-twitter.adoc
  doc/modules/tutorials/ref-comparison-of-sample-integrations.adoc
  doc/shared/attributes.adoc
Labels: backport 1.12.x

#9262 chore: Update to AtlasMap 2.1.1
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9272 fix: define immutables annotation processor
  app/server/endpoint/pom.xml
Labels: size/s

#9273 chore: flag for incremental build of staged files
  package.json
  tools/bin/commands/util/common_funcs
Labels: size/XS

#9275 fix: consider 'none' data shape present
  app/ui-react/packages/api/src/helpers/__test__/integrationFunctions.spec.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
Labels: size/m

#9283 fix: consider 'none' data shape present
  app/ui-react/packages/api/src/helpers/__test__/integrationFunctions.spec.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
Labels: size/m

#9286 chore: Update to AtlasMap 2.1.2
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9285 [BACKPORT 1.12.x] [ENTESB-11603] - prevent configured properties from being cleared in integration + API connector editors
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
Labels: size/s

#9284 fix(ui) [ENTESB-11603] prevent configured properties from being cleared in integration + API connector editors
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
Labels: size/s

#9294 chore: Update to AtlasMap 2.1.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9297 ENTESB-15631: Remove kustomize product recipe
  install/operator/kustomize/Makefile
  install/operator/kustomize/product/image-stream-patch.yaml
  install/operator/kustomize/product/kustomization.yaml
  install/operator/kustomize/release/release.sh
  install/operator/pkg/generator/assets/install/operator_deployment.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/m

#9301 feature(itest): Cache maven packages to speed up action
  .github/workflows/e2e.yml
Labels: size/XS

#9302 fix(ui): [ENTESB-11411] display a generic step icon when replacing a step
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
Labels: size/m

#9303 [backport 1.12x] fix(UI): [ENTESB-11411] - display a generic step icon when replacing a step
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
Labels: size/m

#9299 refactor: also tag the operator with moving tag
  tools/bin/commands/release
Labels: size/s

#9300 chore: push container images to quay.io
  tools/bin/commands/release
Labels: size/m
