Repository syndesisio/syndesis, pull requests merged in 2021-06, with the labels that each got.

#9626 Reverting fix for #7673 on tests to make tests consider non migrated
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoApi-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiprovider/TodoListApi-export/model.json
Labels: size/s

#9631 chore: release using GitHub Actions
  .github/workflows/release.yml
  app/.mvn/settings.release.xml
  app/pom.xml
  tools/bin/commands/release
Labels: size/l

#9634 fix(release): don't trigger on snapshot builds
  .github/workflows/release.yml
Labels: size/XS

#9637 refactor(build): remove Java and Maven in operator
  .github/workflows/checks.yml
Labels: size/s

#9636 chore(server): dependency version updates
  app/pom.xml
  app/server/endpoint/pom.xml
  app/server/logging/jaeger/pom.xml
Labels: size/s

#9645 chore(deps): upgrade RESTEasy to 4.6.0.Final
  app/pom.xml
Labels: size/XS

#9647 fix(release): remove m2e processing instructions
  app/meta/pom.xml
  app/server/runtime/pom.xml
Labels: size/XS

#9648 fix(release): remove `--dry-run`
  .github/workflows/release.yml
Labels: size/XS

#9649 chore(release): moving tag for snapshot release
  tools/bin/commands/release
Labels: size/s

#9651 chore: migrate to Husky 6 and auto-install
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: size/s

#9655 chore(git): polish Husky hooks
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
Labels: size/s

#9656 chore(build): show version, strict checksums
  tools/bin/commands/util/maven_funcs
Labels: size/s

#9657 chore(build): enforce Java 1.8 version
  app/pom.xml
Labels: size/XS

#9659 fix(ui): don't revert to upload on OpenAPI error
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
Labels: size/XS

#9662 fix(build): make sure `unpack` is not skipped
  app/server/runtime/pom.xml
Labels: size/XS
