Repository syndesisio/syndesis, pull requests merged in 2021-07, with the labels that each got.

#9668 chore: nvm configuration & Java version in hooks
  .husky/pre-push
  .nvmrc
Labels: size/XS

#9670 fix(tools): include name of the registry
  tools/bin/commands/release
Labels: size/XS

#9667 fix(ui): don't prompt for credentials in wizard
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/securityValidation.ts
  app/ui-react/packages/ui/stories/Customization/api-connector-create/3-Security.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
Labels: size/xl

#9654 feat: integration labels
  app/common/model/src/main/java/io/syndesis/common/model/WithLabels.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/Integration.java
  app/common/model/src/main/java/io/syndesis/common/model/integration/IntegrationBase.java
  app/common/model/src/main/java/io/syndesis/common/model/validation/integration/ValidLabels.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationBaseTest.java
  app/common/model/src/test/java/io/syndesis/common/model/integration/IntegrationTest.java
  app/common/util/src/main/java/io/syndesis/common/util/Labels.java
  app/common/util/src/test/java/io/syndesis/common/util/LabelsTest.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/dao/src/main/java/io/syndesis/server/dao/validation/integration/LabelsValidator.java
  app/server/dao/src/main/resources/META-INF/validation/integration-constraint.xml
  app/server/dao/src/test/java/io/syndesis/server/dao/validation/NoDuplicateValidatorTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/runtime/src/main/resources/validation-messages.properties
Labels: group/server

#9679 chore(deps): upgrade xnio to 3.8.4.Final
  app/pom.xml
Labels: size/s

#9680 chore(deps): upgrade xnio to 3.8.4.Final
  app/pom.xml
Labels: size/s

#9682 chore: Update to AtlasMap 2.2.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9681 chore: Update to AtlasMap 2.2.3
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9683 chore: remove daily builds of 2.x
  .github/workflows/daily_release.yml
Labels: size/XS

#9684 chore(deps): bump openapi-generator-maven-plugin in /app/server/runtime
  app/server/runtime/pom.xml
Labels: size/XS

#9685 chore: update OpenAPI documents
  app/ui-react/packages/models/openapi.internal.json
  app/ui-react/packages/models/openapi.json
Labels: size/s

#9696 chore: add test case for nested SQL
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/SqlParserTest.java
Labels: size/s

#9694 ENTESB-16809 Camel Clients Getting Started with Managed Kafka
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnector.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaConnectorFactory.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataExtension.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaVerifierExtension.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerService.java
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/service/KafkaBrokerServiceImpl.java
  app/connector/kafka/src/main/resources/META-INF/syndesis/connector/kafka.json
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectionCustomizerTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorCertificateTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorExtraOptionsTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorSASLOAuthBearerTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorSASLPlainTest.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaConnectorTestSupport.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaMetaDataRetrievalTest.java
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  doc/modules/connecting/proc-creating-kafka-connections.adoc
  install/operator/pkg/generator/assets/infrastructure/05-syndesis-cluster-security.yml.tmpl
  install/operator/pkg/generator/assets/install/cluster_role_kafka.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/csv_test.go
Labels: size/xl
