Repository syndesisio/syndesis, pull requests merged in 2021-03, with the labels that each got.

#9390 chore: Update to AtlasMap 2.1.6
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9387 ENTESB-15225: Adds affinity and toleration values on install
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/install_test.go
Labels: size/l

#9404 Set affinity/toleration only for integrations
  install/operator/pkg/syndesis/action/pod_scheduling.go
Labels: size/m

#9405 doc-update-remove-eval-refs downstream update
  doc/assemblies/tutorials/assembly-amq2api-intro.adoc
  doc/assemblies/tutorials/assembly-sf2db-intro.adoc
  doc/assemblies/tutorials/assembly-t2sf-intro.adoc
  doc/modules/tutorials/proc-create-sf-connection.adoc
  doc/modules/tutorials/proc-create-twitter-connection.adoc
  doc/modules/tutorials/proc-register-with-sf.adoc
  doc/modules/tutorials/proc-register-with-twitter.adoc
Labels: backport 1.11.x, size/s

#9398 fix(ui): [backport] ENTESB-15738 - validation for API connector security
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/securityValidation.ts
Labels: size/XS

#9408 FIX for #9407 Minishift installation never finished and sleeps forever
  tools/bin/commands/util/openshift_funcs
Labels: size/XS

#9410 chore(app): bump camel version
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9415 chore: tweak parameters for out of cluster dev env
  app/meta/pom.xml
  app/server/runtime/pom.xml
Labels: size/s

#9417 refactor(tools): moved bump script
  tools/bin/commands/dev
  tools/misc/syndesisCamelVersion.sh
Labels: size/m

#9422 fix: include operator config.yaml in release tag
  tools/bin/commands/release
Labels: size/XS

#9383 doc update slack connector
  doc/modules/connecting/proc-creating-slack-connections.adoc
Labels: size/XS

#9406 doc-update-remove-eval-refs downstream update
  doc/assemblies/tutorials/assembly-amq2api-intro.adoc
  doc/assemblies/tutorials/assembly-sf2db-intro.adoc
  doc/assemblies/tutorials/assembly-t2sf-intro.adoc
  doc/modules/tutorials/proc-create-sf-connection.adoc
  doc/modules/tutorials/proc-create-twitter-connection.adoc
  doc/modules/tutorials/proc-register-with-sf.adoc
  doc/modules/tutorials/proc-register-with-twitter.adoc
Labels: size/s

#9423 WIP doc-update-google-api
  doc/modules/connecting/proc-register-with-google.adoc
Labels: size/m

#9424 chore: add 2.x daily release
  .github/workflows/daily_release.yml
Labels: size/m

#9425 chore: remove circleci badge
  README.md
Labels: size/XS

#9399 fix(ui): ENTESB-15738 - validation for API connector security
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSecurityForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/securityValidation.ts
Labels: size/XS

#9386 fix(ui): ENTESB-15810: update docs to 7.9 from 7.8
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#9428 fix: git authentication and setup in daily release
  .github/workflows/daily_release.yml
Labels: size/XS

#9429 fix: git authentication and setup in daily release
  .github/workflows/daily_release.yml
Labels: size/XS

#9430 fix: git authentication and setup in daily release
  .github/workflows/daily_release.yml
Labels: size/XS

#9431 fix: git authentication and setup in daily release
  .github/workflows/daily_release.yml
Labels: size/s

#9432 chore: don't fail fast on release matrix build
  .github/workflows/daily_release.yml
Labels: size/XS

#9433 fix(build): network issues on GitHub Actions
  app/.mvn/maven.config
Labels: size/XS

#9434 chore: pass github user and token via parameters
  .github/workflows/daily_release.yml
  tools/bin/commands/release
Labels: size/m

#9436 fix: remove backport action
  .github/workflows/backport.yml
Labels: size/s

#9435 fix: wagon TTL setting is a JVM property
  app/.mvn/jvm.config
  app/.mvn/maven.config
Labels: size/XS

#9437 fix: github username/token check
  tools/bin/commands/release
Labels: size/XS

#9439 chore: Change internal version constant of operator to correct value
  install/operator/build/conf/config.yaml
Labels: size/XS

#9445 Doc update datamapper
  doc/assemblies/integrating-applications/assembly-mapping-data.adoc
  doc/modules/integrating-applications/con-about-data-types-and-collections.adoc
  doc/modules/integrating-applications/con-about-types-of-mappings.adoc
  doc/modules/integrating-applications/proc-applying-conditions-to-mappings.adoc
  doc/modules/integrating-applications/proc-combine-multiple-source-fields-into-one-target-field.adoc
  doc/modules/integrating-applications/proc-separate-one-source-field-into-multiple-target-fields.adoc
  doc/modules/integrating-applications/proc-supplying-source-values-missing.adoc
  doc/modules/integrating-applications/proc-transform-target-data.adoc
  doc/modules/integrating-applications/ref-available-transformations.adoc
  doc/modules/integrating-applications/ref-mapping-between-collections-and-non-collections.adoc
Labels: size/l

#9446 fix(ui): ENTESB-15744 - incorrect connection displayed in vertical nav
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
Labels: size/m

#9454 doc-update-datamapper-2 QE review
  doc/modules/integrating-applications/proc-supplying-source-values-missing.adoc
  doc/modules/integrating-applications/ref-available-transformations.adoc
Labels: size/s

#9448 Proposed fix for release build failure due to not including junit4-stub dependency
  .github/workflows/on_pr.yml
  app/connector/sql/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  app/s2i/pom.xml
  app/server/openshift/pom.xml
  app/test/integration-test/pom.xml
  app/test/pom.xml
  app/test/test-support/pom.xml
  app/transitional/junit4-stub/pom.xml
  app/transitional/junit4-stub/src/main/java/org/junit/rules/ExternalResource.java
  app/transitional/junit4-stub/src/main/java/org/junit/rules/Statement.java
  app/transitional/junit4-stub/src/main/java/org/junit/rules/TestRule.java
  app/transitional/junit4-stub/src/main/java/org/junit/runner/RunWith.java
  app/transitional/junit4-stub/src/main/java/org/junit/runners/model/Statement.java
  app/transitional/pom.xml
  app/ui-react/packages/history/.size-snapshot.json
Labels: pr/wip, size/l

#9455 ENTESB-15883 Upgrade Postgresql to 12
  install/operator/build/conf/config.yaml
  install/operator/pkg/cmd/internal/install/install_defaults.go
Labels: size/XS

#9458 doc-update-ftp-connector
  doc/modules/connecting/proc-adding-ftp-finish-middle-connection.adoc
  doc/modules/connecting/proc-adding-ftp-start-connection.adoc
  doc/shared/attributes.adoc
Labels: size/m

#9461 ftp-connector-doc-update-2
  doc/assemblies/connecting/assembly-connecting-to-ftp.adoc
  doc/modules/connecting/proc-adding-ftp-connection-download-named.adoc
  doc/modules/connecting/proc-adding-ftp-connection-upload-named.adoc
  doc/modules/connecting/proc-adding-ftp-finish-middle-connection.adoc
  doc/modules/connecting/proc-adding-ftp-start-connection.adoc
Labels: size/l

#9447 chore(deps): Bump camel to 2.23.2.fuse-790029
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9456 ENTESB-16039 - fix issue with conditional flow throwing exception
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: size/m

#9457 Debugging full-build pr action
  .github/workflows/on_pr.yml
Labels: size/m

#9444 fix: connection reset on GitHub
  app/.mvn/jvm.config
  app/.mvn/maven.config
  app/pom.xml
Labels: size/s

#9462 Use latest release to download syndesis-operator, excluding 2.x
  tools/bin/commands/crc
  tools/bin/commands/install
  tools/bin/commands/minishift
  tools/bin/commands/util/operator_funcs
Labels: size/s
