Repository syndesisio/syndesis, pull requests merged in 2021-09, with the labels that each got.

#9705 fix: Add a test ID to the form group containing a select typeahead for ENTESB-13112
  app/ui-react/packages/auto-form/src/widgets/FormTypeaheadComponent.tsx
Labels: size/XS

#9720 feat(common): doclint configuration parameter
  app/pom.xml
Labels: size/XS

#9718 feat(ui): [ENTESB-15353] - support custom labeling of integration
  app/ui-react/packages/ui/__tests__/Integration/IntegrationEditorLabels.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorExtensionTable.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLabels.tsx
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/packages/ui/stories/Integration/Editor/IntegrationEditorLabels.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
Labels: cat/feature, group/ui, size/xl

#9722 fix(ci): align maven-deploy-plugin
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/s

#9724 chore : remove hardcoded camel version, replace with ${camel.version}
  app/server/runtime/pom.xml
Labels: size/XS

#9726 chore(deps): upgrade to microbundle 0.13.3
  app/pom.xml
  app/ui-react/packages/api/package.json
  app/ui-react/packages/api/tsconfig.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/apicurio-adapter/tsconfig.json
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/tsconfig.json
  app/ui-react/pom.xml
  app/ui-react/yarn.lock
Labels: size/XXL

#9729 update-customer-portal-doc-version
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#9730 doc-kafka-connector-update
  doc/modules/connecting/proc-creating-kafka-connections.adoc
Labels: size/m

#9728 Pf upgrade followup
  app/integration/bom/pom.xml
  app/pom.xml
  app/server/endpoint/pom.xml
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/atlas/SyndesisJavaService.java
  app/ui-react/craco.config.js
  app/ui-react/package.json
  app/ui-react/packages/.storybook/vendor.css
  app/ui-react/packages/.storybook/webpack.config.js
  app/ui-react/packages/api/package.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/apicurio-assembly/package.json
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/__tests__/AppLayout.spec.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Layout/PfVerticalNavItem.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/utils/package.json
  app/ui-react/syndesis/.env.development
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/public/index.html
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/index.css
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
  app/ui-react/tslint.json
  app/ui-react/yarn.lock
Labels: group/ui, size/XXL

#9733 doc-kafka-connector-update-2
  doc/modules/connecting/proc-creating-kafka-connections.adoc
Labels: size/s

#9734 chore(deps): remove node-sass download
  app/pom.xml
  app/ui-react/pom.xml
Labels: size/m

#9736 Fix fail of configuration_test when building in docker
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/XS

#9737 Add dataTestId for DataMapper
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Labels: size/XS

#9739 doc-update-labels
  doc/modules/integrating-applications/con-how-it-works.adoc
  doc/modules/integrating-applications/proc-procedure-for-creating-an-integration.adoc
  doc/modules/integrating-applications/proc-start-with-webhook-connection.adoc
  doc/modules/tutorials/proc-amq2api-name-and-publish.adoc
  doc/modules/tutorials/proc-sf2db-name-and-publish.adoc
  doc/modules/tutorials/proc-t2sf-name-and-publish.adoc
Labels: size/s
