Repository syndesisio/syndesis, pull requests merged in 2021-10, with the labels that each got.

#9738 chore(operator): rework the database upgrade
  install/operator/pkg/syndesis/upgrade/database_upgrade.go
  install/operator/pkg/syndesis/upgrade/database_upgrade_test.go
  install/operator/pkg/syndesis/upgrade/upgrade.go
Labels: size/l

#9742 chore(dep): upgrade commitlint to 13.2
  package.json
  yarn.lock
Labels: size/l

#9743 fix: resource leaks
  app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/auth/oauth/OAuthRefreshTokenProcessor.java
  app/connector/rest-swagger/src/test/java/io/syndesis/connector/rest/swagger/SpecificationResourceCustomizerTest.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestResourceManager.java
  app/meta/src/test/java/io/syndesis/connector/meta/v1/DriverUploadTest.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/util/OpenApiModelParser.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/BindingHelper.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/SoapApiModelParser.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/util/IconGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/ApiConnectorTemplate.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/TestHelper.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/SoapConnectorTemplate.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/parser/AbstractXmlSchemaExtractorTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/parser/XmlSchemaExtractorElementTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/parser/XmlSchemaExtractorTypeTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/parser/XmlSchemaTestHelper.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/ApiDocumentationEndpoint.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/dto/Mixed.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorIconHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/CustomConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/MetadataCommand.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/environment/EnvironmentHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/support/IntegrationSupportHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/AggregateMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/meta/SplitMetadataHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtilTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/user/UserHandlerTest.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/DefaultMigrator.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/IntegrationConfiguration.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/StoredSettings.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/ConnectorsITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/connector/CustomConnectorITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/connector/CustomSwaggerConnectorITCase.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion28Test.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/migrations/UpgradeVersion29Test.java
Labels: size/xl

#9746 chore: remove operator-sdk in $GOPATH requirement
  tools/bin/commands/util/operator_funcs
Labels: size/XS

#9741 Fixes with building locally using docker & fix for ENTESB-17341
  app/server/openshift/src/main/java/io/syndesis/server/openshift/CrdResourceException.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/ui-react/docker/Dockerfile
  install/operator/go.sum
  tools/bin/commands/build
  tools/bin/commands/util/maven_funcs
Labels: size/l, size/m
