Repository syndesisio/syndesis, pull requests merged in 2021-02, with the labels that each got.

#9308 fix(release): fix typo
  tools/bin/commands/release
Labels: size/XS

#9312 fix: typo in release script
  tools/bin/commands/release
Labels: size/XS

#9313 Tagging operator image with moving tag and pushing to quay.io (1.12.x)
  tools/bin/commands/release
Labels: size/m

#9314 Tagging operator image with moving tag and pushing to quay.io (1.11.x)
  tools/bin/commands/release
Labels: size/m

#9305 ENTESB-15631: Creates github action to release kustomize archive
  .github/workflows/kustomize-release.yml
  install/operator/kustomize/release/Makefile
  install/operator/kustomize/release/release.sh
Labels: size/l

#9316 chore: Update to AtlasMap 2.1.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9325 doc update to api provider quickstart
  doc/modules/integrating-applications/proc-configure-publish-api-provider-quickstart.adoc
  doc/modules/integrating-applications/proc-try-api-provider-quickstart.adoc
Labels: backport 1.12.x, size/m

#9323 chore(deps): upgrade testcontainers to 1.15.1
  app/pom.xml
  app/test/integration-test/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/offline/OfflineS2IBuild_IT.java
  app/test/test-support/pom.xml
Labels: size/s

#9319 feat(operator): adding cookie name
  install/operator/pkg/generator/assets/infrastructure/04-syndesis-oauth-proxy.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/XS

#9315 chore: Update to AtlasMap 2.1.4
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9328 ENTESB-15633 - Main build on Github Actions
  .circleci/config.yml
  .github/workflows/on_pr.yml
  app/excluded_tests.txt
Labels: size/m, size/xl

#9337 backport ENTESB-15633 - Main build on Github Actions
  .circleci/config.yml
  .github/workflows/on_pr.yml
Labels: size/XXL

#9347 fix ENTESB-15145 upgrading commons-compress to 1.20
  app/integration/project-generator/pom.xml
  app/pom.xml
Labels: size/XS

#9349 chore: Update to AtlasMap 2.1.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9348 chore: Update to AtlasMap 2.1.5
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/yarn.lock
Labels: size/s

#9353 feature(analysis): Add SonarCloud at the end of the main building job
  .github/workflows/on_pr.yml
  .github/workflows/on_push.yml
  README.md
  app/extension/annotation-processor/pom.xml
  app/pom.xml
  doc/pom.xml
Labels: size/l, size/m

#9365 Fixing typo
  .github/workflows/on_push.yml
Labels: size/XS

#9367 feature(sonarcloud.io): Explicitly set sources and binaries for coverage
  .github/workflows/on_pr.yml
  .github/workflows/on_push.yml
Labels: size/XS

#9363 ENTESB-15773: Removes legacy operator deployment config
  install/operator/pkg/cmd/internal/run/run.go
  install/operator/pkg/controller/syndesis/syndesis_controller.go
Labels: size/m

#9372 Reworking of kustomize installer to make release more flexible
  install/operator/kustomize/.gitignore
  install/operator/kustomize/Makefile
  install/operator/kustomize/app/Makefile
  install/operator/kustomize/app/kustomization.yaml
  install/operator/kustomize/bases/crd/Makefile
  install/operator/kustomize/bases/crd/kustomization.yaml
  install/operator/kustomize/bases/deployment/Makefile
  install/operator/kustomize/bases/deployment/kustomization.yaml
  install/operator/kustomize/bases/grant/Makefile
  install/operator/kustomize/bases/grant/kustomization.yaml
  install/operator/kustomize/bases/jaeger-crd/Makefile
  install/operator/kustomize/bases/jaeger-crd/kustomization.yaml
  install/operator/kustomize/bases/role/Makefile
  install/operator/kustomize/bases/role/kustomization.yaml
  install/operator/kustomize/dev/app/Makefile
  install/operator/kustomize/dev/app/kustomization.yaml
  install/operator/kustomize/dev/operator/Makefile
  install/operator/kustomize/dev/operator/annotation-patch.tmpl
  install/operator/kustomize/dev/operator/env-var-patch.yaml
  install/operator/kustomize/dev/operator/image-stream-patch.tmpl
  install/operator/kustomize/dev/operator/kustomization.yaml
  install/operator/kustomize/release/Makefile
  install/operator/kustomize/setup-jaeger/kustomization.yaml
Labels: size/l

#9382 doc-update-demodata
  doc/assemblies/tutorials/assembly-amq2api-intro.adoc
  doc/modules/integrating-applications/proc-configure-publish-api-provider-quickstart.adoc
  doc/modules/tutorials/ref-comparison-of-sample-integrations.adoc
Labels: size/m

#9381 doc update slack connector
  doc/modules/connecting/proc-creating-slack-connections.adoc
Labels: size/XS

#9384 fix(ui) - ENTESB-15810: update docs to 7.9 from 7.8
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS
