Repository syndesisio/syndesis, pull requests merged in 2021-11, with the labels that each got.

#9778 fix: replace operationId in action id with hash
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiConnectorGenerator.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/openapi/OpenApiConnectorGeneratorTest.java
  app/server/api-generator/src/test/resources/openapi/v2/apikey_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v2/todo.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/apikey_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/basic_auth.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/complex_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/damage_service.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/doubleclick_reporting.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/issue_9638.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/kie-server.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/machine_history.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/petstore_xml.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/reverb.unified_connector.json
  app/server/api-generator/src/test/resources/openapi/v3/todo.unified_connector.json
Labels: size/XXL

#9780 chore: don't create daily releases if unchanged
  .github/workflows/daily_release.yml
Labels: size/s

#9777 Upgrade Fabric8 Kubernetes Client to 4.13.3
  app/connector/kafka/pom.xml
  app/connector/kafka/src/main/java/io/syndesis/connector/kafka/KafkaMetaDataRetrieval.java
  app/connector/kafka/src/test/java/io/syndesis/connector/kafka/KafkaMetaDataRetrievalTest.java
  app/pom.xml
  app/server/controller/pom.xml
  app/server/endpoint/pom.xml
  app/server/logging/jsondb/pom.xml
  app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/KubernetesSupport.java
  app/server/metrics/jsondb/pom.xml
  app/server/metrics/prometheus/pom.xml
  app/server/monitoring/pom.xml
  app/server/openshift/pom.xml
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/crd/IntegrationScheduling.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/crd/Syndesis.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/crd/SyndesisResourceDoneable.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/crd/SyndesisResourceList.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/crd/SyndesisSpec.java
  install/operator/go.mod
  install/operator/pkg/apis/syndesis/v1beta3/syndesis_types.go
  install/operator/pkg/apis/syndesis/v1beta3/syndesis_types_test.go
  install/operator/pkg/generator/assets/infrastructure/03-syndesis-server-config.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/syndesis/configuration/configuration.go
  install/operator/vendor/github.com/ghodss/yaml/LICENSE
  install/operator/vendor/github.com/ghodss/yaml/README.md
  install/operator/vendor/github.com/ghodss/yaml/fields.go
  install/operator/vendor/github.com/ghodss/yaml/go.mod
  install/operator/vendor/github.com/ghodss/yaml/go.sum
  install/operator/vendor/github.com/ghodss/yaml/yaml.go
  install/operator/vendor/github.com/ghodss/yaml/yaml_go110.go
  install/operator/vendor/modules.txt
Labels: size/XXL

#9767 Large memory usage in custom SOAP API client connectors
  app/common/model/src/main/java/io/syndesis/common/model/Kind.java
  app/common/model/src/main/java/io/syndesis/common/model/connection/ConnectorSettings.java
  app/common/model/src/test/java/io/syndesis/common/model/connection/ConnectorSettingsTest.java
  app/common/util/src/main/java/io/syndesis/common/util/CollectionsUtils.java
  app/common/util/src/main/java/io/syndesis/common/util/IOStreams.java
  app/common/util/src/main/java/io/syndesis/common/util/KeyGenerator.java
  app/common/util/src/test/java/io/syndesis/common/util/CollectionsUtilsTest.java
  app/connector/soap/src/main/java/io/syndesis/connector/soap/cxf/SpecificationResourceCustomizer.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/ConnectorStepHandler.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/ConnectorAndActionGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/ConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/OpenApiConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/SoapApiConnectorGenerator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/SoapApiModelInfo.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/SoapConnectorConstants.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/SoapApiModelParser.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/AbstractSoapExampleTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/SoapApiConnectorGeneratorExampleTest.java
  app/server/api-generator/src/test/java/io/syndesis/server/api/generator/soap/parser/SoapApiModelParserTest.java
  app/server/dao/src/main/java/io/syndesis/server/dao/file/SpecificationResourceDao.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/BaseConnectorGeneratorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/CustomConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/LocalMetadataCommandAction.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/resource/ResourceHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/CustomConnectorHandlerTest.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/APIGeneratorConfiguration.java
  app/server/runtime/src/main/java/io/syndesis/server/runtime/FileStoreConfiguration.java
  app/server/runtime/src/test/java/io/syndesis/server/runtime/connector/CustomConnectorITCase.java
  app/test/integration-test/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/SOAP_API_EndToEnd_IT.java
  app/test/integration-test/src/test/java/io/syndesis/test/itest/apiconnector/SoapConnectorBasicAuth_IT.java
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/SOAPBasicAuthentication-export/model.json
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/SOAP_EndToEnd/cmis.wsdl
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/SOAP_EndToEnd/expected-request.xml
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/SOAP_EndToEnd/expected-response.xml
  app/test/integration-test/src/test/resources/io/syndesis/test/itest/apiconnector/SOAP_EndToEnd/mapping.json
  app/ui-react/packages/api/src/useApiConnectorCreator.tsx
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/models/openapi.internal.json
  app/ui-react/packages/models/openapi.json
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ServicePortPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
Labels: size/XXL

#9783 fix: keep track of removed environment variables
  app/common/model/src/main/java/io/syndesis/common/model/WithEnvironment.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/DeploymentData.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/ui-react/packages/models/openapi.internal.json
  app/ui-react/packages/models/openapi.json
Labels: size/l

#9781 chore: support lowercase table names with Oracle
  app/connector/sql/pom.xml
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/DatabaseContainers.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/IfImagePresentCondition.java
  app/connector/sql/src/test/java/io/syndesis/connector/sql/common/OracleSqlMetaDataITCase.java
  app/pom.xml
Labels: size/l

#9782 fix: parameter deletion in mapper parameters
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
Labels: size/s

#9787 ENTESB-17613 update bouncycastle to 1.69
  app/pom.xml
Labels: size/XS

#9791 fix: manage environment variables on publish
  app/common/model/src/main/java/io/syndesis/common/model/WithEnvironment.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/BaseHandler.java
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java
  app/server/controller/src/test/java/io/syndesis/server/controller/integration/online/PublishHandlerTest.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandlerTest.java
  app/ui-react/packages/models/openapi.internal.json
  app/ui-react/packages/models/openapi.json
Labels: size/l

#9802 ENTESB-17480 Fix to align jetty version into syndesis-meta
  app/meta/pom.xml
Labels: size/XS

#9801 refactor: no column metadata error message
  app/connector/sql/src/main/java/io/syndesis/connector/sql/common/DbMetaDataHelper.java
Labels: size/s

#9803 Revert "chore(deps): bump @patternfly/react-icons from 3.15.16 to 4.10.2 in /app/ui-react"
  app/ui-react/yarn.lock
Labels: size/XS

#9805 chore: additional flags in daily release
  .github/workflows/daily_release.yml
  tools/bin/commands/release
Labels: size/s

#9806 chore: fix daily workflow inputs
  .github/workflows/daily_release.yml
Labels: size/XS

#9807 upgrade some UI dependencies
  app/ui-react/package.json
  app/ui-react/yarn.lock
Labels: size/XXL

#9808 fix: connectorTemplateId state
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiConnectorCreatorSelectMethod.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
Labels: size/s

#9811 chore: 2.23.2.fuse-790054-redhat-00001 of Camel
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9814 chore: remove references to jboss-ea repository
  app/extension/bom/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape-variants/pom.xml
  app/extension/maven-plugin/src/it/with-data-shape/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/settings.xml.mustache
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestConstants.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/shouldGenerateSettingsXml/settings.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/shouldGenerateSettingsXmlWithMirror/settings.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/pom.xml
  app/s2i/src/main/resources/settings.xml
  app/server/runtime/pom.xml
  install/operator/build/conf/config.yaml
  tools/bin/commands/util/openshift_funcs
Labels: size/l

#9817 fix: s2i dependency download
  app/s2i/pom.xml
  app/server/builder/image-generator/src/main/java/io/syndesis/server/builder/image/generator/Application.java
Labels: size/s

#9818 chore: upgrade jsoup to 1.14.3
  app/connector/email/pom.xml
Labels: size/XS

#9819 chore: upgrade jaegger and opentracing
  app/common/jaeger-spring-boot-starter/pom.xml
  app/integration/runtime-springboot/pom.xml
  app/integration/runtime/pom.xml
  app/pom.xml
  app/server/logging/jaeger/pom.xml
Labels: size/m

#9821 chore: use same version of jsoup in box connector
  app/connector/box/pom.xml
  app/connector/email/pom.xml
  app/pom.xml
Labels: size/s

#9822 fix: accidental Tomcat inclusion
  app/common/jaeger-spring-boot-starter/pom.xml
  app/pom.xml
Labels: size/s

#9810 chore: align versions in integration and S2I
  app/common/model/pom.xml
  app/extension/bom/pom.xml
  app/extension/maven-plugin/pom.xml
  app/integration/bom/pom.xml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/pom.xml
  app/server/api-generator/pom.xml
  app/server/cli/pom.xml
  app/server/credential/pom.xml
  app/server/dao/pom.xml
  app/server/endpoint/pom.xml
  app/server/metrics/prometheus/pom.xml
  app/server/runtime/pom.xml
  app/server/update-controller/pom.xml
  app/test/test-support/src/main/resources/io/syndesis/test/integration/project/template/pom.xml.mustache
Labels: size/l, size/m

#9785 refactor: name sanitization
  app/common/util/pom.xml
  app/common/util/src/main/java/io/syndesis/common/util/Names.java
  app/common/util/src/test/java/io/syndesis/common/util/NamesTest.java
  app/common/util/src/test/resources/junit-platform.properties
Labels: size/l

#9824 chore: compiler version in integration project
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml
Labels: size/m

#9827 fix: declare spring-boot-starter version
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/pom.xml.mustache
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/pom.xml
Labels: size/s

#9826 fix: force newer Gson version
  app/connector/odata-v2/pom.xml
Labels: size/s
