Repository syndesisio/syndesis, pull requests merged in 2022-01, with the labels that each got.

#9854 Upgrade log4j and logback versions
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9855 Upgrade log4j and logback versions
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
Labels: size/XS

#9856 Use safeconstructor for YAML to limit the classes loaded by yaml parser.
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/util/OpenApiModelParser.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/support/SupportUtil.java
Labels: size/XS

#9865 chore: allow gpg to be skipped
  app/pom.xml
Labels: size/XS

#9866 fix: additional removal of skip=false for gpg [skip-ci]
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
Labels: size/XS

#9864 refactor: mongodb connector tests
  app/connector/mongodb/pom.xml
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/ClosableMongoCollection.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerAllOptionsTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCappedCollectionConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorChangeStreamConsumerTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorCountTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorFindAllTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorInsertTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorRemoveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorSaveTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorTestSupport.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/MongoDBConnectorUpdateTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbedMongoConfiguration.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/embedded/EmbeddedMongoExtension.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/meta/MongoDBMetadataTest.java
  app/connector/mongodb/src/test/java/io/syndesis/connector/mongo/verifier/MongoDBVerifierTest.java
  app/connector/mongodb/src/test/resources/junit-platform.properties
  app/pom.xml
Labels: size/XXL

#9784 fix: monitoring/integrations OpenAPI definition
  app/server/runtime/src/main/resources/openapi-internal.yaml
  app/ui-react/packages/models/openapi.internal.json
  app/ui-react/packages/models/openapi.json
Labels: size/m

#9867 chore: install ActiveMQ broker with TODO addon
  install/operator/build/conf/config.yaml
  install/operator/pkg/generator/assets/infrastructure/04-amq-example.yml.tmpl
  install/operator/pkg/generator/assets_vfsdata.go
Labels: size/s

#9868 Fix: Report output if errors occur in upgrade_app
  tools/misc/bump-version-functions.sh
Labels: size/XS

#9869 chore: remove server-builder-maven-plugin
  app/server/builder/maven-plugin/pom.xml
  app/server/builder/maven-plugin/src/main/java/io/syndesis/server/builder/maven/ExtractConnectorDescriptorsMojo.java
  app/server/builder/maven-plugin/src/main/java/io/syndesis/server/builder/maven/GenerateMapperInspectionsMojo.java
  app/server/pom.xml
  app/server/runtime/pom.xml
Labels: size/xl

#9870 chore(deps): upgrade gson to 2.8.9
  app/pom.xml
Labels: size/XS

#9755 chore: pull images as possible from quay.io
  install/operator/build/conf/config-test.yaml
  install/operator/build/conf/config.yaml
  install/operator/pkg/cmd/internal/install/install_defaults.go
  install/operator/pkg/syndesis/configuration/configuration_test.go
Labels: size/l, size/m

#9871 fix: flaky Events integration test
  app/server/runtime/src/test/java/io/syndesis/server/runtime/EventsITCase.java
Labels: size/XS

#9874 ENTESB-17078: Actions required on metadata bundle
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/config/manifests/bases/syndesis.clusterserviceversion.yaml
  install/operator/config/scorecard/patches/olm.config.yaml
  install/operator/config/vars/Makefile
  install/operator/pkg/apis/syndesis/v1beta3/syndesis_types.go
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
Labels: size/l

#9873 ENTESB-17078: Actions required on metadata bundle
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/config/manifests/bases/syndesis.clusterserviceversion.yaml
  install/operator/config/scorecard/patches/olm.config.yaml
  install/operator/config/vars/Makefile
  install/operator/pkg/apis/syndesis/v1beta3/syndesis_types.go
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
Labels: size/l

#9881 fix(server): correct totalCount in ListResult
  app/common/model/src/main/java/io/syndesis/common/model/ListResult.java
  app/common/model/src/main/java/io/syndesis/common/model/TagFinder.java
  app/common/model/src/test/java/io/syndesis/common/model/TagFinderTest.java
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataAccessObject.java
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/DataManager.java
  app/server/dao/src/main/java/io/syndesis/server/dao/manager/operators/ReverseFilter.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationIdFilter.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthAppHandler.java
  app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilter.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectorHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/external/PublicApiHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationDeploymentHandlerTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationIdFilterTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/integration/IntegrationOverviewHelperTest.java
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/setup/OAuthConnectorFilterTest.java
  app/server/jsondb/src/main/java/io/syndesis/server/jsondb/dao/JsonDbDao.java
  app/server/update-controller/src/test/java/io/syndesis/server/update/controller/usage/UsageUpdateHandlerTest.java
Labels: size/l

#9883 refactor(ci): release trigger change
  .github/workflows/release.yml
Labels: size/s
