Repository syndesisio/syndesis, pull requests merged in 2022-04, with the labels that each got.

#9924 doc update- remove data mapper note
  doc/modules/connecting/proc-adding-amq-connection-finish.adoc
  doc/modules/connecting/proc-adding-amq-connection-middle.adoc
  doc/modules/connecting/proc-adding-amq-connection-start.adoc
  doc/modules/connecting/proc-adding-amqp-connection-middle.adoc
  doc/modules/connecting/proc-adding-amqp-connection-start.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-finish.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-middle.adoc
  doc/modules/connecting/proc-adding-dropbox-connection-start.adoc
  doc/modules/connecting/proc-adding-ftp-finish-middle-connection.adoc
  doc/modules/connecting/proc-adding-ftp-start-connection.adoc
  doc/modules/connecting/proc-adding-http-connections.adoc
  doc/modules/connecting/proc-adding-irc-connection-receive.adoc
  doc/modules/connecting/proc-adding-irc-connection-send.adoc
  doc/modules/connecting/proc-adding-kafka-connection-finish-middle.adoc
  doc/modules/connecting/proc-adding-kafka-connection-start.adoc
  doc/modules/connecting/proc-adding-mongodb-connections-read.adoc
  doc/modules/connecting/proc-adding-mqtt-connection-finish-middle.adoc
  doc/modules/connecting/proc-adding-mqtt-connection-start.adoc
  doc/modules/connecting/proc-adding-s3-connection-finish.adoc
  doc/modules/connecting/proc-adding-s3-connection-middle.adoc
  doc/modules/connecting/proc-adding-s3-connection-start.adoc
  doc/modules/customizing/ref-how-to-specify-data-shapes.adoc
  doc/modules/integrating-applications/proc-how-to-use-webhook.adoc
Labels: size/m

#9929 Small fixes for cluster roles and bundling
  install/operator/config/Makefile
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/config/rbac-grant/kustomization.yaml
  install/operator/config/rbac-role/kustomization.yaml
  install/operator/config/script/build-catalog.sh
  install/operator/config/script/build-install-opm.sh
  install/operator/config/vars/Makefile
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
  install/operator/pkg/generator/assets/install/cluster_role_kafka.yml.tmpl
Labels: size/m

#9923 Dependency alignements
  app/connector/http/pom.xml
  app/connector/odata-v2/pom.xml
  app/connector/odata/pom.xml
  app/pom.xml
Labels: size/m

#9927 Upgrades Spring to 5.3.18 and Spring Boot to 2.5.12
  app/extension/bom/pom.xml
  app/extension/maven-plugin/pom.xml
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/AbstractDependencyFilterMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/AbstractPackagerMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/CustomLayersProvider.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/FilterableDependency.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/JarTypeFilter.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/LoggingMainClassTimeoutWarningListener.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/RepackageMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/SupportMojo.java
  app/extension/maven-plugin/src/main/java/io/syndesis/extension/maven/plugin/layout/ModuleLayoutFactory.java
  app/integration/bom/pom.xml
  app/meta/pom.xml
  app/meta/src/main/resources/application.yml
  app/meta/src/test/java/io/syndesis/connector/meta/ConnectorEndpointIT.java
  app/meta/src/test/java/io/syndesis/connector/meta/MetaIT.java
  app/meta/src/test/java/io/syndesis/connector/meta/PropertyPairDeserializer.java
  app/meta/src/test/java/io/syndesis/connector/meta/SyndesisMetadataDeserializer.java
  app/pom.xml
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/Locator.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/Resolver.java
  app/server/api-generator/src/main/java/io/syndesis/server/api/generator/soap/parser/SoapApiModelParser.java
  app/server/api-generator/src/main/resources/META-INF/jax-ws-catalog.xml
  app/server/api-generator/src/main/resources/schema/schemas.xmlsoap.org_soap_encoding.xml
  app/server/api-generator/src/main/resources/schema/schemas.xmlsoap.org_wsdl.xml
  app/server/runtime/pom.xml
  app/server/runtime/src/main/resources/application.yml
  app/server/runtime/src/test/java/io/syndesis/server/runtime/KubernetesClientITCase.java
  app/server/runtime/src/test/resources/application-test.yml
Labels: size/XXL

#9931 Doc update integrating condition expression
  doc/modules/integrating-applications/proc-using-advanced-expression-builder.adoc
Labels: size/s

#9934 format-update: Indentation updated
  doc/modules/integrating-applications/proc-using-advanced-expression-builder.adoc
Labels: size/XS
