Repository syndesisio/syndesis, pull requests merged in 2022-02, with the labels that each got.

#9885 chore: update UX tools (SVG image optimization)
  ux/connections_icons/svg/package.json
  ux/connections_icons/svg/update_icons.js
  ux/connections_icons/svg/yarn.lock
Labels: size/XXL

#9887 update-customer-portal-doc-version to 7.11
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.it.json
  app/ui-react/syndesis/src/i18n/locales/shared-translations.ru.json
Labels: size/XS

#9882 chore(deps): upgrade Testcontainers to 1.16.3
  app/pom.xml
  app/test/integration-test/src/test/java/io/syndesis/test/itest/csv/CSV_WebHook_to_DB_IT.java
  app/test/integration-test/src/test/resources/logback-test.xml
Labels: size/l, size/s

#9889 doc update todo option includes amq broker
  doc/assemblies/tutorials/assembly-amq2api-intro.adoc
  doc/modules/tutorials/ref-comparison-of-sample-integrations.adoc
Labels: size/XS

#9823 chore: enforce and converge dependencies
  app/connector/amqp/pom.xml
  app/connector/box/pom.xml
  app/connector/http/pom.xml
  app/connector/jira/pom.xml
  app/connector/odata-v2/pom.xml
  app/connector/odata/pom.xml
  app/connector/slack/pom.xml
  app/connector/soap/pom.xml
  app/connector/support/maven-plugin/pom.xml
  app/connector/twitter/pom.xml
  app/extension/maven-plugin/pom.xml
  app/integration/runtime/src/test/java/io/syndesis/integration/runtime/handlers/LogStepHandlerTest.java
  app/pom.xml
  app/server/api-generator/pom.xml
  app/server/cli/pom.xml
  app/server/endpoint/src/test/java/io/syndesis/server/endpoint/v1/handler/connection/ConnectionActionHandlerTest.java
  app/test/integration-test/pom.xml
Labels: size/l, size/xl

#9872 chore(deps): upgrade maven-shared-utils to 3.3.4
  app/pom.xml
Labels: size/XS

#9891 chore(ui): update caniuse-lite to 1.0.30001307
  app/ui-react/yarn.lock
Labels: size/s

#9890 refactor: use embedded resources
  .github/workflows/checks.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/daily_release.yml
  .github/workflows/kustomize-release.yml
  .github/workflows/release.yml
  .lintstagedrc.js
  install/operator/.lib.sh
  install/operator/config/crd/bases/syndesis.io_syndesises.yaml
  install/operator/go.mod
  install/operator/go.sum
  install/operator/pkg/cmd/internal/grant/grant.go
  install/operator/pkg/cmd/internal/grant/grant_test.go
  install/operator/pkg/cmd/internal/install/install_app.go
  install/operator/pkg/cmd/internal/install/install_cluster.go
  install/operator/pkg/cmd/internal/install/install_cluster_test.go
  install/operator/pkg/cmd/internal/install/install_forge.go
  install/operator/pkg/cmd/internal/install/install_operator.go
  install/operator/pkg/cmd/internal/install/install_render_test.go
  install/operator/pkg/generator/assets/assets_generate.go
  install/operator/pkg/generator/assets/install/cluster/syndesis.yml
  install/operator/pkg/generator/assets_vfsdata.go
  install/operator/pkg/generator/dev/dev.go
  install/operator/pkg/generator/generator.go
  install/operator/pkg/generator/generator_test.go
  install/operator/pkg/generator/mode_dev.go
  install/operator/pkg/generator/mode_prod.go
  install/operator/pkg/syndesis/action/install.go
  install/operator/pkg/syndesis/action/install_test.go
  install/operator/pkg/syndesis/backup/backup.go
  install/operator/pkg/syndesis/olm/assets.go
  install/operator/pkg/syndesis/olm/assets/assets_generate.go
  install/operator/pkg/syndesis/olm/assets_test.go
  install/operator/pkg/syndesis/olm/assets_vfsdata.go
  install/operator/pkg/syndesis/olm/cluster_roles.go
  install/operator/pkg/syndesis/olm/crd.go
  install/operator/pkg/syndesis/olm/csv.go
  install/operator/pkg/syndesis/olm/csv_test.go
  install/operator/pkg/syndesis/olm/dev/dev.go
  install/operator/pkg/syndesis/olm/mode_dev.go
  install/operator/pkg/syndesis/olm/mode_prod.go
  install/operator/pkg/syndesis/upgrade/migrations.go
  install/operator/vendor/github.com/shurcooL/httpfs/LICENSE
  install/operator/vendor/github.com/shurcooL/httpfs/filter/filter.go
  install/operator/vendor/github.com/shurcooL/httpfs/filter/filters.go
  install/operator/vendor/github.com/shurcooL/httpfs/vfsutil/file.go
  install/operator/vendor/github.com/shurcooL/httpfs/vfsutil/vfsutil.go
  install/operator/vendor/github.com/shurcooL/httpfs/vfsutil/walk.go
  install/operator/vendor/github.com/shurcooL/vfsgen/CONTRIBUTING.md
  install/operator/vendor/github.com/shurcooL/vfsgen/LICENSE
  install/operator/vendor/github.com/shurcooL/vfsgen/README.md
  install/operator/vendor/github.com/shurcooL/vfsgen/commentwriter.go
  install/operator/vendor/github.com/shurcooL/vfsgen/doc.go
  install/operator/vendor/github.com/shurcooL/vfsgen/generator.go
  install/operator/vendor/github.com/shurcooL/vfsgen/options.go
  install/operator/vendor/github.com/shurcooL/vfsgen/stringwriter.go
  install/operator/vendor/modules.txt
  package.json
Labels: size/XXL

#9895 doc update twitter tutorial
  doc/modules/tutorials/proc-register-with-twitter.adoc
  doc/modules/tutorials/proc-t2sf-add-mapping-step.adoc
Labels: size/s

#9896 doc-update-tutorials-twitter-1-13
  doc/modules/tutorials/proc-register-with-twitter.adoc
  doc/modules/tutorials/proc-t2sf-add-mapping-step.adoc
  doc/modules/tutorials/ref-comparison-of-sample-integrations.adoc
Labels: size/s

#9897 doc-update-twitter-tutorial-2
  doc/modules/tutorials/proc-t2sf-add-mapping-step.adoc
Labels: size/s

#9894 Fix operator install with jaeger enabled, fail to install
  install/operator/pkg/syndesis/action/install.go
Labels: size/XS

#9892 refactor(ui): replace Learna with Lage
  app/ui-react/lage.config.js
  app/ui-react/lerna.json
  app/ui-react/package.json
  app/ui-react/packages/api/package.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/utils/package.json
  app/ui-react/pom.xml
  app/ui-react/syndesis/package.json
  app/ui-react/yarn.lock
Labels: size/XXL

#9804 refactor: move from FMP to KOMP
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorConfiguration.java
  app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGeneratorHelper.java
  app/integration/project-generator/src/main/resources/application-redhat.properties
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/s2i/assemble
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/application.properties.mustache
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/deployment.yml
  app/integration/project-generator/src/main/resources/io/syndesis/integration/project/generator/templates/redhat/pom.xml.mustache
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/ProjectGeneratorTest.java
  app/integration/project-generator/src/test/java/io/syndesis/integration/project/generator/TestResourceManager.java
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/assemble
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application-tracing.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/application.properties
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateProject/redhat/pom.xml
  app/integration/project-generator/src/test/resources/io/syndesis/integration/project/generator/testGenerateTemplateStepProjectDependencies/redhat/pom.xml
  app/meta/pom.xml
  app/meta/src/main/jkube-includes/run-env.sh
  app/pom.xml
  app/s2i/pom.xml
  app/s2i/src/main/docker/Dockerfile
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
  app/server/runtime/pom.xml
  app/server/runtime/src/main/jkube/deployment.yml
  app/test/test-support/src/main/java/io/syndesis/test/container/s2i/S2iProjectBuilder.java
  app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
  app/ui-react/docker/Dockerfile
  app/ui-react/docker/build
  app/ui-react/pom.xml
  tools/bin/commands/build
  tools/bin/commands/release
Labels: size/XXL

#9908 refactor(s2i): less permission changes
  app/s2i/src/main/docker/Dockerfile
  app/test/test-support/src/main/java/io/syndesis/test/container/dockerfile/SyndesisDockerfileBuilder.java
  app/test/test-support/src/main/java/io/syndesis/test/container/s2i/SyndesisS2iAssemblyContainer.java
Labels: size/m

#9909 refactor(s2i): s2i tar.bz2 archive instead of zip
  app/s2i/src/main/assembly/repository.xml
Labels: size/XS

#9912 chore(upgrade): use UBI image for upgrade
  tools/upgrade/BOOT-INF/classes/migrations/up-30.js
  tools/upgrade/Dockerfile
  tools/upgrade/migration/preflight.sh
  tools/upgrade/migration/resource/README.adoc
  tools/upgrade/run.sh
  tools/upgrade/steps/prep_10_backup_resources
  tools/upgrade/steps/prep_15_stop
  tools/upgrade/steps/prep_20_backup_db
  tools/upgrade/steps/upgrade_10_migrate_db
  tools/upgrade/steps/upgrade_20_stop_all
  tools/upgrade/steps/upgrade_40_update_resources
  tools/upgrade/steps/upgrade_60_restart_all
  tools/upgrade/upgrade.sh
Labels: size/xl

#9906 fix(ui): advanced choice expression validation
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.spec.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/setupTests.ts
  app/ui-react/yarn.lock
Labels: size/xl

#9911 Cleanup OpenShiftServiceImpl
  app/pom.xml
  app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/UnpublishHandler.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftConfigurationProperties.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftService.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java
  app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceNoOp.java
  app/server/openshift/src/test/java/io/syndesis/server/openshift/OpenShiftServiceImplTest.java
Labels: size/XXL

#9902 Upgrade AtlasMap to 2.3.13, add warning indicator for data shape changes
  app/extension/bom/pom.xml
  app/integration/bom/pom.xml
  app/pom.xml
  app/ui-react/packages/api/package.json
  app/ui-react/packages/api/src/helpers/__test__/integrationFunctions.spec.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/shape/WithDescribeDataShapeForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.spec.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/yarn.lock
Labels: size/l, size/xl
